### ISSUE TITLE
Long loading time  Loader.load(org.bytedeco.opencv.opencv_java.class);

### ISSUE THREAD

**Issue by JimmySimard** [bytedeco/javacv#1638] opened 2021-04-27 13:32 UTC
When I load the library on startup it take about 30 seconds to finish the loading,,, Is there a way to remove some library to reduce the loading time or something else?

**Comment by saudet** [comment] 2021-04-27 13:39
This has been fixed in with JavaCPP 1.5.5. Please try again with JavaCV 1.5.5.

**Comment by JimmySimard** [comment] 2021-04-27 15:18
Thank you for quick answer ! After updgrading to the lastest version, I have save around 15 seconds. Do you think I can do better or it is the best ?

**Comment by saudet** [comment] 2021-04-27 23:45
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true", and look at the messages displayed on the console. We should be able to tell that way which DLLs are taking so long to load.

**Comment by JimmySimard** [comment] 2021-05-03 18:55
Sorry for the delay... I have run the application with the debug flag on and as you say I see all the dll been loaded but none of them take much time ! What seem to be long is the fact that a lot of dll are loaded ! I have excluded some jar from the javacv maven dependency to reduce loading time but no luck ... I imagine it's the best i can do !

**Comment by saudet** [comment] 2021-05-03 23:36
What do you mean by "a lot"? Could you attach the whole log here?

**Comment by JimmySimard** [comment] 2021-05-04 11:41
This the console log output. You will see what I mean by a lot ! 

[console_log.txt](https://github.com/bytedeco/javacv/files/6420785/console_log.txt)

**Comment by saudet** [comment] 2021-05-06 02:47
Thanks for testing! The same classes and DLLs get loaded for me as well, and on my installation of Windows 10, calling `Loader.load(org.bytedeco.opencv.opencv_java.class);` takes only about 1000 ms to execute. Since I can't reproduce this issue here, I will not be able to fix it without additional information, but there is at least one other user that is experiencing the same slow loading time on Windows, see https://github.com/bytedeco/javacpp/issues/452, so I'll mark this as a duplicate of that, and let's continue the discussion there.

**Comment by saudet** [comment] 2021-05-06 02:48
Duplicate of https://github.com/bytedeco/javacpp/issues/452

**Closed by saudet** 2021-05-06 02:48 UTC
Labels: duplicate, question

**Comment by saudet** [comment] 2022-01-25 01:03
I've done some further optimizations in commit https://github.com/bytedeco/javacpp/commit/e8b5734f7d0469478f399bb58e0fd3cfe4af1906 that should pretty much fix any regression in loading time on Windows.

Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by JimmySimard** [comment] 2022-01-28 18:03
I've just done some tests with your snapshot ! The starting time has past from 20 seconds to only 4 seconds ! Thank you !

**Comment by saudet** [comment] 2022-01-28 23:31
4 seconds is still a lot of time though. I wonder what's going on there. Would you have any ideas @HannesWell?

**Comment by HannesWell** [comment] 2022-01-29 15:05
> 4 seconds is still a lot of time though. I wonder what's going on there. Would you have any ideas @HannesWell?

Not immediately but I can consider this case when looking for further optimizations of the Loader. The more cases I have and the long they the better I can find more hot spots in the code.

What was the exact use case? Did you only call the code mentioned in the title?
`Loader.load(org.bytedeco.opencv.opencv_java.class);`

@saudet can you tell me the largest preset to load? Alternatively I could just load multiple libraries.

**Comment by saudet** [comment] 2022-01-30 00:40
I think the one that takes the most time is SciPy, see https://github.com/bytedeco/javacpp/pull/512#issuecomment-1019789014. The issue with Python libraries is that they have a lot of small files that we have to extract and NTFS is not particularly optimized for this use case.
