### ISSUE TITLE
OOM issue with FFmpegFrameRecorder

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1394] opened 2020-03-31 12:45 UTC
Hi i encounter many issues like this, any suggestion?

java.lang.OutOfMemoryError: 

  at org.bytedeco.javacpp.Pointer.deallocator (Pointer.java:29)
 
  at org.bytedeco.javacpp.Pointer.init (Pointer.java:5)
 
  at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.allocate (Native Method)
 
  at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.<init> (Write_packet_Pointer_BytePointer_int.java:2)
 
  at org.bytedeco.javacv.FFmpegFrameRecorder$WriteCallback.<init> (FFmpegFrameRecorder.java:1)
 
  at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit> (FFmpegFrameRecorder.java:6)

**Comment by saudet** [comment] 2020-03-31 13:15
Make sure to deallocate anything you don't need as soon as you don't need
it.

**Comment by xiaos** [comment] 2020-04-01 01:15
Thanks @saudet  i think i release all resource immediately after use.  e.g For ffmpegGraber, i release it, for IplImage, i release also. 

when i grab image in loop, i don't need release the image each time right?

**Comment by saudet** [comment] 2020-04-01 02:19
We can use a PointerScope to make sure to catch everything, see issue #1383. If you have more questions about that, please add them to issue #1383.

**Comment by saudet** [comment] 2020-04-01 02:19
Duplicate of #1383

**Closed** 2020-04-01 02:19 UTC
Labels: duplicate, question

**Comment by saudet** [comment] 2020-06-18 01:03
BTW, I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by LiuChao96** [comment] 2020-07-15 06:42
> BTW, I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
> Please give it a try with the snapshots: http://bytedeco.org/builds/


Excuse me，Why can't I download 1.5.4-snapshot

**Comment by saudet** [comment] 2020-07-15 07:21
We can download as explained here: http://bytedeco.org/builds/
