### ISSUE TITLE
JVM crash happened when running in docker

### ISSUE THREAD

**Issue by 354613111** [bytedeco/javacv#2245] opened 2024-07-01 11:42 UTC
[hs_err_pid1.log](https://github.com/user-attachments/files/16052192/hs_err_pid1.log)

public static int yuvToWebm(String sourcePath, String targetPath, int width, int height) {
        int duration = 0;
        if (StringUtils.isEmpty(sourcePath) || StringUtils.isEmpty(targetPath)) {
            return duration;
        }
        Frame frame;
        try (FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(sourcePath);
            FFmpegFrameRecorder frameRecorder = new FFmpegFrameRecorder(targetPath, 640, 360)) {
            //设置yuv420p参数
            frameGrabber.setImageWidth(width);
            frameGrabber.setImageHeight(height);
            frameGrabber.setPixelFormat(8);
            //设置webm参数
            frameRecorder.setFormat("webm");
            //压缩成视频, 2帧压缩成一帧
            frameRecorder.setFrameRate(1);
            frameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_VP9);
            frameRecorder.setVideoOption("preset", "superfast");
            frameGrabber.start();
            frameRecorder.start();
            while ((frame = frameGrabber.grabFrame()) != null) {
                try {
                    frameRecorder.record(frame);
                } catch (Exception e) {
                    log.error("convert h264 to webm failed:", e);
                }
            }
            duration = (int) Math.ceil(frameRecorder.getTimestamp() / 1000000d);
        } catch (Exception e) {
            log.debug("catch e:", e);
            return duration;
        }

        return duration;
    }

<dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacv</artifactId>
      <version>1.5.10</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>ffmpeg-platform</artifactId>
      <version>6.1.1-1.5.10</version>
    </dependency>

**Comment by saudet** [comment] 2024-07-01 23:13
Duplicate of #2244

**Closed by saudet** 2024-07-01 23:13 UTC
Labels: duplicate, enhancement, question
