### ISSUE TITLE
1.5.11-SNAPSHOT FFmpegFrameGrabber FFmpegFrameRecorder can't work on linux

### ISSUE THREAD

**Issue by ZhanPro** [bytedeco/javacv#2257] opened 2024-07-29 08:20 UTC
https://github.com/bytedeco/javacv/issues/2256

I have followed the instructions to upgrade the version of JavaCV to 1.5.11-SNAPSHOT. However, I encountered an issue: after the upgrade, my program runs fine on macOS when packaged into a JAR, but it fails to run on Linux, with the following error:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.(Read_packet_Pointer_BytePointer_int.java:45)
at org.bytedeco.javacv.FFmpegFrameGrabber.(FFmpegFrameGrabber.java:372)
at com.sankuai.ai.speech.platform.codec.decoder.javacvdecoder.JavaCVDecoder.(JavaCVDecoder.java:84)
at com.sankuai.ai.speech.platform.codec.uitls.DecodeUtils.decode(DecodeUtils.java:98)
at com.sankuai.ai.speech.platform.api.gateway.component.AudioNormalizeComponent.process(AudioNormalizeComponent.java:79)

The dependencies I am using are:

`
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.5.11-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>7.0-1.5.11-SNAPSHOT</version>
        </dependency>
`
`
<dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>javacv</artifactId>
                <version>1.5.11-SNAPSHOT</version>
            </dependency>

`
What is the reason for this?

**Comment by saudet** [comment] 2024-07-30 12:54
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-07-30 12:54 UTC
Labels: duplicate, enhancement, question
