### ISSUE TITLE
if surport play h265 flv?

### ISSUE THREAD

**Issue by wangpeng1** [bytedeco/javacv#1497] opened 2020-08-26 03:12 UTC

**Comment by saudet** [comment] 2020-08-26 04:17
Please explain what isn't working.

**Comment by saudet** [comment] 2020-08-28 02:19
Duplicate of #1496

**Closed by saudet** 2020-08-28 02:19 UTC
Labels: duplicate, question

**Comment by wangpeng1** [comment] 2020-09-03 05:57
@saudet I have record local video,the format is h265 Flv. if the javacv can play flv with H265.the flv is local video not rtmp.

**Comment by saudet** [comment] 2020-09-03 06:33
Yes, I'm pretty sure that works. Let me know if it does not work though.

**Comment by saudet** [comment] 2020-09-03 06:36
No, actually, it looks like it's not supported:
https://trac.ffmpeg.org/ticket/3581
https://trac.ffmpeg.org/ticket/6389

**Comment by wangpeng1** [comment] 2020-09-11 02:56
@saudet  which  javacv android api can use to play local video，I want to test it

**Comment by saudet** [comment] 2020-09-11 03:15
JavaCV doesn't come with a player, but we can make one with FFmpegFrameGrabber to get audio and video frames.
