### ISSUE TITLE
FFmpegFrameRecorder rtsp stream 

### ISSUE THREAD

**Issue by sezertt** [bytedeco/javacv#763] opened 2017-08-21 07:12 UTC
Hi,

I am trying to stream rtsp using FFmpegFrameRecorder but I get this error message

> avio_open2 error() error -1330794744: Could not open 'null'

```
int bitRate = 1024 * 1024 * 2;
FFmpegFrameRecorder frameRecorder = new FFmpegFrameRecorder("rtsp://ip:port/...", width(), height());
frameRecorder.setFormat("rtp");
frameRecorder.setPixelFormat(AV_PIX_FMT_YUV420P);
frameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
frameRecorder.setFrameRate(25);
frameRecorder.setVideoBitrate(bitRate);
frameRecorder.start();
```
If I wrote rstp instead of rtp it stucks at frameRecorder.start();

Any help would be appreciated,
Thanks

**Comment by saudet** [comment] 2017-08-21 13:02
Please try to enable debug log messages for FFmpeg, and post what you get
here. Thank you

**Comment by sezertt** [comment] 2017-08-21 14:00
Hi saudet, 

Do you mean FFmpegLogCallback.set() ? 

it logs 

> [libx264 @ 25282c00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 25282c00] profile High, level 3.0
[libx264 @ 25282c00] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=11 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=2097 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

and then stucks if I write rtsp then stucks, logs

> [libx264 @ 1660ee00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 1660ee00] profile High, level 3.0
[libx264 @ 1660ee00] final ratefactor: 16.05
avio_open2 error() error -1330794744: Could not open 'null'

if I wrote rtp.

Am I doing it wrong ? If so can you explain how to open the logs ?

**Comment by saudet** [comment] 2017-08-21 14:13
Setting the format to rtp won't work for rtsp, that's normal.

**Comment by sezertt** [comment] 2017-08-22 05:43
Yes, I tried it and it worked for rtp but for rtsp i couldn't make anything work.

**Comment by saudet** [comment] 2017-08-22 12:32
So, what do you get in the log when it doesn't work at all?

**Comment by sezertt** [comment] 2017-08-23 05:37
```
[libx264 @ 25282c00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 25282c00] profile High, level 3.0
[libx264 @ 25282c00] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=11 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=2097 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
```

This one is rtsp output and there are no actions after these

**Comment by saudet** [comment] 2017-08-23 11:20
Try to enable debug level messages. It should give a lot more info.

**Comment by sezertt** [comment] 2017-08-23 13:39
Hi again,
I added this line 
```
av_log_set_level(AV_LOG_TRACE);
```
Extra log was 
> No default whitelist set

So i added 
```
frameRecorder.setOption("protocol_whitelist", "file,crypto,http,https,tls");
```
It logged the file 
[log.txt](https://github.com/bytedeco/javacv/files/1245565/log.txt)

If I add tcp to white list, again it wont play...

By the way thank you for your answers

**Comment by sezertt** [comment] 2017-08-23 14:42
I think my problem become similar to issue #696 .
After adding 
```
frameGrabber.flush();
```
It only lasts 30 seconds

**Comment by saudet** [comment] 2017-08-23 14:51
Does it behave the same way with ffplay?

**Comment by sezertt** [comment] 2017-08-24 12:22
Hi this is the log from
```
ffmpeg -re -i rtsp://ip:554/ch0_unicast_firststream -protocol_whitelist tcp -f rtsp rtsp://asd:asd1234@ip:30001/30001 -loglevel 48
```
[log ff.txt](https://github.com/bytedeco/javacv/files/1248780/log.ff.txt)

If protocol_whitelist is different from tcp it won't start

**Comment by saudet** [comment] 2017-08-24 12:56
Ok, so `setOption("protocol_whitelist", "tcp")` and `setFormat("rtsp")` for JavaCV as well. You can't expect to have different options to have the same effect!

**Comment by saudet** [comment] 2017-08-24 13:16
So, anyway I'll assume ffplay doesn't work either, so I'll mark this as a duplicate of #696. Let's continue the discussion there! Thanks

**Closed by saudet** 2017-08-24 13:16 UTC
