### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by hseshadr** [bytedeco/javacv#360] opened 2016-03-17 21:53 UTC
[Using Android Studio (Jetbrains)]

1) Add Gradle dependencies to build.gradle
```groovy
compile group: 'org.bytedeco', name: 'javacv', version: '1.1'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8-1.1', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier:    'android-arm'
```
2) Download javacv-1.1-bin.zip from javacv site
3) unjar opencv-android-arm.jar 
copy opencv-android-arm/libarmeabi/*.lib to android project src/main/jniLibs/libarmeabi/
4) unjar ffmpeg-android-arm.jar 
copy ffmpeg-android-arm/libarmeabi/*.lib to android project src/main/jniLibs/libarmeabi/
5) In MainActivity onCreate invoke this method with a valid video file
```java
    public void extractFrames(String filePath) {
        Frame frame = null;
        FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(filePath);
        try {
            frameGrabber.start();
            frame = frameGrabber.grab();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }
    }
```
Result:
```
3-17 17:33:39.021 20594-20613/? E/AndroidRuntime: FATAL EXCEPTION: Thread-203
                                                   Process: identv.com.opencv_java_androidstudio, PID: 20594
                                                   java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.Class.forName(Class.java:309)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                       at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2597)
                                                       at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:386)
                                                       at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:380)
                                                       at com.identv.aurora.JavaCVExtractFrames.extractFrames(JavaCVExtractFrames.java:21)
                                                       at com.identv.aurora.JavaCVExtractFrames$1.run(JavaCVExtractFrames.java:37)
                                                       at java.lang.Thread.run(Thread.java:818)

```

**Comment by saudet** [comment] 2016-03-18 09:21
Are you sure your device is not x86?

**Comment by saudet** [comment] 2016-04-07 06:32
Could you try these SNAPSHOT binaries and let me know if they work any better?
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/
Thanks

**Comment by samkgaibek** [comment] 2016-04-27 20:29
@saudet, hi! I tried to use the links. But it did not help.
Error is the same on Marshmallow:
`java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                    at java.lang.Class.classForName(Native Method)
                                                                    at java.lang.Class.forName(Class.java:324)
                                                                    at org.bytedeco.javacpp.Loader.load(Loader.java:446)
                                                                    at org.bytedeco.javacpp.Loader.load(Loader.java:411)
                                                                    at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
                                                                    at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                    at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:126)`

**Comment by saudet** [comment] 2016-04-28 00:01
Duplicate of https://github.com/bytedeco/javacv/issues/133. Try to put your libs in the "app/src/main/jniLibs/armeabi-v7a/ subdirectory" instead.

**Closed by saudet** 2016-04-28 00:01 UTC
Labels: bug, duplicate
