### ISSUE TITLE
How do I implement this command line in JAVACV?

### ISSUE THREAD

**Issue by xiaozhubenben** [bytedeco/javacv#1074] opened 2018-10-24 09:00 UTC
Hi, Ｉneed send a dtmf wav to  callee using rtp, the following command line do this well:
`ffmpeg –re -i "+wavFilePath+" -vn -acodec pcm_alaw -ar 8000 -f rtp rtp://aServer:aPort`
How can I implement this command line with JAVACV? 
Is it the following code? Using the code, on the  callee side I can only  hear some  part of the WAV data content , feeling like  some  is missing.

```
	FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(wavFilePath);
		grabber.setAudioCodec(avcodec.AV_CODEC_ID_PCM_U8); 
		grabber.start();
		String outputRtp = "rtp://" + c.getAddress() + ":" + remoteAudioRtpPort;
		FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputRtp, grabber.getAudioChannels());
		recorder.setAudioCodec(avcodec.AV_CODEC_ID_PCM_ALAW); 	
		recorder.setFormat("rtp");
        recorder.setAudioQuality(0); 		
		recorder.setSampleRate(8000);
		recorder.setFrameRate(grabber.getAudioFrameRate());
		recorder.setAudioBitrate(64000); 	 
                recorder.start();
		Frame frame = null;		
		while ((frame = grabber.grabFrame()) != null) {
			recorder.setTimestamp(grabber.getTimestamp());            		
			recorder.record(frame);
		}
		

		grabber.flush();
		grabber.stop();
		
		grabber.close();
		
		recorder.stop();
		recorder.close();
		recorder.release();
```

**Comment by xiaozhubenben** [comment] 2018-10-25 01:55
My DTMF wav file is a few key sounds that add a lot of empty data before and after the key sounds.
But after sending it with JAVACV, I hear only the key sound on the peer, there is no  silence duration.

**Comment by saudet** [comment] 2018-10-25 02:09
It just sounds like you're losing packets on the network. RTP isn't a reliable protocol. Maybe try with HTTP instead.

**Comment by xiaozhubenben** [comment] 2018-10-25 02:45
> It just sounds like you're losing packets on the network. RTP isn't a reliable protocol. Maybe try with HTTP instead.

Thanks for reply.  Losing package is not the cause,because using command line ,ffmpeg  did this well.

**Comment by saudet** [comment] 2018-10-25 03:10
Are you running the ffmpeg program on the same device as JavaCV?

**Comment by saudet** [comment] 2018-10-27 05:50
Ok, so let's keep debugging this. Does this happen only with RTP? Or does the same thing happen with a file as output?

**Comment by xiaozhubenben** [comment] 2018-10-30 10:08
Sorry for replied so late. I had tried  use file as output ,it is good.
`ffmpeg –re -i c:\temp\dtmf9014913482394511336.wav -vn -acodec pcm_mulaw -ar 8000 -f wav c:\temp\test.wav`

**Comment by saudet** [comment] 2018-10-30 10:47
I mean, does it also work correctly in JavaCV when using a file?

**Comment by xiaozhubenben** [comment] 2018-10-30 23:21
Yes both command line and javacv worked using file as output

**Comment by xiaozhubenben** [comment] 2018-11-05 02:52
use cmd line ffmpeg configuration：
```
ffmpeg version N-92318-g4a976200d7 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 21.100 / 56. 21.100
  libavcodec     58. 34.100 / 58. 34.100
  libavformat    58. 19.102 / 58. 19.102
  libavdevice    58.  4.106 / 58.  4.106
  libavfilter     7. 39.100 /  7. 39.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

**Comment by saudet** [comment] 2018-11-05 02:54
Hum, doesn't look like there's anything related to RTP in that list, but might be worth investigating.

**Comment by xiaozhubenben** [comment] 2018-11-14 02:13
How JavaCV  realize   the  "–re "  Option in ffmpeg command line?

**Comment by saudet** [comment] 2018-11-14 02:38
It doesn't, but we can easily use something like `Thread.sleep(10)` in a loop and wait after we're supposed to get a frame before calling `grab()`. That would probably solve the issue you're having. Something like that could be integrated in JavaCV, so I'll mark this as enhancement.

**Comment by xiaozhubenben** [comment] 2018-11-14 06:05
Thanks, but `Thread.sleep()` doesn't resovle this problem, the `-re `option set RTP send frequence ，and not grab speed

**Comment by saudet** [comment] 2018-11-14 06:08
It ends up throttling record(), same difference.

**Comment by MCourser** [comment] 2019-03-13 08:11
I also want to know how to implement the command -re for a record. I send video and audio frames by RTP protocol. And my video conference shows that the video is ok, but the audio is not in a right frame rate.

**Comment by saudet** [comment] 2019-03-24 00:49
Duplicate of #307

With commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 the `ffmpeg` program itself now gets bundled, so we can use it easily from Java. For this case, we could do something like the following:
```java
   String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);
   ProcessBuilder pb = new ProcessBuilder(ffmpeg, "-re", "-i", "+wavFilePath+", "-vn", "-acodec", "pcm_alaw", "-ar", "8000", "-f", "rtp", "rtp://aServer:aPort");
   pb.inheritIO().start().waitFor();
```
Please give it a try with 1.5-SNAPSHOT before the release: http://bytedeco.org/builds/

**Closed by saudet** 2019-03-24 00:49 UTC
Labels: duplicate, enhancement
