### ISSUE TITLE
Record on filesystem and stream video at the same time

### ISSUE THREAD

**Issue by antoniogiordano** [bytedeco/javacv#367] opened 2016-03-24 16:45 UTC
Hi guys,

it's again me :-)

i'm using the record activity to push a record stream to an RTMP channel, and it works perfectly.
Now i want to show the preview with a certain delay, let me say ~3 seconds ago.
To achieve it i think  i need to push it the stream to the RTMP channel setting the ffmpeg_link to 'rtmp://ecc', and at the same time save it to the filesystem.
In this way i can open the same video, and stream the vidoe with ~3 seconds of delay.

How can i achieve it? 

Thanks

**Comment by saudet** [comment] 2020-11-12 04:24
Duplicate of #1475

**Closed by saudet** 2020-11-12 04:24 UTC
Labels: duplicate, enhancement
