### ISSUE TITLE
FFmpegFrameGrabber不能在docker中初始化,在windows linux下可以

### ISSUE THREAD

**Issue by 354613111** [bytedeco/javacv#2244] opened 2024-07-01 03:39 UTC
![image](https://github.com/bytedeco/javacv/assets/47909289/03559b0d-b02e-487d-920f-c6cdfaecb61e)

**Comment by saudet** [comment] 2024-07-01 03:52
Please follow the instructions at https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by saudet** [comment] 2024-07-01 23:14
I see, this is for Linux in Docker. Please refer to issue https://github.com/bytedeco/javacpp-presets/issues/1379

**Comment by saudet** [comment] 2024-07-01 23:14
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-07-01 23:14 UTC
Labels: duplicate, enhancement, question
