### ISSUE TITLE
Error!!! "avcodec_encode_audio2() error -40: Could not encode audio packet."

### ISSUE THREAD

**Issue by sortjiajun** [bytedeco/javacv#1557] opened 2021-01-04 12:17 UTC
Log
-------------------------------
Info: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://shudoon-prt.oss-cn-shenzhen.aliyuncs.com/mp4/8965f11c107eb4c9b24707a950eb8523.mp4':

Info:   Metadata:

Info:     major_brand     : 
Info: mp42
Info: 

Info:     minor_version   : 
Info: 0
Info: 

Info:     compatible_brands: 
Info: mp42isom
Info: 

Info:     creation_time   : 
Info: 2020-08-26T07:51:13.000000Z
Info: 

Info:     copyright       : 
Info: 

Info:     copyright-eng   : 
Info: 

Info:   Duration: 
Info: 00:00:44.42
Info: , start: 
Info: 0.000000
Info: , bitrate: 
Info: 879 kb/s
Info: 

Info:     Stream #0:0
Info: (und)
Info: : Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
Info:  (default)
Info: 

Info:     Metadata:

Info:       creation_time   : 
Info: 2020-08-26T07:51:13.000000Z
Info: 

Info:     Stream #0:1
Info: (und)
Info: : Video: h264 (High) (avc1 / 0x31637661), yuv420p, 544x960, 746 kb/s
Info: , 
Info: 29.86 fps, 
Info: 29.83 tbr, 
Info: 90k tbn, 
Info: 60 tbc
Info:  (default)
Info: 

Info:     Metadata:

Info:       creation_time   : 
Info: 2020-08-26T07:51:13.000000Z
Info: 

Info:       encoder         : 
Info: JVT/AVC Coding
Info: 

Info: [mp3_mf @ 00000152bd083dc0] MFT name: 'MP3 Encoder ACM Wrapper MFT'

Info: Output #0, mp3, to 'eguid.mp3':

Info:   Metadata:

Info:     TSSE            : 
Info: Lavf58.45.100
Info: 

Info:     Stream #0:0
Info: : Audio: mp3, 44100 Hz, stereo, s16, 192 kb/s
Info: 

Error: [mp3_mf @ 00000152bd083dc0] This encoder requires using the avcodec_send_frame() API.

fail
Error: [mp3_mf @ 00000152bd083dc0] This encoder requires using the avcodec_send_frame() API.

myCode
--------------------------------------------------------------

FFmpegLogCallback.set();
        String url = "https://shudoon-prt.oss-cn-shenzhen.aliyuncs.com/mp4/8965f11c107eb4c9b24707a950eb8523.mp4";
        String outputPath = "eguid.mp3";
        int audioChannel=1;
        int audioBitrate=16;
        int sampleRate=44100;
        int audioCodec=avcodec.AV_CODEC_ID_MP3;

        FFmpegFrameGrabber grabber =null;
        FFmpegFrameRecorder recorder = null;

        try {
            grabber = new FFmpegFrameGrabber(url);

            grabber.start();

            recorder = new FFmpegFrameRecorder(outputPath,grabber.getAudioChannels());

            recorder.setAudioCodec(audioCodec);
            recorder.setAudioOption("crf", "0");
            recorder.setAudioQuality(0);
            //bit rate
            recorder.setAudioBitrate(192000);
            //sample rate
            recorder.setSampleRate(44100);
            recorder.start();
            Frame audioSamples = null;
            for (; ; ) {
                if ((audioSamples = grabber.grab()) != null) {

                    recorder.recordSamples(audioSamples.sampleRate,audioSamples.audioChannels,audioSamples.samples);
                } else {

                    break;
                }

            }

        } catch (org.bytedeco.javacv.FrameGrabber.Exception e1) {
            System.err.println("fail");
        } catch (Exception e) {
            System.err.println("fail");
        }finally {
            if (grabber != null) {
                grabber.close();
            }
            if (recorder != null) {
                recorder.close();
            }
        }

**Comment by saudet** [comment] 2021-01-05 04:25
BTW, if you don't need to use "mp3_mf", we can still use the "libmp3lame" codec with the old API.

**Comment by sortjiajun** [comment] 2021-01-05 05:18
> BTW, if you don't need to use "mp3_mf", we can still use the "libmp3lame" codec with the old API.


I am a noob.
Can you tell me how to do it

**Comment by saudet** [comment] 2021-01-05 05:21
Instead of `setAudioCodec(AV_CODEC_ID_MP3)`, call `setAudioCodecName("libmp3lame")`.

**Comment by sortjiajun** [comment] 2021-01-05 06:07
> setAudioCodecName("libmp3lame")

thank you, it work

**Comment by saudet** [comment] 2021-01-06 15:18
Duplicate of #1238

**Closed by saudet** 2021-01-06 15:18 UTC
Labels: duplicate, enhancement
