### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol 

### ISSUE THREAD

**Issue by sraorao** [bytedeco/javacv#952] opened 2018-04-04 14:44 UTC
Hi,

When using the following in build.gradle for Android,

```
    implementation group: 'org.bytedeco', name: 'javacv', version: '1.4.1'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.2-1.4.1', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.2-1.4.1', classifier: 'android-x86'
```
I get the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
                  Process: com.oxford.srao.playvideo, PID: 15984
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "vp8_short_fdct4x4_sse2" referenced by "/data/app/com.oxford.srao.playvideo-2/lib/x86/libavcodec.so"...
                      at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1220)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:980)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:879)
                      at org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:13)
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:400)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:938)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:895)
                      at org.bytedeco.javacv.FFmpegFrameGrabber.tryLoad(FFmpegFrameGrabber.java:99)
                      at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:122)
                      at com.oxford.srao.playvideo.MainActivity.doConvert(MainActivity.java:133)
                      at com.oxford.srao.playvideo.MainActivity.access$000(MainActivity.java:35)
                      at com.oxford.srao.playvideo.MainActivity$2.run(MainActivity.java:117)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "vp8_short_fdct4x4_sse2" referenced by "/data/app/com.oxford.srao.playvideo-2/lib/x86/libavcodec.so"...
                      at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1220)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:965)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:879) 
                      at org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:13) 
                      at java.lang.Class.classForName(Native Method) 
                      at java.lang.Class.forName(Class.java:400) 
                      at org.bytedeco.javacpp.Loader.load(Loader.java:938) 
                      at org.bytedeco.javacpp.Loader.load(Loader.java:895) 
                      at org.bytedeco.javacv.FFmpegFrameGrabber.tryLoad(FFmpegFrameGrabber.java:99) 
                      at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:122) 
                      at com.oxford.srao.playvideo.MainActivity.doConvert(MainActivity.java:133) 
                      at com.oxford.srao.playvideo.MainActivity.access$000(MainActivity.java:35) 
                      at com.oxford.srao.playvideo.MainActivity$2.run(MainActivity.java:117) 
                      at java.lang.Thread.run(Thread.java:761) 
```

But works fine if I change build.gradle to the following, all other code being identical.
```
    implementation group: 'org.bytedeco', name: 'javacv', version: '1.4'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.0-1.4', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.0-1.4', classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.1-1.4', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.1-1.4', classifier: 'android-x86'
```
Not sure if I am making any mistake here (I am a beginner, just playing with the sample projects right now), but reporting issue just in case this is a bug in the new version. Apologies and feel free to close if not a bug. Thanks!

**Comment by saudet** [comment] 2018-04-04 23:17
Yes, that's a known issue. Marking as duplicate of #945. Please use 1.4.2-SNAPSHOT: http://bytedeco.org/builds/

**Closed by saudet** 2018-04-04 23:17 UTC
