### ISSUE TITLE
How to  use GPU?

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1782] opened 2022-03-21 07:16 UTC
I want to use gpu acceleration in ffmpeg and opencv mat. Is there any doucment or demo?

**Comment by saudet** [comment] 2022-03-21 08:52
For FFmpeg, we can use codecs that supports GPUs: https://trac.ffmpeg.org/wiki/HWAccelIntro

For OpenCV, use GpuMat and UMat, that's what works on GPU.

**Comment by CJL6015** [comment] 2022-03-21 12:38
This is my GPU
![image](https://user-images.githubusercontent.com/42272971/159262478-2a509bbc-eb62-4b85-8ba9-9d4b66d2b8de.png)

**Comment by saudet** [comment] 2022-03-21 12:50
You'll need to use binaries for OpenCV compiled with CUDA, as shown in the README.md file here in the case of Maven:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#the-pomxml-build-file

**Comment by CJL6015** [comment] 2022-03-22 03:13
I add the dependecy of cuda-platform0redist. Do I need to da anything else?
![image](https://user-images.githubusercontent.com/42272971/159400608-98d22ceb-c527-4067-a495-db9d24ae5f21.png)

**Comment by saudet** [comment] 2022-03-22 03:22
You'll need to make sure the latest version of the drivers for your video card are installed on the system.

**Comment by CJL6015** [comment] 2022-03-22 05:44
I have updated the driver to the latest version, but it still doesn't work.
![image](https://user-images.githubusercontent.com/42272971/159415840-c37df793-7ad8-42ca-aa42-e865dd90ddfe.png)

**Comment by saudet** [comment] 2022-03-22 07:05
Set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more messages on the console.

**Comment by CJL6015** [comment] 2022-03-22 07:27
Is it so? It doesn't seem to work.
![image](https://user-images.githubusercontent.com/42272971/159429218-810f7c2e-1384-4772-b63e-96e55592ca20.png)

**Comment by saudet** [comment] 2022-03-22 07:36
You'll need to set it earlier than that. Anyway, there's also issue #1767 that's been fixed recently, so make sure to give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by CJL6015** [comment] 2022-03-22 09:22
I try with the snapshots,but got another error.
![image](https://user-images.githubusercontent.com/42272971/159448145-8f5c376d-a226-4788-9249-f7d616340704.png)

**Comment by saudet** [comment] 2022-03-22 09:30
That means those functions don't work with GPUs. You'll need to find other (similar) functions that do support GPUs.

**Comment by saudet** [comment] 2022-03-22 09:30
Duplicate of #1767

**Closed by saudet** 2022-03-22 09:30 UTC
Labels: bug, duplicate, question

**Comment by CJL6015** [comment] 2022-03-22 10:30
I use the opencv_cudaimgproc.cvtColor,but got another error.
![image](https://user-images.githubusercontent.com/42272971/159462084-d64087aa-bccc-432d-b987-681a0d35658b.png)

**Comment by saudet** [comment] 2022-03-22 11:04
There's some library missing from your system, apparently. Please find out what it is using the Dependencies tool:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by CJL6015** [comment] 2022-03-23 02:33
I use the Dependencies tool,but opencv_cudaimproc and UMat/GpuMat can be loaded normally.Is it because I didn't set the correct module?
![image](https://user-images.githubusercontent.com/42272971/159612524-487f35bb-1452-49d9-85cf-99877cee3768.png)

**Comment by saudet** [comment] 2022-03-23 02:59
You'll need to give it the correct path to the DLL, if that's what you mean, yes. Look inside the JAR file to make sure you have it correctly.

**Comment by CJL6015** [comment] 2022-03-23 03:03
I meanopencv_cudaimgproc can be loaded normally without UnstatisfiedLinkError

**Comment by saudet** [comment] 2022-03-23 03:17
So, everything should be working fine. I don't know what you tell you more.
For me on Windows 10, `opencv_cudaimgproc.cvtColor()` works perfectly.

**Comment by CJL6015** [comment] 2022-03-23 03:24
My system is Winows 11. Will this matter?

**Comment by saudet** [comment] 2022-03-23 03:42
I don't think so, but you can try it on Windows 10 to see if it makes a difference.

**Comment by CJL6015** [comment] 2022-03-25 08:16
Could it be that the package I imported is wrong? I found a same question on stackoverflow:[https://stackoverflow.com/questions/56944945/javacv-with-java-lang-unsatisfiedlinkerror](url).
Here are the packages I'm imported.
![image](https://user-images.githubusercontent.com/42272971/160081521-a6ed890f-5a94-48dc-b107-d01cb06de096.png)

**Comment by saudet** [comment] 2022-03-25 08:19
That doesn't matter. Make sure the "org.bytedeco.javacpp.logger.debug" system property is set to "true" to get possibly useful information displayed on the console.

**Comment by CJL6015** [comment] 2022-03-25 08:24
the "org.bytedeco.javacpp.logger.debug" system property is set to "true",but no more information.
![image](https://user-images.githubusercontent.com/42272971/160082626-f501aca2-5c87-4d60-96d6-2c36088e730b.png)

**Comment by saudet** [comment] 2022-03-25 08:39
It needs to be set earlier.

**Comment by CJL6015** [comment] 2022-03-25 09:11
These libraries failed to load.
`Debug: Loading library zlibwapi
Debug: Failed to load for zlibwapi: java.lang.UnsatisfiedLinkError: no zlibwapi in java.library.path
Debug: Loading library cudart64_110
Debug: Failed to load for cudart64_110: java.lang.UnsatisfiedLinkError: no cudart64_110 in java.library.path
Debug: Loading library cublasLt64_11
Debug: Failed to load for cublasLt64_11: java.lang.UnsatisfiedLinkError: no cublasLt64_11 in java.library.path
Debug: Loading library cublas64_11
Debug: Failed to load for cublas64_11: java.lang.UnsatisfiedLinkError: no cublas64_11 in java.library.path
Debug: Loading library cufft64_10
Debug: Failed to load for cufft64_10: java.lang.UnsatisfiedLinkError: no cufft64_10 in java.library.path
Debug: Loading library cudnn64_8
Debug: Failed to load for cudnn64_8: java.lang.UnsatisfiedLinkError: no cudnn64_8 in java.library.path
Debug: Loading library nppc64_11
Debug: Failed to load for nppc64_11: java.lang.UnsatisfiedLinkError: no nppc64_11 in java.library.path
Debug: Loading library nppial64_11
Debug: Failed to load for nppial64_11: java.lang.UnsatisfiedLinkError: no nppial64_11 in java.library.path
Debug: Loading library nppicc64_11
Debug: Failed to load for nppicc64_11: java.lang.UnsatisfiedLinkError: no nppicc64_11 in java.library.path
Debug: Loading library nppicom64_11
Debug: Failed to load for nppicom64_11: java.lang.UnsatisfiedLinkError: no nppicom64_11 in java.library.path
Debug: Loading library nppidei64_11
Debug: Failed to load for nppidei64_11: java.lang.UnsatisfiedLinkError: no nppidei64_11 in java.library.path
Debug: Loading library nppif64_11
Debug: Failed to load for nppif64_11: java.lang.UnsatisfiedLinkError: no nppif64_11 in java.library.path
Debug: Loading library nppig64_11
Debug: Failed to load for nppig64_11: java.lang.UnsatisfiedLinkError: no nppig64_11 in java.library.path
Debug: Loading library nppim64_11
Debug: Failed to load for nppim64_11: java.lang.UnsatisfiedLinkError: no nppim64_11 in java.library.path
Debug: Loading library nppist64_11
Debug: Failed to load for nppist64_11: java.lang.UnsatisfiedLinkError: no nppist64_11 in java.library.path
Debug: Loading library nppisu64_11
Debug: Failed to load for nppisu64_11: java.lang.UnsatisfiedLinkError: no nppisu64_11 in java.library.path
Debug: Loading library nppitc64_11
Debug: Failed to load for nppitc64_11: java.lang.UnsatisfiedLinkError: no nppitc64_11 in java.library.path
Debug: Loading library npps64_11
Debug: Failed to load for npps64_11: java.lang.UnsatisfiedLinkError: no npps64_11 in java.library.path
Debug: Loading library cudnn_ops_infer64_8
Debug: Failed to load for cudnn_ops_infer64_8: java.lang.UnsatisfiedLinkError: no cudnn_ops_infer64_8 in java.library.path
Debug: Loading library cudnn_ops_train64_8
Debug: Failed to load for cudnn_ops_train64_8: java.lang.UnsatisfiedLinkError: no cudnn_ops_train64_8 in java.library.path
Debug: Loading library cudnn_adv_infer64_8
Debug: Failed to load for cudnn_adv_infer64_8: java.lang.UnsatisfiedLinkError: no cudnn_adv_infer64_8 in java.library.path
Debug: Loading library cudnn_adv_train64_8
Debug: Failed to load for cudnn_adv_train64_8: java.lang.UnsatisfiedLinkError: no cudnn_adv_train64_8 in java.library.path
Debug: Loading library cudnn_cnn_infer64_8
Debug: Failed to load for cudnn_cnn_infer64_8: java.lang.UnsatisfiedLinkError: no cudnn_cnn_infer64_8 in java.library.path
Debug: Loading library cudnn_cnn_train64_8
Debug: Failed to load for cudnn_cnn_train64_8: java.lang.UnsatisfiedLinkError: no cudnn_cnn_train64_8 in java.library.path`

**Comment by saudet** [comment] 2022-03-25 10:16
That just means the redist artifact isn't on the class path. You'll need to
add it, or install CUDA on your machine.
