### ISSUE TITLE
FFmpegFrameRecorder with OutputStream = jvm crash

### ISSUE THREAD

**Issue by mastah84** [bytedeco/javacv#773] opened 2017-08-28 00:22 UTC
This simple Main class grabs BufferedImages from webcam. Unfortunately, after few converted frames, JVM crashes. Outputting to file works ok, but to OutputStream - JVM crashes.

Here are my dependencies:

    <dependencies>
        <dependency>
            <groupId>com.github.sarxos</groupId>
            <artifactId>webcam-capture</artifactId>
            <version>0.3.11</version>
        </dependency>
        <dependency>
            <groupId>com.github.sarxos</groupId>
            <artifactId>webcam-capture-driver-openimaj</artifactId>
            <version>0.3.11</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.3.3</version>
        </dependency>
    </dependencies>

[Main.zip](https://github.com/bytedeco/javacv/files/1254802/Main.zip)

[hs_err_pid10204.zip](https://github.com/bytedeco/javacv/files/1254804/hs_err_pid10204.zip)

:-(

**Comment by mastah84** [comment] 2017-08-28 00:26
Here you have complete project in IntelliJ IDEA, for your convenience.

[webcammy.zip](https://github.com/bytedeco/javacv/files/1254811/webcammy.zip)

**Comment by saudet** [comment] 2017-08-28 21:58
MP4 doesn't support streaming well, you should try another format.

**Comment by saudet** [comment] 2017-09-17 02:10
Marking as duplicate of #775

**Closed by saudet** 2017-09-17 02:10 UTC
Labels: duplicate
