### ISSUE TITLE
How to merge two videos into one video with vstack

### ISSUE THREAD

**Issue by monxarat** [bytedeco/javacv#1062] opened 2018-09-25 08:21 UTC
Hi Guys.

In the FFMPEG, I merge two videos by Command Line below.

`ffmpeg -i test_1.mp4 -i test_2.mp4 -preset ultrafast -filter_complex vstack video_out.mp4`

But honestly, I don't understand how to do this in JavaCV.

**Comment by saudet** [comment] 2018-09-25 08:29
Duplicate of issue #955.

**Closed by saudet** 2018-09-25 08:29 UTC
Labels: duplicate, enhancement

**Comment by monxarat** [comment] 2018-09-25 10:00
The issue #955 have not solved yet.

**Comment by saudet** [comment] 2018-09-25 10:18
Exactly, contributions are welcome!

**Comment by saudet** [comment] 2018-10-28 02:50
I've implemented support for multiple inputs in commit https://github.com/bytedeco/javacv/commit/3c92eef6e3aa21eca170fc8022fd41254cfcc452. You can refer to this sample code, which does what you need: https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L163

Please give it a try with the snapshots: http://bytedeco.org/builds/ Thanks!
