### ISSUE TITLE
FrameRecoder， tune the  voice volume

### ISSUE THREAD

**Issue by linghushaoxia** [bytedeco/javacv#941] opened 2018-03-15 09:21 UTC
Help!Help!
I want to use FrameRecoder to tume the volume of the voice，what params should I set?

**Comment by saudet** [comment] 2018-03-15 12:11
We could use a filter for that, but unfortunately, FFmpegFrameFilter doesn't support audio frames yet... 

Marking this as a duplicate of issue #492. Contributions are welcome!

**Closed by saudet** 2018-03-15 12:11 UTC
Labels: duplicate, enhancement

**Comment by linghushaoxia** [comment] 2018-03-16 04:21
thanks!I see...

**Comment by saudet** [comment] 2018-04-02 14:41
Support for audio frames has been added so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/ 

We can use the [volume](https://ffmpeg.org/ffmpeg-filters.html#volume) filter to change the volume as shown in the unit test: https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L78
