### ISSUE TITLE
FFmpegFrameGrabber.start()  failed  in v1.5.1

### ISSUE THREAD

**Issue by yuyihan666** [bytedeco/javacv#1313] opened 2019-10-10 03:53 UTC
FFmpegFrameGrabber.start()  failed  in  v1.5.1，v1.5  is up and running。

PipedInputStream pis；
grabber = new FFmpegFrameGrabber(pis);
grabber.start();//always waiting

**Comment by saudet** [comment] 2019-10-10 05:16
Duplicate of #1304 and #1298

**Closed by saudet** 2019-10-10 05:16 UTC
Labels: bug, duplicate, enhancement

**Comment by saudet** [comment] 2019-10-10 05:18
Try 1.5.2-SNAPSHOT with `FFmpegFrameGrabber(pis, 0)` instead of `FFmpegFrameGrabber(pis)`.
