### ISSUE TITLE
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

### ISSUE THREAD

**Issue by anujjpandey** [bytedeco/javacv#944] opened 2018-03-21 12:59 UTC
No error in classes but when I click to run the code on android device getting this error

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'org/bytedeco/javacpp/windows-x86_64/api-ms-win-crt-locale-l1-1-0.dll'

**Comment by saudet** [comment] 2018-03-21 13:10
Duplicate of #353

**Closed by saudet** 2018-03-21 13:10 UTC
Labels: duplicate, question
