### ISSUE TITLE
When encoding webp images using umat, the quality parameter does not work

### ISSUE THREAD

**Issue by jpyo0613** [bytedeco/javacv#2010] opened 2023-04-08 21:25 UTC
```
    fun encodeWebP(uMat: UMat): ByteArray {
        val param = IntPointer(1).put(opencv_imgcodecs.IMWRITE_WEBP_QUALITY, 55)
        val bytePointer = BytePointer()
        opencv_imgcodecs.imencode(".webp", uMat, bytePointer, param)
        val length = bytePointer.limit().toInt()
        val result = ByteArray(length)
        bytePointer.get(result)
        return result
    }
```
    
**use UMat result =**
![20230408_003847](https://user-images.githubusercontent.com/33045561/230743125-68fbbcec-784e-4ab2-a534-67407c41b0d7.jpg)

**use Mat result =**
![20230408_003901](https://user-images.githubusercontent.com/33045561/230743126-387fab27-ab2c-4652-bad6-0f48db112a96.jpg)

 Is it a bug in javacv or am I using it incorrectly?

**Comment by saudet** [comment] 2023-04-09 00:36
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1345

**Closed by saudet** 2023-04-09 00:36 UTC
Labels: duplicate, enhancement
