### ISSUE TITLE
Getting "java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil" although platform dependencies are included

### ISSUE THREAD

**Issue by yngvesl** [bytedeco/javacv#109] opened 2015-03-29 15:09 UTC
I've tried to run a simple application with an FFMmpegFrameGrabber.
I've included javacv 0.10 in my pom and ran the
`$ mvn package exec:java -Dplatform.dependencies -Dexec.mainClass=<fqdn to my class>`

However, I get this error:
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:266)
	at org.bytedeco.javacpp.Loader.load(Loader.java:385)
	at org.bytedeco.javacpp.Loader.load(Loader.java:353)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2249)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:346)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:340)

I also tried to build an uber jar and checked that avutil.class actually resided in the jar. Same error.
I run Debian Squeeze kernel 3.2.0.

Any idea, anyone?

**Comment by saudet** [comment] 2015-03-29 23:39
The cause of that exception should be able to tell us what the issue is.
Could copy/paste the cause of that exception as well? Thanks

**Comment by yngvesl** [comment] 2015-03-30 13:22
The cause of that Error seems to be null.

**Comment by yngvesl** [comment] 2015-03-30 13:22
The cause of that Error seems to be null.

**Comment by yngvesl** [comment] 2015-03-30 13:25
The cause of that Error seems to be null.

**Comment by ShihabSoft** [comment] 2015-03-30 13:28
It can't be a null error.
As per your stack trace it is showing that NoClassDefFoundError.
It means the class avutil is not found in the package org.bytedeco.javacpp

So make sure that your dependancies are in the correct place in Android it
is libs.
That means put all additional *.jar to libs folder when you are Eclipse
Android SDK.

And in Android Studio also they are same I think so.

Hope it helps,
ShihabSoft

**Comment by saudet** [comment] 2015-03-30 13:29
Let's see, it's probably caused by an old version of glibc: https://github.com/bytedeco/javacpp-presets/issues/22
If that's the case, a rebuild on your version of Linux should fix that.

**Comment by yngvesl** [comment] 2015-03-30 13:35
Aha, that seems probable. I will upgrade and come back if I'm still stuck. Thank you very much!

ShihabSoft; the Error object and its cause are two different objects, so an Error object can very well have a null cause. And this hasn't anything to do with either Eclipse nor Android; it's a dynamic linking version mismatch, if the hypothesis is correct.

**Comment by ShihabSoft** [comment] 2015-03-30 14:58
Hey Lindal,

If so are you getting a null pointer exception not so ha.

You are getting a NoClassDefFoundError.

And you are getting this stacktrace ,

java.lang.NoClassDefFoundError: Could not initialize class
org.bytedeco.javacpp.avutil
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:266)
at org.bytedeco.javacpp.Loader.load(Loader.java:385)
at org.bytedeco.javacpp.Loader.load(Loader.java:353)
at org.bytedeco.javacpp.avformat$AVFormatContext.(avformat.java:2249)
at
org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:346)
at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:340)

Scenario

At the time of initialization of avutil class.

The org.bytedeco.javacpp.Loader tried to load the class avformat class in
which the sub class named AVFormatContext makes the error NoClassDefFound
error.

Try looking for the avformat class and make sure the avformat is the latest
one that contains the sub class AVFormatContext.

Check for some new classes are introduced in 0.10 version to the prior
version.

It all happens when the grabber.startUnsafe function is called.

That may resolves your problem.

And u r here to solve your problem.
So its ur need.
So please be polite.

And we all together will find a better solution.

Hope u understand,
ShihabSoft

Aha, that seems probable. I will upgrade and come back if I'm still stuck.
Thank you very much!

ShihabSoft; the Error object and its cause are two different objects, so an
Error object can very well have a null cause. And this hasn't anything to
do with either Eclipse nor Android; it's a dynamic linking version
mismatch, if the hypothesis is correct.

--
Reply to this email directly or view it on GitHub
<https://github.com/bytedeco/javacv/issues/109#issuecomment-87684365>.

**Comment by ideastorm** [comment] 2015-04-01 22:41
In case another Windows users runs into this:

I was seeing the exact same error and stack trace (from FFmpegFrameGrabber on).  Debugging the Loader.load method revealed that there was an unsatisfied link error that didn't show up in the error log:
> no jniavutil in java.library.path

I also found that adding a dependency on the org.bytedeco.javacpp-presets:ffmpeg artifact specific to my platform fixed it.  I also had to add the org.bytedeco.javacpp-presets:opencv artifact.

**Comment by yngvesl** [comment] 2015-04-06 15:39
Thank you very much, @saudet. That did the trick!

**Comment by saudet** [comment] 2015-04-07 11:09
Ok, good! Marking as a duplicate of: https://github.com/bytedeco/javacpp-presets/issues/22

**Closed by saudet** 2015-04-07 11:09 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2015-04-07 11:11
@ideastorm I've emphasized the last sentence in the `README.md` file to draw attention. Thanks for the feedback!

**Comment by MarcoVCiotola** [comment] 2015-07-14 02:43
@ideastorm or @saudet, I'm getting the same error, could any of you guys please explain me how to add the artifacts manually? (I'm using windows, maven and IntelliJ). Thanks a lot in advance!.

**Comment by saudet** [comment] 2015-07-14 13:50
@MarcoVCiotola You're under Windows, so GLIBC isn't the issue here. Could you use [Dependency Walker](http://www.dependencywalker.com/) on the DLLs and report what seems to be the problem? Thanks!

**Comment by MarcoVCiotola** [comment] 2015-07-14 23:19
Hi @saudet , I've run Dependency Walker on avutil.dll and it says that API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL, API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL and API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL are missing; but I google those libraries and found that some peolple had the same issue, but most of the times they were not related to those libraries and that the problem lies entirely elsewhere. In this case @ideastorm solve it by adding the artifacts manually, my problem is that I don't know hot to do it :(. If you could be so kind to explain me how to do it I really apreciate it a lot!!. Thanks again for responding even though the issue is closed (I've realized after I posted the question)

**Comment by saudet** [comment] 2015-07-14 23:53
That sounds like Dependency Walker failing as well... The missing
dependency is something else.

**Comment by somesaba** [comment] 2016-05-08 05:21
Hi guys, I am getting the same error with a Raspberry Pi. I'm not exactly sure how to add the platform-specific artifacts manually. I added the org.bytedeco.javacpp-presets:ffmpeg and org.bytedeco.javacpp-presets:opencv to no avail.

**Comment by xswkama** [comment] 2018-03-22 02:58
增加下面的包
 
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>3.4.0-1.4</version>
        </dependency>
        
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>3.4.1-1.4</version>
        </dependency>
