### ISSUE TITLE
FFmpegFrameGrabber ToMat returns null in MP4

### ISSUE THREAD

**Issue by darkfrog26** [bytedeco/javacv#1700] opened 2021-09-22 14:04 UTC
I'm attempting to read from an MP4 file and create a `Mat`, but it's returning null (sorry, it's Scala, but hopefully still readable):

```scala
val grabber = new FFmpegFrameGrabber(new File("PeopleWalking.mp4").getAbsolutePath)
grabber.setFormat("mp4")
grabber.start()
val frame = grabber.grab()
println(s"Frame: $frame")
val converter = new OpenCVFrameConverter.ToMat()
val grabbedImage = converter.convert(frame)
println(s"Grabbed Image: $grabbedImage")
```

The output I see is:
```
[error] Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/mhicks/projects/prototype/javacvtest/PeopleWalking.mp4':
[error]   Metadata:
[error]     major_brand     : isom
[error]     minor_version   : 512
[error]     compatible_brands: isomiso2avc1mp41
[error]     encoder         : Lavf58.76.100
[error]   Duration: 00:01:15.23, start: 0.000000, bitrate: 5560 kb/s
[error]   Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 5431 kb/s, 50 fps, 50 tbr, 90k tbn, 100 tbc (default)
[error]     Metadata:
[error]       handler_name    : VideoHandler
[error]       vendor_id       : [0][0][0][0]
[error]   Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
[error]     Metadata:
[error]       handler_name    : SoundHandler
[error]       vendor_id       : [0][0][0][0]
[info] Frame: org.bytedeco.javacv.Frame@1ed1993a
[info] Grabbed Image: null
```

I'm not sure if this is a bug or I'm just doing it wrong, but I'm able to load and test the MP4 file in VLC and it was created in the first place from ffmpeg.

**Comment by darkfrog26** [comment] 2021-09-22 17:52
Interesting. It would appear that using `grabImage()` instead of `grab()` actually works. This would seem to be a bug?

**Comment by bradh** [comment] 2021-09-22 21:38
grab vs grabImage is very similar - it calls the same code with different flags for audio and data. Maybe your video has something on the start that is not an image? So the first grab does return data, just not an image frame.  Perhaps you just need to loop until you get the first image?

**Comment by saudet** [comment] 2021-09-22 23:18
OpenCVFrameConverter is going to return null on audio frames, yes, that's normal. If you're only interested in grabImage(), that's the one you should call.

**Comment by saudet** [comment] 2021-09-22 23:19
Duplicate of #116

**Closed by saudet** 2021-09-22 23:19 UTC
Labels: duplicate, question
