### ISSUE TITLE
how to stop av_read_frame() when the connection lost

### ISSUE THREAD

**Issue by NacyLiu** [bytedeco/javacv#462] opened 2016-07-24 12:33 UTC
I want to stop the av_read_frame() when the connection lost, i found avioInterruptCB can do this, but there is no explanation about it, can you give me an example?

**Comment by saudet** [comment] 2016-07-24 13:50
There's some info here:
https://github.com/bytedeco/javacv/issues/170
https://github.com/bytedeco/javacv/issues/97

**Comment by saudet** [comment] 2016-07-24 13:55
Marking as duplicate of https://github.com/bytedeco/javacv/issues/430

**Closed by saudet** 2016-07-24 13:55 UTC
Labels: enhancement, question

**Comment by saudet** [comment] 2017-06-15 03:23
FYI, it turns out that we only need to set the "timeout", "rw_timeout" or "stimeout" option, depending on the protocol. Thanks to @d-a-gerashenko we now have working sample code for this:
https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java
