### ISSUE TITLE
Push streaming cpu usage rate is high

### ISSUE THREAD

**Issue by zhangwei941913953** [bytedeco/javacv#1615] opened 2021-03-29 09:19 UTC
We use javacv's FFmpegFrameGrabber to capture the bare media stream from the streaming media gateway, and then use the record() method of FFmpegFrameRecoder to push the frame data obtained from FFmpegFrameGrabber to the srs server. This solution is feasible, but the problem now is that the CPU occupancy rate is very high. Push 8 video streaming servers and then hang up, the initial suspected is that the server cpu occupancy rate caused by the codec is too high. We plan to use the recordPacket method to push AVPacket packets to the srs server. We want to avoid encoding and decoding actions in this way. Is this feasible?

**Comment by saudet** [comment] 2021-03-29 10:15
Yes, that's what FFmpegFrameGrabber.grabPacket() and FFmpegFrameRecoder.recordPacket() are for.

**Comment by saudet** [comment] 2021-04-01 02:53
Those calls are known to be a bit buggy though, so if you're having any problems with them, let's continue this discussion at #818.

**Comment by saudet** [comment] 2021-04-01 02:54
Duplicate of #818

**Closed by saudet** 2021-04-01 02:54 UTC
Labels: bug, duplicate
