### ISSUE TITLE
Couldn't find "libjniContext.so"

### ISSUE THREAD

**Issue by ulohani90** [bytedeco/javacv#1372] opened 2020-01-21 13:53 UTC
`Frame frame = new Frame(screenWidth, screenHeight, Frame.DEPTH_UBYTE, 2);`

The above line gives the following exception

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.android/com.test.android.ui.activities.ScreenRecordingActivityNew}: java.lang.RuntimeException: No native JavaCPP library in memory. (Has Loader.load() been called?)`

On Adding 
`Loader.load();` 
before instantiating frame object, I get the below mentioned exception. 

`Process: com.test.android, PID: 26610
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.android-1/lib/arm64, /data/app/com.test.android-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libjniContext.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
        at com.test.android.ui.activities.ScreenRecordingActivityNew.onCreate(ScreenRecordingActivityNew.java:187)
        at android.app.Activity.performCreate(Activity.java:6875)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) `

I have used the following implementation in build.gradle
`implementation(group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.2')`

Am I missing something over here or is there any issue with the library?

**Comment by saudet** [comment] 2020-01-21 14:31
That's a known limitation. See issue #1305 for more details.

**Comment by saudet** [comment] 2020-01-21 14:31
Duplicate of #1305.

**Closed** 2020-01-21 14:32 UTC
Labels: duplicate, enhancement
