### ISSUE TITLE
1.5.6 FFmpegFrameGrabber could not grab frame

### ISSUE THREAD

**Issue by luunn54** [bytedeco/javacv#1677] opened 2021-07-31 12:13 UTC
after upgrade to ver 1.5.6, some of my unit tests fails

Test code:
```
        try {
            FFmpegLogCallback.set();

            FFmpegFrameGrabber g = new FFmpegFrameGrabber("1.avi");
            g.start();

            int i = 0;
            while (true) {
                Frame frame = g.grab();
                if (frame == null) {
                    System.out.println("end " + i);
                    break;
                }
                i++;
            }

            g.stop();
        } catch (FFmpegFrameGrabber.Exception e) {
            e.printStackTrace();
        }
```

OS: Mac and Centos
Version: 1.5.6-snapshot
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.6-SNAPSHOT</version>
        </dependency>
Test video:
[1.avi.zip](https://github.com/bytedeco/javacv/files/6911141/1.avi.zip)

**Comment by saudet** [comment] 2021-07-31 12:51
What's the error message that you get on the console?

**Comment by luunn54** [comment] 2021-07-31 13:15
thanks @saudet for your reply, below is the console log:

```
(1) Could not find the CLEyeMulticam.dll
(2) Could not find the CLEyeMulticam.dll
Info: [avi @ 0x7f99de937400] non-interleaved AVI

Info: Input #0, avi, from '1.avi':

Info:   Duration: 
Info: 00:00:40.80
Info: , start: 
Info: 0.000000
Info: , bitrate: 
Info: 411 kb/s
Info: 

Info:   Stream #0:0
Info: : Video: vmnc (VMnc / 0x636E4D56), bgr0, 1268x961, 407 kb/s
Info: , 
Info: 5 fps, 
Info: 5 tbr, 
Info: 5 tbn, 
Info: 5 tbc
Info: 

Warning: [avi @ 0x7f99de937400] Packet corrupt (stream = 0, dts = 177)
Warning: .

Error: [vmnc @ 0x7f99dd909e00] Premature end of data!

org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avcodec_send_packet() error -1094995529: Error sending a video packet for decoding. (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame(FFmpegFrameGrabber.java:1372)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grab(FFmpegFrameGrabber.java:1280)
	at abc.Test.main(Test.java:23)
```

**Comment by saudet** [comment] 2021-07-31 14:34
Sounds like a duplicate of #1673: You can probably ignore that error.

**Comment by saudet** [comment] 2021-08-02 02:27
Duplicate of #1673

**Closed by saudet** 2021-08-02 02:27 UTC
Labels: bug, duplicate
