### ISSUE TITLE
No pixel format info in Frame

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1173] opened 2019-04-03 13:58 UTC
Currently there's no way of determining `Frame`'s pixel format, which make's using it not very convenient. Even JavaCV image converters assume a given format has been used, based on things like number of channels (which isn't obviously sufficient information).

**Comment by saudet** [comment] 2019-04-03 14:04
Duplicate of #1075

Many libraries such as OpenCV, Leptonica, NumPy, and TensorFlow do not specify any pixel format in their data structures. If you have any suggestions on how we should proceed, please don't hesitate to make a contribution!

**Closed by saudet** 2019-04-03 14:04 UTC
Labels: duplicate, enhancement

**Comment by b005t3r** [comment] 2019-04-03 14:56
Well, I'd still add it to `Frame` and if not available simply set it to `AV_PIX_FMT_NONE`, if it's unknown, and if it can be determined, I don't see why not set it to the right value.

**Comment by saudet** [comment] 2019-04-03 22:54
That's AVFrame specific, and it's already available from Frame.opaque.

**Comment by saudet** [comment] 2019-04-04 02:46
And we could use it in FFmpegFrameRecorder when it's available. Good point! Let's add it.

**Comment by saudet** [comment] 2019-04-06 01:55
To be clear, of course we need to have something to describe the data, but that means we need to come up with a list of pixel formats to support and add them to Frame and the relevant converters. This is really only needed to support features like what is needed to fix issue #1175, so that's why I'm saying it's a "duplicate", not because we don't need something like this. People like you complain a lot, but it would be nice it you could help too once in a while. :)
