### ISSUE TITLE
No jniopencv_core in java.library.path on Odroid X2 Ubuntu 14.04

### ISSUE THREAD

**Issue by tbolle** [bytedeco/javacv#52] opened 2014-11-12 22:40 UTC
I am trying to get JavaCV running on my Odroid X2 ARM based board with Ubuntu 14.04 LTS. I have got a simple demo program, where I want to connect to a camera attached an output the video stream. On my windows PC it works perfectly, but running the jar on the Odroid causes the following errors:

    Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
       at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
    Caused by: java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
        at org.bytedeco.javacpp.Loader.load(Loader.java:410)
        at org.bytedeco.javacpp.Loader.load(Loader.java:353)
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.bytedeco.javacpp.Loader.load(Loader.java:385)
        at org.bytedeco.javacpp.Loader.load(Loader.java:353)
        at org.bytedeco.javacpp.opencv_highgui.<clinit>(opencv_highgui.java:13)
        at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:174)
        at CameraTest.main(CameraTest.java:11)
        ... 5 more
    Caused by: java.lang.UnsatisfiedLinkError: no tbb in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
        at org.bytedeco.javacpp.Loader.load(Loader.java:401)
        ... 14 more

I had nearly the same problem on my MacBook Pro. Changing the library file opencv.jar to opencv-2.4.10-0.9.1-20141109.113201-4-macosx-x86_64.jar was the solution.

Are you able to help?

Thanks!

**Comment by saudet** [comment] 2015-07-04 03:25
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/37

Please post comments regarding a `linux-arm` build over there, thank you!

**Closed by saudet** 2015-07-04 03:25 UTC
Labels: duplicate, enhancement
