### ISSUE TITLE
overlay a image on video does not working

### ISSUE THREAD

**Issue by lisandrasc** [bytedeco/javacv#672] opened 2017-04-13 18:51 UTC
Hello Samuel, I try to overlay a image on video. But does not working for me. Can you help me? 

this is my code:

mVideoGrabber.start();
            mVideoRecorder = new FFmpegFrameRecorder(mDirectory +"/video" + System.currentTimeMillis() + ".mp4", mVideoGrabber.getImageWidth(), mVideoGrabber.getImageHeight(), audioChannel);
            mVideoRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
            mVideoRecorder.setVideoBitrate(mBitRate);
            mVideoRecorder.start();
            try{
                mFilter = new FFmpegFrameFilter("movie="+ file.getAbsolutePath() +" [logo];[in][logo]overlay=0:0:format=rgb[out]",mVideoGrabber.getImageWidth(), mVideoGrabber.getImageHeight());
                mFilter.start();
            } catch (FrameFilter.Exception e){
                Log.e(TAG,"Error while starting filter: "+e.getMessage());
                e.printStackTrace();
            }

            while ((tempVideoFrame = mVideoGrabber.grab()) != null) {
                if(mVideoGrabber.getTimestamp() > mVideoRecorder.getTimestamp())
                {
                    mVideoRecorder.setTimestamp(mVideoGrabber.getTimestamp());
                }
                if(tempVideoFrame.image!=null){
                    mFilter.push(tempVideoFrame);
                    tempVideoFrame = mFilter.pull();
                    mVideoRecorder.record(tempVideoFrame);
                }
                mVideoRecorder.record(tempVideoFrame);
            }
            mFilter.stop();
            mVideoRecorder.stop();
            mVideoRecorder.release();
            mVideoGrabber.stop();
            mVideoGrabber.release();

The log:

04-13 20:01:23.451: I/System.out(21911): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Teste.mp4':
04-13 20:01:23.451: I/System.out(21911): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Teste.mp4':
04-13 20:01:23.451: I/System.out(21911):   Metadata:
04-13 20:01:23.451: I/System.out(21911):   Metadata:
04-13 20:01:23.451: I/System.out(21911):     major_brand     : 
04-13 20:01:23.451: I/System.out(21911):     major_brand     : 
04-13 20:01:23.451: I/System.out(21911): mp42
04-13 20:01:23.451: I/System.out(21911): mp42
04-13 20:01:23.451: I/System.out(21911):     minor_version   : 
04-13 20:01:23.451: I/System.out(21911):     minor_version   : 
04-13 20:01:23.451: I/System.out(21911): 0
04-13 20:01:23.451: I/System.out(21911): 0
04-13 20:01:23.451: I/System.out(21911):     compatible_brands: 
04-13 20:01:23.451: I/System.out(21911):     compatible_brands: 
04-13 20:01:23.451: I/System.out(21911): mp42mp41isomavc1
04-13 20:01:23.451: I/System.out(21911): mp42mp41isomavc1
04-13 20:01:23.451: I/System.out(21911):     creation_time   : 
04-13 20:01:23.451: I/System.out(21911):     creation_time   : 
04-13 20:01:23.451: I/System.out(21911): 2015-12-04T23:40:28.000000Z
04-13 20:01:23.451: I/System.out(21911): 2015-12-04T23:40:28.000000Z
04-13 20:01:23.451: I/System.out(21911):   Duration: 
04-13 20:01:23.451: I/System.out(21911):   Duration: 
04-13 20:01:23.451: I/System.out(21911): 00:01:01.87
04-13 20:01:23.451: I/System.out(21911): 00:01:01.87
04-13 20:01:23.451: I/System.out(21911): , start: 
04-13 20:01:23.451: I/System.out(21911): , start: 
04-13 20:01:23.451: I/System.out(21911): 0.000000
04-13 20:01:23.451: I/System.out(21911): 0.000000
04-13 20:01:23.451: I/System.out(21911): , bitrate: 
04-13 20:01:23.451: I/System.out(21911): , bitrate: 
04-13 20:01:23.451: I/System.out(21911): 399 kb/s
04-13 20:01:23.451: I/System.out(21911): 399 kb/s
04-13 20:01:23.451: I/System.out(21911):     Stream #0:0
04-13 20:01:23.451: I/System.out(21911):     Stream #0:0
04-13 20:01:23.451: I/System.out(21911): (und)
04-13 20:01:23.451: I/System.out(21911): (und)
04-13 20:01:23.451: I/System.out(21911): : Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt470bg), 480x270 [SAR 1:1 DAR 16:9], 293 kb/s
04-13 20:01:23.451: I/System.out(21911): : Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt470bg), 480x270 [SAR 1:1 DAR 16:9], 293 kb/s
04-13 20:01:23.451: I/System.out(21911): , 
04-13 20:01:23.451: I/System.out(21911): , 
04-13 20:01:23.451: I/System.out(21911): 23.98 fps, 
04-13 20:01:23.451: I/System.out(21911): 23.98 fps, 
04-13 20:01:23.451: I/System.out(21911): 23.98 tbr, 
04-13 20:01:23.451: I/System.out(21911): 23.98 tbr, 
04-13 20:01:23.451: I/System.out(21911): 24k tbn, 
04-13 20:01:23.451: I/System.out(21911): 24k tbn, 
04-13 20:01:23.451: I/System.out(21911): 47.95 tbc
04-13 20:01:23.451: I/System.out(21911): 47.95 tbc
04-13 20:01:23.451: I/System.out(21911):  (default)
04-13 20:01:23.451: I/System.out(21911):  (default)
04-13 20:01:23.451: I/System.out(21911):     Metadata:
04-13 20:01:23.451: I/System.out(21911):     Metadata:
04-13 20:01:23.451: I/System.out(21911):       creation_time   : 
04-13 20:01:23.451: I/System.out(21911):       creation_time   : 
04-13 20:01:23.451: I/System.out(21911): 2015-12-04T23:40:28.000000Z
04-13 20:01:23.451: I/System.out(21911): 2015-12-04T23:40:28.000000Z
04-13 20:01:23.451: I/System.out(21911):       handler_name    : 
04-13 20:01:23.451: I/System.out(21911):       handler_name    : 
04-13 20:01:23.451: I/System.out(21911): L-SMASH Video Handler
04-13 20:01:23.451: I/System.out(21911): L-SMASH Video Handler
04-13 20:01:23.451: I/System.out(21911):       encoder         : 
04-13 20:01:23.451: I/System.out(21911):       encoder         : 
04-13 20:01:23.451: I/System.out(21911): AVC Coding
04-13 20:01:23.451: I/System.out(21911): AVC Coding
04-13 20:01:23.451: I/System.out(21911):     Stream #0:1
04-13 20:01:23.451: I/System.out(21911):     Stream #0:1
04-13 20:01:23.451: I/System.out(21911): (und)
04-13 20:01:23.451: I/System.out(21911): (und)
04-13 20:01:23.451: I/System.out(21911): : Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 102 kb/s
04-13 20:01:23.451: I/System.out(21911): : Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 102 kb/s
04-13 20:01:23.451: I/System.out(21911):  (default)
04-13 20:01:23.451: I/System.out(21911):  (default)
04-13 20:01:23.451: I/System.out(21911):     Metadata:
04-13 20:01:23.451: I/System.out(21911):     Metadata:
04-13 20:01:23.451: I/System.out(21911):       creation_time   : 
04-13 20:01:23.451: I/System.out(21911):       creation_time   : 
04-13 20:01:23.451: I/System.out(21911): 2015-12-04T23:40:28.000000Z
04-13 20:01:23.451: I/System.out(21911): 2015-12-04T23:40:28.000000Z
04-13 20:01:23.451: I/System.out(21911):       handler_name    : 
04-13 20:01:23.451: I/System.out(21911):       handler_name    : 
04-13 20:01:23.451: I/System.out(21911): L-SMASH Audio Handler
04-13 20:01:23.451: I/System.out(21911): L-SMASH Audio Handler

04-13 20:01:24.041: I/System.out(21911): [libx264 @ 0xf4310000] using cpu capabilities: ARMv6 NEON
04-13 20:01:24.041: I/System.out(21911): [libx264 @ 0xf4310000] using cpu capabilities: ARMv6 NEON
04-13 20:01:24.051: I/System.out(21911): [libx264 @ 0xf4310000] profile High, level 3.2
04-13 20:01:24.051: I/System.out(21911): [libx264 @ 0xf4310000] profile High, level 3.2
04-13 20:01:24.051: I/System.out(21911): [libx264 @ 0xf4310000] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=8 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=10000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
04-13 20:01:24.051: I/System.out(21911): [libx264 @ 0xf4310000] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=8 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=10000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
04-13 20:01:24.121: I/System.out(21911): Output #0, mp4, to '/storage/emulated/0/Edited Video/video1492106483979.mp4':
04-13 20:01:24.121: I/System.out(21911): Output #0, mp4, to '/storage/emulated/0/Edited Video/video1492106483979.mp4':
04-13 20:01:24.121: I/System.out(21911):   Metadata:
04-13 20:01:24.121: I/System.out(21911):   Metadata:
04-13 20:01:24.121: I/System.out(21911):     encoder         : 
04-13 20:01:24.121: I/System.out(21911):     encoder         : 
04-13 20:01:24.121: I/System.out(21911): Lavf57.56.100
04-13 20:01:24.121: I/System.out(21911): Lavf57.56.100
04-13 20:01:24.121: I/System.out(21911):     Stream #0:0
04-13 20:01:24.121: I/System.out(21911):     Stream #0:0
04-13 20:01:24.121: I/System.out(21911): : Video: h264 (Constrained Baseline) ([33][0][0][0] / 0x0021), yuv420p, 480x270, q=2-31, 10000 kb/s
04-13 20:01:24.121: I/System.out(21911): : Video: h264 (Constrained Baseline) ([33][0][0][0] / 0x0021), yuv420p, 480x270, q=2-31, 10000 kb/s
04-13 20:01:24.121: I/System.out(21911): , 
04-13 20:01:24.121: I/System.out(21911): , 
04-13 20:01:24.121: I/System.out(21911): 15360 tbn
04-13 20:01:24.121: I/System.out(21911): 15360 tbn
04-13 20:01:24.121: I/System.out(21911):     Stream #0:1
04-13 20:01:24.121: I/System.out(21911):     Stream #0:1
04-13 20:01:24.121: I/System.out(21911): : Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, mono, fltp, 64 kb/s
04-13 20:01:24.121: I/System.out(21911): : Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, mono, fltp, 64 kb/s
04-13 20:01:24.911: W/System.err(21911): Warning: [swscaler @ 0xd5448000] No accelerated colorspace conversion found from yuv420p to bgr24.
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] frame I:28    Avg QP: 1.07  size: 38314
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] frame I:28    Avg QP: 1.07  size: 38314
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] frame P:808   Avg QP: 1.16  size: 27925
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] frame P:808   Avg QP: 1.16  size: 27925
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] frame B:2130  Avg QP: 1.28  size:  6360
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] frame B:2130  Avg QP: 1.28  size:  6360
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] consecutive B-frames:  1.2%  7.3%  5.0% 86.4%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] consecutive B-frames:  1.2%  7.3%  5.0% 86.4%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] mb I  I16..4: 29.4%  7.2% 63.4%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] mb I  I16..4: 29.4%  7.2% 63.4%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] mb P  I16..4:  5.6%  2.9% 10.4%  P16..4: 29.3% 14.7% 14.2%  0.0%  0.0%    skip:22.8%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] mb P  I16..4:  5.6%  2.9% 10.4%  P16..4: 29.3% 14.7% 14.2%  0.0%  0.0%    skip:22.8%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] mb B  I16..4:  0.3%  0.2%  0.8%  B16..8: 20.0%  4.4%  3.0%  direct: 2.7%  skip:68.7%  L0:64.9% L1:30.4% BI: 4.7%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] mb B  I16..4:  0.3%  0.2%  0.8%  B16..8: 20.0%  4.4%  3.0%  direct: 2.7%  skip:68.7%  L0:64.9% L1:30.4% BI: 4.7%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] final ratefactor: -16.37
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] final ratefactor: -16.37
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] 8x8 transform intra:14.0% inter:21.5%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] 8x8 transform intra:14.0% inter:21.5%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] coded y,uvDC,uvAC intra: 77.5% 81.5% 76.9% inter: 27.5% 29.3% 29.0%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] coded y,uvDC,uvAC intra: 77.5% 81.5% 76.9% inter: 27.5% 29.3% 29.0%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] i16 v,h,dc,p: 48% 26% 15% 11%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] i16 v,h,dc,p: 48% 26% 15% 11%
04-13 20:02:01.471: I/System.out(21911): [libx264 @ 0xf4310000] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 29% 27%  2%  2%  2%  3%  3%  4%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 29% 27%  2%  2%  2%  3%  3%  4%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 31% 14%  4%  5%  4%  6%  4%  5%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 31% 14%  4%  5%  4%  6%  4%  5%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] i8c dc,h,v,p: 50% 23% 20%  7%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] i8c dc,h,v,p: 50% 23% 20%  7%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] Weighted P-Frames: Y:4.2% UV:3.1%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] Weighted P-Frames: Y:4.2% UV:3.1%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] ref P L0: 76.4%  5.2% 13.8%  4.6%  0.1%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] ref P L0: 76.4%  5.2% 13.8%  4.6%  0.1%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] ref B L0: 87.8%  8.2%  4.0%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] ref B L0: 87.8%  8.2%  4.0%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] ref B L1: 99.6%  0.4%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] ref B L1: 99.6%  0.4%
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] kb/s:3008.73
04-13 20:02:01.481: I/System.out(21911): [libx264 @ 0xf4310000] kb/s:3008.73
04-13 20:02:01.491: I/System.out(21911): [aac @ 0xf4310c00] Qavg: 369.648
04-13 20:02:01.491: I/System.out(21911): [aac @ 0xf4310c00] Qavg: 369.648
04-13 20:02:01.501: D/VideoProcessing(21911): time:38.234
04-13 20:02:01.501: D/VideoProcessing(21911): Finish

**Comment by saudet** [comment] 2017-04-14 03:00
Could you explain what is the issue?

**Comment by lisandrasc** [comment] 2017-04-14 04:14
I'm trying to add image with transparent background on the video, using ffmpegframefilter on each frame. But the image is not being displayed.

**Comment by saudet** [comment] 2017-04-14 04:26
So, you would like to display images? That would be a duplicate of #668.

**Comment by lisandrasc** [comment] 2017-04-14 16:41
I don't want to record from camera. I have a saved video and I want to edit it adding a image on each frame, like a logo, and save in other file. 
I used this same code to apply sepia in video file, using ffmpegframefilter with colorchannelmixer and it's ok, but when I change the filter to "movie="+ file.getAbsolutePath() +" [logo];[in][logo]overlay=0:0:format=rgb[out]" the video is saved without my image.

**Comment by saudet** [comment] 2017-04-14 23:21
What is `file.getAbsolutePath()`?

**Comment by lisandrasc** [comment] 2017-04-15 02:36
It's the path of the image: "/storage/emulated/0/Image.png"

**Comment by saudet** [comment] 2017-04-15 03:38
Ok, so you've got only one frame, not sure this is supposed to work. Does
the same work on other platforms? Or is it just not working on Android?

**Comment by lisandrasc** [comment] 2017-04-15 14:07
I need this only for android. I have not tested on other platforms.

**Comment by saudet** [comment] 2017-04-15 14:32
I know, but I am asking you: Does it work on other platforms? Yes or no?

**Comment by saudet** [comment] 2017-04-15 14:43
Sounds like a duplicate of #667 

If you ever feel like helping a bit, it would be appreciated.

But thank you for reporting at least

**Closed by saudet** 2017-04-15 14:43 UTC
Labels: duplicate

**Comment by lisandrasc** [comment] 2017-04-15 21:02
Thank you for your help!
And congratulations on the great work!

**Comment by saudet** [comment] 2018-03-31 04:31
This has been fixed with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/
