### ISSUE TITLE
Wrong colors when using Java2DFrameUtils to convert BufferedImage to Mat

### ISSUE THREAD

**Issue by waicool20** [bytedeco/javacv#1323] opened 2019-10-29 08:45 UTC
I'm trying to use Java2DFrameUtils class to convert my BufferedImage to Mat but it seems the R and B channel get mixed up in certain cases and I'm not able to assert what factor comes to play since some images show up just fine while others don't. I've checked the image properties through gimp and don't seem to see any problems between the cases.

I wrote this in kotlin hope you don't mind, the images here are random ones I found laying around as well.
```kotlin
import org.bytedeco.javacv.Java2DFrameUtils
import org.bytedeco.opencv.global.opencv_highgui
import java.io.File
import javax.imageio.ImageIO

fun main() {
    val image = ImageIO.read(File("Vim Cheat Sheet.png"))
    val imageMat = Java2DFrameUtils.toMat(image)

    opencv_highgui.imshow("Test", imageMat)
    opencv_highgui.waitKey()
}
```
Here's the original image: 
![Vim Cheat Sheet](https://user-images.githubusercontent.com/5538666/67750690-af895080-fa6a-11e9-9521-215619dd6aca.png)

And this is what shows up: 
![image](https://user-images.githubusercontent.com/5538666/67750704-b6b05e80-fa6a-11e9-9487-6cded1ac6724.png)

---------
Another example: 
![calculator](https://user-images.githubusercontent.com/5538666/67750744-c8920180-fa6a-11e9-8e18-177f39ddcf43.png)
![image](https://user-images.githubusercontent.com/5538666/67750778-d8114a80-fa6a-11e9-9c18-66570cf2932d.png)

---------------------
This one works fine somehow
![World Of Warships Iowa Class BB Missouri](https://user-images.githubusercontent.com/5538666/67750880-0abb4300-fa6b-11e9-85e3-0a8206df4b92.png)

![image](https://user-images.githubusercontent.com/5538666/67750941-2292c700-fa6b-11e9-84b0-f10b08b293e0.png)

---------
And of course
![bytedeco](https://user-images.githubusercontent.com/5538666/67751050-5f5ebe00-fa6b-11e9-995c-37188599a67f.png)
![image](https://user-images.githubusercontent.com/5538666/67751054-61c11800-fa6b-11e9-8865-953f1d0e26bf.png)

**Comment by saudet** [comment] 2019-10-29 11:09
You need to invert the R and B channels. To do that easily, we can set the `flipChannels` argument of `Java2DFrameConverter.getBufferedImage()` and/or `Java2DFrameConverter.getFrame()` to `true`.

**Comment by saudet** [comment] 2019-10-29 11:10
Duplicate of #1053

**Closed by saudet** 2019-10-29 11:10 UTC
Labels: duplicate, question

**Comment by saudet** [comment] 2019-10-29 11:18
As to why it sometimes happens and sometimes doesn't, that's just how ImageIO and OpenCV work. You can refer to issues #181 and #1075 for additional information about this.
