### ISSUE TITLE
FFmpegFrameGrabber not working in latest version 1.5.7

### ISSUE THREAD

**Issue by khalidwaleed0** [bytedeco/javacv#1774] opened 2022-03-10 12:19 UTC
This is my code :
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("desktop");
grabber.setFormat("gdigrab");
grabber.setFrameRate(30);
grabber.start();

It gives me this error

org.bytedeco.javacv.FFmpegFrameGrabber$Exception: av_find_input_format() error: Could not find input format "gdigrab". (For more details, make sure FFmpegLogCallback.set() has been called.)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:881)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:849)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:844)
	at Main.main(Main.java:11)

Same code works if I downgraded javacv to 1.5.6

**Comment by saudet** [comment] 2022-03-10 12:40
Call FFmpegFrameGrabber.tryLoad() before anything else.

**Comment by saudet** [comment] 2022-03-10 12:41
Duplicate of #1756.

**Closed by saudet** 2022-03-10 12:41 UTC
Labels: bug, duplicate
