### ISSUE TITLE
java.lang.unsatisfiedlinkerror  akaze init final

### ISSUE THREAD

**Issue by itqxsab136681** [bytedeco/javacv#1982] opened 2023-02-09 17:40 UTC
linux
1.5.8

import org.bytedeco.opencv.opencv_features2d.*;
AKAZE akaze = AKAZE.create(); 

Method threw 'java.lang.UnsatisfiedLinkError' exception.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.***.common.tracer.BizRuntimeException: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.opencv.opencv_features2d.AKAZE

**Comment by saudet** [comment] 2023-02-10 00:25
Please include **ALL** the JAR files in your class path.

**Comment by itqxsab136681** [comment] 2023-02-10 03:07
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.5.8</version>
  </dependency>

i'm used all platform，it's ok local good,but remote error for linux-x86_64

**Comment by saudet** [comment] 2023-02-10 03:08
Are you sure your Linux distribution is compatible with CentOS 7? In particular, it's not Alpine?

**Comment by itqxsab136681** [comment] 2023-02-10 03:13
i'm sry,One thing I missed is that akaze cannot be successfully initialized, and other classes are normal (including not limited to mat, classes under improc, etc.)。Please help to confirm whether it is caused by the special environment of linux。

**Comment by saudet** [comment] 2023-02-10 04:24
Works fine on my Linux machine. 
```
        AKAZE akaze = AKAZE.create();
        System.out.println(akaze);
```
Displays something like this:
```
org.bytedeco.opencv.opencv_features2d.AKAZE[address=0x7fb208ee41a0,position=0,limit=0,capacity=0,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fb208ee40b0,deallocatorAddress=0x7fb1491dcc50]]
```
Must be something else unrelated to Linux...

**Comment by saudet** [comment] 2023-02-10 11:22
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by itqxsab136681** [comment] 2023-02-11 04:59
Hello,  I can see that the console has printed relevant logs after setting the properties of native, but my remote linux platform has a separate log system, and I still cannot see detailed error messages . I speculate that it may be an error caused by the abnormality of the link library related to feature detection. The only difference between mine and normal operation is the environment. in CentOS 7

**Comment by saudet** [comment] 2023-02-18 03:04
If your log system is compatible with SLF4J, please set "org.bytedeco.javacpp.logger" to "slf4j" instead.

**Comment by itqxsab136681** [comment] 2023-02-23 08:08
Thank you very much, this problem was finally solved, mainly by installing a new gtk2 in docker.

**Comment by saudet** [comment] 2023-02-23 13:38
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/593

**Closed by saudet** 2023-02-23 13:38 UTC
Labels: duplicate, enhancement, question
