### ISSUE TITLE
What value will get for unknown face recognition

### ISSUE THREAD

**Issue by sudipsadhukhan0295** [bytedeco/javacv#1277] opened 2019-08-21 09:26 UTC
Hi, In LBPHFacerecognizer, I got proper `predictlabel` value when known face is recognized but for unknown face recognizer i get random `predictlabel`. How to recognized the unknown face is recognized.?
Here is my code:

`

        MatVector images = new MatVector(imageFiles.length);

        Mat labels = new Mat(imageFiles.length, 1, CV_32SC1);
        IntBuffer labelsBuf = labels.createBuffer();

        int counter = 0;

        for (File image : imageFiles) {
            Mat img = imread(image.getAbsolutePath(), IMREAD_GRAYSCALE);

            int label = Integer.parseInt(image.getName().split("\\.")[0]);
            images.put(counter, img);

            labelsBuf.put(counter, label);

            counter++;
        }

        LBPHFaceRecognizer faceRecognizer = LBPHFaceRecognizer.create();

        faceRecognizer.train(images, labels);

        IntPointer label = new IntPointer(1);
        DoublePointer distance= new DoublePointer(1);
        if (!testImage.empty()) {
            faceRecognizer.predict(testImage, label, distance);
            int predictedLabel = label.get(0);

            System.out.println("Predicted label: " + predictedLabel);
        }`

**Comment by saudet** [comment] 2019-08-21 10:06
I told you already: We need to check the "confidence" for that.

**Comment by saudet** [comment] 2019-08-21 10:06
Duplicate of #1276

**Closed by saudet** 2019-08-21 10:06 UTC
Labels: duplicate, question

**Comment by sudipsadhukhan0295** [comment] 2019-08-21 10:53
But what is the threshold value for that? I mean I got **confidence** in between 50-60 for known and unknown recognition.

**Comment by saudet** [comment] 2019-08-21 11:17
That means you'll need to train a better model:
https://docs.opencv.org/4.1.1/da/d60/tutorial_face_main.html
