### ISSUE TITLE
after video recording video showing little right part on its left side ,i dont know why

### ISSUE THREAD

**Issue by justflyhard** [bytedeco/javacv#223] opened 2015-09-14 07:25 UTC
![screenshot_2015-09-14-12-29-47 1](https://cloud.githubusercontent.com/assets/7922097/9844324/cfe7ed3e-5adf-11e5-92b2-42000ceb388a.png)

**Comment by saudet** [comment] 2015-09-14 23:41
Looks like a duplicate of #190.

**Closed by saudet** 2015-09-14 23:41 UTC
Labels: bug, duplicate
