### ISSUE TITLE
start crash

### ISSUE THREAD

**Issue by nieyue** [bytedeco/javacv#1122] opened 2019-01-17 11:26 UTC
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007feea105f6d, pid=12688, tid=0x0000000000001d18
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [avformat-58.dll+0xe5f6d]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\YaYao\javacv\hs_err_pid12688.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[rtsp @ 0000000000462400] Status 302: Redirecting to rtsp://120.205.37.102:1554/iptv/import/Tvod/iptv/001/001/ch15021312020660035461.rsc/14724_Uni.sdp?lvst=3&nodeid=node18072311593082&TSTVTimeLife=0&userid=&userip=113.246.105.239&time=20190117112536.790+00&life=86400000&needrelay=0&transferproviderid=001&ctype=01&sid=105515790&domain=0&phycid=ch15021312020660035461&playtype=0&urtm=0&agnt=MTIwLjIwNS4zNy4xMDA6NTU0&sadr=MTIwLjIwNS4zNy4xMDI&cryptmode=0502&crypt=F83BD584419BF4A2D01B308527439C3B
Input #0, rtsp, from 'rtsp://120.205.37.100:554/live/ch15021312020660035461.sdp?vcdnid=001':
  Metadata:
    title           : Camera_A
  Duration: N/A, start: 95380.196800, bitrate: N/A
  Program 302 
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt470bg, top first), 720x576 [SAR 12:11 DAR 15:11], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (HE-AACv2) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 62 kb/s
[flv @ 0000000029aa6840] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[flv @ 0000000029aa6840] Aspect ratio mismatch between muxer (1/1) and encoder layer (12/11)
Output #0, flv, to 'rtmp://bytedance.uplive.ks-cdn.com/live/channel1730':
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt470bg, top first), 720x576 [SAR 12:11 DAR 15:11], q=2-31, SAR 1:1 DAR 5:4, 50 fps, 50 tbn, 50 tbc
    Stream #0:1: Unknown: none
```

**Comment by saudet** [comment] 2019-01-17 12:14
Duplicate of #1119 most likely

**Closed by saudet** 2019-01-17 12:14 UTC
Labels: bug, duplicate
