### ISSUE TITLE
FFmpegFrameGrabber freezes if maximumSize > 0 

### ISSUE THREAD

**Issue by Antoniossss** [bytedeco/javacv#1375] opened 2020-01-31 01:35 UTC
For some reasons I have issues with code below:

- If I set maximumSize in ` new FFmpegFrameGrabber(in, mximumSize);` to > 0, application will freeze on FFmpegFrameGrabber#start() method.
- There is around 1 second of lag in the video

Here is example code
 ````       FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(in, 0);
        grabber.start();
        while (true) {
            Frame frame = grabber.grab();
            canvasFrame.showImage(frame);
        }
````

Where `in` is a socket input stream - it comes from web cam's live feed.

Also it is worth mentioning, that application with maximumSize=0 #start() block for around 12seconds - that main frame capturing group works as expected. Why such delay? How to get rid of it?

**Comment by saudet** [comment] 2020-01-31 01:44
Since cameras don't support seeking anyway, we should set maximumSize to 0, that's fine. As for the delay, please set the log level to "debug" and look at the messages displayed on the console for clues.

**Comment by saudet** [comment] 2020-01-31 01:50
Duplicate of #1376

**Closed by saudet** 2020-01-31 01:50 UTC
Labels: duplicate, question

**Comment by Antoniossss** [comment] 2020-01-31 01:59
@saudet how to set that debug log level?

**Comment by Antoniossss** [comment] 2020-01-31 02:08
I hava turned on trace log leve. Does not look suspicious to me 
https://gist.github.com/Antoniossss/a573cca6014d862c7a78577b1d5b79c5

**Comment by saudet** [comment] 2020-01-31 03:31
This is the same issue as #1376, and you found the cause, right? Let's continue the discussion there.
