### ISSUE TITLE
How does Mat load images from the network。

### ISSUE THREAD

**Issue by wonderfulLand** [bytedeco/javacv#1688] opened 2021-09-08 07:42 UTC
How does Mat load images from the network。

**Comment by wonderfulLand** [comment] 2021-09-08 07:48
Mat back= opencv_imgcodecs.imread("C:\\Users\\John\\Desktop\\1.jpeg");

i want to load image in url.

**Comment by saudet** [comment] 2021-09-08 07:54
Among other things, we can use FFmpegFrameGrabber that, see issue https://github.com/bytedeco/javacv/issues/1628.

**Comment by saudet** [comment] 2021-09-08 07:54
Duplicate of #1628

**Closed by saudet** 2021-09-08 07:54 UTC
Labels: duplicate, question
