### ISSUE TITLE
avformat_open_input() and avformat_find_stream_info() have Long execution time

### ISSUE THREAD

**Issue by banmajio** [bytedeco/javacv#1406] opened 2020-04-24 07:56 UTC
hello:
 I am currently using version 1.5.3，push inputstream data into rtmp。But I have some problems，avformat_open_input () and avformat_find_stream_info () will execute for about 2 seconds，I need to control FFmpegFrameGrabber.start () within 1 second。The following are some of my attempts at this problem, but still can not solve：
1:`grabber = new FFmpegFrameGrabber(inputStream, 0);
			grabber.setOption("stimeout", "200000");
			grabber.setVideoOption("vcodec", "copy");
			grabber.setFormat("mpeg");
			grabber.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
			grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);`

2:`oc.max_delay(maxDelay);
     oc.probesize(10240);
oc.max_analyze_duration(5 * AV_TIME_BASE);
oc.flags(AVFormatContext.AVFMT_FLAG_NOBUFFER);`

And I already know the width, height, bit rate and other information of the video。

Can you help me?  Thanks!!!

**Comment by saudet** [comment] 2020-04-24 08:30
Call `start(false)` to skip over `avformat_find_stream_info()`.

**Comment by saudet** [comment] 2020-04-24 08:30
Duplicate of #1376

**Closed by saudet** 2020-04-24 08:31 UTC
Labels: duplicate, question
