### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xfffffff4 in tid 25352

### ISSUE THREAD

**Issue by michael-destiny** [bytedeco/javacv#1442] opened 2020-06-11 02:51 UTC
Hi developer,

I add below dependency in my gradle file.
    implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.3'
    implementation 'org.bytedeco:opencv:4.3.0-1.5.3:android-arm'
and meet the crash as the title.

and I found this issue was reported in Opencv Issue:
https://github.com/opencv/opencv/issues/14906

it was solved in 
https://github.com/opencv/opencv/pull/15970/commits/af21a3f8f6fc78c89c1a823f56157f84921118d2

And merged in master branch in
https://github.com/opencv/opencv/commit/ad0ab4109aec8173b34ee68d25bb488fbcfe5286

I want to know do the ''org.bytedeco:opencv:4.3.0-1.5.3:android-arm' contains this commit? This arm library crashed also in arm64-v8 devices.

**Comment by saudet** [comment] 2020-06-11 02:59
It looks like that patch was reverted somewhere. It's not on master nor in 4.3.0:
https://github.com/opencv/opencv/blob/4.3.0/modules/core/src/logger.cpp#L184
https://github.com/opencv/opencv/blob/master/modules/core/src/logger.cpp#L184

**Comment by saudet** [comment] 2020-06-12 03:12
If you would like to have it applied to the presets though, please open a PR with that patch here:
https://github.com/bytedeco/javacpp-presets/pulls

**Comment by michael-destiny** [comment] 2020-06-15 07:10
I found the fix code seems been moved to
https://github.com/opencv/opencv/blob/master/modules/core/src/system.cpp#L66

**Comment by saudet** [comment] 2020-06-15 07:56
It's been released in OpenCV 4.3.0, yes:
https://github.com/opencv/opencv/blob/4.3.0/modules/core/src/system.cpp

**Comment by saudet** [comment] 2020-06-15 08:00
BTW, this is probably a duplicate of issues #1133 or #1155.

**Comment by michael-destiny** [comment] 2020-06-15 08:14
Yes, I would do more test on this.

**Comment by saudet** [comment] 2020-06-15 08:16
It might be something that is fixed in more recent versions of the NDK. You might want to try it out locally, and if that fixes the issue, we'd need to update the version used on the CI servers, but it's never an easy task, because so many things change with each version...

**Comment by michael-destiny** [comment] 2020-06-17 03:01
I tried with a cleanest code with bytedeco dependency 

build.gradle
    implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.3'
    implementation 'org.bytedeco:opencv:4.3.0-1.5.3:android-arm'
    implementation 'org.bytedeco:ffmpeg:4.2.2-1.5.3:android-arm'
    implementation 'org.bytedeco:openblas:0.3.9-1.5.3:android-arm'
    implementation ('org.bytedeco:javacpp-presets:1.5.3')
And call the loader function to initialize opencv
Loader.load(opencv_java.class);

This issue seems doestn't happened again.
I would try this code on ABI=armeabi-v7a devices today.

**Closed** 2020-06-25 00:24 UTC
Labels: question
