### ISSUE TITLE
UnstatisfiedLinkedError: no jniopencv_highgui in java.libiary.path

### ISSUE THREAD

**Issue by steeveen** [bytedeco/javacv#2205] opened 2024-03-20 07:29 UTC
I user newest JavaCV on windows and my code works fine, but it report this on linux when running Loader.load(opencv_java.class).

**Comment by saudet** [comment] 2024-03-20 07:34
Please try again with JavaCV 1.5.10

**Comment by steeveen** [comment] 2024-03-20 07:51
Is there something different between 1.5.9 between 1.5.10? I have tested that this error happens on 1.5.8 and 1.5.9

**Comment by steeveen** [comment] 2024-03-20 08:08
1.5.10 meets no jniopenblas_nolapack. now I will try add openblas dependency in pom

**Comment by steeveen** [comment] 2024-03-20 08:17
alter adding openblas dependency in pom. Still meets `no jniopenblas_nolapack`

**Comment by saudet** [comment] 2024-03-20 08:46
You need to add openblas-platform, not openblas

**Comment by saudet** [comment] 2024-03-20 08:49
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-03-20 08:49 UTC
