### ISSUE TITLE
cvconverter.converToIplImage crash the 2nd time 

### ISSUE THREAD

**Issue by oelleo** [bytedeco/javacv#195] opened 2015-08-07 09:49 UTC
Hi,
I'm using the following code to convert a byte[] imageData to an IplImage. 
```
InputStream in = new ByteArrayInputStream(imageData);
BufferedImage bufImage = ImageIO.read(in);
Java2DFrameConverter javaconverter = new Java2DFrameConverter(); 
Frame frame = javaconverter.convert(bufImage);
OpenCVFrameConverter.ToIplImage cvconverter = new OpenCVFrameConverter.ToIplImage(); 
IplImage iplImage = cvconverter.convertToIplImage(frame);
```

It works great the first time but when run again on this function it crashes Java and Stop my server.
From the debug it appears when it arrives on the last line ` IplImage iplImage = cvconverter.convertToIplImage(frame); `
Sometimes it log EXCEPTION_ACCESS_VIOLATION but not always.
Can you help  ?

Thanks

**Comment by saudet** [comment] 2015-08-07 13:57
Duplicate of #150. Basically, we should be keeping the instances of FrameConverter alive instead of recreating them over and over again:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FrameConverter.html
If you can think of a better way to do this, I would very much to hear about it! Thanks

**Closed by saudet** 2015-08-07 13:57 UTC
Labels: duplicate, enhancement

**Comment by oelleo** [comment] 2015-08-07 14:30
Ok, thank you for the answer and sorry for the duplicated entry.
I see in your documentation that FrameConverter is not garbage collected. 
Maybe it would be good to add some function to release them like there is for IplImage (cvReleaseImage) ?

**Comment by saudet** [comment] 2015-08-08 04:16
That's fine for `OpenCVFrameConverter`, but how would we "release" a `BufferedImage` in the case of `Java2DFrameGrabber`?
