### ISSUE TITLE
FFmpegFrameRecorder  - Could not initialize class org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by guylevin** [bytedeco/javacv#429] opened 2016-06-05 14:28 UTC
Hello,
I get `Could not initialize class org.bytedeco.javacpp.avutil when ` when trying to use `FFmpegFrameRecorder`

I've looked everywhere and tried the solutions found on this form, couldn't make it work

Will be grateful if somebody has an answer

Using Windows + Eclipse + Maven 
JavaCV - Version 1.2

This line throws the exception:
`FFmpegFrameRecorder ffr = new FFmpegFrameRecorder("stream_url...",0);`

And this is the stack:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
	at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
	at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:120)
	at com.airobotics.aaaaaa.App.main(App.java:20)
Error putting member offsets for class org/bytedeco/javacpp/avutil$Pool_free_Pointer.
```

The pom looks like this:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.airobotics.common</groupId>
	<artifactId>aaaaaa</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>aaaaaa</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	
	<dependencies>


		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>1.2</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>3.0.2-1.2</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>opencv</artifactId>
			<version>3.1.0-1.2</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp</artifactId>
			<version>1.2</version>
		</dependency>


	</dependencies>
</project>
```

**Comment by guylevin** [comment] 2016-06-05 16:09
After a day spent around this, I moved to version 1.1 and everything seems to work fine.

**Comment by saudet** [comment] 2016-06-06 00:01
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/225

**Closed by saudet** 2016-06-06 00:01 UTC
Labels: bug, duplicate

**Comment by springCoders** [comment] 2017-03-31 05:52
spring tool suite, linux, war file
http://stackoverflow.com/questions/43116353/opencv-java-error-loading-class-org-bytedeco-javacpp-loader-snapshot-from-video

**Comment by skykuns** [comment] 2021-05-14 02:44
> After a day spent around this, I moved to version 1.1 and everything seems to work fine.

It is works , thanks!
