### ISSUE TITLE
record.recordPacket(pkt)  avformat.av_interleaved_write_frame(this.oc, avPacket)   jvm crash

### ISSUE THREAD

**Issue by nieyue** [bytedeco/javacv#1124] opened 2019-01-18 11:32 UTC
Input #0, flv, from 'http://live-rtmp.lotustv.duolaibo.cn/lotustv/5562e9e4d409d24c9600075c.flv':
  Metadata:
    encoder         : Lavf56.4.101
    cdn_ip          : 124.232.129.10
    x-reqid         : ChcAAPgKxp6Y7XoV
    mau             : qn
  Duration: 00:00:00.00, start: 0.044000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt470bg, top first), 720x576 [SAR 12:11 DAR 15:11], 25 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp, 128 kb/s
[flv @ 0000000029066580] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[flv @ 0000000029066580] Aspect ratio mismatch between muxer (1/1) and encoder layer (12/11)
Output #0, flv, to 'rtmp://bytedance.uplive.ks-cdn.com/live/channel1730':
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt470bg, top first), 720x576 [SAR 12:11 DAR 15:11], q=2-31, SAR 1:1 DAR 5:4, 25 fps, 25 tbn, 25 tbc
    Stream #0:1: Unknown: none

**Comment by saudet** [comment] 2019-01-18 11:48
Unless you have more details, I'll just mark this as another duplicate of #1119.

**Closed by saudet** 2019-01-18 11:48 UTC
Labels: bug, duplicate
