### ISSUE TITLE
Time consuming of built-in methods (image processing)

### ISSUE THREAD

**Issue by demonlov** [bytedeco/javacv#1786] opened 2022-03-31 03:50 UTC
When I use
BufferedImage  image = Java2DFrameUtils. toBufferedImage(frame); and
Java2DFrameUtils. toFrame(image);  This method takes a lot of time. I need to do some annotation operations on the image. Is there a better way to reduce the time-consuming? Or how can I add labels more quickly and which objects should I use

**Comment by demonlov** [comment] 2022-03-31 03:51
I don't know whether the processing frame should be converted to bufferedimage. If not, what should I do?

**Comment by saudet** [comment] 2022-03-31 03:53
Don't use Java2DFrameUtils, use one Java2DFrameConverter per thread instead.

**Comment by demonlov** [comment] 2022-03-31 03:53
I need to add a label to each frame obtained by RTSP stream and use ffmpeg framerecorder Record() method

**Comment by demonlov** [comment] 2022-03-31 03:54
Should adding comments to the frame be converted to bufferedimage? Does javacv provide other processing methods?

**Comment by demonlov** [comment] 2022-03-31 03:57
> 不要使用Java2DFrameUtils，而是使用一个Java2DFrameConverter。

In my whole process, this operation takes a lot of time. Can the GPU on my server help me to speed up this method? If so, what should I do

**Comment by saudet** [comment] 2022-03-31 05:54
If you're saying `Java2DFrameConverter` is too slow, @b005t3r proposed a few enhancements that could be made, see #1172. `BufferedImage` in general though is very slow. In performance sensitive applications, you should not be using it for anything.

**Comment by saudet** [comment] 2022-03-31 05:55
Duplicate of #1172.

**Closed by saudet** 2022-03-31 05:55 UTC
Labels: duplicate, enhancement, question

**Comment by b005t3r** [comment] 2022-03-31 08:28
@demonlov no idea what you're after with adding label, but if you mean a simple line of text rendered onto each frame, using  OpenCV might be easier (and probably faster, performance wise). But if you need a quick conversion from/to BufferedImage (since you can use Java2D with it), those methods from #1172 should do the trick (conversion to/from BufferedImage is pretty fast, however rendering to those images with Java2D API will be slow, but you still should be OK with a simple text rendering).
