### ISSUE TITLE
av_interleaved_write_frame() error -10053 while writing interleaved audio packet.

### ISSUE THREAD

**Issue by Achilles2012** [bytedeco/javacv#826] opened 2017-11-03 02:56 UTC
org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -10053 while writing interleaved audio packet.
	at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1040)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:1026)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordSamples(FFmpegFrameRecorder.java:994)
	at com.doll.api.core.WebcamAndMicrophoneCapture$1$1.run(WebcamAndMicrophoneCapture.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Achilles2012** [comment] 2017-11-03 02:57
this error from sample class WebcamAndMicrophoneCapture

**Comment by Achilles2012** [comment] 2017-11-03 02:58
The program runs long,this error will come up

**Comment by saudet** [comment] 2017-11-03 02:58
Duplicate of #525

**Closed by saudet** 2017-11-03 02:58 UTC
Labels: question
