### ISSUE TITLE
how to use opencv_imgproc.polylines()

### ISSUE THREAD

**Issue by crasy1** [bytedeco/javacv#1949] opened 2022-11-29 14:53 UTC
i use like this
```
        Mat mat=new Mat(1000,1000,opencv_core.CV_8U,Scalar.BLACK);
        org.bytedeco.opencv.opencv_core.Point[] pointArr =new org.bytedeco.opencv.opencv_core.Point[]{
                new org.bytedeco.opencv.opencv_core.Point(100,100),
                new org.bytedeco.opencv.opencv_core.Point(500,100),
                new org.bytedeco.opencv.opencv_core.Point(500,500),
                new org.bytedeco.opencv.opencv_core.Point(100,500)
        };
        PointerPointer pointerPointer = new PointerPointer(1);
        pointerPointer.put(pointArr);
        IntPointer intPointer = new IntPointer(1);
        int[] ints = {4};
        intPointer.put(ints);
        polylines(mat,pointerPointer,intPointer,1,true,Scalar.WHITE,1,LINE_8,0);
        imwrite("img.jpg",mat);
```
but result is wrong
![circle2](https://user-images.githubusercontent.com/37093436/204561935-69e263e5-6ba8-4305-8ed6-03042cd81d5a.jpg)

**Comment by saudet** [comment] 2022-11-29 16:06
It's probably easier to use the overloads that take a MatVector instead of a PointerPointer....

**Comment by crasy1** [comment] 2022-11-29 23:34
how to construct MatVector by  Point array

**Comment by saudet** [comment] 2022-11-30 00:04
We can do something like shown in discussion https://github.com/bytedeco/javacv/discussions/1778#discussioncomment-2343876.

**Comment by crasy1** [comment] 2022-11-30 00:11
@saudet got it ,thanks

**Comment by saudet** [comment] 2022-11-30 00:16
Duplicate of #1778

**Closed by saudet** 2022-11-30 00:16 UTC
Labels: duplicate, question
