### ISSUE TITLE
FFmpegFrameRecorder(outputStream) error occurred by .mp4 file

### ISSUE THREAD

**Issue by duck123456** [bytedeco/javacv#1261] opened 2019-07-22 02:36 UTC
desc :
if use [recorder = new FFmpegFrameRecorder("D:\\video_file\\mp4\\file\\1.ts",grabber.getImageWidth(),grabber.getImageHeight(),0);] it is normal，but use  recorder = new FFmpegFrameRecorder(outputStream,grabber.getImageWidth(),grabber.getImageHeight(),0);
will error occurred
log:
[mp4 @ 000000001d8767c0] muxer does not support non seekable output

code:
    public static void main(String[] args) throws FrameGrabber.Exception, FrameRecorder.Exception {
        FFmpegFrameGrabber grabber =null;
        FFmpegFrameRecorder recorder = null;
        ByteArrayOutputStream outputStream = null;
        String requestStreamUrl="D:\\video_file\\mp4\\zao_14.mp4";
        grabber = new FFmpegFrameGrabber(requestStreamUrl);
 grabber.start();
        outputStream = new ByteArrayOutputStream();
        recorder = new FFmpegFrameRecorder(outputStream,grabber.getImageWidth(),grabber.getImageHeight(),0);
        recorder.setFormat("mp4");
        recorder.start();
        while(true){
            recorder.record(grabber.grabFrame());
        }
    }

**Comment by duck123456** [comment] 2019-07-22 02:43
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L430 
Is it adding a seekcallback function here？

**Comment by saudet** [comment] 2019-07-22 03:28
Yes, that's what we need to do.

**Comment by saudet** [comment] 2019-07-22 03:29
Duplicate of #645

**Closed by saudet** 2019-07-22 03:29 UTC
Labels: duplicate, enhancement

**Comment by duck123456** [comment] 2019-07-22 04:56
All right!It works very well,thanks

**Comment by saudet** [comment] 2019-07-22 04:58
Cool, you got it working? Please consider sending a pull request to share your work with others! Thanks

**Comment by duck123456** [comment] 2019-07-22 05:02
> Cool, you got it working? Please consider sending a pull request to share your work with others! Thanks

oh,sorry ,I only to modify the recorder.setFormat("matroska");  haha
