### ISSUE TITLE
Issues in video convert time

### ISSUE THREAD

**Issue by vah13** [bytedeco/javacv#108] opened 2015-03-27 21:18 UTC
Hi dear support. 
Thank you for JavaCV :-)

I have some question. I can record video and save it, but how can convert it - mp4 to webm?
Thank you.

**Comment by ShihabSoft** [comment] 2015-03-28 01:07
Just try to use.
JavaCV FFmpegFrameRecorder dude.

**Comment by saudet** [comment] 2015-03-29 02:02
To support the WebM format, we would need to build FFmpeg with the `libvpx` library. Someone would need to update the `cppbuild.sh` file accordingly...

**Comment by saudet** [comment] 2015-04-04 01:25
Marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/33

**Closed by saudet** 2015-04-04 01:25 UTC
Labels: duplicate, enhancement, help wanted

**Comment by saudet** [comment] 2015-07-17 14:00
FYI, support for WebM has been included in version 1.0. Enjoy!
