### ISSUE TITLE
does this version of ffmpeg support vaapi?

### ISSUE THREAD

**Issue by chenjeff622** [bytedeco/javacv#1504] opened 2020-09-09 04:12 UTC
does this version of ffmpeg support vaapi?

**Comment by saudet** [comment] 2020-09-09 04:21
Yes, if you build from source, but not yet for the default binaries.

**Comment by saudet** [comment] 2020-09-09 04:22
Duplicate of #1188

**Closed by saudet** 2020-09-09 04:22 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2021-08-10 02:49
FFmpeg is now getting built with CentOS 7, so this gets enabled by default.
Please give it a try with the snapshots: http://bytedeco.org/builds/
