### ISSUE TITLE
FFmpegFrameGrabber hangs when calling start()

### ISSUE THREAD

**Issue by MrAlmost0** [bytedeco/javacv#1564] opened 2021-01-14 10:26 UTC
Hi, I found some examples that cause FFmpegFrameGrabber to hangs the thread when calling start().
I have tried the latest version(javacv-platform-1.5.4) and set the stimeout option, but it still doesn't work.
Such as: "rtp://", "rtmp://", "srtp://", "rtsp://" and so on.
My code is as sample as the following:
`FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("rtp://");`
`frameGrabber.setOption("stimeout", String.valueOf(2 * 1_000_000));`
`frameGrabber.start();`

**Comment by saudet** [comment] 2021-01-14 10:42
The correct option is probably "rw_timeout": https://ffmpeg.org/ffmpeg-protocols.html

**Comment by saudet** [comment] 2021-01-14 10:43
Duplicate of #1063

**Closed by saudet** 2021-01-14 10:43 UTC
Labels: duplicate, question

**Comment by MrAlmost0** [comment] 2021-01-14 11:24
I hava tried all options from here: https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java
It still doesn't work, my code is very simple, you can test it.
`FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("rtp://")`
`frameGrabber.setOption("rw_timeout", String.valueOf(2 * 1_000_000));`
`frameGrabber.setOption("stimeout", String.valueOf(2 * 1_000_000));`
`frameGrabber.setOption("timeout", String.valueOf(2 * 1_000_000));`
`frameGrabber.start();`

**Comment by saudet** [comment] 2021-01-14 13:16
"rtp://" is not a valid URL. Just test the URL for validity before passing it to FFmpeg.

**Comment by MrAlmost0** [comment] 2021-01-14 13:59
So there is really no way to make ffmpeg timeout from hanging when encountering these invalid URLs.
Anyway, thanks for your suggestion.

**Comment by saudet** [comment] 2021-01-14 14:14
I don't know, maybe it's a bug in FFmpeg? Make sure to check the messages that it displays in the log, try with the ffmpeg program see what that does, etc. (Running `ffmpeg -i rtp://` seems to be hanging alright, so it looks like that's "normal". You should ask about that upstream: https://ffmpeg.org/bugreports.html)
