### ISSUE TITLE
Interrupt av_find_input_format() function

### ISSUE THREAD

**Issue by banmajio** [bytedeco/javacv#1443] opened 2020-06-12 02:49 UTC
hello:
    If the video stream cannot be opened,Can [FFmpegStreamingTimeout.java ](https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java) be used for interrupt?

**Comment by banmajio** [comment] 2020-06-12 02:52
Because AV_ find_ input_ Format is a blocking function,So I want to interrupt the function if it's still blocked for a few seconds.What should I do?   Hope to get your help!  Thank you

**Comment by saudet** [comment] 2020-06-12 03:05
Yes, that's we should do it. Set the timeout to a few seconds and it will do what you need to do.

It will not work for `av_find_input_format()` though. We can skip over that one with `start(false)`.

**Comment by saudet** [comment] 2020-06-12 03:08
Duplicate of #1376

**Closed by saudet** 2020-06-12 03:08 UTC
Labels: duplicate, question

**Comment by saudet** [comment] 2020-06-12 03:09
BTW, I'm assuming you're talking about `avformat_find_stream_info()`. 
`av_find_input_format()` does not block.

**Comment by banmajio** [comment] 2020-06-12 03:51
sorry,My problem now is that if there is no streaming data, av_ find_ input_ The format() function is blocked,FFmpegStreamingTimeout.java Can interrupt AV_ find_ input_ The format()?

**Comment by banmajio** [comment] 2020-06-12 03:55
I tried as follows, but it didn't work.
![image](https://user-images.githubusercontent.com/53471385/84463192-8fc63600-aca3-11ea-9cfa-1c3b49e8d8cf.png)

**Comment by saudet** [comment] 2020-06-12 03:56
I told you: av_find_input_format() does not block.

**Comment by banmajio** [comment] 2020-06-12 03:59
Ok,thank you!   So there's no way to solve this blocking problem? Sorry to disturb you!

**Comment by saudet** [comment] 2020-06-12 04:04
That function cannot block! It's not possible, unless you have a problem with your machine or something, so start by checking your hardware.
