### ISSUE TITLE
Failed to load in the latest version of windows server2012 R2

### ISSUE THREAD

**Issue by xsjzf** [bytedeco/javacv#1553] opened 2020-12-18 02:25 UTC
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.5.4</version>
</dependency>
i use the maven Repository latest,It is normal in win10 win7 Linux Windows Server 2016 / 2019
but in the windwos server 2012R2 
error：NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avcodec
when i use try catch :
run:
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavcodec in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
    at org.bytedeco.javacpp.Loader.load(Loader.java:410)
    at org.bytedeco.javacpp.Loader.load(Loader.java:353)
    at org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:12)
    at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:103)
    at com.nackloose.util.robot.JavaCVDemo.main(JavaCVDemo.java:37)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Nackloose\AppData\Local\Temp\javacpp29106638795626\jniavcodec.dll: Can't find dependent libraries
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1083)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:524)
    ... 5 more

**I've looked at all the similar questions for issue**
For example:
Load at project startup（Loader.load(swresample.class)
Loader.load(avcodec.class)）
or 
try {
    Loader.load(<module>.class);
} catch (UnsatisfiedLinkError e) {
    String path = Loader.cacheResource(<module>.class, "windows-x86_64/jni<module>.dll").getPath();
    new ProcessBuilder("c:/path/to/DependenciesGui.exe", path).start().waitFor();
}
**All methods have been tried**
when i Loader.load(avcodec.class)
error:
UnsatisfiedLinkError: no jniavutil in java.library.path 
**last**
i use the old version 
 <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.4</version>
        </dependency>

**Comment by xsjzf** [comment] 2020-12-18 02:27
`<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.1</version>
        </dependency>`
**The normal version of this program is replaced at last**

**Comment by saudet** [comment] 2020-12-18 02:27
Please make sure that Media Foundation is installed like this:
https://github.com/bytedeco/javacv/blob/master/.travis.yml#L64

**Comment by saudet** [comment] 2020-12-18 02:28
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/940

**Closed by saudet** 2020-12-18 02:28 UTC
Labels: duplicate, question

**Comment by xsjzf** [comment] 2020-12-18 02:52
> Duplicate of [bytedeco/javacpp-presets#940](https://github.com/bytedeco/javacpp-presets/issues/940)

thanks

**Comment by saudet** [comment] 2020-12-18 02:53
If it still doesn't work after installing Media Foundation though, please let me know!

**Comment by xsjzf** [comment] 2020-12-18 02:57
> If it still doesn't work after installing Media Foundation though, please let me know!

Recently, I tested video service across platforms, and I will give feedback in time if there is any problem
