### ISSUE TITLE
Works on armv8?

### ISSUE THREAD

**Issue by bakua** [bytedeco/javacv#419] opened 2016-05-27 18:38 UTC
Hey, I have an android app. I grab camera preview frames, apply some transformation and encode them with included ffmpeg. However it seems that native binaries are not compiled only for armv7, as the very same app crashes on many new devices. For example on samsung s6, s7, huawei 6p. All of them are armv8. The crash is about system not able to find .so libs.

Is it possible to get armv8 version of javacv as well or do I have to compile myself some way? Thanks

**Comment by saudet** [comment] 2016-05-27 23:50
32-bit binaries work fine on 64-bit devices. We don't need 64-bit binaries, but if you would like to make a contribution, sure they would be welcome.

Marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/52.  If interested, please continue the discussion there.

**Closed by saudet** 2016-05-27 23:50 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2018-02-27 03:11
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
