### ISSUE TITLE
When will the open source transition library gl-transition be compiled into ffmpeg and added to the javacv library?

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2243] opened 2024-06-21 03:21 UTC
When will the open source transition library gl-transition be compiled into ffmpeg and added to the javacv library? Due to the complexity of the ffmpeg transition filter, the command line required for stitching multiple images is very complex...

**Comment by saudet** [comment] 2024-06-21 07:25
Duplicate of https://github.com/bytedeco/javacv/issues/2013

**Closed by saudet** 2024-06-21 07:25 UTC
Labels: duplicate, enhancement
