### ISSUE TITLE
Bundle creation execution failed because - File 'root/lib/x86_64/lib/cmake/openblas/OpenBLASConfig.cmake' uses reserved file or directory name 'lib'.

### ISSUE THREAD

**Issue by akash2018xD** [bytedeco/javacv#1332] opened 2019-11-12 06:15 UTC
Hi, 
my app used Nd4j and I have included theses dependencies in my app - 
    implementation('org.nd4j:nd4j-native:1.0.0-beta') {
        exclude group: 'com.google.code.findbugs', module: 'annotations'
    }
    implementation('org.nd4j:nd4j-native:1.0.0-beta:android-arm') {
        exclude group: 'com.google.code.findbugs', module: 'annotations'
    }
    implementation('org.nd4j:nd4j-native:1.0.0-beta:android-arm64') {
        exclude group: 'com.google.code.findbugs', module: 'annotations'
    }
    implementation('org.nd4j:nd4j-native:1.0.0-beta:android-x86') {
        exclude group: 'com.google.code.findbugs', module: 'annotations'
    }
    implementation('org.nd4j:nd4j-native:1.0.0-beta:android-x86_64') {
        exclude group: 'com.google.code.findbugs', module: 'annotations'
    }
    implementation  "org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-arm"
    implementation  "org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-arm64"
    implementation  "org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-x86"
    implementation  "org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-x86_64"
    . 
My issue is that when I'm trying to create an app bundle to reduce my apk size then I'm getting 
the following : 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebugBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'root/lib/x86_64/lib/cmake/openblas/OpenBLASConfig.cmake' uses reserved file or directory name 'lib'.
.
Can you help me understand what my issue is here and how should I fix it, as it's pretty imp for me to use the bundle
Thanks!

**Comment by saudet** [comment] 2019-11-12 07:31
Duplicate of #1117

**Comment by saudet** [comment] 2019-11-12 07:32
You can exclude those files, they are not necessary at runtime.

**Closed by saudet** 2019-11-12 07:31 UTC
Labels: duplicate, enhancement
