### ISSUE TITLE
Hello,ffmpeg not included linux-arm64,What should I do?

### ISSUE THREAD

**Issue by 18506711722** [bytedeco/javacv#1225] opened 2019-06-08 06:33 UTC
Hello,ffmpeg not included linux-arm64,What should I do?

**Comment by saudet** [comment] 2019-06-09 00:16
Duplicate of #1021 and https://github.com/bytedeco/javacpp-presets/issues/735

Contributions are welcome!

**Closed by saudet** 2019-06-09 00:16 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2019-11-11 08:38
BTW, builds for linux-arm64 are now available since version 1.5.1.
