### ISSUE TITLE
Bug on Windows 10 for webcam camera video capture, maybe platform specific

### ISSUE THREAD

**Issue by PhilAndrew** [bytedeco/javacv#357] opened 2016-03-17 04:46 UTC
The problem is that webcam capture does not work in JavaCV when using OpenCV version 3 + and using a particular API but it did work in JavaCV/OpenCV version 2.4.9.

The API used was new OpenCVFrameGrabber(0) with start method and then grab method, which fails with the error message.

```
cvRetrieveFrame() Error: Could not retrieve frame. (
Has start() been called?)
[info] org.bytedeco.javacv.FrameGrabber$Exception: cvRetrieveFrame() Error: Coul
d not retrieve frame. (Has start() been called?)
[info]  at org.bytedeco.javacv.OpenCVFrameGrabber.grab(OpenCVFrameGrabber.java:2
39)
```

I discovered this bug when trying to run this Akka example of webcam https://github.com/lloydmeta/scala-akka-cv-part1 which I came across from this blog article https://beachape.com/blog/2016/03/08/scala-and-opencv-ep-1-akka-webcam/

I fixed the bug by making this github branch https://github.com/PhilAndrew/scala-akka-cv-part1/tree/windows10 which now uses new VideoCapture(0) rather than new OpenCVFrameGrabber(0).

You can investigate the difference between the two project.

If you need more details refer to this issue. https://github.com/lloydmeta/scala-akka-cv-part1/issues/1

My machine is Intel Windows 10 with SJCAM SJ4000 setup as a USB webcam.

---

Another way to investigate this is to look at this version which works with JavaCV OpenCV 2.4.9

https://github.com/PhilAndrew/ScalaOpenCVCameraWhichWorks/tree/bbea935fa342cdb3d8016afa24c566269e4bb43d

Which when upgraded to JavaCV OpenCV 3+ does not work

https://github.com/PhilAndrew/ScalaOpenCVCameraWhichWorks/tree/opencv3

**Comment by saudet** [comment] 2016-03-17 14:19
OpenCV is known to not work very well for camera capture. As you've discovered, it's better to use either `VideoInputFrameGrabber` or `FFmpegFrameGrabber`.

Still, OpenCV has deprecated the C API, so we should use `VideoCapture` in `OpenCVFrameGrabber`. If you make the necessary modifications, please send a pull request so I can merge this in! Thanks

**Comment by lloydmeta** [comment] 2016-03-17 16:39
Sorry to interject, but if the API works cross-platofrm with 2.4.9 but not with 3+, that seems a little odd, isn't that a regression? 

Also, I believe even `FrameGrabber.createDefault` [isn't working](https://github.com/lloydmeta/scala-akka-cv-part1/issues/1#issuecomment-197484644) in his case, which would have tried using `VideoInputFrameGrabber`.

**Comment by lloydmeta** [comment] 2016-03-17 16:43
Also found that [the sample code](https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java#L52-L55) in this repo for getting a webcam feed uses `OpenCVFrameGrabber` too.

**Comment by saudet** [comment] 2016-03-18 04:51
Yes, if it worked with 2.4.9, but not 3.0 that's a regression. But the OpenCV team doesn't care much for the C API anymore, so even if we report it, they'll probably tell us to use the `VideoCapture` API.

Are you saying `VideoInputFrameGrabber` also fails on your machine?

**Comment by PhilAndrew** [comment] 2016-03-18 04:59
FrameGrabber.createDefault and new OpenCVFrameGrabber(0) didn't work on my Windows 10 machine in the JavaCV 3+ but was working in the 2.x.x JavaCV, this is the regression problem. Where-as new VideoCapture(0) works in JavaCV 3+. 

I have not tested VideoInputFrameGrabber, why do you suggest "As you've discovered, it's better to use either VideoInputFrameGrabber or FFmpegFrameGrabber.". Why are there so many ways to get data from the camera and some work and some do not? What is the "right" way cross platform to get the video data from the generic usb webcam?

**Comment by lloydmeta** [comment] 2016-03-18 05:04
@saudet Ah ok, if it is a regression, I would suggest that this ticket be marked as a bug then instead of enhancement :)

In the interest of keeping the value that JavaCV provides with regards to cross-platform usage, I think we should fix `OpenCVFrameGrabber` or `FrameGrabber.createDefault`, or both. I find it odd that `FrameGrabber.createDefault` fails on Windows 10 because it would try using `VideoInputFrameGrabber` anyways.

**Comment by saudet** [comment] 2016-03-18 05:05
There isn't a right way. It's all a bit broken. FFmpeg is getting pretty good these days though. You might want to try `FFmpegFrameGrabber` with the `setFormat("dshow")` and a filename like "Integrated Camera": https://trac.ffmpeg.org/wiki/DirectShow

**Comment by saudet** [comment] 2016-03-18 05:06
That's why I'm asking if `VideoInputFrameGrabber`. If it fails, we'll need to fix that too.

**Comment by lloydmeta** [comment] 2016-03-18 05:13
I see; I think it's possible that the `VideoInput` preset simply hasn't been included in that project because I don't include it by default in `SBT-JavaCV` (by default I include just the bare OpenCV basics), which begs the question; should it be?

**Comment by saudet** [comment] 2016-03-18 05:20
Yes, I think it should be, but anyway we should be upgrading `OpenCVFrameGrabber` so that it uses `VideoCapture`. You think it's something you could do?

**Comment by lloydmeta** [comment] 2016-03-18 07:59
I'll give it a try and report back, but I'm new to OpenCV and JavaCPP so don't hold your breath.

That said, have you considered simply deprecating `OpenCVFrameGrabber` and promoting `FrameGrabber.createDefault` as the defacto cross-platform solution?

**Comment by saudet** [comment] 2016-03-18 08:00
`FrameGrabber.createDefault()` is just a factory method that will return `OpenCVFrameGrabber` by default, if it doesn't fail.

**Comment by saudet** [comment] 2016-03-18 08:01
Thanks for trying though! Let me know if you have any more questions.

**Comment by lloydmeta** [comment] 2016-03-18 08:04
Looks to me like `FrameGrabber.createDefault` will try the following grabber implementations in order

`"DC1394", "FlyCapture", "FlyCapture2", "OpenKinect", "PS3Eye", "VideoInput", "OpenCV", "FFmpeg", "IPCamera"`

So if earlier ones can be loaded, those will be used

**Comment by saudet** [comment] 2016-03-19 08:10
Right, but unless you have one of those cameras, everything before "VideoInput" will fail.

**Comment by lloydmeta** [comment] 2016-03-19 08:43
The failure gets caught, and later ones tried, which is what you want for
cross platform, rather than failing completely if OpenCVFrameGrabber fails.

**Comment by saudet** [comment] 2016-03-19 09:33
Yes, that's what it does.

**Comment by saudet** [comment] 2016-05-19 09:34
Upgrade is in version 1.2. Thanks for reporting and thanks @lloydmeta for the code!

**Closed by saudet** 2016-05-19 09:34 UTC
Labels: bug, question

**Comment by ikeralbeniz** [comment] 2017-09-28 15:28
adding this dependencie on gradle solve the problem for me

compile 'org.bytedeco.javacpp-presets:videoinput:0.200-1.3:windows-x86_64'
