### ISSUE TITLE
Zero duration on FFmpegFrameRecorder output

### ISSUE THREAD

**Issue by omarzouk** [bytedeco/javacv#1253] opened 2019-07-17 08:11 UTC
Awesome library! great work!
I'm trying to crop a piece of an audio file and write the output in wavefile format. The following code produces the correct segment and the correct number of frames, but the duration on the output file is always 0. I've tried looking around and I'm aware of #1069 and #1179 which prompted me to use the latest version 1.5.1 but I'm not sure what I'm missing.

```
            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputStream);
            grabber.setSampleFormat(AV_SAMPLE_FMT_S16);
            grabber.setSampleRate(targetSampleRate);
            grabber.setAudioChannels(1); // 1 channel mono audio
            grabber.setFormat("m4a");
            grabber.start();
            grabber.setAudioTimestamp(startOffset * 1000000L );


            FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputStream, grabber.getAudioChannels());
            recorder.setSampleFormat(grabber.getSampleFormat());
            recorder.setAudioChannels(grabber.getAudioChannels());
            recorder.setSampleRate(targetSampleRate);
            recorder.setFormat("wav");
            recorder.setAudioCodec(AV_CODEC_ID_PCM_S16LE);

            recorder.start();

            Frame frame = null;
            while ((frame = grabber.grabFrame()) != null && grabber.getTimestamp() <= endOffset * 1000000L) {
                recorder.record(frame);
            }

            recorder.stop();
            recorder.release();

            grabber.stop();
            grabber.release();
```

**Comment by omarzouk** [comment] 2019-07-17 08:29
changing from `wav` to `ogg` seems to fix the issue. However I would like the audio in `wav` format

**Comment by saudet** [comment] 2019-07-17 08:35
Duplicate of #645

**Comment by saudet** [comment] 2019-07-17 08:37
`OutputStream` doesn't support seeking so it won't work for file formats that modify the header on close.
It should be possible to hack something for `ByteArrayOutputStream` and such though, see issue #645.

**Closed by saudet** 2019-07-17 08:37 UTC
Labels: duplicate, enhancement
