### ISSUE TITLE
carsh when recoder output hls 

### ISSUE THREAD

**Issue by buhe** [bytedeco/javacv#1082] opened 2018-11-05 14:48 UTC
Hi, i mix 2 audio to 1 audio and output to hls format, app is crash when ```recorder.stop()``` 
I debug the app, the crash code is ``` av_write_frame(oc, null);```
```
public void stop() throws Exception {
        if (oc != null) {
            try {
                synchronized (oc) {
                    /* flush all the buffers */
                    while (video_st != null && ifmt_ctx == null && recordImage(0, 0, 0, 0, 0, AV_PIX_FMT_NONE, (Buffer[])null));
                    while (audio_st != null && ifmt_ctx == null && recordSamples(0, 0, (Buffer[])null));

                    if (interleaved && video_st != null && audio_st != null) {
                        av_interleaved_write_frame(oc, null);
                    } else {
                        av_write_frame(oc, null);   <--- app crash here
                    }

                    /* write the trailer, if any */
                    av_write_trailer(oc);
                }
            } finally {
                release();
            }
        }
    }
```

Finally, i have a 43 ts file ,but m3u8 file has only 42 ts 

Thanks

**Comment by buhe** [comment] 2018-11-05 14:58
```java
package com.herewhite.audiomix.demo;

import org.bytedeco.javacv.FFmpegFrameFilter;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;

import java.io.File;
import java.nio.Buffer;

import static org.bytedeco.javacpp.avcodec.AV_CODEC_ID_AAC;

/**
 * Created by buhe on 2018/11/2.
 */
public class JavaCVMixer5 {

    public static void main(String[] args) throws Exception {
        File tempFile = new File(".", "1.aac");
        File tempFile2 = new File(".", "2.aac");


        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(tempFile);
        grabber.setAudioChannels(1);
        grabber.start();

        FFmpegFrameGrabber grabberc = new FFmpegFrameGrabber(tempFile2);
        grabber.setAudioChannels(1);
        grabberc.start();

        FFmpegFrameFilter filter = new FFmpegFrameFilter(
                null,
                "[0:a][1:a]amix=inputs=2[a]",
                0, 0, 2);
//        filter.setPixelFormat(grabber.getPixelFormat());
        filter.setAudioChannels(1);
        filter.setSampleFormat(grabber.getSampleFormat());
//        filter.setVideoInputs(2);
        filter.setAudioInputs(2);
        filter.start();


        File tempFile3 = new File(".", "4.aac");

        FFmpegFrameRecorder recorder2 = new FFmpegFrameRecorder(tempFile3, 0, 0, 2);
//        recorder2.setVideoCodec(AV_CODEC_ID_VP8);
        recorder2.setFormat("hls");
        recorder2.setOption("hls_list_size", "0");
        recorder2.setAudioCodec(AV_CODEC_ID_AAC);
        recorder2.start();

//        FFmpegFrameRecorder audio0 = new FFmpegFrameRecorder("", 1);
//        FFmpegFrameRecorder audio1 = new FFmpegFrameRecorder("", 1);
//
//        audio0.start();
//        audio1.start();
//
//        FFmpegFrameFilter amovie = new FFmpegFrameFilter();

        int a = 0, b = 0, c = 0, d = 0;
        Frame frame2;

        while ((frame2 = grabber.grab()) != null) {
            if (frame2.image != null) {
                a++;
            }
            if (frame2.samples != null) {
                b++;
            }
            System.out.println(b + " is " + grabber.getTimestamp());
            filter.push(0, frame2);
            Frame frame4;
            if ((frame4 = grabberc.grab()) != null) {
                filter.push(1, frame4);
            } else {
                filter.push(1, frame2);
            }
            Frame frame3;
            while ((frame3 = filter.pull()) != null) {
                if (frame3.image != null) {
                    c++;
                }
                if (frame3.samples != null) {
                    d++;
                }
                recorder2.record(frame3);
            }
        }


        recorder2.stop();
        recorder2.release();


        System.out.printf("a is %d b is %d c is %d d is ", a, b, c, d);
        filter.stop();
        filter.release();
        grabber.restart();
        grabber.stop();
        grabber.release();

    }
}
```

**Comment by buhe** [comment] 2018-11-05 15:02
the error stack is

```

Stack: [0x000070000fd00000,0x000070000fe00000],  sp=0x000070000fdff680,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libavformat.58.dylib+0x5985e]  av_probe_input_buffer+0x1330e

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 927  org.bytedeco.javacpp.avformat.av_write_frame(Lorg/bytedeco/javacpp/avformat$AVFormatContext;Lorg/bytedeco/javacpp/avcodec$AVPacket;)I (0 bytes) @ 0x000000010eeafc23 [0x000000010eeafbc0+0x63]
j  org.bytedeco.javacv.FFmpegFrameRecorder.stop()V+116
j  com.herewhite.audiomix.demo.JavaCVMixer5.main([Ljava/lang/String;)V+322
v  ~StubRoutines::call_stub
```
Best regards
Thanks

**Comment by saudet** [comment] 2018-11-05 21:15
Sounds like a bug in the "hls" format. Does it happen with any other format?

**Comment by buhe** [comment] 2018-11-06 03:01
thanks relay.

I try flv and mp3 not crash.

recorder2.setFormat("flv");
recorder2.setFormat("mp3");

sadly, only hls is crash

**Comment by saudet** [comment] 2018-11-06 03:19
Thanks for testing! So this is probably something that will need to fixed upstream in FFmpeg though...

**Comment by egorapolonov** [comment] 2020-01-17 09:57
Hi @saudet , @buhe 

I have the same JVM crash in HLS but for video. My STR includes two videos: one of them encoded successfully, but the second one, named "jvmCrashVideoUrl", crashed JVM.

```java
import java.io.File;

import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;
import java.lang.Exception;

 class HlsEncoder {

    public static void main(String[] args) throws Exception {
        System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", "4G");
        System.setProperty("org.bytedeco.javacpp.maxbytes", "4G");

        String goodVideoUrl = "https://www.dropbox.com/s/n9mt98fa3msux2z/encodings_different.mp4?dl=1";
        encodeVideoIntoHls(goodVideoUrl);

        String jvmCrashVideoUrl = "https://www.dropbox.com/s/36rx49w1fvyom3r/1776x1000_nsnd.mp4?dl=1";
        encodeVideoIntoHls(jvmCrashVideoUrl);
    }

    public static void encodeVideoIntoHls(String url) throws Exception {
        File outputFile = new File("hls_fragment_" + System.currentTimeMillis() + ".m3u8");
        try (FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url)) {
            grabber.setVideoOption("threads", "1");
            grabber.setAudioOption("threads", "1");
            grabber.start();

            try (FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputFile, grabber.getImageWidth(),
                    grabber.getImageHeight(), grabber.getAudioChannels())) {
                initializeEncoder(recorder);
                recorder.setVideoOption("threads", "1");
                recorder.setAudioOption("threads", "1");
                recorder.start();

                Frame frame;
                while ((frame = grabber.grab()) != null) {
                    recorder.record(frame);
                }
            }
        }
    }

    public static void initializeEncoder(FFmpegFrameRecorder recorder) {
        //video
        recorder.setVideoCodecName("libx264"); // "libvpx-vp9" - the same crash
        recorder.setFormat("hls");
        recorder.setVideoOption("hls_time", "4");
        recorder.setVideoOption("sc_threshold", "0");
        recorder.setVideoOption("crf", "23");
    }

}
```

And here is my output:
```
/usr/lib/jvm/java-8-oracle/bin/java -javaagent:/home/yehorapolonov/IDE/idea-IU-183.5912.21/lib/idea_rt.jar=45107:/home/yehorapolonov/IDE/idea-IU-183.5912.21/bin -Dfile.encoding=UTF-8 -classpath /home/yehorapolonov/IDE/idea-IU-183.5912.21/lib/idea_rt.jar com.intellij.rt.execution.CommandLineWrapper /tmp/idea_classpath590334960 HlsEncoder
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://www.dropbox.com/s/n9mt98fa3msux2z/encodings_different.mp4?dl=1':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:00:15.04, start: 0.000000, bitrate: 1463 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1252 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 203 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[libx264 @ 0x7f3e0c7ba340] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f3e0c7ba340] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x7f3e0c7ba340] 264 - core 157 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[hls @ 0x7f3e0c7e8f00] Opening '/home/yehorapolonov/Projects/projectname/hls_fragment_15792533992390.ts' for writing
Output #0, hls, to '/home/yehorapolonov/Projects/projectname/hls_fragment_1579253399239.m3u8':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 1280x720, q=2-31, 400 kb/s, 30 fps, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, mono, fltp, 64 kb/s
[hls @ 0x7f3e0c7e8f00] Opening '/home/yehorapolonov/Projects/projectname/hls_fragment_1579253399239.m3u8.tmp' for writing
[hls @ 0x7f3e0c7e8f00] Opening '/home/yehorapolonov/Projects/projectname/hls_fragment_15792533992391.ts' for writing
[hls @ 0x7f3e0c7e8f00] Opening '/home/yehorapolonov/Projects/projectname/hls_fragment_1579253399239.m3u8.tmp' for writing
[libx264 @ 0x7f3e0c7ba340] frame I:2     Avg QP:19.29  size: 58195
[libx264 @ 0x7f3e0c7ba340] frame P:101   Avg QP:21.76  size: 12577
[libx264 @ 0x7f3e0c7ba340] frame B:273   Avg QP:26.79  size:  2181
[libx264 @ 0x7f3e0c7ba340] consecutive B-frames:  0.8%  5.3%  5.6% 88.3%
[libx264 @ 0x7f3e0c7ba340] mb I  I16..4: 14.3% 53.2% 32.4%
[libx264 @ 0x7f3e0c7ba340] mb P  I16..4:  1.8%  3.5%  1.8%  P16..4: 37.9% 11.0%  5.3%  0.0%  0.0%    skip:38.8%
[libx264 @ 0x7f3e0c7ba340] mb B  I16..4:  0.1%  0.2%  0.1%  B16..8: 32.1%  1.8%  0.3%  direct: 0.3%  skip:65.1%  L0:41.8% L1:54.7% BI: 3.6%
[libx264 @ 0x7f3e0c7ba340] 8x8 transform intra:50.2% inter:65.9%
[libx264 @ 0x7f3e0c7ba340] coded y,uvDC,uvAC intra: 57.0% 60.0% 15.1% inter: 5.2% 5.7% 0.0%
[libx264 @ 0x7f3e0c7ba340] i16 v,h,dc,p: 18% 48% 11% 23%
[libx264 @ 0x7f3e0c7ba340] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 25% 22%  5%  5%  5%  6%  6%  7%
[libx264 @ 0x7f3e0c7ba340] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 27% 12%  6%  8%  6%  9%  6%  7%
[libx264 @ 0x7f3e0c7ba340] i8c dc,h,v,p: 49% 29% 17%  5%
[libx264 @ 0x7f3e0c7ba340] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x7f3e0c7ba340] ref P L0: 64.7% 12.5% 17.1%  5.8%
[libx264 @ 0x7f3e0c7ba340] ref B L0: 90.4%  7.9%  1.7%
[libx264 @ 0x7f3e0c7ba340] ref B L1: 96.5%  3.5%
[libx264 @ 0x7f3e0c7ba340] kb/s:1265.13
[aac @ 0x7f3e0c7bb200] Qavg: 117.299
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://www.dropbox.com/s/36rx49w1fvyom3r/1776x1000_nsnd.mp4?dl=1':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:06.00, start: 0.000000, bitrate: 735 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1776x1000, 731 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[libx264 @ 0x7f3e0c7b4cc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f3e0c7b4cc0] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 0x7f3e0c7b4cc0] 264 - core 157 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[hls @ 0x7f3e0c7bb200] Opening '/home/yehorapolonov/Projects/projectname/hls_fragment_15792534211280.ts' for writing
Output #0, hls, to '/home/yehorapolonov/Projects/projectname/hls_fragment_1579253421128.m3u8':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 1776x1000, q=2-31, 400 kb/s, 30 fps, 90k tbn, 30 tbc
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3df464a5d1, pid=22497, tid=0x00007f3e15412700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libavformat.so.58+0xe65d1]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/yehorapolonov/Projects/projectname/hs_err_pid22497.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

I've attached JVM error report file
[hs_err_pid22497.log](https://github.com/bytedeco/javacv/files/4076198/hs_err_pid22497.log)

I tried to encode using **org.bytedeco.ffmpeg.ffmpeg.class** - everything works fine.

If you need more info - let me know.

Thank you!

**Comment by saudet** [comment] 2020-01-17 10:28
@egorapolonov The second one doesn't seem to have any audio channel? It's probably related to that...

**Comment by egorapolonov** [comment] 2020-01-17 11:03
@saudet ,

Looks like you are right.

I've just prepared converted good video without audio command
```bash
ffmpeg -i encodings_different.mp4 -c:v copy -an encoding_different_nsnd.mp4
```
 uploaded it into Dropbox and run 

```java
String goodVideoButNsndUrl = "https://www.dropbox.com/s/ymx9p05445ieecr/encoding_different_nsnd.mp4?dl=1";
encodeVideoIntoHls(goodVideoButNsndUrl);
```

**It also crashed JVM.**

**Comment by egorapolonov** [comment] 2020-01-22 14:52
Hi @saudet ,

I've made some debugging, so I found that the problem is here in FFmpegFrameRecorder
```java
public void flush() throws Exception {
        synchronized (oc) {
            /* flush all the buffers */
            while (video_st != null && ifmt_ctx == null && recordImage(0, 0, 0, 0, 0, AV_PIX_FMT_NONE, (Buffer[])null));
            while (audio_st != null && ifmt_ctx == null && recordSamples(0, 0, (Buffer[])null));

            if (interleaved && video_st != null && audio_st != null) {
                av_interleaved_write_frame(oc, null);
            } else {
                av_write_frame(oc, null);
            }

            /* write the trailer, if any */
            av_write_trailer(oc);
        }
    }
```
The method invocation av_write_frame(oc, null) causes crash.
Possibly, some workaround is to modify above condition
```java
            if (interleaved && ( video_st != null || audio_st != null)) {
                av_interleaved_write_frame(oc, null);
            } 
```

**Comment by egorapolonov** [comment] 2020-01-22 14:55
If someone need fast fix, he could use inheritance + reflection, make own recorder and override the method
```java
public class MyRecorder extends FFmpegFrameRecorder {
    [...some constructors...]
    
    @Override
    public void flush() throws Exception {
        try {
            Class recorderClass = getClass().getSuperclass();
            Field oc_Field = recorderClass.getDeclaredField("oc");
            oc_Field.setAccessible(true);
            AVFormatContext oc = (AVFormatContext) oc_Field.get(this);

            Field video_st_Field = recorderClass.getDeclaredField("video_st");
            video_st_Field.setAccessible(true);
            AVStream video_st = (AVStream) video_st_Field.get(this);

            Field audio_st_Field = recorderClass.getDeclaredField("audio_st");
            audio_st_Field.setAccessible(true);
            AVStream audio_st = (AVStream) audio_st_Field.get(this);

            Field ifmt_ctx_Field = recorderClass.getDeclaredField("ifmt_ctx");
            ifmt_ctx_Field.setAccessible(true);
            AVFormatContext ifmt_ctx = (AVFormatContext) ifmt_ctx_Field.get(this);

            synchronized (oc) {
                // flush all the buffers 
                while (video_st != null && ifmt_ctx == null && recordImage(0, 0, 0, 0, 0, AV_PIX_FMT_NONE, (Buffer[])null));
                while (audio_st != null && ifmt_ctx == null && recordSamples(0, 0, (Buffer[])null));

                // HLS workaround
                if (interleaved && video_st != null || audio_st != null) {
                    av_interleaved_write_frame(oc, null);
                } else {
                    av_write_frame(oc, null);
                }

                // write the trailer, if any 
                av_write_trailer(oc);
            }
        } catch (Throwable e) {
            throw new Exception("Unable to flush recorder", e);
        }
    }
```

**Comment by saudet** [comment] 2020-01-22 21:26
That sounds like a bug in the HLS format... In any case, please send a pull request! Thanks for looking into this

**Comment by saudet** [comment] 2020-01-22 21:32
Actually, it does appear like this is a bug in FFmpegFrameRecorder. From FFmpeg's documentation:
```
 * The data is then sent to the muxer by repeatedly calling av_write_frame() or
 * av_interleaved_write_frame() (consult those functions' documentation for
 * discussion on the difference between them; only one of them may be used with
 * a single muxing context, they should not be mixed). Do note that the timing
 * information on the packets sent to the muxer must be in the corresponding
 * AVStream's timebase. That timebase is set by the muxer (in the
 * avformat_write_header() step) and may be different from the timebase
 * requested by the caller.
```
@egorapolonov So your fix looks good! Please send a pull request and I'll merge it :) Thanks

**Comment by saudet** [comment] 2020-04-15 02:24
JavaCV 1.5.3 has been released with the fix. Thanks again @egorapolonov!

**Closed by saudet** 2020-04-15 02:24 UTC
Labels: bug
