### ISSUE TITLE
FFmpegFrameGrabber frame skipping

### ISSUE THREAD

**Issue by chengpengvb** [bytedeco/javacv#1706] opened 2021-10-13 07:36 UTC
For FFmpegFrameGrabber, setFrameRate is invalid. When grabImage is still decoding, this method can be optimized.

**Comment by chengpengvb** [comment] 2021-10-15 03:26
> 它并不总是无效的。例如，设置相机的帧速率可能是有效的。

It can be controlled only in the program, instead of modifying the parameters of the camera

**Comment by saudet** [comment] 2023-05-29 02:32
Duplicate of #1121

**Closed by saudet** 2023-05-29 02:32 UTC
Labels: duplicate, enhancement
