### ISSUE TITLE
How to utilize CUDA on Jetson Nano when working with the OpenCV DNN module/YOLOnet?

### ISSUE THREAD

**Issue by mrfukai** [bytedeco/javacv#1766] opened 2022-02-27 21:40 UTC
Hi!

I'm trying to run [this](https://github.com/bytedeco/javacv/blob/master/samples/YOLONet.java) sample on a Jetson Nano 2GB Development Kit. Unfortunately, when I print out the results of `getCudaEnabledDevices()`, I see that the output is `0`, which I assume means that JavaCV/OpenCV is unable to detect, much less use, any GPUs. My `build.gradle`, in part, reads:

```
repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'

    // This dependency is used by the application.
    implementation 'com.google.guava:guava:30.1.1-jre'

    implementation group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.7'

    implementation 'com.google.code.gson:gson:2.9.0'

     implementation 'com.google.code.gson:gson:2.9.0'

     implementation group: 'org.bytedeco', name: 'cuda-platform-redist', version: '11.6-8.3-1.5.7'
	
     implementation group: 'org.bytedeco', name: 'cuda-platform', version: '11.0-8.0-1.5.7'

     implementation group: 'org.bytedeco', name: 'opencv-platform-gpu', version: '4.5.5-1.5.7'
}
```

Any help in getting CUDA working would be greatly appreciated.

**Comment by saudet** [comment] 2022-02-27 23:14
Jetson doesn't support CUDA 11, yet. You'll need to do your own builds with CUDA 10.2.

I believe @kwatters had some builds for an old version of OpenCV.

**Comment by saudet** [comment] 2022-02-27 23:15
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/918

**Closed by saudet** 2022-02-27 23:15 UTC
Labels: duplicate, enhancement

**Comment by mrfukai** [comment] 2022-02-27 23:25
Thanks for the response! I'm rather new to this sort of thing. Should I be building OpenCV, and, if I am, how would I build it, and what version, and how would I link that up to JavaCV?

**Comment by mrfukai** [comment] 2022-02-27 23:25
You also mentioned that @kwatters had some prebuilts, where can I find those?

**Comment by saudet** [comment] 2022-02-28 00:48
As I mentioned at issue https://github.com/bytedeco/javacpp-presets/issues/918#issuecomment-667776421, the build instructions are available here:
https://github.com/bytedeco/javacpp-presets#build-instructions

**Comment by kwatters** [comment] 2022-02-28 22:05
I did get it building locally a while back...  My goal back then was to get dl4j working with cuda on the nano, which I was successful at.  Those artifacts (the missing ones anyway)  are here:

http://repo.myrobotlab.org/artifactory/myrobotlab/org/bytedeco/
and 
http://repo.myrobotlab.org/artifactory/myrobotlab/org/deeplearning4j/deeplearning4j-cuda-nano/  

I might still have my development environment setup on the nano...  I was hoping by now jetpack would support the newer versions of cuda...

**Comment by mrfukai** [comment] 2022-03-01 00:50
> I did get it building locally a while back... My goal back then was to get dl4j working with cuda on the nano, which I was successful at. Those artifacts (the missing ones anyway) are here:
> 
> http://repo.myrobotlab.org/artifactory/myrobotlab/org/bytedeco/ and http://repo.myrobotlab.org/artifactory/myrobotlab/org/deeplearning4j/deeplearning4j-cuda-nano/
> 
> I might still have my development environment setup on the nano... I was hoping by now jetpack would support the newer versions of cuda...

Thank you so much! I'll try these out.
