### ISSUE TITLE
Weird synchronized block in FFmpegFrameGrabber

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1698] opened 2021-09-20 14:37 UTC
What's the idea behind this synchronized block using a class:

```java
    public void start(boolean findStreamInfo) throws Exception {
        synchronized (org.bytedeco.ffmpeg.global.avcodec.class) {
            startUnsafe(findStreamInfo);
        }
    }
```

Is this really necessary? What I noticed is if the initialization freezes inside ```startUnsafe()``` for some reason (e.g. no input), you can't really create another instance of ```FFmpegFrameGrabber``` because it will freeze as well when entering the synchronized block. In my app I had to stop using the ```start()``` method and switch to calling ```startUnsafe()``` directly, I'm not sure if I risk anything by doing that.

**Comment by saudet** [comment] 2021-09-20 14:48
Some codecs like libx264 are not thread safe. If your application works fine with startUnsafe(), feel free to keep doing that!

**Comment by saudet** [comment] 2021-09-20 14:48
Duplicate of #1139

**Closed by saudet** 2021-09-20 14:48 UTC
Labels: bug, duplicate
