### ISSUE TITLE
Sample FaceRecognition and OpenCVFaceRecognizer failed to compile

### ISSUE THREAD

**Issue by chinadragon0515** [bytedeco/javacv#200] opened 2015-08-13 01:14 UTC
I tried to run the samples provided in the package, but I failed to compile several samples,
1. For FaceRecognition, method cvEigenDecomposite and variable CV_EIGOBJ_NO_CALLBACK is undefined, I did not find a class define them.

2. For OpenCVFaceRecognizer,type FaceRecognizer and method createFisherFaceRecognizer are undefined.

Anyone meet this issue? Anything I did wrong? Or there is some issues here? thanks

**Comment by saudet** [comment] 2015-08-13 02:41
OpenCV 3.0 doesn't include the legacy module anymore, so use FaceRecognizer instead. And that one requires the face module, which isn't part of JavaCV 1.0 release, so for now we need to build from source.

**Comment by saudet** [comment] 2015-08-13 02:43
Duplicate of #196.

**Closed by saudet** 2015-08-13 02:43 UTC
Labels: duplicate, enhancement, question
