### ISSUE TITLE
Error When Creating Bundles

### ISSUE THREAD

**Issue by nikunjramani** [bytedeco/javacv#1494] opened 2020-08-18 14:21 UTC
hii I am Keep getting this error when i Create A Bundle

File 'root/lib/arm64-v8a/include/opencv2/core/base.hpp' uses reserved file or directory name 'lib'.

Here My Dependencies
implementation 'org.bytedeco:javacv:1.4.4'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm64'
    implementation 'org.bytedeco.javacpp-presets:ffmpeg:4.1-1.4.4:android-arm64'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm'
    implementation 'org.bytedeco.javacpp-presets:ffmpeg:4.1-1.4.4:android-arm'

i also try to add external .jar files but I am still getting this error

**Comment by saudet** [comment] 2020-08-19 01:37
Duplicate of #1117

**Comment by saudet** [comment] 2020-08-19 01:38
You'll need to exclude all the files from `lib/arm64-v8a/include`, etc.

**Closed by saudet** 2020-08-19 01:37 UTC
Labels: duplicate, enhancement
