### ISSUE TITLE
Embed Date and time (Android)

### ISSUE THREAD

**Issue by moster67** [bytedeco/javacv#391] opened 2016-04-18 12:00 UTC
I am streaming a video to a server. I am just wondering if it is possible somehow to embed in the streaming video the date and the time (with seconds) - very much like a surveillance camera.
I don't want to add the date/time as an Overlay since I want the date/time to be in the video so in case the video get recorded, the date/time is shown in the video.

I am rather new to this and I noted there a timestamp method/property but I have a feeling it is used for something else. 

Any help would be must appreciated.

**Comment by moster67** [comment] 2016-04-18 12:58
I found this page on Stackoverflow:
[http://stackoverflow.com/questions/3169916/can-ffmpeg-burn-in-time-code]

but I don't know if I can use it.

**Comment by saudet** [comment] 2016-04-18 14:01
Since we're in Java, why not simply use Java 2D to render text?
https://docs.oracle.com/javase/tutorial/2d/overview/text.html

**Comment by saudet** [comment] 2016-04-18 14:03
Or the equivalent Android? 
http://developer.android.com/guide/topics/graphics/2d-graphics.html

**Comment by moster67** [comment] 2016-04-18 14:21
Well, I've been using the Libstreaming-library and already tried to draw on the surfaceview. While I can see my drawing in the preview on the screen, it crashes the app when trying to send it to the server. I am also experimenting by using MediaCodec and openGL instead of MediaRecorder but it is rather advanced stuff. Maybe drawing on a SurfaceView using your library and FFMpeg will work. I will try.

Anyway, this was the reason why I thought about using your library since it looks like this option is supported in the fullblown FFMpeg and perhaps in your library as well. I thought it would be much easier too. Well, if you know it won't work, using for instance videoOptions and the filter drawtext, then I will try with what you suggested.

**Comment by saudet** [comment] 2016-04-19 04:00
Right, FFmpeg comes with a `drawtext` filter that we can use with `FFmpegFrameFilter`, but we need a copy of FFmpeg that was built with libfreetype: https://github.com/bytedeco/javacv/issues/254. So I'm marking this as a duplicate of that issue. If you would like to make a contribution, please give it a try! Thanks

**Closed by saudet** 2016-04-19 04:00 UTC
Labels: duplicate, enhancement
