### ISSUE TITLE
OOM Issue

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1360] opened 2019-12-25 13:40 UTC
I am facing the oom issue when use cvRect method, any suggestion?

Fatal Exception: java.lang.OutOfMemoryError
Physical memory usage is too high: physicalBytes (1027M) > maxPhysicalBytes (1024M)

org.bytedeco.javacpp.Pointer.deallocator (Pointer.java:585)
org.bytedeco.javacpp.Pointer.init (Pointer.java:125)
org.bytedeco.opencv.global.opencv_core.cvRect (opencv_core.java)

**Comment by saudet** [comment] 2019-12-25 23:21
Make sure you're deallocating memory manually, possibly with `PointerScope` as shown here:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by saudet** [comment] 2019-12-27 01:29
If this is happening on Android, also make sure to set the "largeHeap" to "true":
https://developer.android.com/guide/topics/manifest/application-element

**Comment by saudet** [comment] 2019-12-28 00:43
We can also let the process use more memory by setting the "org.bytedeco.javacpp.maxphysicalbytes" system property to the desired value or "0" to disable the check.

**Comment by saudet** [comment] 2019-12-28 00:44
Duplicate of #599

**Closed by saudet** 2019-12-28 00:44 UTC
Labels: duplicate, question

**Comment by saudet** [comment] 2020-06-18 01:05
BTW, I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
Please give it a try with the snapshots: http://bytedeco.org/builds/
