### ISSUE TITLE
Problem when get image from camera

### ISSUE THREAD

**Issue by wuze455192247** [bytedeco/javacv#346] opened 2016-03-04 00:36 UTC
```java
static class TimerAction implements ActionListener {
        private Graphics2D g;
        private CanvasFrame canvasFrame;
        private int width,height;

        private int delta=10;
        private int count = 0;
        private Timer timer;
        public void setTimer(Timer timer){
            this.timer = timer;
        }
        public TimerAction(CanvasFrame canvasFrame){
            this.g = (Graphics2D)canvasFrame.getCanvas().getGraphics();
            this.canvasFrame = canvasFrame;
            this.width = canvasFrame.getCanvas().getWidth();
            this.height = canvasFrame.getCanvas().getHeight();
        }
        public void actionPerformed(ActionEvent e) {
            int offset = delta*count;
            if(width-offset>=offset && height-offset >= offset) {
                g.drawRect(offset, offset, width-2*offset, height-2*offset);
                canvasFrame.repaint();
                count++;
            }else{          
                timer.stop();
                count = 0;
            }
        }
    }

    public static void main(String[] args) throws Exception
    {

        final String savedImageFile = System.getProperty("user.home")+"/my.jpg";   //拍摄所存储的文件
        final OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(0);
        OpenCVFrameConverter converter = new OpenCVFrameConverter.ToIplImage();
        grabber.start(); 
        opencv_core.IplImage image =converter.convertToIplImage(grabber.grab()); /
        final int width = image.width();
        final int height = image.height();
        final BufferedImage bImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D bGraphics = bImage.createGraphics();

        CanvasFrame canvas = new CanvasFrame("Camera",1);
        canvas.setCanvasSize(width, height);

      
        TimerAction timerAction = new TimerAction(canvas);
        final Timer timer=new Timer(10, timerAction);
        timerAction.setTimer(timer);



        canvas.getCanvas().addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                timer.start();
                try{
                    ImageIO.write(bImage, "jpg", new File(savedImageFile));//数据写入my.jpg
                }
                catch (IOException e1){
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            }
        });
        while(canvas.isVisible() && (converter.convertToIplImage(grabber.grab())) != null){
            if(!timer.isRunning()) {
                canvas.showImage(converter.convert(image));
                bGraphics.drawImage(bImage, null, 0, 0);
            }
        }
        cvReleaseImage(image);
        grabber.stop();
        canvas.dispose();
    }
```

The image I saved is a black image.... How can I get the image from the camera?

**Comment by saudet** [comment] 2016-03-04 02:12
What do you see when running this sample Demo class?
https://github.com/bytedeco/javacv#sample-usage

**Comment by saudet** [comment] 2016-03-27 10:10
Probably a duplicate of #357. But please let me know if `VideoCapture` also doesn't work, thanks!

**Closed by saudet** 2016-03-27 10:10 UTC
Labels: bug, duplicate
