### ISSUE TITLE
I want a linux-arm64 classifier

### ISSUE THREAD

**Issue by 256655** [bytedeco/javacv#1493] opened 2020-08-18 12:25 UTC
It may be like this

```
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>opencv</artifactId>
    <version>4.0.1-1.4.4</version>
    <classifier>linux-arm64</classifier>
</dependency>
```
thanks

**Comment by saudet** [comment] 2020-08-18 12:27
It already exists.

**Comment by 256655** [comment] 2020-08-18 12:28
where is it ?

**Comment by saudet** [comment] 2020-08-18 12:28
Duplicate of #1021.

**Closed by saudet** 2020-08-18 12:28 UTC

**Comment by saudet** [comment] 2020-08-18 12:30
Here, for example: https://repo.maven.apache.org/maven2/org/bytedeco/opencv/4.3.0-1.5.3/

**Comment by 256655** [comment] 2020-08-18 12:47
Thank you very much !

**Comment by jurimengs** [comment] 2023-05-23 11:40
HI its not work for me , can you help , tks!
<img width="1150" alt="image" src="https://github.com/bytedeco/javacv/assets/10648133/7195c8d0-f84d-4a58-9c35-9f76efa321ff">
