### ISSUE TITLE
framegrabber to grab high resolution video

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1203] opened 2019-05-05 02:45 UTC
i have a video 3000*2000 resolution, i use framegrabber on android, find it hang some where when grab frame, i guess its because oom issue in ffmpeg, ang suggestion?

**Comment by saudet** [comment] 2019-05-05 06:34
Duplicate of #707

Try to use a "largeHeap".

**Closed by saudet** 2019-05-05 06:34 UTC
Labels: duplicate, question
