### ISSUE TITLE
version 1.2 Record Activity

### ISSUE THREAD

**Issue by moranmoa** [bytedeco/javacv#413] opened 2016-05-23 09:31 UTC
i am trying to build Record Activity sample using android studio 2.1.1
i extract the zip bin 1.2 to the lib folder 
added to the gradle.build file
compile group: 'org.bytedeco', name: 'javacv', version: '1.2'
i am getting 
Error:A problem occurred configuring project ':app'.

Could not find javacpp-presets-Windows 10-amd64.jar (org.bytedeco:javacpp-presets:1.2).
Searched in the following locations:
https://jcenter.bintray.com/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Windows 10-amd64.jar

ty

**Comment by saudet** [comment] 2016-05-23 09:38
Duplicate of https://github.com/bytedeco/javacv/issues/395

**Closed by saudet** 2016-05-23 09:38 UTC
Labels: bug
