### ISSUE TITLE
PipedInputStream recoder via http

### ISSUE THREAD

**Issue by SpringStudent** [bytedeco/javacv#1690] opened 2021-09-10 09:09 UTC
I want to impl command with javacv like:
`ffmpeg-hwaccel auto-rtsp_transport tcp -i rtsp://xxx -f mpegts -codec :v mpeg1video -bf 0-codec :a mp2-r 30 -q 10 -b:v 1000K -S 960x520-an http://xxx `
but I only can got the PS raw stream from the camera, so I wrapped the stream as `PipedInputStream` then provided it to FFmpegFrameGrabber. I tried to turn the stream into an mpegts format that can play via jsmpeg. js ,and forward it to the front via HTTP ->websocket,jsmpeg.js got the stream but can't play well.

**Comment by SpringStudent** [comment] 2021-09-10 09:11
the code is
`avutil.av_log_set_level(avutil.AV_LOG_INFO);
            FFmpegLogCallback.set();
            grabber = new FFmpegFrameGrabber(pin, 0);
            long stime = System.currentTimeMillis();
            //从这里就要等待海康/大华/宇视等设备sdk回调函数传输数据，所以需要开始阻塞等待，这里只等三秒，大家可以根据自己需要修改
            long waitStreamDelay = 3000;
            for (; ; ) {
                System.out.println("等待检查流");
                //检测管道流中是否存在数据，如果3s后依然没有写入1024的数据，则认为管道流中无数据，避免grabber.start();发生阻塞
                if (System.currentTimeMillis() - stime > waitStreamDelay) {
                    return;
                }
                if (pin.available() == 1024) {
                    break;
                }

                Thread.sleep(100);
            }
            grabber.start();
            // 部分监控设备流信息里携带的帧率为9000，如出现此问题，会导致dts、pts时间戳计算失败，播放器无法播放，故出现错误的帧率时，默认为25帧
            if (grabber.getFrameRate() > 0 && grabber.getFrameRate() < 100) {
                framerate = grabber.getFrameRate();
            } else {
                framerate = 25.0;
            }
            recorder = new FFmpegFrameRecorder("http://172.16.1.214:1111/rtsp/receive?id=1", 960, 520);
//            recorder = new FFmpegFrameRecorder("rtmp://172.16.2.201/live/livestream", grabber.getImageWidth(), grabber.getImageHeight());
            recorder.setInterleaved(true);
            // 关键帧间隔，一般与帧率相同或者是视频帧率的两倍
            recorder.setGopSize((int) framerate * 2);
            // 视频帧率(保证视频质量的情况下最低25，低于25会出现闪屏)
            recorder.setFrameRate(framerate);
            // 设置比特率
            recorder.setVideoBitrate(grabber.getVideoBitrate());
            // 封装flv格式
            recorder.setFormat("mpegts");
            // h264编/解码器
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG1VIDEO);
            recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
            Map<String, String> videoOption = new HashMap<>();
            // 该参数用于降低延迟
            videoOption.put("tune", "zerolatency");
            videoOption.put("preset", "ultrafast");
            // 画面质量参数，0~51；18~28是一个合理范围
            videoOption.put("crf", "28");
            recorder.setOptions(videoOption);
            AVFormatContext fc = grabber.getFormatContext();
            recorder.start(fc);
            logger.debug("开始推流 设备信息");
            // 清空探测时留下的缓存
            grabber.flush();
            AVPacket pkt = null;
            long dts = 0;
            long pts = 0;
            int timebase = 0;
            for (int no_frame_index = 0; no_frame_index < 5 && err_index < 5; ) {
                long time1 = System.currentTimeMillis();
                if (exitcode == 1) {
                    break;
                }
                pkt = grabber.grabPacket();
                if (pkt == null || pkt.size() == 0 || pkt.data() == null) {
                    // 空包记录次数跳过
                    logger.warn("JavaCV 出现空包 设备信息");
                    no_frame_index++;
                    continue;
                }
                // 过滤音频
                if (pkt.stream_index() == 1) {
                    av_packet_unref(pkt);
                    continue;
                }
                // 矫正sdk回调数据的dts，pts每次不从0开始累加所导致的播放器无法续播问题
                pkt.pts(pts);
                pkt.dts(dts);
                err_index += (recorder.recordPacket(pkt) ? 0 : 1);
                // pts,dts累加
                timebase = grabber.getFormatContext().streams(pkt.stream_index()).time_base().den();
                pts += timebase / (int) framerate;
                dts += timebase / (int) framerate;
                // 将缓存空间的引用计数-1，并将Packet中的其他字段设为初始值。如果引用计数为0，自动的释放缓存空间。
                av_packet_unref(pkt);
                long endtime = System.currentTimeMillis();
                if ((long) (1000 / framerate) - (endtime - time1) > 0) {
                    Thread.sleep((long) (1000 / framerate) - (endtime - time1));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally {
            release();
        }`
output is
`Info: Input #0, mpeg, from 'java.io.BufferedInputStream@726533cc':

Info:   Duration: 
Info: N/A
Info: , start: 
Info: 31898.356622
Info: , bitrate: 
Info: N/A
Info: 

Info:     Stream #0:0
Info: [0x1e0]
Info: : Video: h264 (Main), yuv420p(progressive), 1920x1080
Info: , 
Info: 25 fps, 
Info: 25 tbr, 
Info: 90k tbn, 
Info: 50 tbc
Info: 

Warning: [mpegts @ 000000003fd63e80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

Info: Output #0, mpegts, to 'http://172.16.1.214:1111/rtsp/receive?id=1':

Info:   Metadata:

Info:     encoder         : 
Info: Lavf58.29.100
Info: 

Info:     Stream #0:0
Info: : Video: h264 (Main), yuv420p(progressive), 1920x1080, q=2-31
Info: , SAR 1:1 DAR 16:9
Info: , 
Info: 25 fps, 
Info: 90k tbn, 
Info: 25 tbc
Info: `

**Comment by saudet** [comment] 2021-09-10 09:23
We can easily run that ffmpeg command as is from Java:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by SpringStudent** [comment] 2021-09-10 09:28
the media stream was came from camera callback which is byte array,so i can't user ffmpeg command,here is stream source code
```
public class FPlayDataCallBackImpl implements HCNetSDK.FPlayDataCallBack {

    private PsFrameByteDecoder frameByteDecoder;

    @Override
    public void invoke(NativeLong lPlayHandle, int dwDataType, ByteByReference pBuffer, int dwBufSize, int dwUser) {
        switch (dwDataType) {
            // 
            case HCNetSDK.NET_DVR_SYSHEAD:
            // stream media
            case HCNetSDK.NET_DVR_STREAMDATA:
                if (dwBufSize > 0) {
                    try {
                        byte[] outputData = pBuffer.getPointer().getByteArray(0, dwBufSize);
                        if (frameByteDecoder == null) {
                            frameByteDecoder = new PsFrameByteDecoder();
                            frameByteDecoder.start();
                        } else {
                            frameByteDecoder.push(outputData, dwBufSize);
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
        }
    }
}
```

**Comment by saudet** [comment] 2021-09-10 10:03
The grabPacket()/recordPacket() functions do have some problems, see issue #818.

**Comment by saudet** [comment] 2021-09-10 10:03
Duplicate of #818

**Closed by saudet** 2021-09-10 10:03 UTC
Labels: bug, duplicate
