### ISSUE TITLE
Is there a "follow me" for speed up SVM/ANN training using CUDA support?

### ISSUE THREAD

**Issue by yanhuixie** [bytedeco/javacv#639] opened 2017-03-09 08:38 UTC
After searched google and bytedeco/javacv issues I have noticed that javacv supports CUDA already. But I can't find an instruction to make it works. I mainly want to speed up the SVM/ANN training process. You know, it's tooooo slow via the general api and it even not support CPU multi-thread... Could somebody helps? Thanks!

**Comment by saudet** [comment] 2017-03-09 11:27
Duplicate of #481 

Contributions welcome!

**Closed by saudet** 2017-03-09 11:27 UTC
Labels: duplicate, enhancement
