### ISSUE TITLE
OpenCVFrameConverter.ToMat or LeptonicaFrameConverter corrupting image

### ISSUE THREAD

**Issue by msmuenchen** [bytedeco/javacv#2169] opened 2024-01-07 23:24 UTC
I'm trying to pass a black-and-white Mat image (resulting out of some quite heavy preprocessing with OpenCV) to Tesseract for OCR.

The problem was that the Tesseract output was pure and utter garbage, getting worse from top to bottom - investigation showed that apparently the conversion `Mat` to `Frame` or the conversion `Frame` to `PIX` goes bonkers. It seems as if the stride calculation in one of the format converters is the culprit, as each new line is shifted towards the right by 1px more than the previous line and what was white has now very weird color artifacts - however I couldn't find anything to dump a Frame into an image file so I can't say which of the converters is at fault.

I have attached the minimal reproduction case as well as the image that can be used for input.

```java

import org.bytedeco.javacpp.BytePointer;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.LeptonicaFrameConverter;
import org.bytedeco.javacv.OpenCVFrameConverter;
import org.bytedeco.leptonica.PIX;
import org.bytedeco.leptonica.global.leptonica;
import org.bytedeco.opencv.global.opencv_imgcodecs;
import org.bytedeco.opencv.opencv_core.Mat;

public class FrameConverterTest {
    public static void main(String[] args) {
        LeptonicaFrameConverter lfc = new LeptonicaFrameConverter();
        OpenCVFrameConverter.ToMat matConverter = new OpenCVFrameConverter.ToMat();

        Mat originalImage= opencv_imgcodecs.imread(System.getProperty("user.dir")+"/prepare_11_post_denoise.jpg"); // replace this here by whatever method you're getting the original Mat from, this is just for reproduction
        opencv_imgcodecs.imwrite(System.getProperty("user.dir")+"/orig.jpg", originalImage);

        Frame ocrFrame = matConverter.convert(originalImage);
        PIX img = lfc.convert(ocrFrame);
        leptonica.pixWriteJpeg(new BytePointer(System.getProperty("user.dir")+"/pix.jpg"), img, 75, 0);
    }
}

```

Note that Tesseract is not at fault at all - the workaround of just using `leptonica.pixRead` to ingest the image works and yields expected results, but is obviously cumbersome and gobbles up time.

```java
img = leptonica.pixRead(System.getProperty("user.dir")+"/orig.jpg");
```

![orig](https://github.com/bytedeco/javacv/assets/2284268/523873b0-4446-4c2b-917f-202c915064ea)

![pix](https://github.com/bytedeco/javacv/assets/2284268/b6468a1a-a9f4-477b-8310-d755da095da5)

**Comment by saudet** [comment] 2024-01-08 01:17
That happens because Leptonica has strange stride requirements not supported by OpenCV, Java2D, etc. Until someone is nice enough to enhance LeptonicaFrameConverter to copy images in that case, we can work around this by resizing images, see issue #1115

**Comment by saudet** [comment] 2024-01-08 01:18
Duplicate of #1115

**Closed by saudet** 2024-01-08 01:18 UTC
Labels: duplicate, enhancement

**Comment by msmuenchen** [comment] 2024-01-08 08:27
@saudet I'll look into that... do you have helper functions that can directly serialize/deserialize a Frame?

**Comment by saudet** [comment] 2024-01-08 10:29
No, but OpenCV does so we can use those
