### ISSUE TITLE
Fatal signal 11 (SIGSEGV) In SAMSUNG On5 Marshmallow 6.0.1

### ISSUE THREAD

**Issue by Ubhadiyap** [bytedeco/javacv#553] opened 2016-11-08 06:23 UTC
11-07 17:11:58.201: A/libc(29986): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 30245 (IntentService[i)
11-07 17:11:58.266: A/DEBUG(2197): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-07 17:11:58.266: A/DEBUG(2197): Build fingerprint: 'samsung/o5ltedd/o5lte:6.0.1/MMB29K/G550FYDDU1BPH2:user/release-keys'
11-07 17:11:58.266: A/DEBUG(2197): Revision: '0'
11-07 17:11:58.266: A/DEBUG(2197): ABI: 'arm'
11-07 17:11:58.266: A/DEBUG(2197): pid: 29986, tid: 30245, name: IntentService[i  >>> com.slideshowmaker.app <<<
11-07 17:11:58.266: A/DEBUG(2197): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
11-07 17:11:58.306: A/DEBUG(2197):     r0 00000000  r1 00000000  r2 00000000  r3 fffffe98
11-07 17:11:58.306: A/DEBUG(2197):     r4 9c826594  r5 00000000  r6 b38811a4  r7 00000001
11-07 17:11:58.306: A/DEBUG(2197):     r8 b6f1d70c  r9 0000000b  sl b38811a4  fp b6f1658f
11-07 17:11:58.306: A/DEBUG(2197):     ip 00000000  sp 9cfe9ed0  lr 9c7c675d  pc 9c7caf76  cpsr 40070030
11-07 17:11:58.326: A/DEBUG(2197): backtrace:
11-07 17:11:58.326: A/DEBUG(2197):     #00 pc 0001af76  /data/data/com.slideshowmaker.app/cache/javacpp9867438203741/libc.so (_Z18__libc_init_commonR19KernelArgumentBlock+9)
11-07 17:11:58.326: A/DEBUG(2197):     #01 pc 00016759  /data/data/com.slideshowmaker.app/cache/javacpp9867438203741/libc.so (_ZL14__libc_preinitv+12)
11-07 17:11:58.326: A/DEBUG(2197):     #02 pc 000023d1  /system/bin/linker (__dl__ZN6soinfo13call_functionEPKcPFvvE+48)
11-07 17:11:58.326: A/DEBUG(2197):     #03 pc 0000249d  /system/bin/linker (__dl__ZN6soinfo10call_arrayEPKcPPFvvEjb+136)
11-07 17:11:58.326: A/DEBUG(2197):     #04 pc 00002661  /system/bin/linker (__dl__ZN6soinfo17call_constructorsEv+160)
11-07 17:11:58.326: A/DEBUG(2197):     #05 pc 00005f9d  /system/bin/linker (__dl__Z9do_dlopenPKciPK17android_dlextinfo+224)
11-07 17:11:58.326: A/DEBUG(2197):     #06 pc 00001bad  /system/bin/linker (__dl_dlopen+20)
11-07 17:11:58.326: A/DEBUG(2197):     #07 pc 0024f7a1  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectPS9_+608)
11-07 17:11:58.326: A/DEBUG(2197):     #08 pc 002c114b  /system/lib/libart.so (_ZN3artL18Runtime_nativeLoadEP7_JNIEnvP7_jclassP8_jstringP8_jobjectS5_+178)
11-07 17:11:58.326: A/DEBUG(2197):     #09 pc 031dc51d  /system/framework/arm/boot.oat (offset 0x2fcf000)
11-07 17:11:58.431: I/display(2183): [PrimaryDisplay] [DYNAMIC_RECOMP] HWC_2_GLES by low FPS(0)
11-07 17:11:59.201: D/NetworkPolicy(2547): isUidForegroundLocked: 10005, mScreenOn: true, uidstate: 6, mProxSensorScreenOff: false
11-07 17:11:59.201: D/NetworkPolicy(2547): isUidForegroundLocked: 10005, mScreenOn: true, uidstate: 6, mProxSensorScreenOff: false
11-07 17:11:59.381: I/PersonaManager(2547): mKnoxInfo is empty
11-07 17:11:59.386: W/ActivityManager(2547): Process com.slideshowmaker.app has crashed too many times: killing!
11-07 17:11:59.386: A/DEBUG(2197): Tombstone written to: /data/tombstones/tombstone_04
11-07 17:11:59.386: E/DEBUG(2197): AM write failed: Broken pipe
11-07 17:11:59.386: E/(2197): ro.product_ship = true
11-07 17:11:59.386: E/(2197): ro.debug_level = 0x4f4c
11-07 17:11:59.386: E/(2197): sys.mobilecare.preload = false
11-07 17:11:59.386: I/BootReceiver(2547): Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
11-07 17:11:59.386: D/progressDisplay(29986): processing 1
11-07 17:11:59.391: E/audit(3849): type=1701 msg=audit(1478518919.386:846): auid=4294967295 uid=10018 gid=10018 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=30245 comm="IntentService[i" reason="memory violation" sig=11

**Comment by saudet** [comment] 2016-11-08 08:34
Duplicate of #412. Please used the latest version of JavaCPP.

**Closed by saudet** 2016-11-08 08:34 UTC
Labels: bug, duplicate
