### ISSUE TITLE
javacv - 1.5.4 windows server 2012  UnsatisfiedLinkError: no avutil in java.library.path

### ISSUE THREAD

**Issue by lypenghao** [bytedeco/javacv#1562] opened 2021-01-13 09:21 UTC
Environment Details
OS - Windows Server2012
java - jdk-7u79-windows-x64
javacv - 1.5.4

(1)Debug info like this

Debug: Loading library avcodec-58
Debug: Failed to load for avcodec-58: java.lang.UnsatisfiedLinkError: no avcodec
-58 in java.library.path
Debug: Loading library avutil
Debug: Failed to load for avutil@.56: java.lang.UnsatisfiedLinkError: no avutil
in java.library.path
Debug: Loading library swresample
Debug: Failed to load for swresample@.3: java.lang.UnsatisfiedLinkError: no swre
sample in java.library.path
Debug: Loading library avcodec
Debug: Failed to load for avcodec@.58: java.lang.UnsatisfiedLinkError: no avcode
c in java.library.path
Debug: Locking C:\Users\Aurora\.javacpp\cache before extracting
Debug: Extracting jar:file:/E:/apache-tomcat-8.0.53/webapps/DocSystem/WEB-INF/li
b/ffmpeg-windows-x86_64.jar!/org/bytedeco/ffmpeg/windows-x86_64/jniavcodec.dll
Debug: Loading C:\Users\Aurora\.javacpp\cache\ffmpeg-windows-x86_64.jar\org\byte
deco\ffmpeg\windows-x86_64\jniavcodec.dll
Debug: Failed to load C:\Users\Aurora\.javacpp\cache\ffmpeg-windows-x86_64.jar\o
rg\bytedeco\ffmpeg\windows-x86_64\jniavcodec.dll: java.lang.UnsatisfiedLinkError
: C:\Users\Aurora\.javacpp\cache\ffmpeg-windows-x86_64.jar\org\bytedeco\ffmpeg\w
indows-x86_64\jniavcodec.dll: Can't find dependent libraries
Debug: Loading library jniavcodec
Debug: Failed to load for jniavcodec: java.lang.UnsatisfiedLinkError: no jniavco
dec in java.library.path
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Debug: Loading class org.bytedeco.ffmpeg.global.swresample
Debug: Loading class org.bytedeco.ffmpeg.global.avcodec

(2)Other info like this
In directory:C:\Users\myuer\.javacpp\cache\ffmpeg-windows-x86_64.jar\org\bytedeco\ffmpeg\windows-x86_64 
most of file in this directory is Symbol link  file  like this 
![1610529062(1)](https://user-images.githubusercontent.com/16351436/104431492-ea6d9a80-55c2-11eb-9291-1a8b52bac86c.png)

Windows 7，windows 10 OS  files in the same directory are dll

(3) Windows 7，windows 10 OS  javacv  working properly

**Comment by saudet** [comment] 2021-01-13 09:55
Please make sure that Media Foundation is installed like this:
https://github.com/bytedeco/javacv/blob/master/.travis.yml#L64

**Comment by saudet** [comment] 2021-01-13 09:55
Duplicate of bytedeco/javacpp-presets#940

**Closed by saudet** 2021-01-13 09:55 UTC
Labels: duplicate, question

**Comment by lypenghao** [comment] 2021-01-14 02:52
@saudet  
Ok :(, Thank you for helping me @saudet.

**Comment by saudet** [comment] 2021-01-14 03:39
Are you saying you're not able to install Media Foundation?
