### ISSUE TITLE
[JAVA 11] Problem running samples

### ISSUE THREAD

**Issue by denismakogon** [bytedeco/javacv#1251] opened 2019-07-16 14:05 UTC
With JAVA 11 (docker image `openjdk:11`), I was trying to run sample apps (with some modifications like getting an image from a source, etc.). But it doesn't seem to work due to a shared object absence:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
        at java.base/java.lang.System.loadLibrary(System.java:1867)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1483)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1186)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
        at org.bytedeco.opencv.global.opencv_highgui.<clinit>(opencv_highgui.java:22)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
        at org.bytedeco.opencv.opencv_objdetect.CascadeClassifier.<clinit>(CascadeClassifier.java:38)
        at com.pinealpha.demos.jimage.App.detectFaceBoxes(App.java:83)
        at com.pinealpha.demos.jimage.App.main(App.java:66)
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/jimage.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_highgui.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1831)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1457)
        ... 10 more
```

I'm not new to OpenCV and I know that if you want to make it work - compile it from sources. But here, I'm kinda lost, because sample apps work fine on Java 9 and 10, but they are not on J11.

Please assist.

**Comment by saudet** [comment] 2019-07-16 14:09
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/593

**Comment by saudet** [comment] 2019-07-16 14:09
This just means that GTK needs to be installed.

**Closed by saudet** 2019-07-16 14:09 UTC
Labels: duplicate, enhancement, question
