### ISSUE TITLE
JavaCV/CUDA/Win10 64 bit

### ISSUE THREAD

**Issue by neil-benn** [bytedeco/javacv#1585] opened 2021-02-02 16:29 UTC
Hello,

  Sorry to keep messaging about CUDA; I've got a laptop with an Nvidia card in it and an integrated card in it (2X GPU).  I've pulled in the libraries for OpenCV as follows:

    
    <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>javacv-platform</artifactId>
        <version>1.5.4</version>
    </dependency>
    
    <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>opencv-platform-gpu</artifactId>
        <version>4.4.0-1.5.4</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>cuda-platform-redist</artifactId>
        <version>11.0-8.0-1.5.4</version>
    </dependency>

  When I run an appassemblere this brings in the jars:

opencv-platform-gpu-4.4.0-1.5.4.jar
cuda-11.0-8.0-1.5.4-linux-ppc64le-redist.jar
cuda-11.0-8.0-1.5.4-linux-ppc64le.jar
cuda-11.0-8.0-1.5.4-linux-x86_64-redist.jar
cuda-11.0-8.0-1.5.4-linux-x86_64.jar
cuda-11.0-8.0-1.5.4-windows-x86_64-redist.jar
cuda-11.0-8.0-1.5.4-windows-x86_64.jar
cuda-11.0-8.0-1.5.4.jar
cuda-platform-11.0-8.0-1.5.4.jar
cuda-platform-redist-11.0-8.0-1.5.4.jar

  Along with all the other opencv/javacv jars.  I then run my code which has a lot fo image manipulation in OpenCV such as scales, cutout, rotation, thresholding and up the number of threads to 100 - 400 (depending on the job being run).  However monitoring the GPU; it seems that the GPU isn't touched at all and the processing times are exactly the same as not using CUDA..  Am I doing something wrong with my libraries or are there only certain methods which are diverted to the GPU via CUDA?

  Thanks.

Cheers,

Neil

**Comment by saudet** [comment] 2021-02-03 03:27
It's fine to ask as many questions as you want, although the discussion forum is a more appropriate format than issues for that...

OpenCV isn't going to use your GPU automatically unless you explicitly call functions that can use a GPU. In general, you'll need to call functions that accept UMat and/or GpuMat instead of Mat to benefit from GPU acceleration.

**Comment by saudet** [comment] 2021-02-03 03:29
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/984

**Closed by saudet** 2021-02-03 03:29 UTC
Labels: duplicate, question
