### ISSUE TITLE
How to use javacv record  byte[] stream?

### ISSUE THREAD

**Issue by eguid** [bytedeco/javacv#516] opened 2016-09-28 09:23 UTC
I want to use javacv to record as byte[] stream, any suggestion to develop this?

**Comment by saudet** [comment] 2016-09-28 10:47
Use a [ByteArrayInputStream](https://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayInputStream.html), but first need to implement support for InputStream. 

Marking as duplicate of #95

**Closed by saudet** 2016-09-28 10:47 UTC
Labels: duplicate, enhancement
