### ISSUE TITLE
Issue with ".showimage()" method

### ISSUE THREAD

**Issue by valarmoghulis** [bytedeco/javacv#352] opened 2016-03-09 10:09 UTC
I think this is probably because I'm a newbie to this thing.

But I've been having issues with this showimage() method refusing to display an IplImage image type.

Here is a screenshot of the error message
![untitled](https://cloud.githubusercontent.com/assets/5165873/13631795/e21387d8-e5ff-11e5-8fed-35092dfd3c53.png)

I've tried searching to understand why but it just doesn't seem to work. I was feeling I needed a certain import to make it work & I tried almost everything but couldn't make it work.

Someone in stackoverflow suggested using BufferedImage, but it just doesn't work as I want it to.

**Comment by saudet** [comment] 2016-03-09 10:32
Duplicate of #344

**Closed by saudet** 2016-03-09 10:32 UTC
Labels: duplicate, question
