### ISSUE TITLE
setUpNet DNN module was not built with CUDA backend; switching to CPU

### ISSUE THREAD

**Issue by schungzhihuai** [bytedeco/javacv#1512] opened 2020-09-23 10:37 UTC
Hi, previously I was running into errors with the codes due to missing presets. However after installing all of them and adding into the constructor:

net.setPreferableBackend(DNN_BACKEND_CUDA)
net.setPreferableTarget(DNN_TARGET_CUDA)

I received a warning "setUpNet DNN module was not built with CUDA backend; switching to CPU"

I realize the dnn was not detecting fast enough and was checking if it was targeting CUDA. 

I have installed CUDA toolkit and cuDNN but I still encounter the same error.

**Comment by saudet** [comment] 2020-09-23 10:40
You'll need to make sure you have all these dependencies in your class path:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#the-pomxml-build-file

**Comment by saudet** [comment] 2020-09-23 10:40
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/923

**Closed by saudet** 2020-09-23 10:40 UTC
Labels: duplicate, question
