### ISSUE TITLE
how to use OpenGL library interface in JavaCV

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2139] opened 2023-12-06 02:09 UTC
how to use OpenGL library to process complex image effects???

**Comment by saudet** [comment] 2023-12-06 04:17
You probably mean OpenCL. Just use functions accepting UMat instead of Mat, and they will be able to use OpenCL.

**Comment by saudet** [comment] 2023-12-06 04:18
Duplicate of #2063

**Closed by saudet** 2023-12-06 04:18 UTC
Labels: duplicate, question
