### ISSUE TITLE
FrameRecorder packet recording issue with rtsp

### ISSUE THREAD

**Issue by imvinaypatil** [bytedeco/javacv#973] opened 2018-04-26 05:30 UTC
I've been trying to record rtsp stream in a mp4 container with the Sample [PacketRecorderTest.java](https://github.com/bytedeco/javacv/blob/master/samples/PacketRecorderTest.java), The code works well for frame recording but while packet recording only the first frame is being recorded with the following log. @alicanalbayrak am i missing something here ?

**Warning: [mp4 @ 00000000205a3800] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Warning: [mp4 @ 00000000205a3800] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
Warning: [mp4 @ 00000000205a3800] Encoder did not produce proper pts, making some up.**

javacpp  1.4.1
ffmpeg  3.4.2-1.4.1
ffmpeg-platform 3.4.2-1.4.1
javacv 1.4.1

**Comment by saudet** [comment] 2018-04-26 05:45
This is pretty much a duplicate of issue #818. Let's continue the discussion there.

**Closed** 2018-04-26 05:45 UTC
Labels: bug, duplicate
