### ISSUE TITLE
Video codec hevc not compatible with flv

### ISSUE THREAD

**Issue by ChanliuKrush** [bytedeco/javacv#1523] opened 2020-10-12 08:17 UTC
Input #0, mpeg, from 'java.io.BufferedInputStream@7fa5f71':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0[0x1e0]: Video: hevc (Main), yuvj420p(pc, bt709), 1920x1080, 25 fps, 25 tbr, 90k tbn
[flv @ 000002209f2f3440] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[flv @ 000002209f2f3440] Video codec hevc not compatible with flv

 grabber = new FFmpegFrameGrabber(inputStream, 0);
                    grabber.setOption("stimeout", "2000000");
                    grabber.setVideoOption("vcodec", "copy");
                    grabber.setFormat("mpeg");
                    grabber.setPixelFormat(avutil.AV_PIX_FMT_YUVJ420P);
                    grabber.setVideoCodec(avcodec.AV_CODEC_ID_H265);
                    grabber.setAudioStream(Integer.MAX_VALUE);
                    grabber.setFrameRate(25);
                    log.debug("grabber start");
                    grabber.start();
                    log.debug("grabber end");
                    recorder = new FFmpegFrameRecorder(targetUrl,
                            grabber.getImageWidth(), grabber.getImageHeight(), 0);
                    recorder.setInterleaved(true);
                    recorder.setVideoBitrate(2500000);
                    recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
                    recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
                    recorder.setFormat("flv");
                    recorder.setFrameRate(grabber.getFrameRate());
                    recorder.setGopSize((int) grabber.getFrameRate() * 2);
                    AVFormatContext fc = null;
                    fc = grabber.getFormatContext();
                    recorder.start(fc);
                    grabber.flush();

javacv verison:1.5.4

**Comment by saudet** [comment] 2020-10-12 08:19
Duplicate of #1497

**Closed by saudet** 2020-10-12 08:19 UTC
Labels: duplicate, question
