### ISSUE TITLE
How should I set up FFmpegFrameRecorder for hardware acceleration？

### ISSUE THREAD

**Issue by sunplusApp** [bytedeco/javacv#2161] opened 2023-12-31 10:40 UTC
I am using FFmpegFrameRecorder on Android to encode yuv into mp4. The CPU usage is very high, and I want to use hardware acceleration. How should I set up FFmpegFrameRecorder?

**Comment by sunplusApp** [comment] 2023-12-31 10:58
Use mediacodec or vulkan？

**Comment by saudet** [comment] 2023-12-31 11:57
You'll need to call something like setVideoCodecName("h264_mediacodec") before start().

**Comment by saudet** [comment] 2023-12-31 11:57
Duplicate of #2046

**Closed by saudet** 2023-12-31 11:57 UTC
Labels: duplicate, question
