### ISSUE TITLE
AndroidFrameConverter 

### ISSUE THREAD

**Issue by zhengbin1015** [bytedeco/javacv#713] opened 2017-06-07 07:49 UTC
I am trying to convert a Frame of size 1280x720 into Bitmap using javacv AndroidFrameConverter and it takes long time to convert. Here is the sample code of converting.
FrameGrabber grabber = new FFmpegFrameGrabber(videoUrl);
frame = grabber.grab();
AndroidFrameConverter converter = new AndroidFrameConverter();
Bitmap originalBitmap = converter.convert(frame);
is there any other solution which is faster than this?

**Comment by saudet** [comment] 2017-06-07 09:27
Try to use FFmpeg to convert to RGBA.

**Comment by saudet** [comment] 2017-06-07 09:29
Duplicate of #214.

**Closed** 2017-06-07 09:30 UTC
Labels: duplicate, question
