### ISSUE TITLE
Need help, please provide a new version which can run on centos

### ISSUE THREAD

**Issue by ZhanPro** [bytedeco/javacv#2262] opened 2024-08-02 06:56 UTC
Dear JavaCV Developers,

I have been using JavaCV in a production environment for almost a year now. Its performance is excellent, and our team members really appreciate it. I have also promoted the use of JavaCV to other teams. However, there is an issue with off-heap memory leaks in version 1.5.8, which forces us to restart the service every few days.

Recently, you recommended using version 1.5.11-SNAPSHOT in the issues section, but this version does not run on CentOS. Our production servers are still running CentOS 7, and we will not be switching to another OS version in the next year. These decisions are beyond my control as a developer.

Therefore, I earnestly request that you provide a version compiled for CentOS. I believe I am not the only developer facing this issue, and having such a version would be very beneficial. Thank you very much!

Best regards.

**Comment by saudet** [comment] 2024-08-02 11:00
Contributions are welcome!

**Comment by saudet** [comment] 2024-08-02 11:01
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-08-02 11:01 UTC
Labels: duplicate, enhancement
