### ISSUE TITLE
How to capture screen with javacv ? 

### ISSUE THREAD

**Issue by poorvajappja** [bytedeco/javacv#1436] opened 2020-05-30 16:46 UTC
How to capture screen with javacv in windows os?

**Comment by saudet** [comment] 2020-05-30 21:41
https://github.com/bytedeco/javacv/wiki/Screen-Capture-on-Windows

**Comment by saudet** [comment] 2020-05-30 21:42
Duplicate of #31

**Closed by saudet** 2020-05-30 21:42 UTC
Labels: duplicate, question
