### ISSUE TITLE
 java.lang.UnsatisfiedLinkError for the latest release 1.3.2 for Android

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#646] opened 2017-03-22 00:39 UTC
Hi

I update the javacv lib to the latest, nothing else changed, then i found this error:

Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/base.apk"],nativeLibraryDirectories=[/data/app/base.apk/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so"
java.lang.Runtime.loadLibrary (Runtime.java:366)
java.lang.System.loadLibrary (System.java:988)
org.bytedeco.javacpp.Loader.loadLibrary (Loader.java:958)
org.bytedeco.javacpp.Loader.load (Loader.java:747)
org.bytedeco.javacpp.Loader.load (Loader.java:666)
org.bytedeco.javacpp.opencv_core.<clinit> (opencv_core.java:10)
org.bytedeco.javacpp.helper.opencv_core.CV_RGB (opencv_core.java:1635)

**Comment by saudet** [comment] 2017-03-22 01:14
Use JavaCPP 1.3.2 as well, it will fix that error.

**Comment by xiaos** [comment] 2017-03-22 03:15
@saudet , i think i am using javacpp 1.3.2 from http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv-platform/1.3.2/javacv-platform-1.3.2-bin.zip

**Comment by saudet** [comment] 2017-03-22 03:28
Not if you're getting errors like `couldn't find "libgnustl_static.so"`

Marking as duplicate of #617

**Closed by saudet** 2017-03-22 03:28 UTC
Labels: duplicate
