### ISSUE TITLE
FFmpegFrameGrabber.grab() crashes and raise java.lang.OutOfMemoryError:

### ISSUE THREAD

**Issue by Qamar4P** [bytedeco/javacv#721] opened 2017-06-12 12:39 UTC
Code:
```
url = new URL("http://dev.exiv2.org/attachments/372/3D_L0064.MP4");
              urlConnection = (HttpURLConnection) url.openConnection();
              InputStream inputStream = urlConnection.getInputStream();
              FFmpegFrameGrabber grabber= new FFmpegFrameGrabber(inputStream);
              grabber.setFormat("mp4");
              grabber.start();
              grabber.setFrameNumber(100000);

              Frame frame = grabber.grab();

              frameBitmap = new AndroidFrameConverter().convert(frame);

              grabber.stop();
```
Error log:
```
W/art: Throwing OutOfMemoryError "Failed to allocate a 134217740 byte allocation with 16777216 free bytes and 107MB until OOM"
06-12 17:07:36.940 6160-8570/? W/System.err: Error on InputStream.read(): java.lang.OutOfMemoryError: Failed to allocate a 134217740 byte allocation with 16777216 free bytes and 107MB until OOM
06-12 17:07:36.942 6160-8570/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8570 (Thread-2368)
06-12 17:07:37.034 779-886/? D/ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 105] to 60
06-12 17:07:37.043 195-195/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-12 17:07:37.043 195-195/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
06-12 17:07:37.043 195-195/? A/DEBUG: Revision: '11'
06-12 17:07:37.043 195-195/? A/DEBUG: ABI: 'arm'
06-12 17:07:37.043 195-195/? A/DEBUG: pid: 6160, tid: 8570, name: Thread-2368  >>> com.qamar4p.mymediaapp <<<
06-12 17:07:37.043 195-195/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-12 17:07:37.057 195-195/? A/DEBUG:     r0 00000000  r1 0000217a  r2 00000006  r3 9b7ec978
06-12 17:07:37.057 195-195/? A/DEBUG:     r4 9b7ec980  r5 9b7ec930  r6 00000002  r7 0000010c
06-12 17:07:37.057 195-195/? A/DEBUG:     r8 00000000  r9 40fe2400  sl 00000780  fp 40fe2400
06-12 17:07:37.057 195-195/? A/DEBUG:     ip 00000006  sp 9b7ec200  lr b6ceeb61  pc b6cf0f50  cpsr 40010010
06-12 17:07:37.079 195-195/? A/DEBUG: backtrace:
06-12 17:07:37.079 195-195/? A/DEBUG:     #00 pc 00041f50  /system/lib/libc.so (tgkill+12)
06-12 17:07:37.079 195-195/? A/DEBUG:     #01 pc 0003fb5d  /system/lib/libc.so (pthread_kill+32)
06-12 17:07:37.080 195-195/? A/DEBUG:     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
06-12 17:07:37.080 195-195/? A/DEBUG:     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
06-12 17:07:37.080 195-195/? A/DEBUG:     #04 pc 000174ac  /system/lib/libc.so (abort+4)
06-12 17:07:37.080 195-195/? A/DEBUG:     #05 pc 0004af98  /data/app/com.qamar4p.mymediaapp-1/lib/arm/libswscale.so (sws_setColorspaceDetails+4184)
06-12 17:07:37.080 195-195/? A/DEBUG:     #06 pc 000064b0  /data/app/com.qamar4p.mymediaapp-1/lib/arm/libswscale.so (sws_init_context+352)
06-12 17:07:37.080 195-195/? A/DEBUG:     #07 pc 0004b34c  /data/app/com.qamar4p.mymediaapp-1/lib/arm/libswscale.so (sws_getCachedContext+532)
06-12 17:07:37.080 195-195/? A/DEBUG:     #08 pc 000102cc  /data/app/com.qamar4p.mymediaapp-1/lib/arm/libjniswscale.so (Java_org_bytedeco_javacpp_swscale_sws_1getCachedContext__Lorg_bytedeco_javacpp_swscale_00024SwsContext_2IIIIIIILorg_bytedeco_javacpp_swscale_00024SwsFilter_2Lorg_bytedeco_javacpp_swscale_00024SwsFilter_2Lorg_bytedeco_javacpp_DoublePointer_2+360)
06-12 17:07:37.081 195-195/? A/DEBUG:     #09 pc 01ad16d5  /data/app/com.qamar4p.mymediaapp-1/oat/arm/base.odex (offset 0xc5f000) (org.bytedeco.javacpp.swscale$SwsContext org.bytedeco.javacpp.swscale.sws_getCachedContext(org.bytedeco.javacpp.swscale$SwsContext, int, int, int, int, int, int, int, org.bytedeco.javacpp.swscale$SwsFilter, org.bytedeco.javacpp.swscale$SwsFilter, org.bytedeco.javacpp.DoublePointer)+232)
06-12 17:07:37.081 195-195/? A/DEBUG:     #10 pc 01854e5f  /data/app/com.qamar4p.mymediaapp-1/oat/arm/base.odex (offset 0xc5f000) (void org.bytedeco.javacv.FFmpegFrameGrabber.processImage()+1114)
06-12 17:07:37.081 195-195/? A/DEBUG:     #11 pc 0185985d  /data/app/com.qamar4p.mymediaapp-1/oat/arm/base.odex (offset 0xc5f000) (org.bytedeco.javacv.Frame org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame(boolean, boolean, boolean, boolean)+848)
06-12 17:07:37.081 195-195/? A/DEBUG:     #12 pc 018594d9  /data/app/com.qamar4p.mymediaapp-1/oat/arm/base.odex (offset 0xc5f000) (org.bytedeco.javacv.Frame org.bytedeco.javacv.FFmpegFrameGrabber.grab()+84)
```

**Comment by saudet** [comment] 2017-06-12 12:49
Duplicate of #509, #607, and #707.

**Closed by saudet** 2017-06-12 12:49 UTC
Labels: duplicate, question
