### ISSUE TITLE
How to grab frames from the webm format video while preserving the alpha channel?

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#2082] opened 2023-08-09 03:02 UTC
I want to grab frames from the webm format video,but the alpha channel is always 255

**Comment by saudet** [comment] 2023-08-09 11:18
Did you set the pixel format to something like RGBA?

**Comment by saudet** [comment] 2024-01-08 11:39
Duplicate of #2150

**Closed by saudet** 2024-01-08 11:39 UTC
Labels: question
