### ISSUE TITLE
use setFrameRate got av_interleaved_write_frame error 

### ISSUE THREAD

**Issue by duansheli** [bytedeco/javacv#1367] opened 2020-01-12 07:27 UTC
i'm trying make mp4 file smaller
my file : abc.mp4
size: 155MB 
frame every second: 15
audio channel: 2
time length: 13min-54seconds

the first code is this 
and it run correct
```java
import org.bytedeco.ffmpeg.global.avcodec;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber;

import java.io.File;

public class TestCompressMp4 {
  public static void main(String[] args) throws Exception {
    String base_path = "W:/";
    String file_name = "abc.mp4";
    File file = new File(base_path + file_name);

    FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(file);
    grabber.start();

    String fileName = file.getAbsolutePath() + "__compressed.mp4";
    FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(fileName, grabber.getImageWidth(), grabber.getImageHeight());
    recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
    recorder.setFormat("mp4");
    recorder.setSampleRate(grabber.getSampleRate());
    recorder.setAudioChannels(1);
//    recorder.setFrameRate(10);

    recorder.start();
    Frame captured_frame = grabber.grabFrame();
    while (captured_frame != null) {
      recorder.setTimestamp(grabber.getTimestamp());
      recorder.record(captured_frame);
      captured_frame = grabber.grabFrame();
    }

    recorder.stop();
    recorder.release();
    grabber.stop();
  }

}
```

then add code `recorder.setFrameRate(10);`
run will get Exception
```
Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video packet.
	at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1236)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:1031)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:918)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:911)
	at TestCompressMp4.main(TestCompressMp4.java:30)
```

then delete code `recorder.setTimestamp(grabber.getTimestamp());`
it run correct 
but new file become: 20min-50seconds

so how can i 
make FrameRate from 15 to 10

**Comment by saudet** [comment] 2020-01-12 07:50
If you're looking just to reencode a file, it's easier to use the ffmpeg
program.

**Comment by duansheli** [comment] 2020-01-12 08:08
@saudet  
not only one file 
a lot of files
more than 100GB

**Comment by saudet** [comment] 2020-01-14 04:59
It's also easier to use the ffmpeg program for a lot of files, no matter their sizes.

**Comment by saudet** [comment] 2020-01-17 09:55
Please give it a try, it's very easy to use:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by saudet** [comment] 2020-04-15 01:46
I see, you're trying to change the frame rate, correct? We can do that with `FFmpegFrameFilter` and the `fps` filter. There's a working example of this at https://github.com/bytedeco/javacv/issues/1398#issuecomment-613208633.

**Comment by saudet** [comment] 2020-04-15 01:47
Duplicate of #717

**Closed by saudet** 2020-04-15 01:47 UTC
Labels: duplicate, question
