### ISSUE TITLE
How to use javacv to record windows Desktop?

### ISSUE THREAD

**Issue by jliu666** [bytedeco/javacv#934] opened 2018-03-07 15:13 UTC
I want to record screen by java, not only on windows, but also Mac OS and Linux.

**Comment by jliu666** [comment] 2018-03-07 15:15
I want a example.

**Comment by saudet** [comment] 2018-03-08 05:30
There are instructions for this here: https://trac.ffmpeg.org/wiki/Capture/Desktop

But examples using FFmpegFrameGrabber would be great, so please consider making a contribution.

I'll mark this as a duplicate of issue #31. Please post comments/questions there! Thanks

**Closed by saudet** 2018-03-08 05:30 UTC
Labels: duplicate, enhancement
