### ISSUE TITLE
'java.util.zip.ZipException: duplicate entry:' after Proguard

### ISSUE THREAD

**Issue by astroluj** [bytedeco/javacv#554] opened 2016-11-10 09:56 UTC
Hi, i need you helpㅠㅠ
An error occurs after applying Pro Guard.
I write proguard-rule.
it referenced [https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV](https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV)

My project appeared mulidex.
Therefore added '**multiDexEnabled true**' and '**compile 'com.android.support:multidex:1.0.1**',
**'android:name="android.support.multidex.MultiDexApplication"**'.

My project works fine on Android machine version over 5.0.
But, under 5.0

Error content is it.
**Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.**
**> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/bytedeco/javacpp/flandmark$FLANDMARK_Options.class**

how i do?

This is the piece of 'build.grade' on my project
AAR build.gradle
```
// Duplication library file exception
    packagingOptions {
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/flandmark/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/flandmark/pom.xml'
    }
```

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:support-annotations:25.0.0'
    testCompile 'junit:junit:4.12'
    compile project(':openCVLibrary310')
    compile files('src/main/libs/snakeyaml-1.9.jar')
    compile files('src/main/libs/opencv.jar')
    compile files('src/main/libs/javacpp.jar')
    compile files('src/main/libs/flandmark.jar')
    compile files('src/main/libs/livedetect.jar')
    compile files('src/main/libs/ksoap2-android-assembly-3.4.0-jar-with-dependencies.jar')
}
```

Project build.gradle
livenessLibrary145 is AAR
```
dependencies {
    compile 'com.android.support:support-v4:25.0.0'
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.android.support:design:25.0.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'junit:junit:4.12'
    compile project(':livenessLibrary145')
    compile project(':openCVLibrary310')
    compile files('src/main/libs/poi-3.15.jar')
}
```

**Comment by saudet** [comment] 2016-11-11 11:11
Duplicate of #353

**Closed by saudet** 2016-11-11 11:11 UTC
Labels: duplicate, question

**Comment by astroluj** [comment] 2016-11-13 06:43
I'm used javacv 1.2 .ver and java-preset 1.2.4 .ver.
i'm already used version over 1.1.

Is there any other way?
