### ISSUE TITLE
How to conversion OpenCV Mat to JavaCV Mat？

### ISSUE THREAD

**Issue by kongqw** [bytedeco/javacv#748] opened 2017-07-27 04:13 UTC
How to conversion OpenCV Mat to JavaCV Mat？

**Comment by saudet** [comment] 2017-07-27 04:26
Duplicate of https://github.com/bytedeco/javacpp/issues/38

Please consider making a contribution by documenting this in the wiki, for example!

**Closed** 2017-07-31 13:47 UTC
Labels: duplicate, question
