### ISSUE TITLE
javacpp-presets-Linux-amd64.jar not found

### ISSUE THREAD

**Issue by psteinb** [bytedeco/javacv#474] opened 2016-08-01 10:11 UTC
Hi, 
I am using javacv in my build.gradle file as:
```
compile group: 'org.bytedeco', name: 'javacv', version: '1.2'
```
Still, my build fails with:
```
$ gradle build
Could not resolve all dependencies for configuration ':compile'.
> Could not find javacpp-presets-Linux-amd64.jar (org.bytedeco:javacpp-presets:1.2).
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Linux-amd64.jar
```
checking `https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/1.2/` the file does not exist. Should I inject a javacpp-presets dependency manually to fix this? How should I proceed?

**Comment by saudet** [comment] 2016-08-04 01:24
Duplicate of issue #395 

Use the workaround here: https://github.com/bytedeco/javacv/issues/395#issuecomment-220213783

**Closed by saudet** 2016-08-04 01:24 UTC
Labels: bug, duplicate

**Comment by psteinb** [comment] 2016-08-04 10:37
thanks for the hint. I'd humbly suggest to put this into a FAQ or 
something related.

**Comment by saudet** [comment] 2016-08-05 06:43
Yes, that was on my to-do list. Here it is:
https://github.com/bytedeco/javacpp-presets/wiki/Issues-with-Build-Tools
