### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by syusikoku** [bytedeco/javacv#1015] opened 2018-06-22 03:06 UTC
andorid studio 3.1.2,gradle 4.4,gradle dependencies : implementation 'org.bytedeco:javacv-platform:1.4.1' ,build failed, error log
 More than one file was found with OS independent path 'org/bytedeco/javacpp/windows-x86/api-ms-win-crt-locale-l1-1-0.dll'

**Comment by saudet** [comment] 2018-06-22 04:10
Duplicate of #353. You'll need to exclude these files. Some ways to do that are given in issue #353.

**Closed by saudet** 2018-06-22 04:10 UTC
