### ISSUE TITLE
Build failed for javacv on Raspberry Pi

### ISSUE THREAD

**Issue by mpatronska** [bytedeco/javacv#493] opened 2016-08-31 19:10 UTC
Prerequisites:
-  OpenCV v 3.1.0

mvn clean install -Dplatform.name=linux-arm results in

`[ERROR] Failed to execute goal on project javacv: Could not resolve dependencies for project org.bytedeco:javacv:jar:1.2.2: The following artifacts could not be resolved: org.bytedeco.javacpp-presets:opencv:jar:3.1.0-1.2.2, org.bytedeco.javacpp-presets:ffmpeg:jar:3.0.2-1.2.2, org.bytedeco.javacpp-presets:flycapture:jar:2.9.3.43-1.2.2, org.bytedeco.javacpp-presets:libdc1394:jar:2.2.4-1.2.2, org.bytedeco.javacpp-presets:libfreenect:jar:0.5.3-1.2.2, org.bytedeco.javacpp-presets:videoinput:jar:0.200-1.2.2, org.bytedeco.javacpp-presets:artoolkitplus:jar:2.3.1-1.2.2, org.bytedeco.javacpp-presets:flandmark:jar:1.07-1.2.2: Could not find artifact org.bytedeco.javacpp-presets:opencv:jar:3.1.0-1.2.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

Any ideas how this can be resolved?

**Comment by saudet** [comment] 2016-09-02 07:30
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/278

**Closed by saudet** 2016-09-02 07:30 UTC
Labels: duplicate, question
