### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "vp8_short_fdct4x4_sse2"

### ISSUE THREAD

**Issue by anonym24** [bytedeco/javacv#981] opened 2018-05-04 06:53 UTC
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "vp8_short_fdct4x4_sse2" referenced by "/data/data/com.example.app/app_lib/libavcodec.so"...

I'm trying to test it on 23, 27 API in Android Emulator x86

is it problem with x86 libs or Emulator?

I just don't have a x86 Device

**Comment by saudet** [comment] 2018-05-04 07:47
Duplicate of #945. Please use 1.4.2-SNAPSHOT: http://bytedeco.org/builds/

**Closed by saudet** 2018-05-04 07:47 UTC
Labels: bug, duplicate

**Comment by anonym24** [comment] 2018-05-04 07:48
@saudet but another problem, I already use 1.4.2:

```
    implementation files('libs/javacpp-1.4.1.jar')
    implementation files('libs/javacv-1.4.1.jar')
    implementation files('libs/ffmpeg-platform-3.4.2-1.4.1.jar')
    implementation files('libs/ffmpeg-3.4.2-1.4.1.jar')
```

**Comment by anonym24** [comment] 2018-05-04 08:09
java presets 1.4.2 also available or only java cv?

is there link for 1.4.2 like for 1.4.1?
http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv-platform/1.4.1/javacv-platform-1.4.1-bin.zip

https://github.com/bytedeco/javacv/issues/945#issuecomment-382254737 - he uses ffmpeg 1.4.1:

**Comment by saudet** [comment] 2018-05-04 08:11
Please use 1.4.2-SNAPSHOT: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2018-05-04 08:13
You can download the JAR files manually, but no big archive, no.

**Comment by anonym24** [comment] 2018-05-04 08:17
@saudet yes I just forgot about **bytedeco/javacpp-presets/ffmpeg/***  oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/*

I was trying to find ffmpeg libraries at /bytedeco/javacpp-presets/1.4.2-SNAPSHOT/ (when it should be bytedeco/javacpp-presets/ffmpeg/), my fault

**Comment by anonym24** [comment] 2018-05-04 08:27
I'm going to try 

```
    implementation files('libs/javacv-1.4.2-20180501.030242-10.jar')
    implementation files('libs/javacv-platform-1.4.2-20180501.030925-9.jar')
    implementation files('libs/javacpp-1.4.2-20180430.111859-15.jar')
    implementation files('libs/ffmpeg-platform-4.0-1.4.2-20180504.074213-61.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.074158-61.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.034926-56-android-arm.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.041836-57-android-arm64.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.050321-59-android-x86.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.054338-60-android-x86_64.jar')
```

hope it will work, there are so many files with different version/date, I was trying download most recent ones (at page end)

**Comment by anonym24** [comment] 2018-05-04 08:33
new issues with those libraries when trying to start recording `mFFmpegFrameRecorder.start()`: 
```

05-04 11:30:59.898 15273-15273/ W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avcodec_find_encoder() error: Video codec not found.
05-04 11:30:59.898 15273-15273/ W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:447)
```

**Comment by anonym24** [comment] 2018-05-04 14:28
is it a new bug? or did I do something wrong?

**Comment by saudet** [comment] 2018-05-04 22:48
You probably have old files in your project somewhere that we not recompiled...

**Comment by anonym24** [comment] 2018-05-05 09:59
I only compiled those files:

    ```
implementation files('libs/javacv-1.4.2-20180501.030242-10.jar')
    implementation files('libs/javacv-platform-1.4.2-20180501.030925-9.jar')
    implementation files('libs/javacpp-1.4.2-20180430.111859-15.jar')
    implementation files('libs/ffmpeg-platform-4.0-1.4.2-20180504.074213-61.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.074158-61.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.034926-56-android-arm.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.041836-57-android-arm64.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.050321-59-android-x86.jar')
    implementation files('libs/ffmpeg-4.0-1.4.2-20180504.054338-60-android-x86_64.jar')
```

can you please check Recorder with exactly the same files?

**Comment by saudet** [comment] 2018-05-05 11:37
Those are already compiled. What you need to recompile is the source code
of your application and of any other library that depends on JavaCV.

**Comment by anonym24** [comment] 2018-05-05 15:17
I meant I added them to my build gradle file (replace old java entries with those), made project in Android Studio and it how it worked
I'll try again later of course, but I think I will get the same error

**Comment by anonym24** [comment] 2018-05-05 16:09
mb with gradle maven repository in android project (no jars in libs) it will work better:

```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
   ...
```

I'm trying:

```
ext {
    versions = [
            'ffmpeg': '3.4.2-1.4.2-SNAPSHOT'
    ]
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation(group: 'org.bytedeco', name: 'javacv-platform', version: '1.4.2-SNAPSHOT') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm'
```

but get error for preset:

`Failed to resolve: ffmpeg-android-arm`

**Comment by anonym24** [comment] 2018-05-05 16:26
didn't work, there is really something wrong

```
603 26613-26862/ W/linker: /data/app/-1/lib/arm64/libjniavutil.so: unused DT entry: type 0xf arg 0x1c661
618 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
619 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
620 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
621 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
622 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
623 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
624 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
625 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
626 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
627 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
628 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
629 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
630 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
631 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
632 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
633 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext$Free_AVHWFramesContext
634 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesInternal
635 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
636 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
637 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
638 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
639 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
641 26613-26862/ W/System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext$Free_AVHWDeviceContext
    Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceInternal
651 26613-26862/ E/art: No implementation found for int org.bytedeco.javacpp.avutil.AV_OPT_TYPE_IMAGE_SIZE() (tried Java_org_bytedeco_javacpp_avutil_AV_1OPT_1TYPE_1IMAGE_1SIZE and Java_org_bytedeco_javacpp_avutil_AV_1OPT_1TYPE_1IMAGE_1SIZE__)
660 26613-26862/ I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
662 26613-26862/ E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: , PID: 26613
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at org.bytedeco.javacpp.Loader.load(Loader.java:938)
        at org.bytedeco.javacpp.Loader.load(Loader.java:879)
        at org.bytedeco.javacpp.avformat$Write_packet_Pointer_BytePointer_int.<clinit>(avformat.java:640)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:309)
        at .FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:469)
        at .FFmpegRecordActivity.access$1100(FFmpegRecordActivity.java:51)
        at .FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:287)
        at .FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:282)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
688 26613-26862/? I/Process: Sending signal. PID: 26613 SIG: 9

```

so I can use only 1.4.1 

```
ext {
    versions = [
            'ffmpeg': '3.4.2-1.4.1'
    ]
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation(group: 'org.bytedeco', name: 'javacv-platform', version: '1.4.1') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm64'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-x86'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-x86_64'
}
```

**Comment by anonym24** [comment] 2018-05-05 16:29
yes it worked :) (at least on my arm64 device, I'll test on x84 emulator later)

p.s. needed to use 'ffmpeg': '4.0-1.4.2-SNAPSHOT' instead of 'ffmpeg': '3.4.2-1.4.2-SNAPSHOT'

**Comment by anonym24** [comment] 2018-05-07 06:34
actually I found what really was the issue

in previous versions I used:  `mFrameRecorder.setVideoCodec(28); // 28 avcodec.AV_CODEC_ID_H264`

but from (I guess) FFMpeg 4.0 it's not 28 anymore but 27, AV_CODEC_ID_H264 = 27
so it's better to use `mFrameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);`

**Comment by saudet** [comment] 2018-05-07 08:31
Yes, it's never a good idea to use numbers there :)

**Comment by anonym24** [comment] 2018-05-08 09:37
checked again it worked for 8.1 x86 Android Emulator also :)
