### ISSUE TITLE
What if the javacv package used in Android is too large?

### ISSUE THREAD

**Issue by liming1010** [bytedeco/javacv#1699] opened 2021-09-22 07:59 UTC
`
implementation group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.6'
`

The APK generated by javacv is 600m, which is too large. There are many dependencies on other platforms in the APK. What should I do

**Comment by saudet** [comment] 2021-09-22 10:09
Please refer to https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
and the Platform Plugin from Gradle JavaCPP: https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by saudet** [comment] 2021-09-22 10:11
Duplicate of #1308

**Closed** 2021-09-22 10:11 UTC
Labels: duplicate, question
