### ISSUE TITLE
[Android 6.0.1] Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11470 recordactivity

### ISSUE THREAD

**Issue by ywj7931** [bytedeco/javacv#450] opened 2016-07-08 06:20 UTC
I ran the recordActivity at android 6.0.1
the error appears: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11470

I ran the same on Android 4.4.4, there is no error.
I ran javacv 1.2
 compileSdkVersion 23

Is it the problem of opencv?

**Comment by saudet** [comment] 2016-07-08 06:31
Duplicate of https://github.com/bytedeco/javacv/issues/412  Use JavaCPP 1.2.1 or 1.2.2

**Closed by saudet** 2016-07-08 06:31 UTC
Labels: bug, duplicate
