### ISSUE TITLE
No such filter: 'subtitles' Error reinitializing filters!

### ISSUE THREAD

**Issue by E-Artist** [bytedeco/javacv#2043] opened 2023-06-15 09:06 UTC
The output is as follows:
[AVFilterGraph @ 000002f4530e3ac0] No such filter: 'subtitles'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0

my cmd like this
xxx...\org\bytedeco\ffmpeg\windows-x86_64-gpl\ffmpeg.exe -i input.mp4 -vf subtitles=start.ass -preset slow -crf 18 -y output.mp4

javacv version is 1.5.8
It seems that there is a lack of configuration   '--enable-libass'

thanks!

**Comment by E-Artist** [comment] 2023-06-15 09:10
detail info

ffmpeg cmd: C:\Users\xxx\.javacpp\cache\ffmpeg-5.1.2-1.5.8-windows-x86_64-gpl.jar\org\bytedeco\ffmpeg\windows-x86_64-gpl\ffmpeg.exe -i input.mp4 -vf subtitles=start.ass -preset slow -crf 18 -y output.mp4
16:53:16.772 [main] INFO com.netease.newsclient.core.utils.FFMpegUtils - ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
16:53:16.772 [main] INFO com.netease.newsclient.core.utils.FFMpegUtils -   built with gcc 10.2.0 (Rev11, Built by MSYS2 project)
16:53:16.772 [main] INFO com.netease.newsclient.core.utils.FFMpegUtils -   configuration: --prefix=.. --disable-iconv --disable-opencl --disable-sdl2 --disable-bzlib --disable-lzma --disable-linux-perf --disable-xlib --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-zlib --enable-libmp3lame --enable-libspeex --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-openssl --enable-libopenh264 --enable-libvpx --enable-libfreetype --enable-libopus --enable-libxml2 --enable-libsrt --enable-libwebp --enable-gpl --enable-version3 --enable-libx264 --enable-libx265 --enable-cuda --enable-cuvid --enable-nvenc --enable-libmfx --enable-w32threads --enable-indev=dshow --target-os=mingw32 --cc='gcc -m64' --extra-cflags='-DLIBXML_STATIC -I../include/ -I../include/libxml2/' --extra-ldflags=-L../lib/ --extra-libs='-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lgcc_eh -lWs2_32 -lcrypt32 -lpthread -lz -lm -Wl,-Bdynamic -lole32 -luuid'
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
...
...
Press [q] to stop, [?] for help
[AVFilterGraph @ 000002f4530e3ac0] No such filter: 'subtitles'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[aac @ 000002f44ff2b640] Qavg: 357.739
[aac @ 000002f44ff2b640] 2 frames left in the queue on closing
Conversion failed!

**Comment by E-Artist** [comment] 2023-06-15 09:11
detail info

ffmpeg cmd: C:\Users\xxx\.javacpp\cache\ffmpeg-5.1.2-1.5.8-windows-x86_64-gpl.jar\org\bytedeco\ffmpeg\windows-x86_64-gpl\ffmpeg.exe -i input.mp4 -vf subtitles=start.ass -preset slow -crf 18 -y output.mp4
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10.2.0 (Rev11, Built by MSYS2 project)
configuration: --prefix=.. --disable-iconv --disable-opencl --disable-sdl2 --disable-bzlib --disable-lzma --disable-linux-perf --disable-xlib --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-zlib --enable-libmp3lame --enable-libspeex --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-openssl --enable-libopenh264 --enable-libvpx --enable-libfreetype --enable-libopus --enable-libxml2 --enable-libsrt --enable-libwebp --enable-gpl --enable-version3 --enable-libx264 --enable-libx265 --enable-cuda --enable-cuvid --enable-nvenc --enable-libmfx --enable-w32threads --enable-indev=dshow --target-os=mingw32 --cc='gcc -m64' --extra-cflags='-DLIBXML_STATIC -I../include/ -I../include/libxml2/' --extra-ldflags=-L../lib/ --extra-libs='-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lgcc_eh -lWs2_32 -lcrypt32 -lpthread -lz -lm -Wl,-Bdynamic -lole32 -luuid'
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
...
...
Press [q] to stop, [?] for help
[AVFilterGraph @ 000002f4530e3ac0] No such filter: 'subtitles'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[aac @ 000002f44ff2b640] Qavg: 357.739
[aac @ 000002f44ff2b640] 2 frames left in the queue on closing
Conversion failed!

**Comment by saudet** [comment] 2023-06-15 09:27
Duplicate of #1905

**Closed by saudet** 2023-06-15 09:27 UTC
Labels: duplicate, enhancement
