### ISSUE TITLE
Does it support h264_qsv to encode video?

### ISSUE THREAD

**Issue by zhouhang95** [bytedeco/javacv#1446] opened 2020-06-16 12:46 UTC
I try use h264_qsv, get error.
```
        String path = "a.mp4";
        int w = 640;
        int h = 360;
        FFmpegFrameRecorder recorder = FFmpegFrameRecorder.createDefault(path, w, h);
        recorder.setVideoCodecName("h264_qsv");
        recorder.setFormat("mp4");
        recorder.setFrameRate(30);
        recorder.start();
```
Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:743)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:401)
	at org.example.App.main(App.java:15)
[h264_qsv @ 000001c0792accc0] Specified pixel format yuv420p is invalid or not supported

**Comment by saudet** [comment] 2020-06-16 12:56
Looks like you'll need to set a supported pixel format, see https://github.com/bytedeco/javacv/issues/1183#issuecomment-482014301.

**Comment by saudet** [comment] 2020-06-16 12:57
Duplicate of #1183

**Closed by saudet** 2020-06-16 12:57 UTC
Labels: duplicate, enhancement

**Comment by zhouhang95** [comment] 2020-06-16 13:06
```
import static org.bytedeco.ffmpeg.global.avutil.AV_PIX_FMT_NV12;
recorder.setPixelFormat(AV_PIX_FMT_NV12);
```
