### ISSUE TITLE
audio delay than video while rtmp looply

### ISSUE THREAD

**Issue by ggslayer** [bytedeco/javacv#1932] opened 2022-11-08 07:33 UTC
Hi, In my test mp4 file, the audio length(last timestamp) is longer than video length(last timestamp)  about 300ms,  In my program, I'm push the file to rtmp frame by frame looply by grabber and recorder,  I will restart grabber and set grabber's timestamp to 0 when file is over,  In this case, after some loop times,  in vlc, the audio is delay than video.  I think this is caused by "the audio len is longer than video len", please help me how to avoid the problem?  Thank you very much !!

`

  public class Simple {

    public static FFmpegFrameRecorder recorder = null;
    public static FFmpegFrameGrabber frameGrabber = null;

    static long startTime = 0;

    static long frame_durations_sended = 0;
    static long frame_durations_sended_audio = 0;

    public static void main(String[] args) throws FrameGrabber.Exception, FrameRecorder.Exception {

        String srcfile = "./videos/1.mp4";
        String destfile = "rtmp://127.0.0.1/live/livestream";

        FFmpegLogCallback.set();
        //FFmpegLogCallback.setLevel(2);

        frameGrabber = new FFmpegFrameGrabber(srcfile);
        //frameGrabber.setVideoCodecName("libvpx-vp9");
        //frameGrabber.setVideoCodecName("h264");
        //frameGrabber.setAudioCodecName("aac_fixed");
        frameGrabber.setPixelFormat(avutil.AV_PIX_FMT_ABGR);

        Frame captured_frame = null;

        try {
            frameGrabber.setTimestamp(0);
            frameGrabber.start();

            if(!InitRecorder(destfile)){
                System.out.printf("start recorder exception");
                return;
            }

            while(true){                  // loop the 1.mp4
                while (true) {
                    try {

                        try{
                            captured_frame = grabWithFrameRate();

                        }catch(Exception e){
                            System.out.printf("error\n");
                        }

                        if (captured_frame == null) {
                            frameGrabber.setTimestamp(0);
                            frameGrabber.restart();
                            break;
                        }

                        if(captured_frame.type == Frame.Type.VIDEO){
                            frame_durations_sended += 40;    // fps is 25
                           
                        }else if(captured_frame.type == Frame.Type.AUDIO){
                            long audio_duration = (long)((double)captured_frame.samples[0].limit() / captured_frame.sampleRate / frameGrabber.getAudioChannels() * 1000);
                            frame_durations_sended_audio += audio_duration;
                          
                        }else{
                            System.out.printf("Drop Frame!!!!!!!!!!!!!");
                            continue;
                        }

                        try{
                            recorder.record(captured_frame, avutil.AV_PIX_FMT_ABGR);
                        }catch (Exception e){
                             System.out.printf("record exception:%s, restart it...", e.toString());
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }

            recorder.flush();
            recorder.stop();
            recorder.release();
            frameGrabber.stop();
            frameGrabber.release();
            recorder.close();
            frameGrabber.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static boolean InitRecorder(String destfile){
        recorder = new FFmpegFrameRecorder(destfile, frameGrabber.getImageWidth(), frameGrabber.getImageHeight(), frameGrabber.getAudioChannels());
        recorder.setInterleaved(true);
        recorder.setVideoOption("tune","zerolatency");
        recorder.setVideoOption("preset", "ultrafast");
        recorder.setVideoOption("crf", "0");
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setFormat("flv");
        recorder.setGopSize(25);        
        //recorder.setPixelFormat(avutil.AV_PIX_FMT_RGBA);
        recorder.setFrameRate(frameGrabber.getFrameRate());

        //recorder.setVideoBitrate(0);

        recorder.setAudioBitrate(192000);
        recorder.setAudioOptions(frameGrabber.getAudioOptions());
        recorder.setAudioQuality(0);
        recorder.setSampleRate(44100);
        recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);

        try{
            recorder.start();
            return true;
        }catch (Exception e){
            return false;
        }
    }

    public static Frame grabWithFrameRate() throws FrameGrabber.Exception, InterruptedException {
        Frame frame = frameGrabber.grab();
        if (frame != null) {
            waitForTimestamp_new(frame);
        }

        return frame;
    }

    public static boolean waitForTimestamp_new(Frame frame) throws InterruptedException {
        if (startTime == 0L) {
            startTime = System.nanoTime() / 1000L;
        } else {
            if(frame.type != Frame.Type.VIDEO)  // control video fps only
                return true;

            long delay = frame_durations_sended*1000 - (System.nanoTime() / 1000L - startTime);
            if (delay > 0L) {
                Thread.sleep(delay / 1000L, (int)(delay % 1000L) * 1000);
                return true;
            }
        }

        return false;
    }
}

`

**Comment by saudet** [comment] 2022-11-09 09:59
Like I said before, you'll need to call setTimestamp() with values that make sense for your stream.

**Comment by saudet** [comment] 2022-11-09 10:01
Duplicate of #1913

**Closed by saudet** 2022-11-09 10:01 UTC
Labels: duplicate, question

**Comment by ggslayer** [comment] 2022-11-15 12:03
setTimestamp should call on frame?  or on recorder?   is there some example about this?  @saudet

**Comment by saudet** [comment] 2022-11-15 13:08
FFmpegFrameRecorder.setTimestamp(), there are a couple of examples here, yes:
https://github.com/bytedeco/javacv/tree/master/samples

**Comment by saudet** [comment] 2022-11-15 13:10
BTW, please do not open multiple issues asking the same questions. If you have more questions about this, please ask them in the other initial issue you opened about this.

**Comment by ggslayer** [comment] 2022-11-16 03:46
Ok, Thank you.
