### ISSUE TITLE
I want to ask is there a clean JavaCV framework may available in feature or not? 

### ISSUE THREAD

**Issue by Bahramudin** [bytedeco/javacv#670] opened 2017-04-11 14:28 UTC
I have downloaded the JavaCV in my project, but I saw there is a lot of deprecated things inside, like Iplmage, CvMat, Mat, many kinds of grabbers, and also a lot of conversions, this convert to that, that convert to this, that really very bad in performance, and also lot of libraries that make project very heavy ...etc. Is it possible or that make a clean and remove the deprecated types and classes that will help the framework more readable, more comfortable to use, and make a good API to easily understand the algorithms and make good and easy tutorials, it will be very good. Hope JavaCV framework take care to this point, and release a clean version in the soon next.

**Comment by saudet** [comment] 2018-05-24 04:00
Marking as duplicate of issue #734.

BTW, JavaCV now also includes the official Java API of OpenCV, so we can also use that.

**Closed by saudet** 2018-05-24 04:00 UTC
Labels: duplicate, enhancement
