### ISSUE TITLE
Exclude unnecessary modules

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1186] opened 2019-04-11 08:03 UTC
Is it even possible to have JavaCV without all of the libs, only with the ones that I actually plan to use (line OpenCV and FFmpeg)?

I tried this in my `build.graddle`, but I don't think it actually did anything:

```gradle
dependencies {
    compile('org.bytedeco:javacv-platform:1.4.4') {
        exclude group: 'org.bytedeco', module: 'flycapture-platform'
        exclude group: 'org.bytedeco', module: 'libdc1394-platform'
        exclude group: 'org.bytedeco', module: 'libfreenect-platform'
        exclude group: 'org.bytedeco', module: 'ibfreenect2-platform'
        exclude group: 'org.bytedeco', module: 'librealsense-platform'
        exclude group: 'org.bytedeco', module: 'videoinput-platform'
        exclude group: 'org.bytedeco', module: 'artoolkitplus-platform'
        exclude group: 'org.bytedeco', module: 'flandmark-platform'
        exclude group: 'org.bytedeco', module: 'leptonica-platform'
        exclude group: 'org.bytedeco', module: 'tesseract-platform'
    }
}
```

Also, you're mentioning something like this in the readme:

> to get binaries for only one platform we can set the `javacpp.platform` system property (via the `-D` command line option) to something like `android-arm`, `linux-x86_64`, `macosx-x86_64`, `windows-x86_64`, etc.

How do I set it in gradle? Is it even possible? I tried it with `local.properties` and `settings.gradle`, but it didn't work.

**Comment by saudet** [comment] 2019-04-11 08:06
Duplicate of #1071

Additional documentation, etc welcome

No, Gradle doesn't support profiles. One more reason to learn and use Maven instead!

**Closed by saudet** 2019-04-11 08:06 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2019-04-11 08:19
Gradle supports excluding artifacts at least that yes, see here for example:
https://deeplearning4j.org/docs/latest/deeplearning4j-android
Works just fine! If you're having issues using Gradle, ask over on their forums.

**Comment by b005t3r** [comment] 2019-04-11 08:19
OK, understood. However, would be nice to have what the guy from the other issue suggests - JavaCV split into more modules.

**Comment by saudet** [comment] 2019-04-11 08:19
Yes, sure, contributions welcome!

**Comment by daclear** [comment] 2019-05-14 05:30
I had the same problem like @b005t3r, I want to exclude all the unused libs other than ffmpeg / ffmpeg-platform. 
With the first try i had the same result, no effect and all dependecies have been loaded. 
Than i recognized that the libs from the javacv dependency are located into javacpp-presets. 
I adjust the build.gradle which solves my problem. 
`//Excluding transitive dependency for a particular dependency declaration
 //for further information see: https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html
  	compile (group: 'org.bytedeco', name: 'javacv-platform', version: '1.4.4'){
   		exclude group: 'org.bytedeco.javacpp-presets', module: 'opencv'
   		exclude group: 'org.bytedeco.javacpp-presets', module: 'opencv-platform'
  		exclude group: 'org.bytedeco.javacpp-presets', module: 'flycapture'
   		exclude group: 'org.bytedeco.javacpp-presets', module: 'flycapture-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'libdc1394'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'libdc1394-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'libfreenect'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'libfreenect-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'libfreenect2'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'libfreenect2-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'librealsense'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'librealsense-platform'
		exclude group: 'org.bytedeco.javacpp-presets', module: 'videoinput'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'videoinput-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'artoolkitplus'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'artoolkitplus-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'flandmark'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'flandmark-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'leptonica'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'leptonica-platform'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'tesseract'
                exclude group: 'org.bytedeco.javacpp-presets', module: 'tesseract-platform'
  	}`

**Comment by saudet** [comment] 2019-05-14 05:42
Right, the group name changed a bit between the 1.4.x and 1.5.x series:
http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/

**Comment by b005t3r** [comment] 2019-05-14 09:06
Brilliant! @daclear, could you also post how your jar building task looks like? I'll test this in my project as soon as I'm done with other stuff and report back.

**Comment by daclear** [comment] 2019-05-14 12:11
> Brilliant! @daclear, could you also post how your jar building task looks like? I'll test this in my project as soon as I'm done with other stuff and report back.

Thanks! What you exactly mean with "jar building task"? My build.gradle is one of many subprojects.

**Comment by b005t3r** [comment] 2019-05-15 11:10
@daclear, I meant something like this:

```
jar {
    manifest {
        attributes 'Main-Class': 'com.lazarecki.Main'
    }

    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

I use this simple task to pack all dependencies into a single jar, along with the application itself.

Anyway, your gradle magic seems to work, my output jar is much smaller now :) However, there are still binaries for all platforms in it, any idea how to filter those out as well? E.g. I want to keep ffmpeg and opencv, but only for the target platform.

**Comment by saudet** [comment] 2019-05-15 11:49
In that case it's probably easier to add the "javacv" artifact and add the
dependencies you use instead of excluding everything from "javacv-platform".

**Comment by b005t3r** [comment] 2019-05-15 12:12
@saudet, I'll try any method, I just need to know how :)
