### ISSUE TITLE
UnsatisfiedLinkError due to missing jniavutil in java.library.path

### ISSUE THREAD

**Issue by everAndNever** [bytedeco/javacv#2210] opened 2024-03-28 03:43 UTC
When running an application using Javacv1.5.10 on Debian, I encountered an unsatisfactory linking error that seemed to be related to the Java Native Interface (JNI) and Java. library. path system properties. The error message indicates that the jniavutil library cannot be found in the specified path.
Here is the full stack trace of the error:
`2024-03-28 10:05:21 [http-nio-10362-exec-1] ERROR c.l.c.a.SystemAdvice - Exception occurred, errorMsg: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path...`
`Caused by: java.lang.UnsatisfiedLinkError: /home/lancoo/.javacpp/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: /usr/lib64/libm.so.6: version 'GLIBC_2.29' not found (required by /home/lancoo/.javacpp/cache/ffmpeg-6.1.1-1.5.10-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.58)...`
Any assistance in resolving this issue would be greatly appreciated

**Comment by saudet** [comment] 2024-03-28 03:47
Please try again with Ubuntu

**Comment by saudet** [comment] 2024-03-28 03:47
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-03-28 03:47 UTC
Labels: duplicate, enhancement

**Comment by everAndNever** [comment] 2024-03-28 03:56
However, it runs in a production environment and I cannot easily switch to Ubuntu
