### ISSUE TITLE
OpenCV(3.4.1) Error: Assertion failed ((flags & FIXED_TYPE) != 0) in cv::_InputArray::type, file C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.1\modules\core\src\matrix_wrap.cpp, line 807

### ISSUE THREAD

**Issue by makeiteasyforme** [bytedeco/javacv#1023] opened 2018-07-01 04:03 UTC
OpenCV(3.4.1) Error: Assertion failed ((flags & FIXED_TYPE) != 0) in cv::_InputArray::type, file C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.1\modules\core\src\matrix_wrap.cpp, line 807
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffe31303c58, pid=196, tid=0x0000000000002178
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x33c58]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\iken\workspace\Digital Image Processing\hs_err_pid196.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

***** VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****

SETUP: Setting up device 0
SETUP: HP Wide Vision HD
SETUP: Couldn't find preview pin using SmartTee
SETUP: Default Format is set to 640 by 480 
SETUP: trying requested format RGB24 @ 640 by 480
SETUP: trying format RGB24 @ 640 by 480
SETUP: trying format RGB32 @ 640 by 480
SETUP: trying format RGB555 @ 640 by 480
SETUP: trying format RGB565 @ 640 by 480
SETUP: trying format YUY2 @ 640 by 480
SETUP: Capture callback set
SETUP: Device is setup and ready to capture.

**Comment by saudet** [comment] 2018-07-02 03:52
Sounds like a duplicate of #998. Use the C++ API instead, it should work fine.

**Closed by saudet** 2018-07-02 03:52 UTC
Labels: bug, duplicate

**Comment by saudet** [comment] 2018-07-04 02:15
Which function are you calling?

**Comment by makeiteasyforme** [comment] 2018-07-04 02:18
im using eclipse

package dev.nekiayaj.smoother;

import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgcodecs.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;

public class Smoother {
	public static void main(String[] args){
		smooth("C:\\Users\\schoolpc\\Downloads\\jeepney.jpg");
	}
	
	public static void smooth(String filename) {
		IplImage image = cvLoadImage(filename);
		if (image != null) {
			cvSmooth(image, image);
			cvSaveImage(filename, image);
			cvReleaseImage(image);
		} else {
			System.out.print("image not found");
		}
	}
}

**Comment by makeiteasyforme** [comment] 2018-07-04 02:48
i got this code from the internet it said it works fine

import org.bytedeco.javacv.*;

import static org.bytedeco.javacpp.opencv_core.IplImage;
import static org.bytedeco.javacpp.opencv_core.cvFlip;
import static org.bytedeco.javacpp.opencv_imgcodecs.cvSaveImage;


/**
 * Created by gtiwari on 1/3/2017.
 */

public class Test implements Runnable {
    final int INTERVAL = 100;///you may use interval
    CanvasFrame canvas = new CanvasFrame("Web Cam");

    public Test() {
        canvas.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    }

    public void run() {

        FrameGrabber grabber = new VideoInputFrameGrabber(0); // 1 for next camera
        OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
        IplImage img;
        int i = 0;
        try {
            grabber.start();
            while (true) {
                Frame frame = grabber.grab();

                img = converter.convert(frame);

                //the grabbed frame will be flipped, re-flip to make it right
                cvFlip(img, img, 1);// l-r = 90_degrees_steps_anti_clockwise

                //save
                cvSaveImage((i++) + "-aa.jpg", img);

                canvas.showImage(converter.convert(img));

                Thread.sleep(INTERVAL);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        Test gs = new Test();
        Thread th = new Thread(gs);
        th.start();
    }
}

**Comment by saudet** [comment] 2018-07-04 02:51
Recent versions of OpenCV don't work too well with the C API, so we should use `flip()` instead of `cvFlip()` in this case, for example.

**Comment by makeiteasyforme** [comment] 2018-07-04 02:54
ok but i use the sample code smoother and it gives me the OpenCV(3.4.1) Error: Assertion failed ((flags & FIXED_TYPE) != 0) in cv::_InputArray::type, file C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.1\modules\core\src\matrix_wrap.cpp, line 807
i think its not the code there must be something to do like what you said about C++API

**Comment by saudet** [comment] 2018-07-04 02:58
For `cvSmooth()` there is `smooth()`, so please use that.

Since they seem to have dropped support for the C API, we should eventually update our README.md file accordingly, yes.

**Comment by makeiteasyforme** [comment] 2018-07-04 03:01
ok so what should I do now?

**Comment by makeiteasyforme** [comment] 2018-07-04 03:04
I just i want a code that capture image using web cam and i think javaCV is the right one can you help me with this?

**Comment by makeiteasyforme** [comment] 2018-07-04 03:47
hello! have you ever tried capturing image in web cam using javaCV in eclipse?

**Comment by saudet** [comment] 2018-07-04 04:12
Yes, we can do this now and it works fine.

**Comment by makeiteasyforme** [comment] 2018-07-04 04:15
so tell me how to eliminate this error... OpenCV(3.4.1) Error: Assertion failed ((flags & FIXED_TYPE) != 0) in cv::_InputArray::type, file C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.1\modules\core\src\matrix_wrap.cpp, line 807

**Comment by saudet** [comment] 2018-07-04 04:20
I told you: Don't use the C API. For example, this works fine:
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java

**Comment by makeiteasyforme** [comment] 2018-07-04 04:41
thanks for the help bro but i don't still get it... maybe i should quit XD

**Comment by makeiteasyforme** [comment] 2018-07-04 05:02
wait bro i got it are you still there?

**Comment by makeiteasyforme** [comment] 2018-07-04 05:06
where can i see all C++ API specially for saving the image?

**Comment by saudet** [comment] 2018-07-04 05:09
It's `imwrite()`: https://docs.opencv.org/3.4.1/db/d64/tutorial_load_save_image.html

**Comment by makeiteasyforme** [comment] 2018-07-04 05:14
tysm bro your the best

**Comment by makeiteasyforme** [comment] 2018-07-04 05:57
last question for today hehe... this codes doesn't works cvSaveImage((i++) + "-aa.jpg", img); what should i use to save image?

**Comment by makeiteasyforme** [comment] 2018-07-04 06:55
i dont have libraries for imwrite() what should i do? i cannot import it?

**Comment by saudet** [comment] 2018-07-05 01:40
`imwrite()` is available here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_imgcodecs.html#imwrite-java.lang.String-org.bytedeco.javacpp.opencv_core.Mat-

And `CanvasFrame` is just a `JFrame`:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/CanvasFrame.html
So we can add buttons or anything we want, as shown in the tutorial:
https://docs.oracle.com/javase/tutorial/uiswing/components/frame.html
