### ISSUE TITLE
 OpenGLFrameConverter and GLFWFrameRenderer class still cannot be found after introducing org.jogamp.gluegen.gluegen-rt-main and org.jogamp.jogl.jogl-all-main ???

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2160] opened 2023-12-29 02:06 UTC
Sorry, I tried. but OpenGLFrameConverter and GLFWFrameRenderer class still cannot be found after introducing org.jogamp.gluegen.gluegen-rt-main and org.jogamp.jogl.jogl-all-main ??? #2155

**Comment by saudet** [comment] 2023-12-29 02:09
Duplicate of #2155

**Closed by saudet** 2023-12-29 02:09 UTC
Labels: duplicate, question
