### ISSUE TITLE
No jniopencv_core UnsatisfiedLinkError Android Studio

### ISSUE THREAD

**Issue by zocheyado** [bytedeco/javacv#56] opened 2014-11-24 21:32 UTC
I am trying to install JavaCV so I can use FFMPEG in my project. Specifically I am trying to use the sample code "RecordActivity" I have created a brand new project, followed the install instructions and then the specific OpenCV / FFMPEG instructinos https://github.com/bytedeco/javacv#manual-installation-for-opencv-and-ffmpeg and I am still gettting the error referenced several times on the forums about jniopencv_core and opencv_core not being referenced. Do you think it is an android studio issue?  I tried doing eclipse and has the same issue although I did not go through it as thoroughly. Issues that are related to this.
#28 
#1 
#9 

I am using the 9.0 release using gradle 
```
    dependencies 
   {
        compile group: 'org.bytedeco', name: 'javacv', version: '0.9'
    }
```
is there a more up to date version I could try? or something im not doing?

**Comment by MkrMkr** [comment] 2015-01-08 13:53
Looks like the way with copying native files to jniLibs... doesn't work anymore. My project suddenly starts crashes today and I get error (one of my favorite):  Caused by: java.lang.UnsatisfiedLinkError: Couldn't load opencv_core: findLibrary returned null. 
Please tell me that I'm wrong.

**Comment by saudet** [comment] 2015-01-10 01:38
Extracting all the native libraries to `app/src/main/jniLibs` should still work, but it's easier to just copy the JAR files themselves to the `app/libs` directory. I've confirmed that Android Studio's Gradle still does the extracting of JAR files for us:
https://github.com/bytedeco/javacv#manual-installation
So I guess I'll close this issue :)

**Closed by saudet** 2015-01-10 01:38 UTC
Labels: enhancement
