### ISSUE TITLE
How can i  merge multiple audios with a certain delay

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1753] opened 2022-02-15 07:40 UTC
I want to merge aduios with a certain delay. This is my code, but it doesn't cork.`FFmpegLogCallback.set();
        FFmpegLogCallback.setLevel(avutil.AV_LOG_DEBUG);

        String filterStr = "[0]adelay=3030[a0];[1]adelay=10000[a1];[a0][a1]amix[out]";
        FFmpegFrameFilter filter = new FFmpegFrameFilter(filterStr, 1);
        FFmpegFrameGrabber grabber1 = new FFmpegFrameGrabber(new File("D:\\video\\audio\\input.wav"));
        FFmpegFrameGrabber grabber2 = new FFmpegFrameGrabber(new File("D:\\video\\audio\\input1.wav"));
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(new File("D:\\video\\audio\\output.wav"), 1);
        try {
            grabber1.start();
            grabber2.start();
            recorder.setFormat("wav");
            recorder.start();
            filter.setPixelFormat(grabber1.getSampleFormat());
            filter.setAudioInputs(2);
            filter.start();

            Frame outFrame, inputFrame1, inputFrame2;
            boolean readAll1 = false, readAll2 = false;

            do {
                inputFrame1 = grabber1.grabSamples();
                inputFrame2 = grabber2.grabSamples();
                if (inputFrame1 != null) {
                    filter.push(0, inputFrame1);
                } else {
                    readAll1 = true;
                }

                if (inputFrame2 != null) {
                    filter.push(1, inputFrame2);
                } else {
                    readAll2 = true;
                }

                while ((outFrame = filter.pullSamples()) != null) {
                    recorder.record(outFrame);
                }
            } while (!readAll1 || !readAll2);

            recorder.stop();
            recorder.close();
            recorder.release();

            filter.stop();
            filter.close();
            filter.release();

            grabber1.stop();
            grabber1.close();
            grabber1.release();

            grabber2.stop();
            grabber2.close();
            grabber2.release();

        } catch (Exception e) {
            e.printStackTrace();
        }`

**Comment by CJL6015** [comment] 2022-02-15 07:41
![image](https://user-images.githubusercontent.com/42272971/154015138-a617797e-1f4e-4845-8069-7dd5dab0b1c0.png)
This is the error

**Comment by saudet** [comment] 2022-02-15 08:13
Don't try to set values for the input and output pads, that's not going to work. Simply leave them out of your filter string.

And you'll need to call recorder.setTimestamp() with something valid (monotonically increasing, etc) before recorder.record().

**Comment by saudet** [comment] 2022-02-15 08:16
I see you're using 2 audio inputs, in that case you'll need to use these names for the input and output pads:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L171

**Comment by CJL6015** [comment] 2022-02-21 05:54
Thank you very much! I replace filter with "[0:a]adelay=3000[a0];[1:a]adelay=5000[a1];[a0][a1]amix[a]" and fixed it.

**Comment by saudet** [comment] 2022-02-21 07:50
Duplicate of #1214

**Closed by saudet** 2022-02-21 07:50 UTC
Labels: duplicate, enhancement, question
