### ISSUE TITLE
trim video

### ISSUE THREAD

**Issue by djp0507** [bytedeco/javacv#117] opened 2015-04-07 08:24 UTC
I want to trim video in Android like “ffmpeg -ss 0:1:30 -t 0:0:20 -i input.mp4 -vcodec copy -acodec copy output.mp4 ”，but the ffmpeg.h does not exist .
what should i do？ Thank you

**Comment by saudet** [comment] 2015-04-07 13:56
It's not exactly the same thing, but we can do something like this:
```java
FrameGrabber grabber = new FFmpegFrameGrabber("input.avi");
grabber.start();
grabber.setTimestamp((1 * 60 + 30) * 1000000);

FrameRecorder recorder = new FFmpegFrameRecorder("output.mp4");
recorder.setFrameRate(grabber.getFrameRate());
recorder.setSampleRate(grabber.getSampleRate());
recorder.start();

Frame frame;
while ((frame = grabber.grab()) != null && recorder.getTimestamp() < 20 * 1000000) {
    recorder.record(frame);
}
recorder.stop();
grabber.stop();
```

**Comment by pengliren** [comment] 2015-04-08 05:11
-vcodec copy -acodec copy
no transcoding

**Comment by saudet** [comment] 2015-04-08 12:36
@pengliren That's correct. But we could provide something like `grabPacket()` and `recordPacket()` methods to let user pass around packets without decoding them. Would you have some time to make the necessary modifications? Let me know, thanks!

**Comment by pengliren** [comment] 2015-04-09 01:31
@saudet ok, you provide grabPacket() and recordPacket() methods, I will try modifications.

**Comment by djp0507** [comment] 2015-04-09 02:09
@saudet  It can, but time is too long.

**Comment by saudet** [comment] 2015-04-11 02:34
Marking as a duplicate of https://github.com/bytedeco/javacv/issues/93

**Closed by saudet** 2015-04-11 02:34 UTC
Labels: duplicate, enhancement, help wanted, question

**Comment by saudet** [comment] 2019-03-24 00:38
FYI, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
