### ISSUE TITLE
avformat_write_header error() error -40: Could not write header to 'rtmp://192.168.103.227:1985/myapp/6'

### ISSUE THREAD

**Issue by LW-Francis** [bytedeco/javacv#1631] opened 2021-04-22 01:57 UTC
avformat_write_header error() error -40: Could not write header to 'rtmp://192.168.103.227:1985/myapp/6'

**Comment by saudet** [comment] 2021-04-22 02:10
Could you also provide the messages that get displayed on the console?

**Comment by LW-Francis** [comment] 2021-04-22 02:27
i call FFmpegLogCallback.set() and the console output

Warning: [nvenc_hevc @ 000002a9ad3c9ac0] This encoder is deprecated, use 'hevc_nvenc' instead

Error: [flv @ 000002a9ad952000] Video codec hevc not compatible with flv

**Comment by LW-Francis** [comment] 2021-04-22 02:28
how do i change the encoder

**Comment by saudet** [comment] 2021-04-22 02:45
You're probably calling `setVideoCodecName("nvenc_hevc")`, so don't call that, and call `setVideoCodecName("hevc_nvenc")` instead. Also don't use flv, use some other format like mp4.

**Comment by saudet** [comment] 2021-04-22 02:46
Duplicate of #1497.

**Closed by saudet** 2021-04-22 02:46 UTC
Labels: duplicate, question

**Comment by LW-Francis** [comment] 2021-04-22 02:53
ok,thank you
