### ISSUE TITLE
Android :: Couldn't find "libjniopencv_core.so"

### ISSUE THREAD

**Issue by ArjunAchatz-MF** [bytedeco/javacv#382] opened 2016-04-11 21:00 UTC
Cannot figure out for the life of me why this isn't working ... I have tried:

1) compile group: 'org.bytedeco', name: 'javacv', version: '1.1'

2) app -> libs -> ffmpeg.jar, javacpp.jar, javacv.jar, opencv.jar

both of these give me the same error about jniopencv_lib

I have other NDK/JNI code compiled so my project structure also has

app -> src -> main -> libs -> armeabi
                                         -> armeabi-v7a
                                         -> mips
                                         -> x86

I desperately need help here. My ultimate goal here is to get a video and extract frames. 

I have tried native android ( method called getFrameAtTime() ) I have tried jCodec, I have tried OpenCv4Android .. nothing works !!

JavaCV seems like it would be the perfect fit ... if I could only get it to run :|

**Comment by saudet** [comment] 2016-04-12 04:48
This is probably a duplicate of https://github.com/bytedeco/javacv/issues/133. Try to extract the native library files in the directory Android Studio wants us to put them in.

**Closed by saudet** 2016-04-12 04:48 UTC
Labels: bug, duplicate
