### ISSUE TITLE
Cannot play high resolution video in MediaPlayer

### ISSUE THREAD

**Issue by Adi-18** [bytedeco/javacv#1262] opened 2019-07-22 19:07 UTC
There is no problem to play recorded low resolution video. But when I play high resolution i.E. 1600 x 1200 and more (duration 4 sec), JavaFX MedaPlayer cannot play the recorded file. MediaPlayer is not starting.

BTW: How can I zoom in source video for save new?

MediaInfo:
General
Complete name                            : D:\Documents\Projekte\NetBeansProjects\SEMDApp\media\maz_UHBEO_Int_Left-Cam1563815424981.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 2,38 MiB
Duration                                 : 4s 167 ms
Overall bit rate                         : 4 798 kb/s
Writing application                      : Lavf58.20.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Ja
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 4s 167 ms
Bit rate                                 : 4 794 kb/s
Width                                    : 1 600 Pixel
Height                                   : 1 200 Pixel
Display aspect ratio                     : 4:3
Frame rate mode                          : konstant
Frame rate                               : 30,000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : progressiv
Bits/(Pixel*Frame)                       : 0.083
Stream size                              : 2,38 MiB (100%)
Writing library                          : x264 core 157
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=60 / keyint_min=6 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00

**Comment by saudet** [comment] 2019-07-22 23:14
Do you mean like crop? There is a filter for that:
https://ffmpeg.org/ffmpeg-filters.html#crop

**Comment by Adi-18** [comment] 2019-07-23 06:19
Think you for the hind with crop.

Now how do I solve play hd movie in MediaPlayer?

**Comment by saudet** [comment] 2019-07-23 06:42
I don't know, that's an issue with JavaFX. You've already opened an issue about that previously, so let's not open a new issue about that.

**Comment by saudet** [comment] 2019-07-23 06:42
Duplicate of #1140

**Closed by saudet** 2019-07-23 06:42 UTC
Labels: duplicate, question
