### ISSUE TITLE
Apple M1 doesn't work properly

### ISSUE THREAD

**Issue by lunima618** [bytedeco/javacv#1696] opened 2021-09-19 08:50 UTC
Ver 1.5.6 (release version)

```
16:46:15.544 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.javacpp.presets.javacpp
16:46:15.546 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.javacpp.Loader
16:46:15.559 [main] DEBUG org.bytedeco.javacpp.Loader - Loading /Users/lubaba/.javacpp/cache/javacpp-macosx-arm64.jar/org/bytedeco/javacpp/macosx-arm64/libjnijavacpp.dylib
16:46:15.566 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.javacpp.presets.javacpp
16:46:15.567 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.javacpp.Pointer
16:46:15.571 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.javacpp.presets.javacpp
16:46:15.571 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.ffmpeg.global.avutil
16:46:15.573 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.javacpp.presets.javacpp
16:46:15.573 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.ffmpeg.global.avutil
16:46:15.606 [main] DEBUG org.bytedeco.javacpp.Loader - Loading library avutil
16:46:15.607 [main] DEBUG org.bytedeco.javacpp.Loader - Failed to load for avutil@.56: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
16:46:15.643 [main] DEBUG org.bytedeco.javacpp.Loader - Loading library jniavutil
16:46:15.643 [main] DEBUG org.bytedeco.javacpp.Loader - Failed to load for jniavutil: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
16:46:15.645 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.javacpp.presets.javacpp
16:46:15.645 [main] DEBUG org.bytedeco.javacpp.Loader - Loading class org.bytedeco.ffmpeg.global.avutil
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at org.bytedeco.javacpp.Loader.load(Loader.java:1212)
at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
at org.bytedeco.javacpp.Loader.load(Loader.java:1133)
at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45)
at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:363)
```

**Comment by saudet** [comment] 2021-09-19 12:31
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1069

**Closed by saudet** 2021-09-19 12:31 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2022-01-21 05:01
I've introduced `macosx-x86_64` builds in commit https://github.com/bytedeco/javacpp-presets/commit/e38c9d192505b76227acb8a645a405e986bfc696.
Please give it a try with the snapshots: http://bytedeco.org/builds/
