### ISSUE TITLE
How to setup the javacv in the Beaglebone Black

### ISSUE THREAD

**Issue by max90727** [bytedeco/javacv#219] opened 2015-09-04 08:58 UTC
Hi:
I am trying the use the javacv in the Beaglebone Black to stream the video.
But I got this error while I running the program using Ant:
[java] java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:194)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:771)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:221)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:348)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:435)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
     [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
     [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
     [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
     [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
     [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
     [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
     [java] Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
     [java] 	at java.lang.Class.forName0(Native Method)
     [java] 	at java.lang.Class.forName(Class.java:274)
     [java] 	at org.bytedeco.javacpp.Loader.load(Loader.java:390)
     [java] 	at org.bytedeco.javacpp.Loader.load(Loader.java:358)
     [java] 	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2539)
     [java] 	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:383)
     [java] 	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:377)
     [java] 	at test.camera.TestVideo3.main(TestVideo3.java:29)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:217)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:152)
     [java] 	... 21 more

**Comment by saudet** [comment] 2015-09-04 11:02
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/37. This device has an ARM processor, so you're going to need to build for the `linux-arm` platform.

**Closed by saudet** 2015-09-04 11:02 UTC
Labels: duplicate, enhancement
