### ISSUE TITLE
Runing report an 'ClassNotFoundException' error,Caused by:org.bytedeco.javacpp.avutil$Pool_free_Pointer

### ISSUE THREAD

**Issue by eguid** [bytedeco/javacv#514] opened 2016-09-26 08:44 UTC
Unable to find the "avutil" ,cannot be recording video
my code:
```java
FrameGrabber grabber = FrameGrabber.createDefault(0);
		grabber.start();

		OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
		IplImage grabbedImage = converter.convert(grabber.grab());
		int width = grabbedImage.width();
		int height = grabbedImage.height();
	
		FrameRecorder recorder = FrameRecorder.createDefault("output.flv", width, height);
		recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); // avcodec.AV_CODEC_ID_H264
		recorder.setFormat("flv");
		recorder.setFrameRate(v_rs);
		recorder.setGopSize(v_rs);
		recorder.start();

		CanvasFrame frame = new CanvasFrame("camera", CanvasFrame.getDefaultGamma() / grabber.getGamma());
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setAlwaysOnTop(true);
		while (frame.isVisible() && (grabbedImage = converter.convert(grabber.grab())) != null) {
			Frame rotatedFrame = converter.convert(grabbedImage);
			frame.showImage(rotatedFrame);
			if (startTime == 0) {
				startTime = System.currentTimeMillis();
			}
			videoTS = 1000 * (System.currentTimeMillis() - startTime);
			recorder.setTimestamp(videoTS);
			recorder.record(rotatedFrame);
			Thread.sleep(40);
		}
		frame.dispose();
		recorder.stop();
		recorder.release();
		grabber.stop();
		System.exit(2);
```

**Comment by saudet** [comment] 2016-09-26 08:55
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/225

**Closed by saudet** 2016-09-26 08:55 UTC
Labels: bug, duplicate
