### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/lib/x86_64/libavutil.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by coralinejones1985** [bytedeco/javacv#530] opened 2016-10-14 03:31 UTC
Hi, I've already asked a question about using 32-bit libs for 64-bit devices. I was told that 32-bit libs can work on 64-bit devices, but it appeared to fail :( I wonder, if there are some binaries for 64-bit system?

**Comment by saudet** [comment] 2016-10-14 03:57
No, there aren't. Marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/52

**Closed by saudet** 2016-10-14 03:57 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2018-02-27 03:10
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
