### ISSUE TITLE
Some Libraries in Face Recognition Examples are missing

### ISSUE THREAD

**Issue by Refikcanmalli** [bytedeco/javacv#221] opened 2015-09-07 18:40 UTC
I have added org.bytedeco.javacv to my gradle project .When I was trying face recognition examples, I noticed that some functions are missing. There is the list of missing libraries

import static org.bytedeco.javacpp.opencv_legacy.*;
import static org.bytedeco.javacpp.opencv_face.*;

EDIT: After I looked into Javacpp-presets repo I have noticed that bins that are uploaded maven repo not the ones that should be created by the cppbuild.sh files that are shared , because opencv_contrib package is not included in bins but is included in script.

**Comment by saudet** [comment] 2015-09-08 12:29
`opencv_legacy` is no longer part of OpenCV 3.0, so unless we find a replacement for the missing functions, we might as well consider removing that sample entirely. `OpenCVFaceRecognizer.java` works better anyway. What's your opinion?

`opencv_contrib` was added after the last release, so it's not part of the release, that's all.

**Comment by Refikcanmalli** [comment] 2015-09-08 13:34
OpenCVFaceRecognizer.java sample also needs opencv_face package that cannot be found in 1.0 release gradle import.

**Comment by saudet** [comment] 2015-09-12 06:55
Duplicate of #200.

**Closed by saudet** 2015-09-12 06:55 UTC
Labels: duplicate
