### ISSUE TITLE
Custom build for FFPMEG, Opencv

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1200] opened 2019-04-30 07:01 UTC
On android, i want to have less size of the libraries files.
What should I do, can i just build the ffmpeg libraries on arm platform then replace the .so files?

**Comment by saudet** [comment] 2019-04-30 07:24
Duplicate of #1199 and https://github.com/bytedeco/javacpp-presets/issues/593

**Closed by saudet** 2019-04-30 07:24 UTC
