### ISSUE TITLE
how to use javacpp presets with version 1.5?

### ISSUE THREAD

**Issue by ramsundark5** [bytedeco/javacv#1213] opened 2019-05-27 06:50 UTC
With javacv 1.4.4, the following definitions worked perfectly,

```
implementation 'org.bytedeco:javacv:1.4.4'
implementation 'org.bytedeco.javacpp-presets:ffmpeg:4.1-1.4.4:android-arm'
implementation 'org.bytedeco.javacpp-presets:ffmpeg:4.1-1.4.4:android-x86'
```

I tried to update javacv to version 1.5 using below dependency,

```
implementation 'org.bytedeco:javacv:1.5'
implementation 'org.bytedeco.ffmpeg-platform:4.1.3-1.5'
```

and get an error "Failed to install native libraries" and unable to install the apk.

Same error for below dependencies also,

```
implementation 'org.bytedeco:javacv:1.5'
implementation 'org.bytedeco.ffmpeg:4.1.3-1.5:android-arm'
```

What is the correct way to use javacv 1.5 with ffmpeg in android?

**Comment by saudet** [comment] 2019-05-27 07:24
Duplicate of #1197

Make sure you're using the latest version of Android Studio!

**Closed by saudet** 2019-05-27 07:24 UTC
Labels: duplicate, question

**Comment by ramsundark5** [comment] 2019-05-27 14:04
@saudet are there any examples of using javacv 1.5 with android? I have the latest android studio and even tried the command line build but still get the below error,

Unable to install /Users/ram.kuppusamy/personal/aiwatch/android/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2
        at com.android.ddmlib.Device.installRemotePackage(Device.java:1063)
        at com.android.ddmlib.Device.installPackage(Device.java:903)
        at com.android.ddmlib.Device.installPackage(Device.java:881)
        at com.android.ddmlib.Device.installPackage(Device.java:870)
        at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:126)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.install(InstallVariantTask.java:179)

Error happens only if I use javacv 1.5 and ffmpeg-platform:4.1.3-1.5.

**Comment by saudet** [comment] 2019-05-28 00:52
It works fine the same as it always did. For example, these sample projects run without issue:
https://github.com/deeplearning4j/dl4j-examples/tree/master/android

**Comment by ramsundark5** [comment] 2019-05-28 05:30
Thanks for the reference. My config seems similar to the ones used in deeplearning4j. The only noticeable difference being, they are not using ffmpeg and I'm using it. For now, I'm reverting back to 1.4.4.
