### ISSUE TITLE
【help】How to use javacv in docker?

### ISSUE THREAD

**Issue by ZhouYixun** [bytedeco/javacv#1738] opened 2022-01-10 02:25 UTC
I use it in linux-x86_64，but I get 
`no jniopencv_highgui in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib`

my maven dependency
`  
     <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>openblas-platform</artifactId>
            <version>0.3.9-1.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.3.0-1.5.3</version>
        </dependency> 
`

**Comment by ZhouYixun** [comment] 2022-01-10 02:28
I do not know how to install GTK in Dockerfile. Please help me

**Comment by saudet** [comment] 2022-01-10 03:47
As shown here, please run `yum install gtk2-devel`:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by saudet** [comment] 2022-01-10 03:49
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/593

**Closed by saudet** 2022-01-10 03:49 UTC
Labels: duplicate, enhancement, question

**Comment by saudet** [comment] 2022-01-10 03:53
We still need javacv-platform, yes.

**Comment by ZhouYixun** [comment] 2022-01-10 04:38
> We still need javacv-platform, yes.

only gtk2-devel and javacv-platform,right? I will try it tonight. Thx!
