### ISSUE TITLE
JavaCV/CUDA/Jetson

### ISSUE THREAD

**Issue by neil-benn** [bytedeco/javacv#1584] opened 2021-02-01 18:41 UTC
Hello,

  I'm trying to get JavaCV working on jetson; my pom has:

		<dependency>
		  <groupId>org.bytedeco</groupId>
		  <artifactId>cuda-platform-redist</artifactId>
		  <version>11.0-8.0-1.5.4</version>
		</dependency>

and

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.5.4</version>
		</dependency>

  When I look at what is pulled down I get the following cuda jars:

linux-x86_64
linux_ppc64le
windows-x86_64
linux-x86_64-redist
linux_ppc64le-redist
windows-x86_64-redist

  However from my searching it seems that CUDA has been successfully compiled for the jetson nano, it is described as developer kit (https://developer.nvidia.com/embedded/jetson-nano-developer-kit).  Is there a snapshot that has these which allows me to access CUDA on the Jetson?

  Thanks.

Cheers,

Neil

**Comment by saudet** [comment] 2021-02-01 23:45
I'm working on getting it working with CUDA 11.2 for linux-arm64 as available here:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=sbsa&compilation=compilation_native&target_distro=Ubuntu&target_version=1804&target_type=runfilelocal
I'm unsure if that will be compatible with Jetson though. In any case, I'll let you know when you can try it out.

/cc @kwatters

**Comment by neil-benn** [comment] 2021-02-02 13:22
Thanks; let us know if there is anything we can do; I've got it ready here to test out whenever you ask.

**Comment by kwatters** [comment] 2021-02-02 21:11
Happy to try it out on the jetson nano here!  Thanks for the heads up.

**Comment by saudet** [comment] 2021-02-03 03:20
Ok, it's done! See commit https://github.com/bytedeco/javacpp-presets/commit/71596aab8e8a8692ddbe7b2192880bb878b9d0df. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2021-02-03 03:21
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/735

**Closed by saudet** 2021-02-03 03:21 UTC
Labels: duplicate, enhancement
