### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by fische17** [bytedeco/javacv#479] opened 2016-08-13 18:47 UTC
Hi, I have seen multiple post about this issue but their solutions don't seem to be working for me. I am running the sample of webcam and audio capture and manually importing the jars in my project. I have been trying what the other suggestions said but still no luck. Any help would be great! 

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
	at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
	at gui.camera.CameraViewPortController.startRecording(CameraViewPortController.java:87)
	at gui.camera.CameraViewPortController.initialize(CameraViewPortController.java:65)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)

**Comment by saudet** [comment] 2016-08-14 00:42
I'm guessing this is on Windows, so marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/225

**Closed by saudet** 2016-08-14 00:42 UTC
Labels: bug, duplicate
