### ISSUE TITLE
Imread (opencv_imgcodecs.imread) - OutOfMemoryError

### ISSUE THREAD

**Issue by Alesh17** [bytedeco/javacv#1532] opened 2020-10-26 10:46 UTC
Physical memory usage is too high: physicalBytes (1067M) > maxPhysicalBytes (1024M).

I try to increase heap by this way: ` android:largeHeap="true"` - but unsuccessfully.

Any advice?

**Comment by saudet** [comment] 2020-10-26 10:47
You can try to increase the value of "org.bytedeco.javacpp.maxPhysicalBytes".

**Comment by saudet** [comment] 2020-10-26 10:49
Duplicate of #599

**Closed by saudet** 2020-10-26 10:49 UTC
Labels: duplicate, question
