### ISSUE TITLE
FFmpegFrameGrabber's method startUnsafe() will  permanetly blocks other thread 

### ISSUE THREAD

**Issue by szlzhm** [bytedeco/javacv#1403] opened 2020-04-22 03:11 UTC
This below code in FFmpegFrameGrabber  will  blocked  other thread always when under multi-thread running.

public void start() throws Exception {
        synchronized (org.bytedeco.javacpp.avcodec.class) {
            startUnsafe();
        }
    }

The block of code has a thread blocking situation, that is, when the video stream is interrupted and our code is calling the avformat_find_stream_info method, the method will always wait for no return, and will not throw an exception, resulting in the thread can not exit the synchronized block, so that other threads will be blocked at the synchronization block.

**Comment by saudet** [comment] 2020-04-22 03:49
Call `start(false)` to skip over `avformat_find_stream_info()`.

**Comment by saudet** [comment] 2020-04-22 03:49
Duplicate of #1376

**Closed by saudet** 2020-04-22 03:49 UTC
Labels: duplicate, question
