### ISSUE TITLE
FFmpegFrameFilter does not support lots of filters

### ISSUE THREAD

**Issue by SumitMarwha** [bytedeco/javacv#838] opened 2017-11-23 11:01 UTC
I want to use eq ffmpeg filter
http://ffmpeg.org/ffmpeg-filters.html#eq
but not able to execute another filters like hue is also not working
http://ffmpeg.org/ffmpeg-filters.html#hue
does anyone knows how to execute it using ffmpegframefilter

**Comment by saudet** [comment] 2017-11-23 11:47
Duplicate of #717.

BTW, contributions are welcome!

**Closed by saudet** 2017-11-23 11:47 UTC

**Comment by saudet** [comment] 2018-04-02 11:45
FYI, filters like "eq" and "hue" are now fixed with JavaCV 1.4.1. Please see issue #887 for details.
