### ISSUE TITLE
RuntimeException on trying to convert Frame to Bitmap AndroidFrameConverter

### ISSUE THREAD

**Issue by akhilc1** [bytedeco/javacv#417] opened 2016-05-25 05:50 UTC
While I try to convert a frame into Bitmap I get the following exception:
```
_FATAL EXCEPTION: pool-14-thread-1
                                                                 Process: com.visho.visho, PID: 26961
                                                                 java.lang.RuntimeException: Buffer not large enough for pixels
                                                                     at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:561)
                                                                     at org.bytedeco.javacv.AndroidFrameConverter.convert(AndroidFrameConverter.java:179)
                                                                     at com.visho.visho.service.WriteCoverImageService$CoverImageHandlerThread$2.run(WriteCoverImageService.java:172)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)_
```
The code is as shown below:
```java 
((ByteBuffer) frame.image[0].position(0)).put(event.getImageData());
                    Frame pulledFrame = null;
                    try {
                        if (event.getCameraId() == FrameMergerHandlerThread.BACK_CAM) {
                            backCamFilter.push(frame);
                            pulledFrame = backCamFilter.pull();
                        } else {
                            frontCamFilter.push(frame);
                            pulledFrame = frontCamFilter.pull();
                        }
                        /*byte[] data = ((ByteBuffer) pulledFrame.image[0].position(0)).array();
                        Frame convertedFrame = converter.convert(data, 480, 480);*/
                        Bitmap bitmap = null;
                        if (pulledFrame != null) {
                            bitmap = converter.convert(pulledFrame);  //Exception happens here.
                        } else {
                            Log.d(TAG, "run: PulledFrame Null!!!!!");
                        }
                        if (bitmap != null) {
                            outputStream = new FileOutputStream(Constants.COVER_IMAGE_FOLDER + "/" + System.currentTimeMillis() + ".jpg");
                            bitmap.compress(Bitmap.CompressFormat.JPEG, 75, outputStream);
                        }
                    } catch (FrameFilter.Exception | FileNotFoundException e) {
                        e.printStackTrace();
                    }
 ```

I have no idea what's wrong with my code, has anybody faced this issue? I am using JavaCV 1.1

**Comment by saudet** [comment] 2016-05-25 06:09
Please try again with JavaCV 1.2. This has been heavily modified.

**Comment by akhilc1** [comment] 2016-05-25 09:06
I updated the dependency in the gradle file as shown:
```compile 'org.bytedeco:javacv:1.2'```
But it gives me the error shown below:
_Error:Could not find javacpp-presets-Mac OS X-x86_64.jar (org.bytedeco:javacpp-presets:1.2).
Searched in the following locations:
    https://jcenter.bintray.com/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Mac OS X-x86_64.jar_

**Comment by saudet** [comment] 2016-05-25 09:21
Duplicate of https://github.com/bytedeco/javacv/issues/395

**Closed by saudet** 2016-05-25 09:21 UTC
Labels: bug, duplicate

**Comment by akhilc1** [comment] 2016-05-25 10:13
Okay, from #395 I was able to build the project, but there is still the same exception "RuntimeException: Buffer not large enough for pixels" while trying to convert frame to bitmap using AndroidFrameConverter

**Comment by saudet** [comment] 2016-05-25 10:34
Make sure "pulledFrame" is either in BGR or RGBA format. It's not made to convert pixel formats other than those 2...

**Comment by akhilc1** [comment] 2016-05-25 12:45
@saudet  Thanks mate this solved the issue. I used ScriptIntrinsicYuvToRGB for the conversion.
