### ISSUE TITLE
4.3.1-1.5.4 version, problems encountered on Mac

### ISSUE THREAD

**Issue by Willdas** [bytedeco/javacv#1542] opened 2020-12-02 04:12 UTC
1. Version 4.3.1-1.5.4, the revers command cannot be used on Mac,
The command is as follows: ffmpeg -i input.mp4 -vf reverse output.mp4
2. Version 4.3.1-1.5.4, libx264 command cannot be used on Mac, libx265 can
The command is as follows: ffmpeg -i input.mp4 -vcodec libx264 -crf 23 output.mp4
But: version 4.2.2-1.5.3 can run the above commands correctly.
Hard-working open source workers can see the difference between these two versions.
The strange thing is that there is no error, or the input file size is only 48kb.

**Comment by saudet** [comment] 2020-12-02 04:15
Yes, there's something wrong with libx264's assembly optimizations on Mac, so they have been disabled since the release.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2020-12-02 04:15
Duplicate of #1519

**Closed by saudet** 2020-12-02 04:15 UTC
Labels: bug, duplicate

**Comment by Willdas** [comment] 2020-12-02 04:19
Thanks

**Comment by saudet** [comment] 2021-03-10 01:13
The workaround has been released with JavaCV 1.5.5. Enjoy!

**Comment by Willdas** [comment] 2021-03-25 07:11
Thanks. I will update the version and use it.
