### ISSUE TITLE
FfmpegFrameRecorder video output not smooth

### ISSUE THREAD

**Issue by mcxycross** [bytedeco/javacv#636] opened 2017-03-08 04:01 UTC
Hi there,
I've created an activity to record video in 1280x720 with FfmpegFrameRecorder. But the video output is not smooth and kinda laggy. I use this setting:

```
...
recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);
recorder.setFormat("flv");
recorder.setSampleRate(sampleAudioRateInHz);
recorder.setFrameRate(15);
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setGopSize(60);     
recorder.setVideoOption("profile", "baseline");
recorder.setVideoOption("preset", "veryfast");
...
```

Is this because the recorder setting or something else? I can't find any documentations or guides about FfmpegFrameRecorder setting and how to get a better video output.
I really appreciate the help.

**Comment by saudet** [comment] 2017-03-08 04:27
Could you provide more information about your hardware?

**Comment by mcxycross** [comment] 2017-03-08 04:37
I test it on my Xperia M5 with android M with Mediatek MT6795 Helio X10, octa-core 2.0 GHz Cortex-A53, with GPU PowerVR G6200 and it's 3GB RAM. Here's the full spec [link](http://www.gsmarena.com/sony_xperia_m5_dual-7465.php).
And I use the front camera to record. Do you think hardware can affect video quality?

**Comment by saudet** [comment] 2017-03-08 05:14
Duplicate of https://github.com/bytedeco/javacv/issues/612
You'll need to use hardware acceleration via the Android API, for example:
https://github.com/google/grafika/blob/master/src/com/android/grafika/ContinuousCaptureActivity.java

**Closed by saudet** 2017-03-08 05:14 UTC
Labels: duplicate, question
