### ISSUE TITLE
Failed to load XXXX when running on Linux

### ISSUE THREAD

**Issue by YanaBirukova** [bytedeco/javacv#2238] opened 2024-05-31 10:29 UTC
Everything runs as expected on local, Windows 11 machine through intellij, but fails on Linux in docker. 
In Gradle I have dependency:
`implementation("org.bytedeco:javacv-platform:1.5.10")
`

Logs:
```
2024-05-31 14:24:18 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:18 Debug: Loading class org.bytedeco.javacpp.Pointer
2024-05-31 14:24:18 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:18 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
2024-05-31 14:24:18 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
2024-05-31 14:24:18 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:18 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:18 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:18 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:18 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:18 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/openblas/linux-x86_64/libgcc_s.so.1
2024-05-31 14:24:18 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libgcc_s.so.1
2024-05-31 14:24:18 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libgcc_s.so
2024-05-31 14:24:18 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:18 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/openblas/linux-x86_64/libquadmath.so.0
2024-05-31 14:24:18 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libquadmath.so.0
2024-05-31 14:24:18 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libquadmath.so
2024-05-31 14:24:18 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:18 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/openblas/linux-x86_64/libgfortran.so.5
2024-05-31 14:24:18 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libgfortran.so.5
2024-05-31 14:24:18 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libgfortran.so
2024-05-31 14:24:18 Debug: Loading library gfortran
2024-05-31 14:24:18 Debug: Failed to load for gfortran@.4: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:18 Debug: Loading library gfortran
2024-05-31 14:24:18 Debug: Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:18 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:18 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/openblas/linux-x86_64/libopenblas.so.0
2024-05-31 14:24:20 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libopenblas_nolapack.so.0
2024-05-31 14:24:20 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libopenblas_nolapack.so
2024-05-31 14:24:21 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:21 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/openblas/linux-x86_64/libjniopenblas_nolapack.so
2024-05-31 14:24:21 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libjniopenblas_nolapack.so
2024-05-31 14:24:21 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:21 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:21 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:21 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:21 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:21 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/openblas/linux-x86_64/libopenblas.so.0
2024-05-31 14:24:23 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libopenblas.so.0
2024-05-31 14:24:23 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libopenblas.so
2024-05-31 14:24:23 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:23 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/openblas/linux-x86_64/libjniopenblas.so
2024-05-31 14:24:24 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libjniopenblas.so
2024-05-31 14:24:24 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:24 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:24 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:24 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:24 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:24 Debug: Loading library cudart
2024-05-31 14:24:24 Debug: Failed to load for cudart@.12: java.lang.UnsatisfiedLinkError: no cudart in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cublasLt
2024-05-31 14:24:24 Debug: Failed to load for cublasLt@.12: java.lang.UnsatisfiedLinkError: no cublasLt in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cublas
2024-05-31 14:24:24 Debug: Failed to load for cublas@.12: java.lang.UnsatisfiedLinkError: no cublas in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cufft
2024-05-31 14:24:24 Debug: Failed to load for cufft@.11: java.lang.UnsatisfiedLinkError: no cufft in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cudnn
2024-05-31 14:24:24 Debug: Failed to load for cudnn@.8: java.lang.UnsatisfiedLinkError: no cudnn in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppc
2024-05-31 14:24:24 Debug: Failed to load for nppc@.12: java.lang.UnsatisfiedLinkError: no nppc in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppial
2024-05-31 14:24:24 Debug: Failed to load for nppial@.12: java.lang.UnsatisfiedLinkError: no nppial in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppicc
2024-05-31 14:24:24 Debug: Failed to load for nppicc@.12: java.lang.UnsatisfiedLinkError: no nppicc in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppicom
2024-05-31 14:24:24 Debug: Failed to load for nppicom@.12: java.lang.UnsatisfiedLinkError: no nppicom in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppidei
2024-05-31 14:24:24 Debug: Failed to load for nppidei@.12: java.lang.UnsatisfiedLinkError: no nppidei in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppif
2024-05-31 14:24:24 Debug: Failed to load for nppif@.12: java.lang.UnsatisfiedLinkError: no nppif in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppig
2024-05-31 14:24:24 Debug: Failed to load for nppig@.12: java.lang.UnsatisfiedLinkError: no nppig in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppim
2024-05-31 14:24:24 Debug: Failed to load for nppim@.12: java.lang.UnsatisfiedLinkError: no nppim in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppist
2024-05-31 14:24:24 Debug: Failed to load for nppist@.12: java.lang.UnsatisfiedLinkError: no nppist in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppisu
2024-05-31 14:24:24 Debug: Failed to load for nppisu@.12: java.lang.UnsatisfiedLinkError: no nppisu in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library nppitc
2024-05-31 14:24:24 Debug: Failed to load for nppitc@.12: java.lang.UnsatisfiedLinkError: no nppitc in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library npps
2024-05-31 14:24:24 Debug: Failed to load for npps@.12: java.lang.UnsatisfiedLinkError: no npps in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cudnn_ops_infer
2024-05-31 14:24:24 Debug: Failed to load for cudnn_ops_infer@.8: java.lang.UnsatisfiedLinkError: no cudnn_ops_infer in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cudnn_ops_train
2024-05-31 14:24:24 Debug: Failed to load for cudnn_ops_train@.8: java.lang.UnsatisfiedLinkError: no cudnn_ops_train in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cudnn_adv_infer
2024-05-31 14:24:24 Debug: Failed to load for cudnn_adv_infer@.8: java.lang.UnsatisfiedLinkError: no cudnn_adv_infer in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cudnn_adv_train
2024-05-31 14:24:24 Debug: Failed to load for cudnn_adv_train@.8: java.lang.UnsatisfiedLinkError: no cudnn_adv_train in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cudnn_cnn_infer
2024-05-31 14:24:24 Debug: Failed to load for cudnn_cnn_infer@.8: java.lang.UnsatisfiedLinkError: no cudnn_cnn_infer in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library cudnn_cnn_train
2024-05-31 14:24:24 Debug: Failed to load for cudnn_cnn_train@.8: java.lang.UnsatisfiedLinkError: no cudnn_cnn_train in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Loading library opencv_cudev
2024-05-31 14:24:24 Debug: Failed to load for opencv_cudev@.409: java.lang.UnsatisfiedLinkError: no opencv_cudev in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:24 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:24 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libopencv_core.so.409
2024-05-31 14:24:24 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libgcc_s.so.1 to /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libgcc_s.so.1
2024-05-31 14:24:24 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libquadmath.so.0 to /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libquadmath.so.0
2024-05-31 14:24:24 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libgfortran.so.5 to /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libgfortran.so.5
2024-05-31 14:24:24 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopenblas.so.0 to /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/openblas/linux-x86_64/libopenblas.so.0
2024-05-31 14:24:24 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_core.so.409
2024-05-31 14:24:24 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_core.so
2024-05-31 14:24:25 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:25 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libopencv_imgproc.so.409
2024-05-31 14:24:25 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_imgproc.so.409
2024-05-31 14:24:25 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_imgproc.so
2024-05-31 14:24:25 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:25 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libjniopencv_core.so
2024-05-31 14:24:25 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_core.so
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.opencv_core.CvSlice
2024-05-31 14:24:25 Debug: Registering org.bytedeco.opencv.opencv_core.CvSlice[address=0x7f09cc3bc040,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc3bc040,deallocatorAddress=0x7f08c675dda0]]
2024-05-31 14:24:25 Debug: Registering org.bytedeco.opencv.opencv_core.CvSlice[address=0x7f09cc3bc460,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc3bc460,deallocatorAddress=0x7f08c675dda0]]
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.opencv_core.AbstractArray
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.opencv_core.Mat
2024-05-31 14:24:25 Debug: Registering org.bytedeco.opencv.opencv_core.Mat[width=1,height=3120220,depth=8,channels=1]
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.javacpp.BytePointer
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.global.opencv_imgproc
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.global.opencv_imgproc
2024-05-31 14:24:25 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:25 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libjniopencv_imgproc.so
2024-05-31 14:24:25 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_imgproc.so
2024-05-31 14:24:25 Debug: Loading class org.bytedeco.opencv.global.opencv_imgcodecs
2024-05-31 14:24:26 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:26 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libopencv_imgcodecs.so.409
2024-05-31 14:24:26 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_imgcodecs.so.409
2024-05-31 14:24:26 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_imgcodecs.so
2024-05-31 14:24:26 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:26 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libjniopencv_imgcodecs.so
2024-05-31 14:24:26 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_imgcodecs.so
2024-05-31 14:24:26 Debug: Registering org.bytedeco.opencv.opencv_core.Mat[width=1200,height=1600,depth=8,channels=3]
2024-05-31 14:24:26 Debug: Registering org.bytedeco.opencv.opencv_core.Mat[width=1,height=24269,depth=8,channels=1]
2024-05-31 14:24:26 Debug: Registering org.bytedeco.opencv.opencv_core.Mat[width=503,height=503,depth=8,channels=4]
2024-05-31 14:24:26 Debug: Registering org.bytedeco.opencv.opencv_core.Mat[width=1,height=38467,depth=8,channels=1]
2024-05-31 14:24:26 Debug: Registering org.bytedeco.opencv.opencv_core.Mat[width=500,height=500,depth=8,channels=4]
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_imgproc
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_imgcodecs
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_videoio
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_imgproc
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_imgcodecs
2024-05-31 14:24:26 Debug: Loading class org.bytedeco.opencv.global.opencv_videoio
2024-05-31 14:24:26 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:26 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libopencv_videoio.so.409
2024-05-31 14:24:27 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_videoio.so.409
2024-05-31 14:24:27 Debug: Creating symbolic link /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_videoio.so
2024-05-31 14:24:27 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:27 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libjniopencv_videoio.so
2024-05-31 14:24:27 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_videoio.so
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.opencv.global.opencv_highgui
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.javacpp.presets.javacpp
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.openblas.global.openblas
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.opencv.global.opencv_core
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.opencv.global.opencv_imgproc
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.opencv.global.opencv_imgcodecs
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.opencv.global.opencv_videoio
2024-05-31 14:24:27 Debug: Loading class org.bytedeco.opencv.global.opencv_highgui
2024-05-31 14:24:27 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:27 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libopencv_highgui.so.409
2024-05-31 14:24:27 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_highgui.so.409
2024-05-31 14:24:27 Debug: Failed to load /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_highgui.so.409: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libopencv_highgui.so.409: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
2024-05-31 14:24:27 Debug: Loading library opencv_highgui
2024-05-31 14:24:27 Debug: Failed to load for opencv_highgui@.409: java.lang.UnsatisfiedLinkError: no opencv_highgui in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:27 Debug: Locking /root/.javacpp/cache before extracting
2024-05-31 14:24:27 Debug: Extracting jar:file:/app/mobbot-2.0.0-all.jar!/org/bytedeco/opencv/linux-x86_64/libjniopencv_highgui.so
2024-05-31 14:24:27 Debug: Loading /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_highgui.so
2024-05-31 14:24:27 Debug: Failed to load /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_highgui.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_highgui.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
2024-05-31 14:24:27 Debug: Loading library jniopencv_highgui
2024-05-31 14:24:27 Debug: Failed to load for jniopencv_highgui: java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:27 2024-05-31 10:24:27.213 [eventLoopGroupProxy-4-2] ERROR Application - Unhandled: POST - /
2024-05-31 14:24:27 java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2024-05-31 14:24:27     at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
2024-05-31 14:24:27     at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
2024-05-31 14:24:27     at java.base/java.lang.System.loadLibrary(Unknown Source)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
2024-05-31 14:24:27     at org.bytedeco.opencv.global.opencv_highgui.<clinit>(opencv_highgui.java:23)
2024-05-31 14:24:27     at java.base/java.lang.Class.forName0(Native Method)
2024-05-31 14:24:27     at java.base/java.lang.Class.forName(Unknown Source)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
2024-05-31 14:24:27     at org.bytedeco.opencv.opencv_objdetect.CascadeClassifier.<clinit>(CascadeClassifier.java:41)
2024-05-31 14:24:27     at com.innowise.mobile.data_db_impl.repository_impl.OpenCVRepositoryImpl.recogniseFace(OpenCVRepositoryImpl.kt:107)
2024-05-31 14:24:27     at com.innowise.mobile.data_db_impl.repository_impl.OpenCVRepositoryImpl.overlayImages(OpenCVRepositoryImpl.kt:65)
2024-05-31 14:24:27     at com.innowise.mobile.data_db_impl.repository_impl.OpenCVRepositoryImpl$overlayImages$1.invokeSuspend(OpenCVRepositoryImpl.kt)
2024-05-31 14:24:27     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-05-31 14:24:27     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-05-31 14:24:27     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2024-05-31 14:24:27     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
2024-05-31 14:24:27     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
2024-05-31 14:24:27     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2024-05-31 14:24:27     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-05-31 14:24:27     at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:251)
2024-05-31 14:24:27     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-05-31 14:24:27     at java.base/java.lang.Thread.run(Unknown Source)
2024-05-31 14:24:27 Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/mobbot-2.0.0-all.jar/org/bytedeco/opencv/linux-x86_64/libjniopencv_highgui.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
2024-05-31 14:24:27     at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
2024-05-31 14:24:27     at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
2024-05-31 14:24:27     at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
2024-05-31 14:24:27     at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
2024-05-31 14:24:27     at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
2024-05-31 14:24:27     at java.base/java.lang.Runtime.load0(Unknown Source)
2024-05-31 14:24:27     at java.base/java.lang.System.load(Unknown Source)
2024-05-31 14:24:27     at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1779)
2024-05-31 14:24:27     ... 23 common frames omitted
2024-05-31 14:24:27 Debug: Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc3525c0,deallocatorAddress=0x7f0a1805f880]
2024-05-31 14:24:27 Debug: Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc3523c0,deallocatorAddress=0x7f08c675fd60]
2024-05-31 14:24:27 Debug: Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc352350,deallocatorAddress=0x7f0a1805f880]
2024-05-31 14:24:27 Debug: Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc34dd20,deallocatorAddress=0x7f08c675fd60]
2024-05-31 14:24:27 Debug: Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc42aea0,deallocatorAddress=0x7f0a1805f880]
2024-05-31 14:24:27 Debug: Collecting org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f09cc3b23e0,deallocatorAddress=0x7f08c675fd60]
```

Could you please help to solve this problem?

**Comment by saudet** [comment] 2024-06-02 00:11
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-06-02 00:11 UTC
Labels: duplicate, enhancement
