### ISSUE TITLE
When I package a docker image, javacv 1.5.10 has bugs, but 1.5.9 is good

### ISSUE THREAD

**Issue by phial3** [bytedeco/javacv#2276] opened 2024-08-21 07:15 UTC
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/6109256a-08ce-4331-a71e-4b300945aae7">

```java
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45)
	at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:366)
```

**Comment by steeveen** [comment] 2024-08-21 07:39
完整的代码发出来看一下呢，pom中的依赖，系统中的ffmpeg版本

**Comment by saudet** [comment] 2024-08-21 08:28
Please try again with Ubuntu

**Comment by phial3** [comment] 2024-08-21 12:17
> Please try again with Ubuntu

java project pom.xml

```xml
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.5.10</version>
</dependency>
```

Dockerfile base image is :
```Dockerfile
FROM bellsoft/liberica-openjdk-alpine:8u412
````

**Comment by phial3** [comment] 2024-08-21 12:18
> 完整的代码发出来看一下呢，pom中的依赖，系统中的ffmpeg版本

`javacv-platform` 1.5.10 contains ffmpeg

**Comment by saudet** [comment] 2024-08-21 16:36
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-08-21 16:36 UTC
Labels: duplicate, question
