### ISSUE TITLE
javacv - 1.5.4 windows server 2018 UnsatisfiedLinkError: no avutil in java.library.path

### ISSUE THREAD

**Issue by 7743366427** [bytedeco/javacv#1577] opened 2021-01-27 12:08 UTC
jdk 1.8

**Comment by saudet** [comment] 2021-01-27 12:25
Please make sure that Media Foundation is installed like this:
https://github.com/bytedeco/javacv/blob/master/.travis.yml#L64

**Comment by saudet** [comment] 2021-01-27 12:26
Duplicate of bytedeco/javacpp-presets#940

**Closed by saudet** 2021-01-27 12:26 UTC
Labels: duplicate, question
