### ISSUE TITLE
record multiple audio streams

### ISSUE THREAD

**Issue by tahaarian** [bytedeco/javacv#1591] opened 2021-02-09 13:02 UTC
Hello @saudet 

I hope you are doing well. 

We need to record a video and 2 audio streams with the `FFmpegFrameRecorder `and according to this [issue](https://github.com/bytedeco/javacv/issues/466) , we have added `audio_st2 `same as `audio_st `in all methods and create an index for detecting related part for the frame.
 
```java
We have sent frames according to below example :

           if (recorder != null) {
                                    synchronized (Vframes) {

                                        if (!Vframes.isEmpty()) {
                                            recorder.record(1, Vframes.remove());
                                        }
                                    }


                                    synchronized (Aframes) {

                                        if (!Aframes.isEmpty()) {
                                            recorder.recordSamples(1, Aframes.remove().samples);
                                        }
                                    }


                                    synchronized (Aframes2) {
                                        if (!Aframes2.isEmpty()) {
                                            recorder.recordSamples(2, Aframes2.remove().samples);

                                        }
                                    }
                                }
```

Then we could detect both audios on final player but it has bad quality or they were mixed frames. 

How could we say that to write frame on specific `AVStream `? I think we did somethings wrong 

I have attached our `FFmpegFrameRecorder `class ( a custom class).

[FFmpegFrameRecorderCustom.txt](https://github.com/bytedeco/javacv/files/5951480/FFmpegFrameRecorderCustom.txt)

We will appreciated if you could help us.

Thank you in advance

**Comment by saudet** [comment] 2021-02-09 19:57
Please don't open duplicate issues.

**Comment by saudet** [comment] 2021-02-09 19:57
Duplicate of #466

**Closed by saudet** 2021-02-09 19:57 UTC
Labels: duplicate, enhancement
