### ISSUE TITLE
MacOS Catalina:  videoInput.listDevices() gives Platform "macosx-x86_64" not supported

### ISSUE THREAD

**Issue by javaspeak** [bytedeco/javacv#1650] opened 2021-05-29 13:09 UTC
I have MacOS Catalina and am running jdk 16 from Oracle.  When I run:

    videoInput.listDevices();

I get:

    Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "macosx-x86_64" not supported by class org.bytedeco.videoinput.videoInput
	at org.bytedeco.javacpp.Loader.load(Loader.java:1172)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.bytedeco.videoinput.videoInput.<clinit>(videoInput.java:23)
	at com.spotadev.javacv_exp.revised.WebcamAndMicrophoneCaptureRevised.listWebcamNames(WebcamAndMicrophoneCaptureRevised.java:44)
	at com.spotadev.javacv_exp.revised.WebcamAndMicrophoneCaptureRevised.main(WebcamAndMicrophoneCaptureRevised.java:263)

Code like this works:

     final WEBCAM_DEVICE_INDEX = 0;
     final OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(WEBCAM_DEVICE_INDEX);

However I want to choose which webcam to use.  It seems like that videoInput.listDevices() is not supported for Mac Catalina.

Does any smart person know how I can query and get the list of webcams and then pass the correct index to:

     new OpenCVFrameGrabber(WEBCAM_DEVICE_INDEX);
     
Thank you for your time.

**Comment by saudet** [comment] 2021-05-30 00:18
videoInput is a Windows-only library, that's normal. FFmpeg is able to list devices too, but it would require some work to complete what @alanwhite and others have started working on, see issue https://github.com/bytedeco/javacv/issues/189#issuecomment-728150951.

**Comment by saudet** [comment] 2021-05-30 00:18
Duplicate of #189

**Closed by saudet** 2021-05-30 00:18 UTC
Labels: duplicate, enhancement, question
