### ISSUE TITLE
AndroidFrameConverter crash with "Attempt to read from null array" while convert frame to bitmap 

### ISSUE THREAD

**Issue by DesenYang** [bytedeco/javacv#1661] opened 2021-06-08 05:39 UTC
Android log as below : 
 _E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tz.javacv, PID: 14430
    java.lang.NullPointerException: Attempt to read from null array
        at org.bytedeco.javacv.AndroidFrameConverter.convert(AndroidFrameConverter.java:195)
        at com.tz.javacv.MainActivity$3.run(MainActivity.java:116)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)_
        
       
       i track the code as below  
       it crash at   ByteBuffer in = (ByteBuffer)frame.image[0];   
``` java

    public Bitmap convert(Frame frame) {
        if (frame != null && frame.image != null) {
            Config config = null;
            switch(frame.imageChannels) {
            case 1:
            case 3:
            case 4:
                config = Config.ARGB_8888;
                break;
            case 2:
                config = Config.RGB_565;
                break;
            default:
                assert false;
            }

            if (this.bitmap == null || this.bitmap.getWidth() != frame.imageWidth || this.bitmap.getHeight() != frame.imageHeight || this.bitmap.getConfig() != config) {
                this.bitmap = Bitmap.createBitmap(frame.imageWidth, frame.imageHeight, config);
            }

            ByteBuffer in = (ByteBuffer)frame.image[0];
            int width = frame.imageWidth;
            int height = frame.imageHeight;
            int stride = frame.imageStride;
            int rowBytes = this.bitmap.getRowBytes();
            if (frame.imageChannels == 1) {
                this.gray2rgba(in, width, height, stride, rowBytes);
                this.bitmap.copyPixelsFromBuffer(this.buffer.position(0));
            } else if (frame.imageChannels == 3) {
                this.bgr2rgba(in, width, height, stride, rowBytes);
                this.bitmap.copyPixelsFromBuffer(this.buffer.position(0));
            } else {
                this.bitmap.copyPixelsFromBuffer(in.position(0));
            }

            return this.bitmap;
        } else {
            return null;
        }
    }
```

**Comment by saudet** [comment] 2021-06-08 05:53
You'll need to make sure it's not null, yes. What is the issue?

**Comment by DesenYang** [comment] 2021-06-08 05:57
i try to covert frame which is from ffmpeggrabber  to a bitmap ,but it crash at AndroidFrameConverter.convert
My code is like this: 
``` java 
    final String SOURCE_RTSP = "rtmp://192.168.2.100/live/room";
    final String SOURCE_SRT = "srt://192.168.2.100:8080?streamid=live.sls.com/live/test";

    final AndroidFrameConverter converter = new AndroidFrameConverter();
    final int TIMEOUT = 10; // In seconds.
    @RequiresApi(api = Build.VERSION_CODES.O)
    public void rtspStreamingTest() {
        try {
            FFmpegLogCallback.set();
            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(SOURCE_SRT);
            grabber.setOption(
                    TimeoutOption.STIMEOUT.getKey(),
                    String.valueOf(TIMEOUT * 1000000)
            );
            grabber.setFormat("mpegts");
            grabber.start();

            Frame frame = null;
            while ((frame = grabber.grab()) != null) {
                Log.d(TAG, "log: image width:" + frame.imageWidth + " : height" + frame.imageHeight);
                if(frame.imageHeight == 0  || frame.imageWidth == 0 || frame.image[0] == null)
                    continue;
                Frame finalFrame = frame;
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        if(finalFrame.imageWidth >0 && finalFrame.imageHeight > 0 && finalFrame != null && finalFrame.image != null &&  finalFrame.image[0] != null)
                           previewpic.setImageBitmap(  converter.convert(finalFrame));
                    }
                });
                System.out.println("frame grabbed at " + grabber.getTimestamp());
            }
            System.out.println("loop end with frame: " + frame);
        } catch (FrameGrabber.Exception ex) {
            System.out.println("exception: " + ex);
        }
        System.out.println("end");
    }
```

**Comment by saudet** [comment] 2021-06-08 06:20
If you're only interested in video frames, call grabImage() instead of grab().

**Comment by DesenYang** [comment] 2021-06-08 11:45
thanks , it run everything fine now

**Comment by saudet** [comment] 2021-06-14 08:28
Duplicate of #116

**Closed by saudet** 2021-06-14 08:28 UTC
Labels: duplicate, question
