### ISSUE TITLE
FFmpeg hardware decoding support + JavaFX

### ISSUE THREAD

**Issue by streamingdv** [bytedeco/javacv#1999] opened 2023-03-22 16:41 UTC
Hi, first of all thanks for this amazing lib. I'm currently porting my Android/ iOS streaming app to Windows/ Linux and I'm looking for a way to integrate FFmpeg in my project, first I wanted to compile it by my own but then I found your project which seems to support all things I need. I just a a few questions and I'm sorry if they are already answered somewhere else. I receive the encoded video stream from a server via h264 or HEVC so "all I need to do" is to decode the frames and render them as fast al possible (usually 60fps)

As far as I have seen FFmpeg and the associated libs are compiled with hardware video decoding acceleration support and are compiled without GPL? Is that correct?

As frontend I want to use JavaFX, as I came with an Android/ iOS background there is usually some kind of surface to render the decoder frames but I don't think this feature exists in JavaFX. I saw that the frame is rendered via ImageView but is there a faster way, maybe via OpenGL?

Last question is more like asking if someone already has experience with that? If not then I will play around with that myself of course. Thanks.

**Comment by saudet** [comment] 2023-03-23 00:40
There is some support for hardware acceleration, yes, and the non-gpl builds are compiled without GPL code, correct.

You can check https://github.com/rladstaetter/javacv-webcam for ways to render quicktly with JavaFX

/cc @rladstaetter @johanvos

**Comment by saudet** [comment] 2023-03-23 00:41
Duplicate of #1989

**Closed by saudet** 2023-03-23 00:41 UTC
Labels: duplicate, question

**Comment by saudet** [comment] 2023-03-23 09:21
nvdec gets enabled, see the build results for that commit: 
https://github.com/bytedeco/javacpp-presets/actions/runs/4314418089
