### ISSUE TITLE
In flv, hevc video coding is not supported. What should I do?

### ISSUE THREAD

**Issue by duanmugou** [bytedeco/javacv#1620] opened 2021-04-08 02:46 UTC
class PushRtmp{
    public static void PushRtmp(String  input,String  output)throws java.lang.Exception,org.bytedeco.javacv.FFmpegFrameGrabber.Exception {
        Integer width,height;
         double frameRate = 5;
         FFmpegFrameGrabber grabber=new FFmpegFrameGrabber(input);   
        avutil.av_log_set_level(avutil.AV_LOG_ERROR);
        FFmpegLogCallback.set();

        grabber.start();

        width=grabber.getImageWidth();
        height=grabber.getImageHeight();

        FFmpegFrameRecorder recorder2=new FFmpegFrameRecorder(output,width,height,2);
        //FFmpegFrameRecorder recorder2=new FFmpegFrameRecorder(input,width,height,2);
        recorder2.setVideoCodec(avcodec.AV_CODEC_ID_H265);
        recorder2.setFormat("flv");

        recorder2.setSampleRate(44100);
        recorder2.setVideoQuality(0);
        recorder2.setVideoBitrate(1000000);
        recorder2.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
        recorder2.start();

        CanvasFrame canvas=new CanvasFrame("videoshow");
        canvas.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Frame frame=null;
    
        for (;(frame = grabber.grabImage()) != null;) {
            try {       
                recorder2.record(frame);                
                canvas.showImage(frame);
            } catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
                e.printStackTrace();
            }finally {
                System.out.println("finish");
            }
        }

        recorder2.close();
        grabber.close();
        canvas.dispose();
    }
}

**Comment by saudet** [comment] 2021-04-08 03:26
Don't use FLV, use another format.

**Comment by saudet** [comment] 2021-04-08 03:26
Duplicate of #1497

**Closed by saudet** 2021-04-08 03:26 UTC
Labels: duplicate, question
