### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopenblas_nolapack.so" not found

### ISSUE THREAD

**Issue by ApexcupDeveloper** [bytedeco/javacv#2017] opened 2023-05-03 17:05 UTC
I am new in javacv & opencv.
when I run the project on my real android device, the app crashed at
`Loader.load(opencv_java.class)`
and
`MatVector images = new MatVector()`

I got this error:
`  java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopenblas_nolapack.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1825)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1416)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
        at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1282)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
        at org.bytedeco.opencv.opencv_core.MatVector.<clinit>(MatVector.java:17)`

   how can I solve this issue? Please help me.

**Comment by saudet** [comment] 2023-05-04 00:38
There's probably a few things that need to be adjusted to get Java SE working on Android. Contributions are welcome though!

**Comment by saudet** [comment] 2023-05-04 00:38
Duplicate of https://github.com/bytedeco/javacpp/issues/659

**Closed by saudet** 2023-05-04 00:38 UTC
Labels: duplicate, enhancement
