### ISSUE TITLE
FFmpegFrameRecorder doesn't work properly 1. Recording more than 30-50 second app crash. 2. Alternate frame skipped.

### ISSUE THREAD

**Issue by shivamsingh** [bytedeco/javacv#555] opened 2016-11-11 07:26 UTC
FFmpegFrameRecorder doesn't work properly 

1. Recording more than 30-50 second app crash. 
2. Alternate frame skipped.

` 
// Camera preview.

@Override
    public void onPreviewFrame(byte[] data, Camera camera) {
      long frameTimeStamp = 1000L * (System.currentTimeMillis() - firstTime);
      if (recording) {
        if (lastSavedframe != null && lastSavedframe.getFrameBytesData() != null) {
          recorderThread.putByteData(lastSavedframe);
        }
      }
      lastSavedframe = new SavedFrames(data, frameTimeStamp, isRotateVideo, isFrontCam);
      cameraDevice.addCallbackBuffer(bufferByte);
    }

// Video Recorder.

package com.videorecorder;
public class RecorderThread extends Thread {

  private int outputWidth;
  private int outputHeight;
  private FFmpegFrameRecorder mVideoRecorder;
  private AtomicBoolean mIsStop = new AtomicBoolean(false);
  private AtomicBoolean mIsFinish = new AtomicBoolean(false);

  private Frame yuvFrame;
  private ArrayList<SavedFrames> savedFrameList = null;

  private FFmpegFrameFilter filterRotateVideoFrontCam = null;
  private FFmpegFrameFilter filterRotateVideoBackCam = null;
  private FFmpegFrameFilter filterCropVideoBackCam = null;
  private FFmpegFrameFilter filterCropVideoFrontCam = null;

  private int previewWidth = 0, previewHeight = 0;

  public RecorderThread(FFmpegFrameRecorder videoRecorder, int previewWidth, int previewHeight,
      int outputWidth, int outputHeight) {
    try {
      this.previewWidth = previewWidth;
      this.previewHeight = previewHeight;
      this.outputWidth = outputWidth;
      this.outputHeight = outputHeight;

      savedFrameList = new ArrayList<>();
      this.yuvFrame = new Frame(previewWidth, previewHeight, Frame.DEPTH_UBYTE, 2);
      this.mVideoRecorder = videoRecorder;
      setFilters();
    } catch (Exception e) {
    }
  }

  public void putByteData(SavedFrames lastSavedframe) {
    if (savedFrameList != null) savedFrameList.add(lastSavedframe);
  }

  @Override
  public void run() {
    try {
      while (!mIsFinish.get()) {
        if (processFramesFromList()) {

        } else {
          if (mIsStop.get()) {
            break;
          }
          try {
            Thread.sleep(10);
          } catch (Exception e) {
            e.printStackTrace();
          }
        }
      }
    } finally {
      release();
    }
  }

  private boolean processFramesFromList() {
    boolean isListPending = false;
    if (savedFrameList != null && savedFrameList.size() > 0) {
      SavedFrames savedFrame = savedFrameList.get(0);
      savedFrameList.remove(0);
      mVideoRecorder.setTimestamp(savedFrame.getTimeStamp());
      if (savedFrameList.size() > 0) {
        isListPending = true;
      }
      Log.d(RecorderThread.class.getSimpleName(), "savedFrameList: " + savedFrameList.size());
    }
    return isListPending;
  }

  public void stopRecord() {
    mIsStop.set(true);
    try {
      this.join();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public void finish() {
    mIsFinish.set(true);
    try {
      this.join();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private void release() {
    mVideoRecorder = null;
    yuvFrame = null;
    savedFrameList = null;
    try {
      if (filterRotateVideoFrontCam != null) {
        filterRotateVideoFrontCam.stop();
        filterRotateVideoFrontCam.release();
        filterRotateVideoFrontCam = null;
      }
      if (filterRotateVideoBackCam != null) {
        filterRotateVideoBackCam.stop();
        filterRotateVideoBackCam.release();
        filterRotateVideoBackCam = null;
      }
      if (filterCropVideoBackCam != null) {
        filterCropVideoBackCam.stop();
        filterCropVideoBackCam.release();
        filterCropVideoBackCam = null;
      }
      if (filterCropVideoFrontCam != null) {
        filterCropVideoFrontCam.stop();
        filterCropVideoFrontCam.release();
        filterCropVideoFrontCam = null;
      }
    } catch (FrameFilter.Exception e) {
      Log.e("RecorderThread release", e.getMessage());
    }
  }

  private void processBytesUsingFrame(SavedFrames frame) {
    ((ByteBuffer) yuvFrame.image[0].position(0)).put(frame.getFrameBytesData());
    Frame pulledFrame = null;

    if (frame.isRotateVideo()) {
      if (frame.isFrontCam()) {
        try {
          filterRotateVideoFrontCam.push(yuvFrame);
          while ((pulledFrame = filterRotateVideoFrontCam.pull()) != null) {
            mVideoRecorder.record(pulledFrame);
          }
        } catch (FrameFilter.Exception e) {
          e.printStackTrace();
        } catch (FrameRecorder.Exception e) {
          e.printStackTrace();
        }
      } else {
        try {
          filterRotateVideoBackCam.push(yuvFrame);
          while ((pulledFrame = filterRotateVideoBackCam.pull()) != null) {
            mVideoRecorder.record(pulledFrame);
          }
        } catch (FrameFilter.Exception e) {
          e.printStackTrace();
        } catch (FrameRecorder.Exception e) {
          e.printStackTrace();
        }
      }
    } else {
      if (frame.isFrontCam()) {
        try {
          filterCropVideoFrontCam.push(yuvFrame);
          while ((pulledFrame = filterCropVideoFrontCam.pull()) != null) {
            mVideoRecorder.record(pulledFrame);
          }
        } catch (FrameFilter.Exception e) {
          e.printStackTrace();
        } catch (FrameRecorder.Exception e) {
          e.printStackTrace();
        }
      } else {
        try {
          filterCropVideoBackCam.push(yuvFrame);
          while ((pulledFrame = filterCropVideoBackCam.pull()) != null) {
            mVideoRecorder.record(pulledFrame);
          }
        } catch (FrameFilter.Exception e) {
          e.printStackTrace();
        } catch (FrameRecorder.Exception e) {
          e.printStackTrace();
        }
      }
    }
  }

  private void setFilters() {
    String cropVideo = ",crop=w=" + outputWidth + ":h=" + outputHeight + ":x=" + 0 + ":y=" + 0;
    String rotateVideoFrontCam = "transpose=cclock,hflip" + cropVideo;
    String rotateVideoBackCam = "transpose=clock" + cropVideo;
    String cropVideoFrontCam = "hflip" + cropVideo;

    filterRotateVideoFrontCam =
        new FFmpegFrameFilter(rotateVideoFrontCam, previewWidth, previewHeight);
    filterRotateVideoFrontCam.setPixelFormat(avutil.AV_PIX_FMT_NV21);

    filterRotateVideoBackCam =
        new FFmpegFrameFilter(rotateVideoBackCam, previewWidth, previewHeight);
    filterRotateVideoBackCam.setPixelFormat(avutil.AV_PIX_FMT_NV21);

    filterCropVideoBackCam = new FFmpegFrameFilter(cropVideo, previewWidth, previewHeight);
    filterCropVideoBackCam.setPixelFormat(avutil.AV_PIX_FMT_NV21);

    filterCropVideoFrontCam = new FFmpegFrameFilter(cropVideoFrontCam, previewWidth, previewHeight);
    filterCropVideoFrontCam.setPixelFormat(avutil.AV_PIX_FMT_NV21);

    try {
      filterRotateVideoFrontCam.start();
      filterRotateVideoBackCam.start();
      filterCropVideoBackCam.start();
      filterCropVideoFrontCam.start();
    } catch (FrameFilter.Exception e) {
      Log.e("RecordThread setFilter", e.getMessage());
    }
  }
}
`

**Comment by saudet** [comment] 2016-11-11 07:36
You'll need to provide more information!

**Comment by shivamsingh** [comment] 2016-11-11 08:12
Thanks Saudet,

I am actually developing an Android application to record Video without any audio.
So, I am using FFmpegFrameRecorder to record video.

I came across many VideoRecording application on Github using FFmpegFrameRecorder but all of them have set max recoding duration to 10 seconds. If I increase the max duration from 10 seconds  to 2 minutes app crashes.

Here is the link to my application on Github.
https://github.com/shivamsingh/VideoRecorder.

Here are the reference applications.
https://github.com/amosyuen/FFmpegVideoRecorder
https://github.com/CrazyOrr/FFmpegRecorder
https://github.com/sourab-sharma/TouchToRecord

**Comment by saudet** [comment] 2016-11-11 08:48
Duplicate of #303. In short: Use the Android API.

**Closed by saudet** 2016-11-11 08:48 UTC
Labels: duplicate, question
