### ISSUE TITLE
How to Get Frame at Time?

### ISSUE THREAD

**Issue by xulihang** [bytedeco/javacv#1804] opened 2022-04-27 10:05 UTC
I need to grab a frame at a specific timestamp.

In Android, I can use MediaMetadataRetriever's `getFrameAtTime` method. I wonder what the equivalent is in javacv. I am using FFMpegFrameGrabber.

**Comment by saudet** [comment] 2022-04-27 11:14
setTimestamp()

**Comment by saudet** [comment] 2022-04-27 11:15
Duplicate of #1792

**Closed by saudet** 2022-04-27 11:15 UTC
Labels: duplicate, question
