### ISSUE TITLE
Stream and record Question

### ISSUE THREAD

**Issue by kaiser24** [bytedeco/javacv#1537] opened 2020-11-10 13:59 UTC
Hello, 

I am streaming a video through rtmp to a server that I have, using FFmpegFrameRecorder.
to stream to my server I pass the stream link when I create the recorder but I also want to record the video on the phone, however the path where to save the video on the phone takes the same input as the stream link. how can I do both at the same time?

thanks

**Comment by saudet** [comment] 2020-11-12 04:22
Duplicate of #1475

**Closed by saudet** 2020-11-12 04:22 UTC
Labels: duplicate, enhancement
