### ISSUE TITLE
Murshmallow compatibility

### ISSUE THREAD

**Issue by coralinejones1985** [bytedeco/javacv#313] opened 2016-01-22 07:42 UTC
Hello.
I've got several questions (maybe silly ones):
1. Related to #310. Library works fine on armeabi-v7a and on most x86 devices since I copied .so libs in jni folder. But I'm still getting the same error (#310) on x86-emulatior (android api 23 murshmallow). 
2. What should I do to make my app work with mips and x86_64 devices as well.

**Comment by saudet** [comment] 2016-01-24 02:36
Duplicate of #245, https://github.com/bytedeco/javacpp-presets/issues/52, and https://github.com/bytedeco/javacpp-presets/issues/68. Please follow up the appropriate discussions there, thank you.

BTW, 64-bit devices support 32-bit binaries just fine. You don't need to do anything special.

**Closed by saudet** 2016-01-24 02:36 UTC
Labels: bug, duplicate, enhancement

**Comment by coralinejones1985** [comment] 2016-02-15 09:18
Oh, sorry, not exactly same error as in #310. 
Does it related to those discussions too?
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.Class.forName(Class.java:324)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                                          at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                                          at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
                                                                          at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                          at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                                                                          at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:123)

**Comment by saudet** [comment] 2018-02-27 03:11
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
