### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by urvishjarvis1** [bytedeco/javacv#1014] opened 2018-06-15 09:53 UTC
More than one file was found with OS independent path 'org/bytedeco/javacpp/windows-x86/api-ms-win-crt-locale-l1-1-0.dll'
getting this exception while using it for development

**Comment by saudet** [comment] 2018-06-15 11:01
Duplicate of #353. You'll need to exclude these files. Some ways to do that are given in issue #353.

**Closed by saudet** 2018-06-15 11:01 UTC
Labels: duplicate, enhancement
