### ISSUE TITLE
Cannot encode with H264

### ISSUE THREAD

**Issue by edukun** [bytedeco/javacv#778] opened 2017-09-01 01:38 UTC
I'm trying to create a video encoded with h264 on a Samsung Galaxy S8. I'm using javacv-1.3.4-Snapshot and ffmpeg-3.3.2-1.3.4. I get the next error:

org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -542398533: Could not encode video packet.
at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:943)
at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:855)
at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:848)
...

I get the same error with older versions of javacv and ffmpeg also.

Snippet from code:

...
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setFormat("mp4");
...

**Comment by saudet** [comment] 2017-09-01 02:04
Check the messages in FFmpeg's log for details please.

**Comment by edukun** [comment] 2017-09-01 08:34
Here is the full FFmpeg log:

I/System.out: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///storage/emulated/0/Pictures/MP4_20170901_102844_1575908013.mp4':
I/System.out: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///storage/emulated/0/Pictures/MP4_20170901_102844_1575908013.mp4':
I/System.out:   Metadata:
I/System.out:   Metadata:
I/System.out:     major_brand     : 
I/System.out:     major_brand     : 
I/System.out: isom
I/System.out: isom
I/System.out:     minor_version   : 
I/System.out:     minor_version   : 
I/System.out: 512
I/System.out: 512
I/System.out:     compatible_brands: 
I/System.out:     compatible_brands: 
I/System.out: isomiso2avc1mp41
I/System.out: isomiso2avc1mp41
I/System.out:     encoder         : 
I/System.out:     encoder         : 
I/System.out: Lavf56.36.100
I/System.out: Lavf56.36.100
I/System.out:   Duration: 
I/System.out:   Duration: 
I/System.out: 00:00:00.44
I/System.out: 00:00:00.44
I/System.out: , start: 
I/System.out: , start: 
I/System.out: 0.000000
I/System.out: 0.000000
I/System.out: , bitrate: 
I/System.out: , bitrate: 
I/System.out: 849 kb/s
I/System.out: 849 kb/s
I/System.out:     Stream #0:0
I/System.out:     Stream #0:0
I/System.out: (und)
I/System.out: (und)
I/System.out: : Video: h264 (High) (avc1 / 0x31637661), yuv420p, 420x420, 832 kb/s
I/System.out: : Video: h264 (High) (avc1 / 0x31637661), yuv420p, 420x420, 832 kb/s
I/System.out: , 
I/System.out: , 
I/System.out: 25 fps, 
I/System.out: 25 fps, 
I/System.out: 25 tbr, 
I/System.out: 25 tbr, 
I/System.out: 12800 tbn, 
I/System.out: 12800 tbn, 
I/System.out: 50 tbc
I/System.out: 50 tbc
I/System.out:  (default)
I/System.out:  (default)
I/System.out:     Metadata:
I/System.out:     Metadata:
I/System.out:       handler_name    : 
I/System.out:       handler_name    : 
I/System.out: VideoHandler
I/System.out: VideoHandler
W/System.err: Warning: [wav @ 0x9f68a000] Estimating duration from bitrate, this may be inaccurate
I/System.out: Input #0, wav, from 'file:///storage/emulated/0/Android/data/com.example/cache/recorded_audio.wav':
I/System.out: Input #0, wav, from 'file:///storage/emulated/0/Android/data/com.example/cache/recorded_audio.wav':
I/System.out:   Duration: 
I/System.out:   Duration: 
I/System.out: 00:00:02.08
I/System.out: 00:00:02.08
I/System.out: , bitrate: 
I/System.out: , bitrate: 
I/System.out: 1536 kb/s
I/System.out: 1536 kb/s
I/System.out:     Stream #0:0
I/System.out:     Stream #0:0
I/System.out: : Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
I/System.out: : Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
W/System.err: Warning: [libx264 @ 0x9f6bf400] -qscale is ignored, -crf is recommended.
I/System.out: [libx264 @ 0x9f6bf400] using cpu capabilities: ARMv6 NEON
I/System.out: [libx264 @ 0x9f6bf400] using cpu capabilities: ARMv6 NEON
I/System.out: [libx264 @ 0x9f6bf400] profile High, level 2.1
I/System.out: [libx264 @ 0x9f6bf400] profile High, level 2.1
I/System.out: [libx264 @ 0x9f6bf400] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
I/System.out: [libx264 @ 0x9f6bf400] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
I/System.out: Output #0, mp4, to '/storage/emulated/0/Pictures/RESULT_20170901_102851_1351434887.mp4':
I/System.out: Output #0, mp4, to '/storage/emulated/0/Pictures/RESULT_20170901_102851_1351434887.mp4':
I/System.out:   Metadata:
I/System.out:   Metadata:
I/System.out:     encoder         : 
I/System.out:     encoder         : 
I/System.out: Lavf57.71.100
I/System.out: Lavf57.71.100
I/System.out:     Stream #0:0
I/System.out:     Stream #0:0
I/System.out: : Video: h264 (Constrained Baseline) ([33][0][0][0] / 0x0021), yuv420p, 420x420, q=2-31, 832 kb/s
I/System.out: : Video: h264 (Constrained Baseline) ([33][0][0][0] / 0x0021), yuv420p, 420x420, q=2-31, 832 kb/s
I/System.out: , 
I/System.out: , 
I/System.out: 12800 tbn
I/System.out: 12800 tbn
I/System.out:     Stream #0:1
I/System.out:     Stream #0:1
I/System.out: : Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp, 64 kb/s
I/System.out: : Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp, 64 kb/s
W/System.err: Warning: [swscaler @ 0x973b6000] No accelerated colorspace conversion found from yuv420p to bgr24.
I/System.out: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///storage/emulated/0/Pictures/MP4_20170901_102844_1575908013.mp4':
I/System.out: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///storage/emulated/0/Pictures/MP4_20170901_102844_1575908013.mp4':
I/System.out:   Metadata:
I/System.out:   Metadata:
I/System.out:     major_brand     : 
I/System.out:     major_brand     : 
I/System.out: isom
I/System.out: isom
I/System.out:     minor_version   : 
I/System.out:     minor_version   : 
I/System.out: 512
I/System.out: 512
I/System.out:     compatible_brands: 
I/System.out:     compatible_brands: 
I/System.out: isomiso2avc1mp41
I/System.out: isomiso2avc1mp41
I/System.out:     encoder         : 
I/System.out:     encoder         : 
I/System.out: Lavf56.36.100
I/System.out: Lavf56.36.100
I/System.out:   Duration: 
I/System.out:   Duration: 
I/System.out: 00:00:00.44
I/System.out: 00:00:00.44
I/System.out: , start: 
I/System.out: , start: 
I/System.out: 0.000000
I/System.out: 0.000000
I/System.out: , bitrate: 
I/System.out: , bitrate: 
I/System.out: 849 kb/s
I/System.out: 849 kb/s
I/System.out:     Stream #0:0
I/System.out:     Stream #0:0
I/System.out: (und)
I/System.out: (und)
I/System.out: : Video: h264 (High) (avc1 / 0x31637661), yuv420p, 420x420, 832 kb/s
I/System.out: : Video: h264 (High) (avc1 / 0x31637661), yuv420p, 420x420, 832 kb/s
I/System.out: , 
I/System.out: , 
I/System.out: 25 fps, 
I/System.out: 25 fps, 
I/System.out: 25 tbr, 
I/System.out: 25 tbr, 
I/System.out: 12800 tbn, 
I/System.out: 12800 tbn, 
I/System.out: 50 tbc
I/System.out: 50 tbc
I/System.out:  (default)
I/System.out:  (default)
I/System.out:     Metadata:
I/System.out:     Metadata:
I/System.out:       handler_name    : 
I/System.out:       handler_name    : 
I/System.out: VideoHandler
I/System.out: VideoHandler
W/System.err: Warning: [swscaler @ 0x96336000] No accelerated colorspace conversion found from yuv420p to bgr24.
W/System.err: Error: [libx264 @ 0x9f6bf400] lookahead thread is already stopped
W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -542398533: Could not encode video packet.
W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:943)
W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:855)
W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:848)

**Comment by saudet** [comment] 2017-09-01 12:03
Does this happen on another platform than Android? Or is it specific to Android?

**Comment by edukun** [comment] 2017-09-01 12:09
I've only tested in Android. I'm developing an Android app.

I've tried with different heights and widths, but always same error. I don't know if it's a problem with bitrate, fps, sizes...

MPEG4 works flawlessly with same parameters

**Comment by saudet** [comment] 2017-09-01 12:33
Does the same thing happen with FFmpeg 3.2.1?

**Comment by edukun** [comment] 2017-09-01 12:44
Yes, exactly the same errors

**Comment by saudet** [comment] 2017-09-01 12:47
Could you provide the few lines of code to reproduce this with FFmpegFrameRecorder?

**Comment by edukun** [comment] 2017-09-01 12:59
Sure. mPicture is this mp4: https://media.tenor.com/videos/ad05ca571ff0283b4103f1e94cfc014a/mp4

                FrameGrabber grabber = new FFmpegFrameGrabber(mPicture);

                grabber.start();

                FrameRecorder recorder = new FFmpegFrameRecorder(output, grabber.getImageWidth(), grabber.getImageHeight(), 2);
                recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
                recorder.setFormat("mp4");
                recorder.setVideoBitrate(grabber.getVideoBitrate());
                recorder.setVideoQuality(1);
                recorder.setFrameRate(grabber.getFrameRate());
                recorder.setSampleRate(grabber.getSampleRate());
                recorder.start();
                Frame frame= null;
                int i = 0;
                while ((frame = grabber.grabFrame()) != null) {
                    recorder.record(frame);
                }
                recorder.stop();
                grabber.stop();

**Comment by saudet** [comment] 2017-09-01 13:06
x264 might not support what you're passing there so you should remove these lines:
```java
            recorder.setVideoBitrate(grabber.getVideoBitrate());
            recorder.setVideoQuality(1);
            recorder.setFrameRate(grabber.getFrameRate());
            recorder.setSampleRate(grabber.getSampleRate());
```

**Comment by edukun** [comment] 2017-09-01 13:09
I removed them and same result...

**Comment by saudet** [comment] 2017-09-01 13:25
Well, if you could reproduce that on another platform than Android, please let me know. It will make things much easier to debug. Thanks!

**Comment by edukun** [comment] 2017-09-01 13:48
Ok, I'll try to reproduce it. Thanks for the help!

**Comment by saudet** [comment] 2017-09-17 02:06
Does this happen by any chance in `FFmpegFrameRecorder.stop()`?
Do you get the same error if you call `FFmpegFrameRecorder.release()` instead?

**Comment by edukun** [comment] 2017-09-18 10:27
It happens at start, just when grabbing the first frame, never ends the encoding

**Comment by saudet** [comment] 2017-11-16 02:53
Any updates?

**Comment by saudet** [comment] 2017-11-16 02:59
I see you are trying to use libx264 with threads, which is known to be buggy, so you should consider disabling multithreading: https://github.com/bytedeco/javacv/issues/745#issuecomment-336786816

I'll mark this as a duplicate of #745 but let me know if you still have issues even with only 1 thread.

On the other hand, if multithreading is important to you, please consider reporting this issue upstream.

**Closed by saudet** 2017-11-16 02:59 UTC
Labels: duplicate

**Comment by edukun** [comment] 2017-11-16 10:05
Thanks for the tip. But as it didn't manage to encode it, I finally ended using ffmpeg library... In a future, I hope I can use again javacv, hundred times easier than ffmpeg!

**Comment by avanibhatnagar** [comment] 2018-08-14 17:58
@edukun Did you ever manage to encode with H264? I'm getting the same error..

**Comment by edukun** [comment] 2018-08-14 18:00
No... I used ffmpeg directly.

**Comment by avanibhatnagar** [comment] 2018-08-14 18:14
Do you mean ffmpeg command line? I see.. Thanks!

**Comment by edukun** [comment] 2018-08-14 18:15
Yes! couldn’t use javacv
