### ISSUE TITLE
Ffmpegframegrabber delay in Java 1.5.3

### ISSUE THREAD

**Issue by TangJhan** [bytedeco/javacv#1540] opened 2020-12-01 11:37 UTC
Using Swing to display images, FFmpegFrameGrabber to call grab function, latency and a bit of a lag, not an issue on version 1.3.3

**Comment by saudet** [comment] 2020-12-01 12:19
Please provide some sample code to reproduce this issue.

**Comment by zuiyuexun** [comment] 2020-12-02 02:56
Hello, my code is as follows
```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(clientSocket.getInputStream(),0);
grabber.setFormat("h264");
grabber.setOption("rtsp_transport", "tcp");
grabber.start();
Java2DFrameConverter java2dFrameConverter = new Java2DFrameConverter();
while(true) {
        Frame frame = grabber.grabImage();
        BufferedImage image = java2dFrameConverter.convert(frame);
        if(frame != null){
              simulatorScreenView.setIcon(new ImageIcon(image));	
        }else {
              grabber.stop();
              grabber.close();
              throw new IOException("The connection is broken");
        }
}
```

**Comment by saudet** [comment] 2020-12-02 02:59
Please also provide the messages that are displayed on the console.

**Comment by saudet** [comment] 2020-12-03 01:38
If you're not seeing any messages on the console, make sure that FFmpegLogCallback.set() has been called

**Comment by TangJhan** [comment] 2020-12-03 02:34
I've seen the log information, which is shown below
Info: Input #0, h264, from 'java.io.BufferedInputStream@28b9b938':

Info:   Duration: 
Info: N/A
Info: , bitrate: 
Info: N/A
Info: 

Info:     Stream #0:0
Info: : Video: h264 (High), yuv420p(tv, smpte170m/bt470bg/smpte170m, progressive), 544x1080
Info: , 
Info: 25 fps, 
Info: 25 tbr, 
Info: 1200k tbn, 
Info: 50 tbc
Info:

**Comment by saudet** [comment] 2020-12-03 02:43
Is this with 1.3.3? or 1.5.3? What messages do you get with 1.3.3 and 1.5.3?
Also, please try 1.5.4 and 1.5.5-SNAPSHOT: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2021-08-03 08:30
This could be related to issue #1498. JavaCV 1.5.6 no longer uses the deprecated API, so it might fix this issue as well. Please let me know if this is still happening with 1.5.6, but for now I will assume that using the new API fixes this.

**Comment by saudet** [comment] 2021-08-03 08:30
Duplicate of #1498

**Closed by saudet** 2021-08-03 08:30 UTC
Labels: bug, duplicate
