### ISSUE TITLE
Does JavaCV support grab subtitle Stream with FFmpegFrameGrabber?

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2149] opened 2023-12-20 09:31 UTC
Does JavaCV support grab subtitle stream with FFmpegFrameGrabber?

If I want to grab a subtitle file , I found these in JavaCV source code ,like:
if (video_st == null && audio_st == null) {
            throw new Exception("Did not find a video or audio stream inside \"" + filename
                    + "\" for videoStream == " + videoStream + " and audioStream == " + audioStream + ".");
}
Why not added srtStream condition? FFmpeg supports soft subtitles.

**Comment by saudet** [comment] 2023-12-20 13:05
No, it's not currently supported, but as always contributions are welcome!

**Comment by saudet** [comment] 2023-12-20 13:06
Duplicate of #503

**Closed by saudet** 2023-12-20 13:06 UTC
Labels: duplicate, enhancement
