### ISSUE TITLE
FFmpegFrameGrabber giving timeStamp 0 after grabbing first audio frame.

### ISSUE THREAD

**Issue by rajib3hasan** [bytedeco/javacv#1178] opened 2019-04-08 06:22 UTC
Sometimes it gives 0 after till 3rd grab(). Why?

**Comment by saudet** [comment] 2019-04-08 06:28
It's probably caused by a buggy codec, maybe just ignoring those would work for you...

In any case, I'll mark this as a duplicate of issue #1035.

Please report upstream if this important to you!

**Closed by saudet** 2019-04-08 06:28 UTC
Labels: bug, duplicate
