### ISSUE TITLE
Support ffmpeg VA-API version 1.17.0

### ISSUE THREAD

**Issue by plandol** [bytedeco/javacv#1995] opened 2023-03-15 14:00 UTC
Can you please support a recent version of VA-API? Currently version 0.40.0 is supported:
```
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva error: /usr/lib64/dri/iHD_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1
```
My Linux System supports VA-API 1.17.0:
```
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.13.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.3.4 ()
```
I would appreciate any VA-API 1.0 version.
Is this possible?

**Comment by saudet** [comment] 2023-03-15 23:19
Sure it's possible. And contributions are welcome too!

**Comment by saudet** [comment] 2023-03-15 23:19
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1289

**Closed by saudet** 2023-03-15 23:19 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2023-05-07 02:23
Thanks to @silenium-dev, this has been fixed! Please give it a try with the snapshots: http://bytedeco.org/builds/
