### ISSUE TITLE
Rotation / Orientation data now in 'Side data'?

### ISSUE THREAD

**Issue by akozmic-prisidio** [bytedeco/javacv#1823] opened 2022-06-07 23:09 UTC
When taking videos with my phone, the resulting .MOV and .mp4 files (tried with android and iPhone) don't have "rotate" metadata.

here's an example of the output from a video I took today:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'horizontal - right.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2022-06-07T18:51:20.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 8
    com.apple.quicktime.software: 15.5
    com.apple.quicktime.creationdate: 2022-06-07T13:48:04-0500
    com.apple.photos.originating.signature: AZt9m4wHzmANYSNIAgQ3U5At/3VW
  Duration: 00:00:06.50, start: 0.000000, bitrate: 14934 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 90 kb/s (default)
    Metadata:
      creation_time   : 2022-06-07T18:51:20.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 14798 kb/s, 30.01 fps, 30 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2022-06-07T18:51:20.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -180.00 degrees
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2022-06-07T18:51:20.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2022-06-07T18:51:20.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 34 kb/s (default)
    Metadata:
      creation_time   : 2022-06-07T18:51:20.000000Z
      handler_name    : Core Media Metadata
```

The only metadata related to orientation or rotation is:
`displaymatrix: rotation of -180.00 degrees`

If I use FFmpegFrameGrabber to grab an image of a frame, the result is upside down.   I'd like to look up the metadata and based on the orientation, I want to rotate the image myself.

All the examples I could find say to use
` String rotationMetadata = g.getVideoMetadata("rotate");`
which should be one of [0,90,180,270]
 but this appears to no longer be the case as the "rotate" metadata is not present.  That code returns null for me as its not there.

Is there a way for me to get the "Side data" ? 
```    
Side data:
      displaymatrix: rotation of -180.00 degrees
```

**Comment by saudet** [comment] 2022-06-07 23:18
FFmpegFrameGrabber needs to be updated to support that. Contributions are welcome!

**Comment by saudet** [comment] 2022-06-07 23:19
Duplicate of #1361

**Closed by saudet** 2022-06-07 23:19 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2022-07-23 13:45
I've added `FFmpegFrameGrabber.getDisplayRotation()` in commit https://github.com/bytedeco/javacv/commit/d1b1f4e1d445e764fc542d335ba5235483613bd7.
Please give it a try with the snapshots: http://bytedeco.org/builds/
