### ISSUE TITLE
Unable to read data from camera, is it a possible bug in JavaCV 1.1

### ISSUE THREAD

**Issue by greeninho** [bytedeco/javacv#404] opened 2016-05-02 12:01 UTC
http://stackoverflow.com/questions/36981641/unable-to-read-data-from-camera-is-it-a-possible-bug-in-javacv-1-1

**Comment by saudet** [comment] 2016-05-02 12:08
Duplicate of https://github.com/bytedeco/javacv/issues/357

**Closed by saudet** 2016-05-02 12:08 UTC
Labels: bug, duplicate
