### ISSUE TITLE
 FFmpegFrameGrabber is not starting. It got stucked and not giving any exception.

### ISSUE THREAD

**Issue by sumit33** [bytedeco/javacv#1768] opened 2022-03-01 10:30 UTC
This is my code (mac) `...`

`

            grabber = new FFmpegFrameGrabber("Capture screen 0:none");
            grabber.setFormat("avfoundation");
            grabber.setOption("-capture_cursor", "1");
            grabber.setPixelFormat(AV_PIX_FMT_YUYV422);
            System.out.println("Before");
            grabber.start();
            System.out.println("After");
`
In my console, "Before" is printing but not printing "After". Please Help

**Comment by saudet** [comment] 2022-03-01 10:45
You'll need to call start().

**Comment by sumit33** [comment] 2022-03-01 10:55
@saudet Thanks for your reply and sorry for the typing mistake..I actually called start()..

**Comment by saudet** [comment] 2022-03-01 11:04
According to the docs at https://trac.ffmpeg.org/wiki/Capture/Desktop something like this should work:
```java
  FrameGrabber grabber = new FFmpegFrameGrabber("1");
  grabber.setFormat("avfoundation");
  grabber.setFrameRate(30);
  grabber.start();
```

**Comment by saudet** [comment] 2022-03-07 05:09
Duplicate of #1756

**Closed by saudet** 2022-03-07 05:09 UTC
Labels: duplicate, question
