### ISSUE TITLE
Artifact in a video recorded with FFmpegFrameRecorder

### ISSUE THREAD

**Issue by shchurov** [bytedeco/javacv#218] opened 2015-09-03 19:02 UTC
Hello, I use FFmpegFrameRecorder and it works good except a small artifact on the videos. 
Check this test video (there's a strange line on the left): https://drive.google.com/file/d/0Bzb8d9xvN0SjMW1WRG8yd0FpOWs/view?usp=sharing

Looks like it takes a few pixel-rows from the bottom and put it on the top (the video is rotated). I observe the same issue in the RecordActivity from samples. I saved YUV420sp data from camera as .jpg and it looks just fine, so I think the problem is in FFmpegFrameRecorder. My phone is Oneplus One, here're my dependencies: 
```
compile group: 'org.bytedeco', name: 'javacv', version: '1.0'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.7.1-1.0', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.7.1-1.0', classifier: 'android-x86'
```

**Comment by bgiori** [comment] 2015-09-03 21:32
I have the same issue on a Nexus 7 tablet and a few other phones also. I'm streaming horizontally and on the left side there is a block of pixels taken from the right of the frame.
<img width="434" alt="screen shot 2015-09-03 at 2 31 48 pm" src="https://cloud.githubusercontent.com/assets/3282199/9671560/905449dc-5248-11e5-9daf-58db8707bfe4.png">

**Comment by saudet** [comment] 2015-09-04 05:47
I'm pretty sure this is a duplicate of #190. Let me know if the fix doesn't work, thanks!

**Closed by saudet** 2015-09-04 05:47 UTC
