### ISSUE TITLE
Create video with vertical and horizontal images.

### ISSUE THREAD

**Issue by mastep20** [bytedeco/javacv#296] opened 2016-01-04 23:45 UTC
I want to create video from vertical and horizontal images using javacv. In my FFmpegFrameRecorder I set width = 1280 and height = 720. The horizontal images display corectly in video but vertical images are automatically resized to FFmpegFrameRecorder definition. Is there any way to achieve the same effect with vertical images like in the picture below? 

![1](https://cloud.githubusercontent.com/assets/16455562/12103726/27cf964c-b345-11e5-9c95-24b0bade1cfd.jpg)

**Comment by saudet** [comment] 2016-01-11 03:50
Duplicate of https://github.com/bytedeco/javacv/issues/264

**Closed by saudet** 2016-01-11 03:50 UTC
Labels: duplicate, question
