### ISSUE TITLE
Getting below error with building bundle(s) with android studio

### ISSUE THREAD

**Issue by Midhun9638** [bytedeco/javacv#1239] opened 2019-06-27 15:22 UTC
com.android.tools.build.bundletool.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/lib/x86_64/include/opencv2/bioinspired.hpp' uses reserved file or directory name 'lib'.

**Comment by saudet** [comment] 2019-06-27 21:43
Duplicate of #1117

**Closed by saudet** 2019-06-27 21:43 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2019-11-12 07:34
FYI, you can exclude those files, they are not necessary at runtime.
