### ISSUE TITLE
How can i record a pcm mp4 on Android?

### ISSUE THREAD

**Issue by cuijianzhi** [bytedeco/javacv#637] opened 2017-03-08 09:38 UTC
I set the  audio params,it crashed when start record.
` library "/system/lib/libdl.so" ("/system/lib/libdl.so") needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.github.crazyorr.ffmpegrecorder-2/lib/arm:/data/app/com.github.crazyorr.ffmpegrecorder-2/base.apk!/lib/armeabi", permitted_paths="/data:/mnt/expand:/data/data/com.github.crazyorr.ffmpegrecorder"]`

here is my code

` mFrameRecorder = new FFmpegFrameRecorder(mVideo, videoWidth, videoHeight, 1);
        mFrameRecorder.setFormat("mp4");
        mFrameRecorder.setSampleRate(sampleAudioRateInHz);
        mFrameRecorder.setFrameRate(frameRate);
        // Use H264
        mFrameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
        mFrameRecorder.setAudioCodec(avcodec.AV_CODEC_ID_PCM_S16LE);
`

**Comment by saudet** [comment] 2017-03-08 10:57
Duplicate of bytedeco/javacv#617

Use JavaCPP 1.3.2-SNAPSHOT

**Closed by saudet** 2017-03-08 10:57 UTC
Labels: bug, duplicate

**Comment by cuijianzhi** [comment] 2017-03-09 06:35
what should i do if i want to record a pcm video (video format is mp4 and audio format is pcm without encode)?

**Comment by saudet** [comment] 2017-03-09 06:42
`AV_CODEC_ID_PCM_S16LE` is fine, what is the issue?
