### ISSUE TITLE
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.

### ISSUE THREAD

**Issue by kongqw** [bytedeco/javacv#634] opened 2017-03-03 06:54 UTC
``` log
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/libopencv_videostab.so
  	File1: /Users/kongqingwei/.gradle/caches/modules-2/files-2.1/org.bytedeco.javacpp-presets/opencv/3.1.0-1.3/848d352b867bf2c6d94c482ab694c504eaeef9d9/opencv-3.1.0-1.3-android-x86.jar
  	File2: /Users/kongqingwei/Workspace/GitHubProjects/KqwFaceDetectionDemo/openCVLibrary2411/build/intermediates/bundles/default/jni
```

**Comment by saudet** [comment] 2017-03-03 07:11
Duplicate of https://github.com/bytedeco/javacv/issues/353

**Closed by saudet** 2017-03-03 07:11 UTC
Labels: duplicate

**Comment by kongqw** [comment] 2017-03-03 07:36
@saudet I do it, gradle version 2.2.3 is no problem，but 2.3.0 is not,this log show in 2.3.0

**Comment by saudet** [comment] 2017-03-03 07:44
Ok, so please post your log in the thread for issue #353 with the rest, thank you!
