### ISSUE TITLE
rtmp broadcasting huge delay

### ISSUE THREAD

**Issue by ywj7931** [bytedeco/javacv#456] opened 2016-07-11 18:38 UTC
Now I normally have around 20s delay,
Is there any way to decrease rtmp stream? 
video bit rate?encode format?
It should not be the problem of Internet.
Anyone has an idea?

**Comment by ywj7931** [comment] 2016-07-11 20:47
I searched it seemed FFmpeg does not use of any 
hardware acceleration... 

Is there any way to use hardware acceleration?

**Comment by saudet** [comment] 2016-07-14 13:57
Duplicate of https://github.com/bytedeco/javacv/issues/55: FFmpeg doesn't support hardware acceleration. You'll need to use Android's API to get that.

**Closed by saudet** 2016-07-14 13:57 UTC
Labels: duplicate, question

**Comment by y4nnick** [comment] 2016-08-30 21:16
@ywj7931 Could you please share your code with me, i am currently struggling with streaming to facebook, (see https://github.com/bytedeco/javacv/issues/491)
