### ISSUE TITLE
Execution failed for task ':app:mergeDebugJavaResource'. when try to import javacv to android studio project on M1 Pro

### ISSUE THREAD

**Issue by chenzx** [bytedeco/javacv#1997] opened 2023-03-22 07:25 UTC
```
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 14 files found with path 'META-INF/native-image/linux-x86_64/jnijavacpp/jni-config.json' from inputs:
      - /Users/czx/.gradle/caches/transforms-3/04a7296607ef8a9f59307fff62cb775d/transformed/jetified-flandmark-1.07-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/7a1e2181b3f8c1efc8b5cc9f3c8440aa/transformed/jetified-opencv-4.6.0-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/103fa53c89a9708b4dc061aab462efb6/transformed/jetified-openblas-0.3.21-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/871b3b2a0b4c6a93149106b0597f6d55/transformed/jetified-ffmpeg-5.1.2-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/c707ae39284367ce6293ffac064f3ec7/transformed/jetified-flycapture-2.13.3.31-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/2d66a7a0cec4214ef94dada95a5428fd/transformed/jetified-libdc1394-2.2.6-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/1b27779552dc2afba3d548b00390186f/transformed/jetified-libfreenect-0.5.7-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/b171a4e44dd3d15ba1c30c452194bc41/transformed/jetified-libfreenect2-0.2.0-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/d06224a573f3baab3478724ec9666fc0/transformed/jetified-librealsense-1.12.4-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/7a35f7175f08748379168110aa71fc73/transformed/jetified-librealsense2-2.50.0-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/979982fcc6af642f2c8c3d5cf0336549/transformed/jetified-artoolkitplus-2.3.1-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/49e4d512a1fc43ad337a5ca33e05c35f/transformed/jetified-tesseract-5.2.0-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/401ff3ed9324a07f8716247a5848db80/transformed/jetified-leptonica-1.82.0-1.5.8-linux-x86_64.jar
      - /Users/czx/.gradle/caches/transforms-3/25c0d330f5bb85170cf25a4717d9b032/transformed/jetified-javacpp-1.5.8-linux-x86_64.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.4/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information
```

I see adding `implementation group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.8'` to build.gradle imports a lot of jars(but the ios and 3 desktop's prebuilt version should not be needed)

**Comment by chenzx** [comment] 2023-03-22 08:20
I see https://github.com/bytedeco/javacv/issues/1514
But the built debug apk is 1.2G, too large
I only need `FFmpegFrameGrabber.grabPacket` api for testing...

**Comment by saudet** [comment] 2023-03-22 08:55
Please try to use a javacppExtract task as shown here:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by saudet** [comment] 2023-03-24 10:59
Duplicate of #1117

**Closed by saudet** 2023-03-24 10:59 UTC
Labels: duplicate, question
