### ISSUE TITLE
UnsatisfiedLinkError on 1.5.4 version

### ISSUE THREAD

**Issue by Alesh17** [bytedeco/javacv#1527] opened 2020-10-16 08:47 UTC
Hi! When i use this versions - all good:

`implementation 'org.bytedeco:javacv:1.4.4'`
`implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm64'`
`implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm'`
`implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-x86'`

But in case with newer versions:

`implementation 'org.bytedeco:javacv:1.5.4'`
`implementation group: 'org.bytedeco', name: 'opencv', version: '4.4.0-1.5.4', classifier: "android-arm64"`
`implementation group: 'org.bytedeco', name: 'opencv', version: '4.4.0-1.5.4', classifier: "android-arm"`
`implementation group: 'org.bytedeco', name: 'opencv', version: '4.4.0-1.5.4', classifier: "android-x86"`

I have two UnsatisfiedLinkError:

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.alesh.imagestitcher-rd0olw6Rhakf-8KhnlR2-A==/base.apk"],nativeLibraryDirectories=[/data/app/com.alesh.imagestitcher-rd0olw6Rhakf-8KhnlR2-A==/lib/arm64, /data/app/com.alesh.imagestitcher-rd0olw6Rhakf-8KhnlR2-A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libjniopenblas_nolapack.so"`

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.alesh.imagestitcher-rd0olw6Rhakf-8KhnlR2-A==/base.apk"],nativeLibraryDirectories=[/data/app/com.alesh.imagestitcher-rd0olw6Rhakf-8KhnlR2-A==/lib/arm64, /data/app/com.alesh.imagestitcher-rd0olw6Rhakf-8KhnlR2-A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libopenblas.so"`

On this line:

`val images = MatVector(10L)`

Thanks in advance for any advice!

**Comment by saudet** [comment] 2020-10-16 08:50
You'll need to add OpenBLAS as well, see issue
#1329.

**Comment by saudet** [comment] 2020-10-16 08:51
Duplicate of #1329.

**Closed by saudet** 2020-10-16 08:51 UTC
Labels: duplicate, question

**Comment by IroMp** [comment] 2021-07-08 14:44
Despite having openblas.jar of javacv into the libs of my Android app, I encountered the same error ("...couldn't find "libjniopenblas_nolapack.so") while trying to extract frames from video with ffmpeg and convert in into Mat. 

This is my solution:

Get "libjniopenblas_nolapack.so" library from the "openblas-android-arm.jar" file. Open the JAR file with WinRAR and extract it straight into "app/src/(main)/jniLibs/armeabi" folder.

**Comment by saudet** [comment] 2022-12-07 10:46
Either from Maven or the archives here: https://github.com/bytedeco/javacv/releases
