### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1370] opened 2020-01-19 02:23 UTC
Fatal Exception: java.lang.UnsatisfiedLinkError

dlopen failed: cannot locate symbol "getpagesize" referenced by "libjniopencv_core.so"

Hi may i know why i got this error on Android 4.4? Any suggestion?

**Comment by saudet** [comment] 2020-01-19 02:51
The distributed binaries are for Android 5.0+.

**Comment by xiaos** [comment] 2020-01-19 10:11
how do i know the distributed binaries are for which Android version?

**Comment by saudet** [comment] 2020-01-19 10:36
It written in the README.md file here:
https://github.com/bytedeco/javacpp-presets/#manual-installation

**Comment by xiaos** [comment] 2020-01-19 10:43
Thanks!

**Comment by saudet** [comment] 2020-01-21 01:56
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/562

**Closed** 2020-01-21 01:56 UTC
Labels: duplicate, enhancement
