### ISSUE TITLE
[Question] ffmpeg MediaCodec hardware acceleration for Android

### ISSUE THREAD

**Issue by hnvn** [bytedeco/javacv#690] opened 2017-05-05 11:36 UTC
After I managed to use ffmpeg in javacv to compress video data in h264, I tried to look for a similar solution for iOS. 
At the glance, I tried to use ffmpeg in iOS too, but some experienced coders tell me that is not the best way to go, instead of that, use standard API in iOS SDK. Try to google, I ended up with this [article](http://blog.denivip.ru/index.php/2013/10/how-to-live-stream-video-as-you-shoot-it-in-ios/?lang=en). It showed me a comparison between two approaches, using ffmpeg and using standard API. The second approach is much faster and cheaper in consuming CPU. The reason is the standard API uses hardware acceleration to compress video data in h264. And I wonder how to use hardware acceleration in Android too? 
It seems ffmpeg also supports this technology ([document](https://trac.ffmpeg.org/wiki/HWAccelIntro)). But It's too much information for me to understand how to do that. Some experienced guys in ffmpeg can give some advice?

**Comment by saudet** [comment] 2017-05-05 11:50
Yes, we have to do the same thing on Android. FFmpeg doesn't support
arbitrary hardware on Android devices.

**Comment by saudet** [comment] 2017-05-05 13:45
Marking as duplicate of bytedeco/javacpp-presets#389

**Closed by saudet** 2017-05-05 13:45 UTC
Labels: question
