### ISSUE TITLE
FFmpegFrameGrabber works great at 640x480@60 fps but the framerate is decreased to 18 fps at 1920x1080@30 fps

### ISSUE THREAD

**Issue by rgm-22** [bytedeco/javacv#1701] opened 2021-09-27 23:16 UTC
Hi @saudet!

Thank you very much for your awesome support! 😀

I am having this issue with JavaCV 1.5.4.

I can record perfectly with my camera at 640x480 @ 60 fps. 
But when I set 1280x720 (HD) @ 60 fps and 1920x1080 (FullHD) @ 30 fps the preview is slowed down and the resulting recording video is 1280x720 (HD) @ 40 fps and 1920x1080 (FullHD) @ 18 fps.

My configuration:
ffmpeg_Frame_Recorder = new FFmpegFrameRecorder(videoPath, 1920, 1080, 2);

/// Video
ffmpeg_Frame_Recorder.setFormat("mp4");
ffmpeg_Frame_Recorder.setFrameRate(30);
ffmpeg_Frame_Recorder.setPixelFormat(0);
ffmpeg_Frame_Recorder.setVideoBitrate(10000000);
ffmpeg_Frame_Recorder.setVideoQuality(0);

/// Audio
ffmpeg_Frame_Recorder.setAudioBitrate(194000);
ffmpeg_Frame_Recorder.setSampleRate(48000);
mAudioRecordRunnable = new AudioRecordRunnable();

I am using OpenCV and 

ffmpeg_Frame_Recorder.record(new OpenCVFrameConverter.ToOrgOpenCvCoreMat().convert(mat));

Any help is really appreciated!

**Comment by saudet** [comment] 2021-09-27 23:31
Please try to use hardware acceleration...

**Comment by rgm-22** [comment] 2021-09-28 10:24
Thank you for your answer!

Do you know if it is possible on Android? I have checked out that you mentioned this in another issue:

"You'll probably need hardware acceleration to encode at any kind of speed though. Unfortunately, FFmpeg doesn't support hardware acceleration for encoding on Android: https://trac.ffmpeg.org/wiki/HWAccelIntro (Unless this has changed recently @tmm1?)"

Thank you again!

**Comment by saudet** [comment] 2021-09-28 10:47
Nope, not available on Android. You'll need to use the MediaCodec API for that

**Comment by saudet** [comment] 2021-09-28 10:47
Duplicate of #1693.

**Closed by saudet** 2021-09-28 10:47 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2023-03-03 11:56
FFmpeg 6.0 now includes support for hardware accelerated encoding using MediaCodec.
Please give it a try with the snapshots: http://bytedeco.org/builds/
