### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by beckondelve1** [bytedeco/javacv#228] opened 2015-09-21 14:31 UTC
hi Saudet, i'm facing same problem, 
That many people got, but didn't able to success

I have updated both file javacv and javacpp from download from github, full zip 135 mb.
I just copy "RecordActivity" to our example and try to use things but everything same issue reported.. App crash when i start recording.
Showing me this logcat
I'm using eclipse 
```
09-21 19:15:49.676: E/dalvikvm(25769): Could not find class 'org.bytedeco.javacpp.avcodec$AVPacket', referenced from method org.bytedeco.javacv.FFmpegFrameRecorder.
09-21 19:15:49.676: E/dalvikvm(25769): Could not find class 'org.bytedeco.javacpp.avutil', referenced from method org.bytedeco.javacv.FFmpegFrameRecorder.tryLoad
09-21 19:15:49.681: E/dalvikvm(25769): Could not find class 'org.bytedeco.javacpp.avcodec', referenced from method org.bytedeco.javacv.FFmpegFrameRecorder.release
09-21 19:15:49.691: E/dalvikvm(25769): Could not find class 'org.bytedeco.javacpp.avcodec', referenced from method org.bytedeco.javacv.FFmpegFrameRecorder.start
09-21 19:15:49.706: E/AndroidRuntime(25769): FATAL EXCEPTION: main
09-21 19:15:49.706: E/AndroidRuntime(25769): Process: com.example.testswitchcam, PID: 25769
09-21 19:15:49.706: E/AndroidRuntime(25769): java.lang.NoClassDefFoundError: org.bytedeco.javacpp.avcodec$AVPacket
09-21 19:15:49.706: E/AndroidRuntime(25769): at org.bytedeco.javacv.FFmpegFrameRecorder.(FFmpegFrameRecorder.java:149)
09-21 19:15:49.706: E/AndroidRuntime(25769): at com.example.testswitchcam.RecordActivity.initRecorder(RecordActivity.java:277)
09-21 19:15:49.706: E/AndroidRuntime(25769): at com.example.testswitchcam.RecordActivity.startRecording(RecordActivity.java:292)
09-21 19:15:49.706: E/AndroidRuntime(25769): at com.example.testswitchcam.RecordActivity.onClick(RecordActivity.java:584)
09-21 19:15:49.706: E/AndroidRuntime(25769): at android.view.View.performClick(View.java:4654)
09-21 19:15:49.706: E/AndroidRuntime(25769): at android.view.View$PerformClick.run(View.java:19438)
09-21 19:15:49.706: E/AndroidRuntime(25769): at android.os.Handler.handleCallback(Handler.java:733)
09-21 19:15:49.706: E/AndroidRuntime(25769): at android.os.Handler.dispatchMessage(Handler.java:95)
09-21 19:15:49.706: E/AndroidRuntime(25769): at android.os.Looper.loop(Looper.java:146)
09-21 19:15:49.706: E/AndroidRuntime(25769): at android.app.ActivityThread.main(ActivityThread.java:5602)
09-21 19:15:49.706: E/AndroidRuntime(25769): at java.lang.reflect.Method.invokeNative(Native Method)
09-21 19:15:49.706: E/AndroidRuntime(25769): at java.lang.reflect.Method.invoke(Method.java:515)
09-21 19:15:49.706: E/AndroidRuntime(25769): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
09-21 19:15:49.706: E/AndroidRuntime(25769): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
09-21 19:15:49.706: E/AndroidRuntime(25769): at dalvik.system.NativeStart.main(Native Method)
```

**Comment by saudet** [comment] 2015-09-22 03:13
Did you make sure ProGuard isn't removing those classes?

**Comment by saudet** [comment] 2015-09-22 09:42
Marking as duplicate of #79.

**Closed by saudet** 2015-09-22 09:42 UTC
Labels: duplicate
