### ISSUE TITLE
no such file: /libpostproc.57.dylib

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2151] opened 2023-12-21 07:54 UTC
I tried the solution in #2039, but when I use the following dependent libraries:
```
       <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>6.0-1.5.10-SNAPSHOT</version>
        </dependency>
       <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>6.0-1.5.9</version>
        </dependency>
```
 I still get an error message as like：
dyld[1176]: Library not loaded: @rpath/libpostproc.57.dylib
  Referenced from: /Users/admin/.javacpp/cache/ffmpeg-6.0-1.5.9-macosx-x86_64-gpl.jar/org/bytedeco/ffmpeg/macosx-x86_64-gpl/ffmpeg
  Reason: tried: '/Users/admin/.javacpp/cache/ffmpeg-6.0-1.5.9-macosx-x86_64-gpl.jar/org/bytedeco/ffmpeg/macosx-x86_64-gpl/libpostproc.57.dylib' (no such file), '/Users/admin/.javacpp/cache/ffmpeg-6.0-1.5.9-macosx-x86_64-gpl.jar/org/bytedeco/ffmpeg/macosx-x86_64-gpl/libpostproc.57.dylib' (no such file), '/usr/local/lib/libpostproc.57.dylib' (no such file), '/usr/lib/libpostproc.57.dylib' (no such file)

Is there any problem with the dependent maven package version?

**Comment by DearTan** [comment] 2023-12-21 09:26
When introducing dependency packages, an error is always reported: org.bytedeco:ffmpeg:linux-x86_64-gpl:6.0-1.5.10--SNAPSHOT. This dependent library can't download.
`
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>6.1-1.5.10-SNAPSHOT</version>
        </dependency>
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>6.0-1.5.10-SNAPSHOT</version>
        </dependency>
<repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
    </pluginRepositories>`

**Comment by saudet** [comment] 2023-12-21 11:58
Please try again with 6.1-1.5.10-SNAPSHOT

**Comment by saudet** [comment] 2023-12-21 11:59
Duplicate of #2039

**Closed by saudet** 2023-12-21 11:59 UTC
Labels: bug, duplicate

**Comment by DearTan** [comment] 2023-12-22 02:01
> Please try again with 6.1-1.5.10-SNAPSHOT

Thanks!
