### ISSUE TITLE
[swscaler @ 0x7fcf4844ee40] deprecated pixel format used, make sure you did set range correctly

### ISSUE THREAD

**Issue by YukiDmZhao** [bytedeco/javacv#1283] opened 2019-08-28 06:46 UTC
The problem has never been solved.
Try to set 
grabber.setPixelFormat(avutil.AV_PIX_FMT_YUVJ420P);

try to set avutil.

**Comment by saudet** [comment] 2019-08-28 06:51
No, it hasn't been solved yet, but contributions are welcome. See issue #780.

**Comment by saudet** [comment] 2019-08-28 06:51
Duplicate of #780

**Closed by saudet** 2019-08-28 06:51 UTC
Labels: bug, duplicate
