### ISSUE TITLE
JDK17 / javacv:1.5.9, an error occurred while executing image synthesis video. The operating system is normal on Windows, but an error occurs on Linux

### ISSUE THREAD

**Issue by zhushizhan** [bytedeco/javacv#2273] opened 2024-08-14 06:13 UTC
*** Error in `./zulu17.52.17-ca-jdk17.0.12-linux_x64/bin/java': free(): invalid pointer: 0x00007f06d47f7c80 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f0834499329]
/lib64/libstdc++.so.6(_ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE+0x142)[0x7f06d4561192]
/lib64/libstdc++.so.6(_ZNSt6locale5_ImplC1Em+0x1e3)[0x7f06d45615e3]
/lib64/libstdc++.so.6(+0x71555)[0x7f06d4562555]
/lib64/libpthread.so.0(+0x620b)[0x7f08349f020b]
/lib64/libstdc++.so.6(+0x715a1)[0x7f06d45625a1]
/lib64/libstdc++.so.6(_ZNSt6localeC2Ev+0x13)[0x7f06d45625e3]
/lib64/libstdc++.so.6(_ZNSt8ios_base4InitC2Ev+0xbc)[0x7f06d455f43c]
/root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.60(+0xd7a00)[0x7f06bf6f6a00]
/lib64/ld-linux-x86-64.so.2(+0xf9c3)[0x7f0834e2b9c3]
/lib64/ld-linux-x86-64.so.2(+0x1459e)[0x7f0834e3059e]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x7f0834e2b7d4]
/lib64/ld-linux-x86-64.so.2(+0x13b8b)[0x7f0834e2fb8b]
/lib64/libdl.so.2(+0xfab)[0x7f08347e6fab]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x7f0834e2b7d4]
/lib64/libdl.so.2(+0x15ad)[0x7f08347e75ad]
/lib64/libdl.so.2(dlopen+0x31)[0x7f08347e7041]
/root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/lib/server/libjvm.so(+0xbe2794)[0x7f0833c98794]
/root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/lib/server/libjvm.so(+0xbe28c2)[0x7f0833c988c2]
/root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/lib/server/libjvm.so(JVM_LoadLibrary+0xd0)[0x7f0833998030]
/root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/lib/libjava.so(Java_jdk_internal_loader_NativeLibraries_load+0x1df)[0x7f0834edc1cf]
[0x7f081c7fa5ba]
======= Memory map: ========
85a00000-8ba00000 rw-p 00000000 00:00 0 
8ba00000-8f400000 ---p 00000000 00:00 0 
8f400000-8f600000 rw-p 00000000 00:00 0 
8f600000-ffd00000 ---p 00000000 00:00 0 
ffd00000-ffe00000 rw-p 00000000 00:00 0 
ffe00000-ffe77000 rw-p 00ca9000 fd:00 104788630                          /root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/lib/server/classes.jsa
ffe77000-fff00000 rw-p 00000000 00:00 0 
fff00000-fff77000 rw-p 00c32000 fd:00 104788630                          /root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/lib/server/classes.jsa
fff77000-100000000 rw-p 00000000 00:00 0 
5642f7f3b000-5642f7f3c000 r-xp 00000000 fd:00 104788579                  /root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/bin/java
5642f7f3d000-5642f7f3e000 r--p 00001000 fd:00 104788579                  /root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/bin/java
5642f7f3e000-5642f7f3f000 rw-p 00002000 fd:00 104788579                  /root/java/jdk/zulu17.52.17-ca-jdk17.0.12-linux_x64/bin/java
5642f80c8000-5642f810f000 rw-p 00000000 00:00 0                          [heap]
7f0698000000-7f0698927000 rw-p 00000000 00:00 0 
7f0698927000-7f069c000000 ---p 00000000 00:00 0 
7f069c000000-7f069c9be000 rw-p 00000000 00:00 0 
7f069c9be000-7f06a0000000 ---p 00000000 00:00 0 
7f06a0000000-7f06a0c37000 rw-p 00000000 00:00 0 
7f06a0c37000-7f06a4000000 ---p 00000000 00:00 0 
7f06a4000000-7f06a458a000 rw-p 00000000 00:00 0 
7f06a458a000-7f06a8000000 ---p 00000000 00:00 0 
7f06a8000000-7f06a8021000 rw-p 00000000 00:00 0 
7f06a8021000-7f06ac000000 ---p 00000000 00:00 0 
7f06ac000000-7f06ac0b6000 rw-p 00000000 00:00 0 
7f06ac0b6000-7f06b0000000 ---p 00000000 00:00 0 
7f06b0000000-7f06b0021000 rw-p 00000000 00:00 0 
7f06b0021000-7f06b4000000 ---p 00000000 00:00 0 
7f06b4000000-7f06b4021000 rw-p 00000000 00:00 0 
7f06b4021000-7f06b8000000 ---p 00000000 00:00 0 
7f06b8000000-7f06b8021000 rw-p 00000000 00:00 0 
7f06b8021000-7f06bc000000 ---p 00000000 00:00 0 
7f06bf61f000-7f06bf6de000 r--p 00000000 fd:00 2703224                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.60
7f06bf6de000-7f06bfd97000 r-xp 000bf000 fd:00 2703224                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.60
7f06bfd97000-7f06bff59000 r--p 00778000 fd:00 2703224                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.60
7f06bff59000-7f06bffee000 r--p 00939000 fd:00 2703224                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.60
7f06bffee000-7f06bfff7000 rw-p 009ce000 fd:00 2703224                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.60
7f06bfff7000-7f06c0000000 rw-p 00000000 00:00 0 
7f06c0000000-7f06c0021000 rw-p 00000000 00:00 0 
7f06c0021000-7f06c4000000 ---p 00000000 00:00 0 
7f06c4000000-7f06c4021000 rw-p 00000000 00:00 0 
7f06c4021000-7f06c8000000 ---p 00000000 00:00 0 
7f06c8000000-7f06c8021000 rw-p 00000000 00:00 0 
7f06c8021000-7f06cc000000 ---p 00000000 00:00 0 
7f06cc331000-7f06cc3de000 r--p 00000000 fd:00 2703221                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.60
7f06cc3de000-7f06cdc9d000 r-xp 000ad000 fd:00 2703221                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.60
7f06cdc9d000-7f06ce275000 r--p 0196c000 fd:00 2703221                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.60
7f06ce275000-7f06ce276000 ---p 01f44000 fd:00 2703221                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.60
7f06ce276000-7f06ce304000 r--p 01f44000 fd:00 2703221                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.60
7f06ce304000-7f06ce31b000 rw-p 01fd2000 fd:00 2703221                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.60
7f06ce31b000-7f06cecc3000 rw-p 00000000 00:00 0 
7f06cecc3000-7f06ced1f000 r--p 00000000 fd:00 2703217                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
7f06ced1f000-7f06ceda5000 r-xp 0005c000 fd:00 2703217                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
7f06ceda5000-7f06cede1000 r--p 000e2000 fd:00 2703217                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
7f06cede1000-7f06cedee000 r--p 0011d000 fd:00 2703217                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
7f06cedee000-7f06cedf0000 rw-p 0012a000 fd:00 2703217                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
7f06cedf0000-7f06cedf1000 rw-p 00000000 00:00 0 
7f06cedf1000-7f06cee08000 r--p 00000000 fd:00 2703215                    /root/.javacpp/cache/ffmpeg-6.0-1.5.9-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.58Aborted

        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp-platform</artifactId>
            <version>1.5.9</version>
        </dependency>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.9</version>
        </dependency>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>6.0-1.5.9</version>
        </dependency>

**Comment by saudet** [comment] 2024-08-14 12:25
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-08-14 12:25 UTC
Labels: duplicate, question
