### ISSUE TITLE
PointerScope not work

### ISSUE THREAD

**Issue by lixiangflyin** [bytedeco/javacv#1425] opened 2020-05-11 02:57 UTC
I use javacv to sement audio and operation with muti thread.
Offen OOM. AND use pointerScope, but still OOM.

    try (PointerScope scope = new PointerScope()) {
        FFmpegLogCallback.set();
        CustomFFmpegFrameGrabber customFFmpegFrameGrabber = new 
       CustomFFmpegFrameGrabber(rtmpUrl, 3));
        customFFmpegFrameGrabber.getFFmpegFrameGrabber().subscribeBlockCallBack(this::onTaskInterrupt);
        ByteArrayOutputStream outputStream = null;
        CustomFFmpegFrameRecorder recorder = null;
        try {
            if (!canConnected(customFFmpegFrameGrabber)) {
                return;
            }

            outputStream = new ByteArrayOutputStream();
            recorder = getFrameRecorder(outputStream, customFFmpegFrameGrabber.getFFmpegFrameGrabber());
            recorder.startUnsafe(customFFmpegFrameGrabber.getFFmpegFrameGrabber().getFormatContext());
           

           while (true) {
              AVPacket frame = customFFmpegFrameGrabber.getFFmpegFrameGrabber().grabPacket();
              //if null and continue
              if (frame == null) {
                break;
              }

            recorder.recordPacket(frame);

            ThreadUtils.sleep(0);
        }

        } catch (FrameGrabber.Exception e) {
            
        } catch (PgFFmpegFrameRecorder.Exception e) {
            log.error("recorder exception ", e);
        } catch (Exception e) {
            log.error("other error ", e);
        } finally {
            //close recorder
            if (recorder != null) {
                stopRecord(recorder);
            }
            //close grabber
            if (customFFmpegFrameGrabber.getFFmpegFrameGrabber() != null) {
                try {
                    customFFmpegFrameGrabber.getFFmpegFrameGrabber().releaseUnsafe();
                } catch (FrameGrabber.Exception e) {
                    log.error("grabber shutdown error ", e);
                }
            }
            if (outputStream != null) {
                try {
                    outputStream.close();
                } catch (Exception e) {
                    log.error("output stream close error", e);
                }
            }
        }
}

**Comment by saudet** [comment] 2020-05-11 04:41
`FFmpegFrameGrabber` and `FFmpegFrameRecorder` are not thread safe. Do not try to use them from multiple threads.

**Comment by lixiangflyin** [comment] 2020-05-11 06:38
but I must operation many streams at the same time.

If i use thread-safe, programs will block.

**Comment by saudet** [comment] 2020-05-11 06:43
Ok, but please reproduce the issue with a single stream.

**Comment by lixiangflyin** [comment] 2020-05-11 06:50
Can you detail? Share your idea? I have not understand.

**Comment by saudet** [comment] 2020-05-11 08:01
If it doesn't happen with a single stream, then the problem is with your threads. So, please make sure your issue happens with a single stream.

**Comment by lixiangflyin** [comment] 2020-05-11 09:21
ok, I try

**Comment by saudet** [comment] 2020-06-12 07:43
I've added `synchronized` and `PointerScope` to the methods of FFmpegFrameGrabber and FFmpegFrameRecorder in commits https://github.com/bytedeco/javacv/commit/cbe7ccda1db5a432c4d481a007acddefdad79d2f and https://github.com/bytedeco/javacv/commit/28b90ef25cc54d4deeba89f078270793abdd525f. That should solve the problems you're having so please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2020-06-12 07:45
Duplicate of #1434

**Comment by saudet** [comment] 2020-06-12 07:45
Duplicate of #1383

**Closed by saudet** 2020-06-12 07:45 UTC
Labels: duplicate, enhancement
