### ISSUE TITLE
How to use the img_hash module with JavaCV

### ISSUE THREAD

**Issue by anatolyra** [bytedeco/javacv#933] opened 2018-03-07 10:28 UTC
I'm trying to generate a phash for an image. Unless I'm missing something, the img_hash module is not integrated into the JavaCV lib. Is there a way of doing that? 

Thanks!

**Comment by saudet** [comment] 2018-03-08 05:33
Marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/319

Contributions welcome!

**Closed by saudet** 2018-03-08 05:33 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2018-03-10 15:25
I've just added it in commit https://github.com/bytedeco/javacpp-presets/commit/fdc7008402da3a985cad23993986fd17fc0370dd
Please try it out with the snapshots: http://bytedeco.org/builds/

**Comment by anatolyra** [comment] 2018-03-14 14:15
Works great, thank you!

When is it going to be released?

**Comment by saudet** [comment] 2018-03-14 14:30
Probably before long, but binaries are already available as snapshots, so
please try them out!

**Comment by anatolyra** [comment] 2018-03-20 12:16
Having issues with the snapshot repo (it seems to be flakey). Is there an ETA on the release?

**Comment by saudet** [comment] 2018-03-20 13:11
Did something break with the latest binaries?

**Comment by anatolyra** [comment] 2018-03-20 14:16
No. But there are issues with availability when maven tries to download the
jar from the snapshot repo.

**Comment by saudet** [comment] 2018-03-31 05:42
Released! Enjoy

**Comment by anatolyra** [comment] 2018-04-03 13:57
Hey,

It seems I'm getting this error now: 
java.lang.OutOfMemoryError: Cannot allocate new BytePointer(62063): totalBytes = 16, physicalBytes = 1G(Cannot allocate new BytePointer(62063): totalBytes = 16, physicalBytes = 1G)
  at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:106)
  at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:71)

Caused by:java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 1G > maxPhysicalBytes = 989M(Physical memory usage is too high: physicalBytes = 1G > maxPhysicalBytes = 989M)
  at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:576)
  at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
  at org.bytedeco.javacpp.BytePointer.allocateArray(BytePointer.java:-2)
  at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:98)

I'm not sure if I got that with the snapshot. Are you familiar with this type of error?

**Comment by anatolyra** [comment] 2018-04-03 15:37
Yes, but by how much? I'm handling up to 50 images concurrently. And have
seen this error for small images. Is 1G of memory allocated for each and
every image?

**Comment by saudet** [comment] 2018-04-03 21:41
As much as it needs, probably not 1 GB per image.
