### ISSUE TITLE
Port ffmpeg cmd utility to java as well

### ISSUE THREAD

**Issue by RobertoUa** [bytedeco/javacv#1073] opened 2018-10-24 07:51 UTC
`FFmpegFrameGrabber` and `FFmpegFrameRecorder` duplicates some functionality that's already implemented in ffmpeg. That's okay but I would love to be able to also pass ffmpeg cli arguments to javacv. For example `java -jar ffmpeg.jar -i input.mp4 output.avi`

**Comment by saudet** [comment] 2019-03-24 00:56
Done! See commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134. It now gets bundled and can be used easily from Java. Please give it a try with 1.5-SNAPSHOT before the release: http://bytedeco.org/builds/

**Comment by RobertoUa** [comment] 2019-03-25 10:25
awesome!
but I get 
```Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1077)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1006)
	at org.bytedeco.javacpp.Loader.load(Loader.java:963)
```

**Comment by saudet** [comment] 2019-03-25 10:39
Make sure to have a dependency on ffmpeg-platform.

**Comment by RobertoUa** [comment] 2019-03-25 10:54
I have a dependency on `ffmpeg` but with a `classifier` for macos (I want a smaller .jar). Is `ffmpeg` of `4.1.1-1.5-SNAPSHOT` available?

**Comment by saudet** [comment] 2019-03-25 11:20
Sure, I tested it on Mac and it works just fine.

**Comment by saudet** [comment] 2019-03-26 03:18
It's however been updated to 4.1.2, so make sure to use that version.

**Comment by RobertoUa** [comment] 2019-03-26 07:52
it's not here :(
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg-platform/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/

**Comment by saudet** [comment] 2019-03-26 08:37
The group name got shorten:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/ffmpeg/

**Comment by RobertoUa** [comment] 2019-03-26 15:28
Great! it works on mac but it doesn't on linux
```
[16:29:31][Step 3/5] Caused by: java.lang.UnsatisfiedLinkError: /user/.javacpp/cache/ffmpeg-4.1.2-1.5-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavdevice.so: libxcb-shape.so.0: cannot open shared object file: No such file or directory
[16:29:31][Step 3/5] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[16:29:31][Step 3/5] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
[16:29:31][Step 3/5] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[16:29:31][Step 3/5] 	at java.lang.Runtime.load0(Runtime.java:809)
[16:29:31][Step 3/5] 	at java.lang.System.load(System.java:1086)
[16:29:31][Step 3/5] 	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1316)
[16:29:31][Step 3/5] 	... 33 common frames omitted
```

**Comment by saudet** [comment] 2019-03-26 22:50
Install libxcb, it's pretty much standard these days.

**Comment by RobertoUa** [comment] 2019-03-27 06:30
I haven't checked yet, but I wonder whether AWS Lambda has it installed. But using binary ffmpeg works on lambda https://johnvansickle.com/ffmpeg/

**Comment by saudet** [comment] 2019-03-27 06:49
Sure, it's possible to build FFmpeg without support for libxcb.

**Comment by saudet** [comment] 2019-04-11 07:20
The ffmpeg program is now being bundled starting with JavaCV 1.5. Enjoy!

As for providing headless builds, I'll mark this as a duplicate of issue https://github.com/bytedeco/javacpp-presets/issues/593. Contributions welcome!

**Closed by saudet** 2019-04-11 07:20 UTC
Labels: duplicate, enhancement
