### ISSUE TITLE
Android - wrong bitmap when converting bitmap to Mat 

### ISSUE THREAD

**Issue by webtjw** [bytedeco/javacv#1158] opened 2019-03-18 11:03 UTC
Hi,
I need help urgently！

When I converted some bitmaps to Mat object, some of the images were distorted.

```
private AndroidFrameConverter converterToBitmap = new AndroidFrameConverter();
private OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();

Frame frame = converterToBitmap.convert(bitmap);
Mat rgbaMat = converterToMat.convert(frame);
Mat greyMat = new Mat(rgbaMat.rows(), rgbaMat.cols());
cvtColor(rgbaMat, greyMat, CV_BGR2GRAY);
imwrite("/storage/emulated/0/cache_hsx/rgb_" + i + ".jpg", rgbaMat);
imwrite("/storage/emulated/0/cache_hsx/grey_" + i + ".jpg", greyMat);
```

convert before:
![hello](https://user-images.githubusercontent.com/12931038/54525909-2bd59480-49b0-11e9-9c68-bff5c87b9924.jpg)

convert after:
![grey_4](https://user-images.githubusercontent.com/12931038/54525918-36902980-49b0-11e9-9f92-b98833576031.jpg)

Do you know what the cause of the problem is?
Thanks!

**Comment by saudet** [comment] 2019-03-18 11:12
Duplicate of #1143

Please give it a try with the snapshots:
http://bytedeco.org/builds/

**Closed by saudet** 2019-03-18 11:12 UTC
