### ISSUE TITLE
Issue with setting up ffmpeg- DuplicateFileException

### ISSUE THREAD

**Issue by manav95** [bytedeco/javacv#602] opened 2017-01-15 05:30 UTC
I am trying to setup ffmpeg via Javacv for an Android app, but when I try to build the APK: I get the following error:
```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK org/bytedeco/javacpp/macosx-x86_64/libusb-1.0.dylib
  	File1: /Users/manavdutta1/.gradle/caches/modules-2/files-2.1/org.bytedeco.javacpp-presets/libdc1394/2.2.4-1.3/f1498dacc46162ab68faeb8d66cf02b96fe41c61/libdc1394-2.2.4-1.3-macosx-x86_64.jar
  	File2: /Users/manavdutta1/.gradle/caches/modules-2/files-2.1/org.bytedeco.javacpp-presets/libfreenect/0.5.3-1.3/736d65a3ef042258429d8e7742128c411806b432/libfreenect-0.5.3-1.3-macosx-x86_64.jar
```

I'm not sure how to go about fixing the issue. Here is my current build.gradle:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    sourceSets.main.jni.srcDirs = []
    defaultConfig {
        applicationId 'com.manavdutta1.affdexdemo'
        minSdkVersion 21
        targetSdkVersion 23
        versionCode 1
        multiDexEnabled true
        versionName "1.0"
    }
    aaptOptions
            {
                cruncherEnabled = false
            }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/services/javax.annotation.processing.Processor'

        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
        pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
        //might need these if you use openCV
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/libdc1394/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/libdc1394/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/librealsense/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/librealsense/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/libfreenect/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/libfreenect/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/libfreenect2/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/libfreenect2/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/flandmark/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/flandmark/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/artoolkitplus/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/artoolkitplus/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/flycapture/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/flycapture/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/videoinput/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/videoinput/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp/macosx-x86_64/'

    }
    buildTypes {
        release {
            resValue 'string', 'app_name', 'AffdexMe'
            minifyEnabled false
        }
    }
    productFlavors {
    }
}
configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}
dependencies {
    compile fileTree(dir: 'java/libs', include: ['*.jar'])
    compile fileTree(dir: new File(buildDir, 'libs'), include: '*.jar')
    testCompile 'junit:junit:4.12'
    compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.1'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.6.1-0.11', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.6.1-0.11', classifier: 'android-x86'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:design:23.0.0'
    compile 'com.affectiva.android:affdexsdk:3.0.1'
    compile 'com.microsoft.projectoxford:face:1.0.0'
    compile 'com.microsoft.projectoxford:emotion:1.0.0'
    compile 'com.google.android.gms:play-services-vision:9.2.1'
    compile 'com.android.support:multidex:+'
    compile 'com.affectiva.android:affdexsdk:3.1.2'
    compile 'com.ibm.watson.developer_cloud:java-sdk:3.5.1'
    compile 'com.ibm.watson.developer_cloud:android-sdk:0.1.0'
    compile 'com.google.android.gms:play-services-appindexing:9.2.1'
}
```
What should I do to get all this to work right?

**Comment by saudet** [comment] 2017-01-15 06:10
Duplicate of #353

**Closed by saudet** 2017-01-15 06:10 UTC
Labels: duplicate
