### ISSUE TITLE
Exception in thread "pool-4-thread-3" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacv.FFmpegFrameGrabber

### ISSUE THREAD

**Issue by gggitpl** [bytedeco/javacv#1010] opened 2018-06-04 08:04 UTC
FFmpegFrameGrabber instantiates error in thread run() method
```
 @Override
        public void run() {
            try {
                FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new ByteBufInputStream(content));
                grabber.setOption("rtsp_transport", "tcp");
                grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);
                grabber.setFormat("h264");
                grabber.start();
            } catch (FrameGrabber.Exception e) {
                e.printStackTrace();
            }
        }
```

```
<dependency>
       <groupId>org.bytedeco</groupId>
       <artifactId>javacv-platform</artifactId>
       <version>1.4.1</version>
</dependency>
```

How do you solve this problem?

**Comment by saudet** [comment] 2018-06-04 08:20
What does FFmpeg output to the console log?

**Comment by gggitpl** [comment] 2018-06-04 08:22
```
Exception in thread "pool-5-thread-1" java.lang.ExceptionInInitializerError
	at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:309)
	at com.skuo.monitor.sip.mediaserver.Rtmp$Recorder.run(Rtmp.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1165)
	at org.bytedeco.javacpp.Loader.load(Loader.java:980)
	at org.bytedeco.javacpp.Loader.load(Loader.java:879)
	at org.bytedeco.javacpp.avformat$Write_packet_Pointer_BytePointer_int.<clinit>(avformat.java:640)
	... 5 more
Exception in thread "pool-4-thread-3" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacv.FFmpegFrameGrabber
	at com.skuo.monitor.sip.mediaserver.Rtmp$Grabber.run(Rtmp.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by saudet** [comment] 2018-06-04 08:27
Yes, that usually means something is missing. Further errors should show up on the console, but if they do not, try to set the "org.bytedeco.javacpp.logger.debug" system property to "true"

**Comment by gggitpl** [comment] 2018-06-04 08:31
The same code on the main thread can be executed correctly, just in the thread run() method, and the full-fledged class cannot be initialized

**Comment by saudet** [comment] 2018-06-04 08:37
There is apparently an issue related to thread safety with the `stop()` method somewhere.

I'll mark this as a duplicate of issue #991.

**Closed by saudet** 2018-06-04 08:37 UTC
Labels: bug, duplicate
