### ISSUE TITLE
BackgroundSubtractorMOG2 crashes on .apply in JavaCV 1.2.1

### ISSUE THREAD

**Issue by rickfluck** [bytedeco/javacv#445] opened 2016-06-29 22:24 UTC
Hello Samuel and friends,

I am trying to implement BackgroundSubtractorMOG2 in the newest JavaCV version 1.2.1. When I run my application it silently crashes at BackgroundSubtraction.apply(src, dst). I am running my application under Windows 10 using JRE 1.7.0_55. Below is my test method to implement the library:

```
    public static IplImage subtractBackground(IplImage source) {
        Mat mtx = new Mat(source);
        IplImage single = cvCreateImage(cvGetSize(source), 8, 1);
        cvSplit(source, single, null, null, null);
        BackgroundSubtractorMOG2 bgMOG = new BackgroundSubtractorMOG2(mtx);
        Mat fgMask = new Mat(single);
        bgMOG.apply(mtx, fgMask); // crashes here silently (fatal error runtime env)
        IplImage img = new IplImage(fgMask);
        bgMOG.close();
        detected2.showImage(converter.convert(img));
    	return img;    	
    }
```

Thank you, -Rick

**Comment by saudet** [comment] 2016-06-30 00:03
Do you have working code in C++?

**Comment by rickfluck** [comment] 2016-06-30 14:06
Samuel, I am currently in a video project where I develop working OpenCV code in Python and then convert that code to Java, as the end game is to port it all to Android (hence I favor JavaCV), so no, I do not have working code in C++ using the BackgroundSubtractorMOG2(ptr) as constructed in JavaCV version 1.2.1. 
I have seen however BackgroundSubtractorMOG2 with this construct: BackgroundSubtractorMOG2(int history, float varThreshold, bool bShadowDetection=true ), as suggested in the OpenCV docs:  [http://docs.opencv.org/2.4/modules/video/doc/motion_analysis_and_object_tracking.html#backgroundsubtractormog2] with an example as seen at: [http://stackoverflow.com/questions/13600021/how-to-get-moving-objects-mask-using-opencv-backgroundsubtractormog2], but that construct is undefined in JavaCV 1.2.1. -Rick

**Comment by saudet** [comment] 2016-07-01 02:58
So it's a duplicate of https://github.com/bytedeco/javacv/issues/279. That method is available here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_video.html#createBackgroundSubtractorMOG2-int-double-boolean-

**Closed by saudet** 2016-07-01 02:58 UTC
Labels: duplicate, question

**Comment by rickfluck** [comment] 2016-07-01 15:36
Samuel, thank you for your answer and suggestion. 

What I found was the need to statically import  org.bytedeco.javacpp.opencv_video.createBackgroundSubtractorMOG2 as importing org.bytedeco.javacpp.opencv_video.BackgroundSubtractorMOG2 non-statically did not allow my IDE to see the static createBackgroundSubtractorMOG2 method.

Below is working code in Java for BackgroundSubtractorMOG2 using JavaCV:

`import org.bytedeco.javacpp.opencv_video.BackgroundSubtractorMOG2;
import static org.bytedeco.javacpp.opencv_video.createBackgroundSubtractorMOG2;

public static IplImage subtractBackground(IplImage source) {

    	Mat mtx = new Mat(source);
    	IplImage sourceSingle = cvCreateImage(cvGetSize(source), 8, 1);
        BackgroundSubtractorMOG2 backgroundSubtractorMOG = null;
        backgroundSubtractorMOG = createBackgroundSubtractorMOG2(); 
        Mat fgMask = new Mat(sourceSingle);
        backgroundSubtractorMOG.apply(mtx, fgMask);        
	IplImage img = new IplImage(fgMask);
	sourceSingle.release();
	mtx.close();
	fgMask.close();
	backgroundSubtractorMOG.close();
	detected2.showImage(converter.convert(oldResult));
    	return img;    	
    }`

Thank you and cheers, -Rick
