### ISSUE TITLE
1.5.9 FFmpegFrameGrabber occur memory leak in centos7

### ISSUE THREAD

**Issue by Love122** [bytedeco/javacv#2270] opened 2024-08-09 02:57 UTC
Hello developer, thank you very much for sharing the open source. Through tcmalloc analysis, I discovered a memory leak in the CentOS 7 system in version 1.5.9. Can you guide me on how to fix it? Thank you again.
![WechatIMG2037](https://github.com/user-attachments/assets/5d79c69e-aea4-4efc-a6db-f9c578d8399a)

**Comment by saudet** [comment] 2024-08-09 11:50
Please try again with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment] 2024-08-11 03:35
Duplicate of #2249

**Closed by saudet** 2024-08-11 03:35 UTC
Labels: duplicate, question
