### ISSUE TITLE
Unwanted skewing and distorting  using ffmpegframerecorder

### ISSUE THREAD

**Issue by Hosseinyzr** [bytedeco/javacv#1143] opened 2019-02-25 10:35 UTC
I am using ffmpegframerecorder to record Bitamps that converted to Frame Object.
 for some Bitmap sizes mostly near to square sizes the out put is skewd... (but for some others there is no problem)
![capture](https://user-images.githubusercontent.com/18720898/53331501-4e6f1300-3906-11e9-96de-5655c883d39a.PNG)

is there any way to solve it?

**Comment by saudet** [comment] 2019-02-25 10:55
Would you have some code snippet to reproduce that?

**Comment by Hosseinyzr** [comment] 2019-02-25 13:34
File file = new File(soundAddress);

                fFmpegSoundFrameGrabber = new FFmpegFrameGrabber(file);
                fFmpegSoundFrameGrabber.setAudioChannels(1);
                fFmpegSoundFrameGrabber.start();


                recorderVideoWithSound = new FFmpegFrameRecorder(ouputFile, outputWidth, outputheight, 1);

                recorderVideoWithSound.setFormat("mp4");
                recorderVideoWithSound.setVideoQuality(1);
                recorderVideoWithSound.setVideoCodec(AV_CODEC_ID_H264);
                recorderVideoWithSound.setPixelFormat(AV_PIX_FMT_YUV420P);
                recorderVideoWithSound.setFrameRate(frameRate);
                recorderVideoWithSound.setAudioCodec(fFmpegSoundFrameGrabber.getAudioCodec());
                recorderVideoWithSound.setSampleFormat(fFmpegSoundFrameGrabber.getSampleFormat());
                recorderVideoWithSound.setSampleRate(fFmpegSoundFrameGrabber.getSampleRate());
                recorderVideoWithSound.setAudioBitrate(fFmpegSoundFrameGrabber.getAudioBitrate());




                recorderVideoWithSound.start();

                Frame frame2;
                int i = 0;
                while ((frame2 = fFmpegSoundFrameGrabber.grabFrame()) != null) {
                    recorderVideoWithSound.record(frame2);
                    if (recorderVideoWithSound.getTimestamp() <= fFmpegSoundFrameGrabber.getLengthInTime()) {
                        recorderVideoWithSound.record(proccessedFrames[i % proccessedFrames.length]);
                    }


                    i++;
                }
                recorderVideoWithSound.stop();
                recorderVideoWithSound.release();
                fFmpegSoundFrameGrabber.stop();
                fFmpegSoundFrameGrabber.release();

**Comment by saudet** [comment] 2019-02-25 13:44
How do you create a "proccessedFrames"?

**Comment by Hosseinyzr** [comment] 2019-02-25 13:47
I have some Bitmaps that using this yo convert them:
                   ` Frame frame = new AndroidFrameConverter().convert(bitmap);`

**Comment by saudet** [comment] 2019-02-25 13:50
Could you explain how to create one of those problematic Bitmap?

**Comment by Hosseinyzr** [comment] 2019-02-25 14:07
I make them by some basic operation like canvas.drawBitmap() and etc...
 I have tried to save each bitmap after generating and there was no problem with them. 
and I have tried to resize them to 480 pixel width and the record them and the problem solved.
so for example if I record series of bitmap of size: 741 *723  this problem occurs but if I resize them to 480 * 468 , the problem won't occurs .

**Comment by Hosseinyzr** [comment] 2019-02-25 14:13
and also i don't think it is related to `AndroidFrameConverter().convert(bitmap)` because i tried another test that I convert the Frame result of it to Bitmap again and save it, and i see they have no problem.
I think there is problem with recorder maybe , or its settings...

**Comment by saudet** [comment] 2019-02-25 14:18
Yes, I think it's an issue with AndroidFrameConverter, but I won't be able to solve this unless I am able to reproduce this issue here. You're still not giving me anything to create such a Bitmap.

**Comment by Hosseinyzr** [comment] 2019-02-25 14:34
Aha, but I think the AndroidFrameConverter is doing well.
and maybe when the image size becomes large , the recorder having problem. yes?
I don't know which part to send , there are many classes related to this.
but I tried to save the result bitmap to png and load it , and there was the same problem.
here is that png file
![valen](https://user-images.githubusercontent.com/18720898/53344096-15936600-3927-11e9-8b22-0765dd010ce4.png)

[valen.zip](https://github.com/bytedeco/javacv/files/2900930/valen.zip)

**Comment by saudet** [comment] 2019-02-25 23:24
Thanks! And how do I load this image to cause this issue?

**Comment by saudet** [comment] 2019-02-27 15:08
In any case, I probably found the cause. This should be fixed with commit https://github.com/bytedeco/javacv/commit/531220d7622a94cbcb0ac4a88b019491a3bb2a83.
Please give it a try with 1.4.5-SNAPSHOT: http://bytedeco.org/builds/

**Comment by Hosseinyzr** [comment] 2019-03-05 10:13
Hello again,
sorry for my latency !
and ok , I will see that snapshot.🙏

**Comment by Hosseinyzr** [comment] 2019-03-05 10:23
I have another issue , and because it maybe related to AndroidFrameConertor so I ask it here or if you want, I will open new Issue:
If the bitmap has black pixels , they turn into blue or green!
here is the output gif. I have tested it for mp4 output and it has also this problem.
![image](https://user-images.githubusercontent.com/18720898/53798513-a2ed4080-3f4d-11e9-9267-1afe078b56c1.png)

If I brighter the image the problem will be vanished .

**Comment by saudet** [comment] 2019-03-05 10:53
Looks like your image has an alpha channel, you'll need to deal with it.

**Comment by Hosseinyzr** [comment] 2019-03-05 10:55
but It does not have alpha channel..
its was a jpeg image that was loaded...

**Comment by saudet** [comment] 2019-03-05 12:34
Even if your file doesn't have one Android uses RBGA so there is an alpha
channel that gets added.

**Comment by Hosseinyzr** [comment] 2019-03-05 13:05
so what is the problem with having alpha channel , though the pixels are fully colored.
and it just affect some black pixels although those black pixels are not transparent.
any idea to solve it?

**Comment by Hosseinyzr** [comment] 2019-03-05 13:14
I checked my code, and I fund this problem is not related to your library ... thanks

**Comment by saudet** [comment] 2019-04-11 07:08
The skewing issue with AndroidFrameConverter is now fixed with JavaCV 1.5.
Thanks for reporting and enjoy!

**Closed by saudet** 2019-04-11 07:08 UTC
Labels: bug
