### ISSUE TITLE
OpenCVFrameGrabber.getDeviceDescriptions() throws UnsupportedOperationException on Mac OS X

### ISSUE THREAD

**Issue by clicit** [bytedeco/javacv#664] opened 2017-04-06 09:18 UTC
On Windows I'm successfully using `VideoInputFrameGrabber.getDeviceDescriptions()`

Now since `VideoInputFrameGrabber` is only available on Windows, I tried to use `OpenCVFrameGrabber` and `FFmpegFrameGrabber` for Mac OS X. 

Now getting:

> java.lang.UnsupportedOperationException: Device enumeration not support by OpenCV.

..respectively..

> java.lang.UnsupportedOperationException: Device enumeration not support by FFmpeg.

when trying to `getDeviceDescription()`.

Is there any solution? I need the device description ...

Thanks!

**Comment by saudet** [comment] 2017-04-06 10:36
FFmpeg has some support for listing devices: https://trac.ffmpeg.org/wiki/Capture/Webcam

We just need someone to make a contribution :)

**Comment by clicit** [comment] 2017-04-06 10:55
@saudet yes I'm actually using that via a command line wrapper and some parsing in another project ;) though the current version is: https://trac.ffmpeg.org/wiki/DirectShow

but would be nice to have it implemented in javacv of course :)

**Comment by saudet** [comment] 2018-01-18 04:02
Marking as duplicate of #189

**Closed by saudet** 2018-01-18 04:02 UTC
Labels: duplicate, enhancement
