### ISSUE TITLE
1.5.10 Could not initialize class org.bytedeco.javacpp.avutil Linux x86_64

### ISSUE THREAD

**Issue by jzw-1989** [bytedeco/javacv#2231] opened 2024-05-15 07:49 UTC
Hello,
I tried to use javaCV to call ffmpeg for video merging, and an error was reported when initializing FFmpegFrameGrabber:
Could not initialize class org.bytedeco.javacpp.avutil.
It is normal for me on the windows10 platform, I have this error when I push my code to the linux server
When I used 1.5.9, both linux and windows  are ok
 my dependencies 
 <dependency>
	<groupId>org.bytedeco</groupId>
	<artifactId>javacv-platform</artifactId>
	<version>1.5.10</version>
</dependency>

**Comment by saudet** [comment] 2024-05-15 08:26
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Closed by saudet** 2024-05-15 08:26 UTC
Labels: duplicate, enhancement, question
