### ISSUE TITLE
how to record 2 rtp streams with one grabber?

### ISSUE THREAD

**Issue by DeweyNULL** [bytedeco/javacv#1596] opened 2021-02-18 11:34 UTC
hello , I have a question about this;
I receive one RTMP stream and I want to record 2 rtp streams,
the ffmpeg commands  :
```
ffmpeg -fflags nobuffer -i rtmp://127.0.0.1:1935/live/test1 -vcodec libx264 -bsf:v  h264_mp4toannexb -an -f rtp -payload_type 103 rtp://172.17.0.2:25520 -acodec copy -vn -f rtp rtp://172.17.0.2:9286
```
but I don't know how to do with JavaCV ;

In JavaCV I can only use grabImage or grabSample like this:
```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(RTMPurl);

FFmpegFrameRecorder videoRecorder = new FFmpegFrameRecorder(RTPVideoUrl,480,360,0);
videoRecorder.setVideoCodec( avcodec.AV_CODEC_ID_H264);
videoRecorder.setOption("payload_type","103");
videoRecorder.setFormat("rtp");

grabber.start();
videoRecorder.start();

while (true){
 Frame frame = grabber.grabImage();
 if (frame == null) {
   log.info("no frame accepted!");
   break;
  }
   videoRecorder.record(frame);
 }
```
and I can't record both video and audio;
is there any way to record like ffmpeg commands ??

**Comment by saudet** [comment] 2021-02-18 13:00
Duplicate of #1475

**Comment by saudet** [comment] 2021-02-18 13:01
BTW, if the ffmpeg program does everything you need, you can keep using that easily from Java as well:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Closed by saudet** 2021-02-18 13:00 UTC
Labels: duplicate, enhancement

**Comment by DeweyNULL** [comment] 2021-02-19 06:59
thank you so much
