### ISSUE TITLE
Delay without movement on FFmpegFrameGrabber.start().

### ISSUE THREAD

**Issue by cqhblg** [bytedeco/javacv#1345] opened 2019-11-29 04:31 UTC
Hello,I want to read video stream from pipe source,but it can't work.When I run code, I get stuck on FFmpegFrameGrabber.start().

`
import java.util
import scala.util.control.Breaks._
import org.bytedeco.javacpp.Loader
import org.bytedeco.javacv.{FFmpegFrameGrabber, FFmpegFrameGrabber1, FFmpegFrameRecorder}
import java.io.{File, FileInputStream, FileOutputStream, InputStream, OutputStream}
import java.nio.ByteBuffer
import java.nio.channels.{Channels, DatagramChannel}
import java.nio.channels.Pipe.{SinkChannel, SourceChannel}
import java.util.concurrent.{ExecutorService, Executors}

import org.bytedeco.ffmpeg.global.avcodec
import org.seekloud.theia.processor.stream.PipeStream

import scala.util.Random

object TestLostPackage {
  val FilePath = "D:/ScalaWorkSpace/theia/processor/src/test/scala/test.mp4"
  val OutPath = "D:/ScalaWorkSpace/theia/processor/src/test/scala/testout.mp4"
  var audioChannels = 2 //todo
  var frameRate = 30
  val bitRate = 2000000

  class ReadFromPipeThread(fis:SourceChannel) extends Runnable {
    override def run(): Unit ={

      println("start thread")
      //read data from pipe
      val buf = Channels.newInputStream(fis)
      println(s"buf = $buf")
      val grabber = new FFmpegFrameGrabber(buf)
      grabber.setFormat("mp4")
      println(s"grabber = $grabber")
      try {

       // problem in here
        grabber.start()
      } catch {
        case e: Exception =>
          println(s"exception occured in grabber start")
      }
      println("grabber started")
      val ffLength = grabber.getLengthInFrames()
      print(s"length = $ffLength")
      val outputStream = new FileOutputStream(new File(OutPath))
      val recorder = new FFmpegFrameRecorder(outputStream,640,480,audioChannels)
      recorder.setFrameRate(frameRate)
      recorder.setVideoBitrate(bitRate)
      recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG2VIDEO)
      recorder.setAudioCodec(avcodec.AV_CODEC_ID_MP2)
      recorder.setMaxBFrames(0)
      recorder.setFormat("mpegts")
      try {
        recorder.startUnsafe()
      } catch {
        case e: Exception =>
          print(s" recorder meet error when start:$e")
      }
      var i = 0
      while (i<ffLength){
        val frame = grabber.grab()
        print(frame)
        recorder.record(frame)
        i+=1
      }
    }

  def fileInput(filePath: String,out:SinkChannel): Unit ={

    val fileInputStream = new FileInputStream(new File(filePath))
    val buf_tempRead = new Array[Byte]( 1024 * 1024 * 2)
    fileInputStream.read(buf_tempRead)

    val buf = ByteBuffer.wrap(buf_tempRead)
//    print(buf)
    out.write(buf)

  }
  def main(args: Array[String]): Unit = {

    val threadPool:ExecutorService = Executors.newFixedThreadPool(60)

    val pipe = new PipeStream
    val source = pipe.getSource
    val sink = pipe.getSink
    val out = Channels.newOutputStream(sink)
    val in = Channels.newInputStream(source)
    //Write to pipeline from file stream
    fileInput(FilePath,sink)

    //Start a thread to read data from the pipeline
    try {
      Thread.sleep(3000)
      threadPool.execute(new ReadFromPipeThread(source))
    }finally {
      threadPool.shutdown()
    }
  }
}
`

**Comment by saudet** [comment] 2019-11-29 05:15
Make sure to set the maximumSize to 0 like this:

val grabber = new FFmpegFrameGrabber(buf, 0)

**Comment by cqhblg** [comment] 2019-11-29 07:14
Wow,thank you very much.It is going on now but it still doesn't work.Because when FFmpegFrameGrabber.start(),there are some errors that called"Error on InputStream.reset()java.io.IOException: Resetting to invalid mark" .
Also,when I reduce buffer capacity from (1024 * 1024 * 2) to (1024 * 2),it will still delay without movement on FFmpegFrameGrabber.start just like befor.
I'm a novice. Thank you for helping me and this question has been bothering me for a long time.

**Comment by saudet** [comment] 2019-11-29 08:04
If you set maximumSize to 0, the seek function is not going to get set and you're not going to get any errors like that. If it still doesn't work, you'll need to find another format that doesn't require seeking.

**Comment by saudet** [comment] 2019-11-29 08:05
Duplicate of #1304

**Closed by saudet** 2019-11-29 08:05 UTC
Labels: duplicate, question
