### ISSUE TITLE
-re option

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#1842] opened 2022-07-16 18:53 UTC
FFmpeg has a -re option for playback in real time. 
Is there a way to replicate that in ffmpegFrameGrabber?

**Comment by saudet** [comment] 2022-07-16 23:59
Yes, that's what `FrameGrabber.grabAtFrameRate()` is for.

**Comment by saudet** [comment] 2022-07-17 00:00
Duplicate of #1633

**Closed by saudet** 2022-07-17 00:00 UTC
Labels: duplicate, enhancement, question
