### ISSUE TITLE
FFmpegFrameFilter.pull() gives null frame

### ISSUE THREAD

**Issue by rajib-brain-craft** [bytedeco/javacv#1727] opened 2021-12-06 09:16 UTC
Working filter: "setpts=N,split[s0][s1];[s0]palettegen=stats_mode=single[p];[s1][p]paletteuse=dither=none:diff_mode=rectangle"
Not working filter: "setpts=N,split[s0][s1];[s0]palettegen=stats_mode=diff[p];[s1][p]paletteuse=dither=none:diff_mode=rectangle"
First filter is working but second filter is not working. The only change is stats_mode=diff.

**Comment by saudet** [comment] 2021-12-06 09:19
That shouldn't be a problem, just skip them if you don't need them?

**Comment by rajib-brain-craft** [comment] 2021-12-06 09:24
I have updated the description. Please read and give solution.

**Comment by saudet** [comment] 2021-12-06 11:16
Did you try to call `push(null)` before calling `pull()`?

**Comment by rajib-brain-craft** [comment] 2021-12-06 11:43
Yeah this works. Thanks.

**Comment by saudet** [comment] 2021-12-06 13:28
Duplicate of #287

**Closed by saudet** 2021-12-06 13:28 UTC
Labels: duplicate, question
