### ISSUE TITLE
How do I extract the orientation data from a video file?

### ISSUE THREAD

**Issue by Farhan-Islam** [bytedeco/javacv#1180] opened 2019-04-08 20:47 UTC
Hi, I am trying to find out how to get the rotation data from a video file like an Mp4 or an Mov. For example I have a video that I am passing in that is in portrait mode but java cv is returning me the width and height in landscape mode. How can I get the rotation meta data tag that says this video is actually rotated?

**Comment by saudet** [comment] 2019-04-08 22:59
Probably in the metadata, what does ffprobe reports?

**Comment by Farhan-Islam** [comment] 2019-04-08 23:31
Ive checked all the metadata from the framegrabber, nothing relates to rotation orientation. I don't see anywhere I can use ffprobe within this library.

**Comment by Farhan-Islam** [comment] 2019-04-08 23:42
Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-03-14T17:53:17.000000Z
    location        : +54.7120+020.5096/
    location-eng    : +54.7120+020.5096/
    com.android.version: 9
    com.android.capture.fps: 30.000000
  Duration: 00:00:10.67, start: 0.000000, bitrate: 14587 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/smpte170m), 1920x1080, 14372 kb/s, SAR 1:1 DAR 16:9, 30.75 fps, 31 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2019-03-14T17:53:17.000000Z
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      creation_time   : 2019-03-14T17:53:17.000000Z
      handler_name    : SoundHandle

**Comment by Farhan-Islam** [comment] 2019-04-08 23:43
How do I grab that rotate data from the library?

**Comment by saudet** [comment] 2019-04-09 00:59
There's getMetadata() and getVideoMetadata().

**Comment by Farhan-Islam** [comment] 2019-04-09 01:05
That doesnt seem to be returning rotation metadata, what string key are you providing?

**Comment by saudet** [comment] 2019-04-09 01:11
Could you give me a video file for which this is failing?

**Comment by Farhan-Islam** [comment] 2019-04-09 01:28
It's not failing, its just returning an empty hashmap when i try frameGrabber.getMetaData() or frameGrabber.getVideoMetaData(). Other methods work like frameGrabber.getImageWidth. Is there a way to pass in a string key to getVideoMetaData() to get rotation data? Also it doesnt allow me to attach videos here.

**Comment by saudet** [comment] 2019-04-09 01:52
Yes, those methods return the all metadata, and it works fine for the video files I have here. If you could provide me with a video file for which that fails, the chances of getting this fixed will improve. If you cannot give me a way to reproduce this issue, I will not be able to fix this. I cannot fix what isn't broken!

**Comment by saudet** [comment] 2019-04-09 01:54
To attach some random file on GitHub, just put it in a zip file or something.

**Comment by saudet** [comment] 2019-04-09 04:32
Ah, I see what the issue might be. They are not getting filled after `start()`, so we need to use the variants taking a string parameter like `getMetadata("rotate")` or `getVideoMetadata("rotate")`. That could be enhanced.

**Comment by saudet** [comment] 2019-04-09 06:18
Fixed in commit https://github.com/bytedeco/javacv/commit/dd8fc3fddb1a7d9889d6328cb1487de6580f887f. Thanks for reporting!
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by Farhan-Islam** [comment] 2019-04-09 22:05
So I am trying this new snapshot build, but now my previous imports are failing, is there a new way to import the frameGrabber? 
import org.bytedeco.javacv.{FFmpegFrameGrabber, Frame, Java2DFrameConverter} 
this import no longer works, it seems javacv is no longer in the library for some reason

this is the dependency i am using in sbt:
  val javacv = "org.bytedeco" % "javacv" % "1.5-SNAPSHOT"

**Comment by saudet** [comment] 2019-04-09 23:03
That's the same, but use "javacv-platform", not "javacv".

**Comment by Farhan-Islam** [comment] 2019-04-10 18:39
So I'm still running into issue tryin to use the snapshot build, whenever I try to use this dependency it finds 

https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5-SNAPSHOT/javacpp-1.5-20190407.151727-40.jar and 

https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5-SNAPSHOT/javacpp-1.5-20190407.151727-40.jar , 

but when it tries to look for other dependencies in the snapshot directory like for example: 

 https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/opencv/4.0.1-1.5-SNAPSHOT/opencv-4.0.1-1.5-20190408.013453-692-ios-arm64.jar

 https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/opencv/4.0.1-1.5-SNAPSHOT/opencv-4.0.1-1.5-SNAPSHOT-ios-arm64.jar,

it fails and does not find these dependencies. is there some configuration that I need to specify on my end to omit these other dependencies like opencv and others? because it seems like it is trying t pull everything in from that snapshot directory

**Comment by Farhan-Islam** [comment] 2019-04-10 21:11
It looks like 1.5 got released recently , and that seems to be working

**Comment by saudet** [comment] 2019-04-10 22:17
Yes, it's been released, but instructions for Gradle are on the page I gave you above: http://bytedeco.org/builds/
Please take the time to read a bit next time, thank you.

**Closed by saudet** 2019-04-10 22:17 UTC
Labels: enhancement

**Comment by kennardconsulting** [comment] 2022-07-22 00:32
For those travelling this way again: despite lots of attempts I couldn't manage to read the orientation side data using JavaCV. It always returned null. However https://github.com/drewnoakes/metadata-extractor read it just fine!

**Comment by saudet** [comment] 2022-07-22 00:36
@kennardconsulting We need to add support for reading "side data", see issue #1361. Contributions are welcome!

**Comment by saudet** [comment] 2022-07-22 00:37
Duplicate of #1361

**Comment by kennardconsulting** [comment] 2022-07-22 00:40
JavaCV is an amazing library, and your work is much appreciated!

I only made your comment because this thread https://github.com/bytedeco/javacv/issues/1377 seems to imply reading side data is already fixed by https://github.com/bytedeco/javacv/commit/11016316165f238f6db163be341bb6fe1b2b234c

However there must be some confusion because it doesn't seem to work for me.

**Comment by saudet** [comment] 2022-07-23 13:45
I've added `FFmpegFrameGrabber.getDisplayRotation()` in commit https://github.com/bytedeco/javacv/commit/d1b1f4e1d445e764fc542d335ba5235483613bd7.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by kennardconsulting** [comment] 2022-07-24 00:04
This works **great** for both MP4 and MOV videos! Thanks so much!

When is 1.5.8 expected to release?

**Comment by saudet** [comment] 2022-07-24 00:15
Probably sometime this fall
