### ISSUE TITLE
Grabber hangs with multithreading

### ISSUE THREAD

**Issue by wyh0919** [bytedeco/javacv#1320] opened 2019-10-24 07:13 UTC
Hi, 
I use grabber.startUnsafe() function for multithreading method. But when I add about 400 streams per second to grab, some streams will hang at the startUnsafe function.
Is there any cocurrent limit for javacv or ffmpeg?

**Comment by wyh0919** [comment] 2019-10-24 07:17
In addition, no exception throws here and I cannot kill the hang thread with thread.stop() or thread.interrupt().

**Comment by wyh0919** [comment] 2019-10-24 07:57
but if I call .start(), the first thread will wait for the locking class of the second thread.

**Comment by wyh0919** [comment] 2019-10-24 07:57
but if I call .start(), the first thread will wait for the locking class of the second thread.

**Comment by saudet** [comment] 2019-10-24 07:57
Yes, that's how it's supposed to work. What's wrong with that?

**Comment by wyh0919** [comment] 2019-10-24 08:02
In this case, i will not change the locking class, so I use unsafe function.
I want to implement for multithreading to process stream at the same time instead of processing one by one.

**Comment by saudet** [comment] 2019-10-24 08:04
If you want to use `startUnsafe()`, you'll need to use a codec that is thread-safe.

**Comment by wyh0919** [comment] 2019-10-24 08:05
Yes, it is normal when i process about 300 streams, but will hang at the start function when i add to 400 streams

**Comment by saudet** [comment] 2019-10-24 08:07
Duplicate of #1139

**Closed by saudet** 2019-10-24 08:07 UTC
Labels: bug, duplicate

**Comment by saudet** [comment] 2019-10-24 08:09
It doesn't matter if it fails at 400 or 500 streams, the codec you are using isn't thread-safe! You'll need to use one that is thread-safe.

**Comment by wyh0919** [comment] 2019-10-24 08:13
ok I will try

**Comment by mifritscher** [comment] 2019-10-30 19:19
Which codec do you use? Perhaps somebody can fix this codec. But this is out of scope for JavaCV. As a first start, you could try to use visualVM (and then ProcessExplorer or a proper debugger) to get the backtraces of the hang threads. If there are indeed in the lib itself this is a ffmpeg problem.
