### ISSUE TITLE
How to use GPU to speed up processing

### ISSUE THREAD

**Issue by demonlov** [bytedeco/javacv#1785] opened 2022-03-31 03:28 UTC
Hello developer, how can I use GPU to speed up my task and how to set it in the code

**Comment by saudet** [comment] 2022-03-31 03:34
You'll need to include binaries that have been built with GPU support enable, for example:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#the-pomxml-build-file

**Comment by saudet** [comment] 2022-03-31 03:34
Duplicate of #1767

**Closed by saudet** 2022-03-31 03:34 UTC
Labels: duplicate, question
