### ISSUE TITLE
Can not grap frame from MOV format file

### ISSUE THREAD

**Issue by sppluskimo** [bytedeco/javacv#821] opened 2017-10-26 06:48 UTC
I use the following code to grab the first frame from the file and WMV,MP4,AVI these format works fine but MOV not.
```
FFmpegFrameGrabber g = new FFmpegFrameGrabber(is);
g.start();
Java2DFrameConverter converter = new Java2DFrameConverter();				
ImageIO.write(converter.getBufferedImage(g.grab()), "png", new File("d:\\tmp\\video-frame-" + System.currentTimeMillis() + ".png"));
g.stop();
```
Can someone tell me how to solve this problem?

**Comment by saudet** [comment] 2017-10-26 06:50
It's probably not supported by FFmpeg itself. You can probably rebuild FFmpeg from source with the right external codec module. Check the console output of FFmpeg, and it will tell you if that's the case.

**Comment by sppluskimo** [comment] 2017-10-26 07:08
Where can I check the console output? Is it look like following?

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'java.io.BufferedInputStream@6b2fad11':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2017-02-16T06:18:00.000000Z
    com.apple.quicktime.location.ISO6709: +34.9862+135.7589+071.322/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 6s
    com.apple.quicktime.software: 10.2.1
    com.apple.quicktime.creationdate: 2017-02-16T15:17:59+0900
  Duration: 00:00:35.39, start: 0.000000, bitrate: N/A
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 15329 kb/s, 29.98 fps, 29.97 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2017-02-16T06:18:00.000000Z
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 83 kb/s (default)
    Metadata:
      creation_time   : 2017-02-16T06:18:00.000000Z
      handler_name    : Core Media Data Handler
    Stream #0:2(und): Data: none (mebx / 0x7862656D), 12 kb/s (default)
    Metadata:
      creation_time   : 2017-02-16T06:18:00.000000Z
      handler_name    : Core Media Data Handler
    Stream #0:3(und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2017-02-16T06:18:00.000000Z
      handler_name    : Core Media Data Handler

**Comment by saudet** [comment] 2017-10-26 07:11
It says "h264", so that shouldn't be a problem. What error do you get?

**Comment by sppluskimo** [comment] 2017-10-26 07:19
I got the following error.
java.lang.IllegalArgumentException: image == null!
	at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925)
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1592)
	at javax.imageio.ImageIO.write(ImageIO.java:1520)
	at test.javacv.App.grapFrame(App.java:24)
	at test.javacv.App.main(App.java:45)

**Comment by sppluskimo** [comment] 2017-10-26 07:25
I tried to print the object content and got the following result.

System.out.println(g.grab());
    org.bytedeco.javacv.Frame@dfd3711

System.out.println(g.grab().image);
    null

**Comment by saudet** [comment] 2017-10-26 07:27
That just means you got an audio package. Call grabImage() instead.

**Comment by saudet** [comment] 2017-10-26 07:29
Duplicate of #116

**Closed by saudet** 2017-10-26 07:29 UTC
Labels: duplicate, question
