### ISSUE TITLE
FFmpegFrameFilter problem when multi filters

### ISSUE THREAD

**Issue by varlxj** [bytedeco/javacv#1268] opened 2019-08-09 02:18 UTC
hello
this is what i want
`ffplay test.mp4 -vf "drawbox=100:100:100:100:black@1,vflip"`

the source video
![image](https://user-images.githubusercontent.com/1623325/62749497-3abc0100-ba8f-11e9-8912-1ba24bd2666f.png)

right result
![image](https://user-images.githubusercontent.com/1623325/62749526-5aebc000-ba8f-11e9-859d-9723dfd891e8.png)

but when i use FFmpegFrameFilter， I can not get the same result

error result
![image](https://user-images.githubusercontent.com/1623325/62749550-6dfe9000-ba8f-11e9-9d3e-48ccd9b4135f.png)

FFmpegFrameFilter with sigle filter i can get correctly result, but when i use filterchain or filtergraph, the final result is always like [this](https://ibb.co/j44XgqK)

this is my code:  
```java
FFmpegFrameFilter filter = new FFmpegFrameFilter("drawbox=100:100:100:100,vflip",  
 grabber.getImageWidth(), grabber.getImageHeight());  
filter.setFrameRate(grabber.getFrameRate());  
filter.start();  

while (true) {
    Frame frame = grabber.grabFrame();  
    if (frame == null) { 
        break;  
    } 

    if (frame.getTypes().contains(Frame.Type.VIDEO)) { 
        filter.push(frame); 
        frame = filter.pull(); 
    } 

    recorder.record(frame);  
} 
```

-------

```xml
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>opencv</artifactId>
    <version>4.1.0-1.5.1</version>
    <classifier>macosx-x86_64</classifier> 
</dependency> 
<dependency> 
    <groupId>org.bytedeco</groupId>
    <artifactId>ffmpeg</artifactId>
    <version>4.1.3-1.5.1</version>
    <classifier>macosx-x86_64</classifier>
</dependency>
<dependency>
    <groupId>org.bytedeco</groupId> 
    <artifactId>javacv</artifactId> 
    <version>1.5.1</version> 
</dependency> 
```

thank you

**Comment by saudet** [comment] 2019-08-09 08:06
The filters you're using probably don't support your pixel format and are converting it to something else. Make sure to convert it back to what you need with, for example, the `format` filter after.

**Comment by saudet** [comment] 2019-08-09 08:10
Duplicate of #945

**Closed by saudet** 2019-08-09 08:10 UTC
Labels: duplicate, question
