### ISSUE TITLE
The grabber's setFrameRate does not take effect

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1841] opened 2022-07-14 01:46 UTC
I setFrameRate before start the grabber, but it didn't work.

**Comment by saudet** [comment] 2022-07-14 01:54
That doesn't do anything for video files, the frame rate is set by the file.

**Comment by saudet** [comment] 2022-07-14 01:55
Duplicate of #1121

**Closed by saudet** 2022-07-14 01:55 UTC
Labels: duplicate, question

**Comment by CJL6015** [comment] 2022-07-14 01:57
I am not trying to change the frame rate of the video file. I want to resample the video but it still doesn't work

**Comment by saudet** [comment] 2022-07-14 01:59
We can use FFmpegFrameFilter with the fps filter for that: https://ffmpeg.org/ffmpeg-filters.html#fps-1

**Comment by saudet** [comment] 2022-07-16 10:55
BTW, it might be easier for your use case to use the ffmpeg program instead:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by CJL6015** [comment] 2022-07-18 02:15
Thank you for your reply!
