### ISSUE TITLE
Pull stream by RTMP, block at av_read_frame() 

### ISSUE THREAD

**Issue by lixiangflyin** [bytedeco/javacv#1400] opened 2020-04-14 06:38 UTC
version: 1.5.2
env: linux  java（springbot）
My service pull many audio streams by RTMP，every service machine almost 500-1000 streams.
Can connection, but offen block at av_read_frame().
I try add setting (stimeout ： 50000000，probesize：10240， analyzemaxduration：1000000)
But no use.

Can help me ? Thanks!

errors :
thread-4456" #4876 prio=5 os_prio=0 tid=0x00007f55bc7f6800 nid=0x12bd runnable [0x00007f52c4f41000]
   java.lang.Thread.State: RUNNABLE
	at org.bytedeco.ffmpeg.global.avformat.av_read_frame(Native Method)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame(FFmpegFrameGrabber.java:1257)
	at org.bytedeco.javacv.FFmpegFrameGrabber.grabSamples(FFmpegFrameGrabber.java:1212)

AND 
RTMP set timeout , no use. And set loglevel "info", also no log info .

**Comment by saudet** [comment] 2020-04-14 09:55
The option we need to set is "rw_timeout": https://ffmpeg.org/ffmpeg-protocols.html

**Comment by saudet** [comment] 2020-04-14 09:56
Duplicate of #1209

**Closed by saudet** 2020-04-14 09:56 UTC
Labels: duplicate, question
