### ISSUE TITLE
Video biteRate reduce

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1780] opened 2022-03-14 07:52 UTC
`
public static void recordeVideo(String inputPath, String outputPath) {

        File input = new File(inputPath);
        if (!input.exists()) {
            return;
        }
        try {
            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(input);
            grabber.start();
            FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(new File(outputPath),
                    grabber.getImageWidth(), grabber.getImageHeight());
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
            recorder.setFormat("mp4");
            recorder.setFrameRate(grabber.getFrameRate());
            recorder.setVideoBitrate(grabber.getVideoBitrate());
            recorder.start();
            Frame frame;
            while ((frame = grabber.grabImage()) != null) {
                recorder.record(frame);
            }
            grabber.stop();
            grabber.close();
            grabber.release();

            recorder.stop();
            recorder.close();
            recorder.release();
        } catch (FrameGrabber.Exception | FrameRecorder.Exception e) {
            e.printStackTrace();
        }
    }
`
This is my code, the bite rate of the source video is 2139 kb/s, but the bite rate of the output video is just only 337 kb/s.

**Comment by saudet** [comment] 2022-03-14 08:22
Please try to use libx264 instead of OpenH264.

**Comment by saudet** [comment] 2022-03-14 08:23
Duplicate of #1775

**Closed by saudet** 2022-03-14 08:23 UTC
Labels: duplicate, question
