### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.bytedeco.javacv.FFmpegFrameGrabber with later version 1.5.9

### ISSUE THREAD

**Issue by verigle** [bytedeco/javacv#2173] opened 2024-01-19 08:57 UTC
```
NoClassDefFoundError: Could not initialize class org.bytedeco.javacv.FFmpegFrameGrabber
```
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45)
        at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:366)
```

pom ：
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.9</version>
        </dependency>
```

use docker image  alpine with openjdk8

**Comment by saudet** [comment] 2024-01-19 08:58
Please try again with the snapshots: http://bytedeco.org/builds/

**Comment by verigle** [comment] 2024-01-22 04:29
could you provider the offical docker image for javacv with Dockfile?

**Comment by saudet** [comment] 2024-01-22 04:49
I'm using the images from GitHub Actions, not Docker

**Comment by saudet** [comment] 2024-01-22 04:49
Ah, you're using Alpine, that won't work

**Comment by verigle** [comment] 2024-01-22 05:38
> GitHub Actions

can you tell me the envirenment of  GitHub Actions , such as  OS, lib

**Comment by saudet** [comment] 2024-01-22 07:09
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379

**Comment by saudet** [comment] 2024-01-22 07:09
GitHub Actions uses Ubuntu: https://github.com/actions/runner-images

**Closed by saudet** 2024-01-22 07:09 UTC
Labels: duplicate, enhancement
