### ISSUE TITLE
FFmpegFrameGrabber doesn't return all video frames from a video on Android 5.x

### ISSUE THREAD

**Issue by markuswilke** [bytedeco/javacv#355] opened 2016-03-16 10:07 UTC
Hi Samuel,
first of all, many thanks to you and all contributors for providing us with JavaCV. For me it's an essential lib for working with videos and images in Java.
Currently I'm using JavaCV 1.1 for recording/reencoding and playback of videos on Android devices.
On **Android 4.1.2** devices like Galaxy S2 everything just works fine and as expected. 
But on **Android 5.x** devices like Galaxy S5 (Android 5.0) or Sony Xperia Z1 compact (Android 5.1) the FFmpegFrameGrabber only grabs the first few frames of a video. In some cases I only get the very frist frame and in other cases I get only the first 30 frames of a video which contains at least 130 frames.
Here is my gradle configuration:
`compile group: 'org.bytedeco', name: 'javacv', version: '1.1'`
`compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-arm'`
`compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'`

The relevant piece of code looks like this:
  ...
  final FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(sourceVideo);
  final FrameRecorder frameRecorder =
          new FFmpegFrameRecorder(targetVideo, videoInfo.getWidth(), videoInfo.getHeight());
  frameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
  frameRecorder.setVideoQuality(4);
  frameRecorder.setAudioChannels(0);
  try {
      frameGrabber.start();
      frameRecorder.start();
      Frame frame;
      int recordedFrames = 0;
     ** while ((frame = frameGrabber.grabImage()) != null) {
              frameRecorder.record(frame);
      }**
  } finally {
      try {
          frameGrabber.stop();
      } catch (Exception ignore) {
      }
      try {
          frameRecorder.stop();
      } catch (Exception ignore) {
      }
  }
...
I have no clues why the FrameGrabber behaves so differently on Android 4.x and 5.x.
Could this a bug in FFmpeg or is something wrong with my code?
Any hints would be much appreciated.
Thanks,
Markus

**Comment by saudet** [comment] 2016-03-16 10:16
Could you call FFmpegLogCallback.set() on init and check what shows up in
the log?

**Comment by markuswilke** [comment] 2016-03-16 10:25
Here is the only signifcant output I get on Android 5.x:

03-13 18:48:09.519 com.wilke.virtualpro W/linker: libjniavutil.so: unused DT entry: type 0x1d arg 0x18f9c
03-13 18:48:09.519 com.wilke.virtualpro W/linker: libjniavutil.so: unused DT entry: type 0x6ffffffe arg 0x222f0
03-13 18:48:09.519 com.wilke.virtualpro W/linker: libjniavutil.so: unused DT entry: type 0x6fffffff arg 0x1
03-13 18:48:09.598 com.wilke.virtualpro W/linker: libswresample.so: unused DT entry: type 0x6ffffffe arg 0xca4
03-13 18:48:09.598 com.wilke.virtualpro W/linker: libswresample.so: unused DT entry: type 0x6fffffff arg 0x1
03-13 18:48:09.606 com.wilke.virtualpro W/linker: libjniswresample.so: unused DT entry: type 0x1d arg 0x280c
03-13 18:48:09.606 com.wilke.virtualpro W/linker: libjniswresample.so: unused DT entry: type 0x6ffffffe arg 0x45f0
03-13 18:48:09.606 com.wilke.virtualpro W/linker: libjniswresample.so: unused DT entry: type 0x6fffffff arg 0x2
03-13 18:48:09.664 com.wilke.virtualpro W/linker: libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x668c
03-13 18:48:09.665 com.wilke.virtualpro W/linker: libavcodec.so: unused DT entry: type 0x6fffffff arg 0x2
**03-13 18:48:09.665 com.wilke.virtualpro W/linker: libavcodec.so has text relocations. This is wasting memory and prevents security hardening. Please fix.**
03-13 18:48:09.673 com.wilke.virtualpro W/linker: libjniavcodec.so: unused DT entry: type 0x1d arg 0x1ab7d
03-13 18:48:09.673 com.wilke.virtualpro W/linker: libjniavcodec.so: unused DT entry: type 0x6ffffffe arg 0x23fd8
03-13 18:48:09.673 com.wilke.virtualpro W/linker: libjniavcodec.so: unused DT entry: type 0x6fffffff arg 0x2
03-13 18:48:09.759 com.wilke.virtualpro W/linker: libavformat.so: unused DT entry: type 0x6ffffffe arg 0x64b8
03-13 18:48:09.759 com.wilke.virtualpro W/linker: libavformat.so: unused DT entry: type 0x6fffffff arg 0x2
03-13 18:48:09.774 com.wilke.virtualpro W/linker: libjniavformat.so: unused DT entry: type 0x1d arg 0x16629
03-13 18:48:09.774 com.wilke.virtualpro W/linker: libjniavformat.so: unused DT entry: type 0x6ffffffe arg 0x1e610
03-13 18:48:09.774 com.wilke.virtualpro W/linker: libjniavformat.so: unused DT entry: type 0x6fffffff arg 0x2
03-13 18:48:09.843 com.wilke.virtualpro W/linker: libswscale.so: unused DT entry: type 0x6ffffffe arg 0xdd0
03-13 18:48:09.843 com.wilke.virtualpro W/linker: libswscale.so: unused DT entry: type 0x6fffffff arg 0x1
03-13 18:48:09.850 com.wilke.virtualpro W/linker: libjniswscale.so: unused DT entry: type 0x1d arg 0x3993
03-13 18:48:09.850 com.wilke.virtualpro W/linker: libjniswscale.so: unused DT entry: type 0x6ffffffe arg 0x5bc0
03-13 18:48:09.850 com.wilke.virtualpro W/linker: libjniswscale.so: unused DT entry: type 0x6fffffff arg 0x2
03-13 18:48:11.781 com.wilke.virtualpro W/linker: libjniopencv_core.so: unused DT entry: type 0x1d arg 0x4f533

**Comment by markuswilke** [comment] 2016-03-16 10:25
Sorry, didn't mean to close this issue.

**Comment by saudet** [comment] 2016-03-16 11:04
That's ok, it's a duplicate of #245 :)

**Closed by saudet** 2016-03-16 11:04 UTC
Labels: bug, duplicate

**Comment by saudet** [comment] 2016-03-20 14:40
I've uploaded SNAPSHOT binaries here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/
They should work, but please let me know if you encounter any problems! Thanks

**Comment by markuswilke** [comment] 2016-03-20 18:30
Hi Samuel,
    
    thanks for your message. I just tried to build against the snapshot
    repo but got the following dependency issues:
    
       > Could not resolve
    org.bytedeco.javacpp-presets:flycapture:2.8.3.1-1.2-SNAPSHOT.
         Required by: org.bytedeco:javacv:1.2-SNAPSHOT
       > Could not resolve
    org.bytedeco.javacpp-presets:libdc1394:2.2.4-1.2-SNAPSHOT.
         Required by: org.bytedeco:javacv:1.2-SNAPSHOT
       > Could not resolve
    org.bytedeco.javacpp-presets:libfreenect:0.5.3-1.2-SNAPSHOT.
         Required by: org.bytedeco:javacv:1.2-SNAPSHOT
       > Could not resolve
    org.bytedeco.javacpp-presets:videoinput:0.200-1.2-SNAPSHOT.
         Required by: org.bytedeco:javacv:1.2-SNAPSHOT
       > Could not resolve
    org.bytedeco.javacpp-presets:artoolkitplus:2.3.1-1.2-SNAPSHOT.
         Required by: org.bytedeco:javacv:1.2-SNAPSHOT
       > Could not resolve
    org.bytedeco.javacpp-presets:flandmark:1.07-1.2-SNAPSHOT.
         Required by: org.bytedeco:javacv:1.2-SNAPSHOT
    
    The snapshot versions of opencv and ffmpeg were resolved but not the
    others.
    What can I do?
    
    Regards,
    
    Markus
    
    Am 20.03.16 um 15:40 schrieb Samuel
      Audet:
    
    
      I've uploaded SNAPSHOT binaries here:
        https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
        https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/
        https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/
        They should work, but please let me know if you encounter any
        problems! Thanks
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    
    -- 
      
      Wilke gmx Signatur
      
_________________________________________________________________________
        Markus Wilke
        Diplom-Informatiker
        
        Mobil   :
        +49  151 68402978
        
        Telefon : +49 8133 996144
        
        Fax     :
        +49 8133 8357
        
        Mail    : markus.wilke@gmx.de

**Comment by saudet** [comment] 2016-03-21 00:33
Just try to put the JAR files manually in your project.

**Comment by markuswilke** [comment] 2016-03-21 06:41
How can I achieve this?
    I'm using Android Studio and gradle.
    The missing dependencies (flandmark, etc.) are declared as Maven
    dependencies in the javacv pom.
    In my project I don't need them at runtime, so I just tried to
    declare them as "provided" in my buildfile
    but this didn't work either.
    Is there any gradle configuration, which gets the job done?
    
    
    Am 21.03.16 um 01:33 schrieb Samuel
      Audet:
    
    
      Just try to put the JAR files manually in your project.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    
    -- 
      
      Wilke gmx Signatur
      
_________________________________________________________________________
        Markus Wilke
        Diplom-Informatiker
        
        Mobil   :
        +49  151 68402978
        
        Telefon : +49 8133 996144
        
        Fax     :
        +49 8133 8357
        
        Mail    : markus.wilke@gmx.de

**Comment by saudet** [comment] 2016-03-21 07:21
https://github.com/bytedeco/javacv#manual-installation

**Comment by markuswilke** [comment] 2016-03-21 09:59
After migrating to Android Studio and Gradle I totally forgot that
    this option also exists.
    
    Current status after manually installing the 1.2-SNAPSHOT libs and
    building:
    - build is ok
    - FfmpegFrameGrabber works fine on Android 4.1.2 (like before) but
    get an UnsatisfiedLinkError in logcat:
    
    03-21 10:43:51.558 com.wilke.virtualpro W/dalvikvm: Exception
      Ljava/lang/UnsatisfiedLinkError; thrown while initializing
      Lorg/bytedeco/javacpp/postproc;
      
    The app functionality seem not to be affected by this Error.
    
    Will try the new APK also on 5.1.1 device this evening (can't get
    hold of the device just now).
    
    Thank you so much for your help!
    
    Markus
    
    
    
    
    Am 21.03.16 um 08:21 schrieb Samuel
      Audet:
    
    
      https://github.com/bytedeco/javacv#manual-installation
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    
    -- 
      
      Wilke gmx Signatur
      
_________________________________________________________________________
        Markus Wilke
        Diplom-Informatiker
        
        Mobil   :
        +49  151 68402978
        
        Telefon : +49 8133 996144
        
        Fax     :
        +49 8133 8357
        
        Mail    : markus.wilke@gmx.de

**Comment by markuswilke** [comment] 2016-03-21 21:01
Yes and thumbs up!!! 
    FfmpegFrameGrabber now grabs all frames on Android 5.1.2 too.
    
    Thanks again,
    
    Markus
    
    P.S.: do you already know, when the final 1.2 version will be
    released?
    
    Am 20.03.16 um 15:40 schrieb Samuel
      Audet:
    
    
      I've uploaded SNAPSHOT binaries here:
        https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
        https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/
        https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/
        They should work, but please let me know if you encounter any
        problems! Thanks
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    
    -- 
      
      Wilke gmx Signatur
      
_________________________________________________________________________
        Markus Wilke
        Diplom-Informatiker
        
        Mobil   :
        +49  151 68402978
        
        Telefon : +49 8133 996144
        
        Fax     :
        +49 8133 8357
        
        Mail    : markus.wilke@gmx.de

**Comment by saudet** [comment] 2016-03-22 00:41
Good! Thanks for testing. As for the release, sooner than later, I hope, but can't make any promises :(

**Comment by Nischitha-S** [comment] 2017-09-09 12:07
09-09 17:30:08.427 21161-21161/com.example.samuel.videostabilization W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-09 17:30:08.767 21161-21161/com.example.samuel.videostabilization W/linker: libjniavutil.so: unused DT entry: type 0x1d arg 0x18f9c
09-09 17:30:08.767 21161-21161/com.example.samuel.videostabilization W/linker: libjniavutil.so: unused DT entry: type 0x6ffffffe arg 0x222f0
09-09 17:30:08.767 21161-21161/com.example.samuel.videostabilization W/linker: libjniavutil.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:08.847 21161-21161/com.example.samuel.videostabilization W/linker: libswresample.so: unused DT entry: type 0x6ffffffe arg 0xca4
09-09 17:30:08.847 21161-21161/com.example.samuel.videostabilization W/linker: libswresample.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:08.857 21161-21161/com.example.samuel.videostabilization W/linker: libjniswresample.so: unused DT entry: type 0x1d arg 0x280c
09-09 17:30:08.857 21161-21161/com.example.samuel.videostabilization W/linker: libjniswresample.so: unused DT entry: type 0x6ffffffe arg 0x45f0
09-09 17:30:08.857 21161-21161/com.example.samuel.videostabilization W/linker: libjniswresample.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:08.917 21161-21161/com.example.samuel.videostabilization W/linker: libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x668c
09-09 17:30:08.917 21161-21161/com.example.samuel.videostabilization W/linker: libavcodec.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:08.917 21161-21161/com.example.samuel.videostabilization W/linker: libavcodec.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
09-09 17:30:08.937 21161-21161/com.example.samuel.videostabilization W/linker: libjniavcodec.so: unused DT entry: type 0x1d arg 0x1ab7d
09-09 17:30:08.937 21161-21161/com.example.samuel.videostabilization W/linker: libjniavcodec.so: unused DT entry: type 0x6ffffffe arg 0x23fd8
09-09 17:30:08.937 21161-21161/com.example.samuel.videostabilization W/linker: libjniavcodec.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.027 21161-21161/com.example.samuel.videostabilization W/linker: libavformat.so: unused DT entry: type 0x6ffffffe arg 0x64b8
09-09 17:30:09.027 21161-21161/com.example.samuel.videostabilization W/linker: libavformat.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.047 21161-21161/com.example.samuel.videostabilization W/linker: libjniavformat.so: unused DT entry: type 0x1d arg 0x16629
09-09 17:30:09.047 21161-21161/com.example.samuel.videostabilization W/linker: libjniavformat.so: unused DT entry: type 0x6ffffffe arg 0x1e610
09-09 17:30:09.047 21161-21161/com.example.samuel.videostabilization W/linker: libjniavformat.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.117 21161-21161/com.example.samuel.videostabilization W/linker: libswscale.so: unused DT entry: type 0x6ffffffe arg 0xdd0
09-09 17:30:09.117 21161-21161/com.example.samuel.videostabilization W/linker: libswscale.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:09.127 21161-21161/com.example.samuel.videostabilization W/linker: libjniswscale.so: unused DT entry: type 0x1d arg 0x3993
09-09 17:30:09.127 21161-21161/com.example.samuel.videostabilization W/linker: libjniswscale.so: unused DT entry: type 0x6ffffffe arg 0x5bc0
09-09 17:30:09.127 21161-21161/com.example.samuel.videostabilization W/linker: libjniswscale.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.197 21161-21161/com.example.samuel.videostabilization W/linker: libpostproc.so: unused DT entry: type 0x6ffffffe arg 0x7a0
09-09 17:30:09.197 21161-21161/com.example.samuel.videostabilization W/linker: libpostproc.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:09.207 21161-21161/com.example.samuel.videostabilization W/linker: libjnipostproc.so: unused DT entry: type 0x1d arg 0x2411
09-09 17:30:09.207 21161-21161/com.example.samuel.videostabilization W/linker: libjnipostproc.so: unused DT entry: type 0x6ffffffe arg 0x3e98
09-09 17:30:09.207 21161-21161/com.example.samuel.videostabilization W/linker: libjnipostproc.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.247 21161-21161/com.example.samuel.videostabilization W/linker: libavfilter.so: unused DT entry: type 0x6ffffffe arg 0x4408
09-09 17:30:09.247 21161-21161/com.example.samuel.videostabilization W/linker: libavfilter.so: unused DT entry: type 0x6fffffff arg 0x6
09-09 17:30:09.257 21161-21161/com.example.samuel.videostabilization W/linker: libjniavfilter.so: unused DT entry: type 0x1d arg 0xd2e3
09-09 17:30:09.257 21161-21161/com.example.samuel.videostabilization W/linker: libjniavfilter.so: unused DT entry: type 0x6ffffffe arg 0x11f6c
09-09 17:30:09.257 21161-21161/com.example.samuel.videostabilization W/linker: libjniavfilter.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.307 21161-21161/com.example.samuel.videostabilization W/linker: libavdevice.so: unused DT entry: type 0x6ffffffe arg 0x1a38
09-09 17:30:09.307 21161-21161/com.example.samuel.videostabilization W/linker: libavdevice.so: unused DT entry: type 0x6fffffff arg 0x4
09-09 17:30:09.317 21161-21161/com.example.samuel.videostabilization W/linker: libjniavdevice.so: unused DT entry: type 0x1d arg 0x41e3
09-09 17:30:09.317 21161-21161/com.example.samuel.videostabilization W/linker: libjniavdevice.so: unused DT entry: type 0x6ffffffe arg 0x6570
09-09 17:30:09.317 21161-21161/com.example.samuel.videostabilization W/linker: libjniavdevice.so: unused DT entry: type 0x6fffffff arg 0x2

**Comment by Nischitha-S** [comment] 2017-09-09 12:10
Hi,
    Iam getting the below bug and iam not able to get all the frames  from the video



09-09 17:30:08.427 21161-21161/com.example.samuel.videostabilization W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-09 17:30:08.767 21161-21161/com.example.samuel.videostabilization W/linker: libjniavutil.so: unused DT entry: type 0x1d arg 0x18f9c
09-09 17:30:08.767 21161-21161/com.example.samuel.videostabilization W/linker: libjniavutil.so: unused DT entry: type 0x6ffffffe arg 0x222f0
09-09 17:30:08.767 21161-21161/com.example.samuel.videostabilization W/linker: libjniavutil.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:08.847 21161-21161/com.example.samuel.videostabilization W/linker: libswresample.so: unused DT entry: type 0x6ffffffe arg 0xca4
09-09 17:30:08.847 21161-21161/com.example.samuel.videostabilization W/linker: libswresample.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:08.857 21161-21161/com.example.samuel.videostabilization W/linker: libjniswresample.so: unused DT entry: type 0x1d arg 0x280c
09-09 17:30:08.857 21161-21161/com.example.samuel.videostabilization W/linker: libjniswresample.so: unused DT entry: type 0x6ffffffe arg 0x45f0
09-09 17:30:08.857 21161-21161/com.example.samuel.videostabilization W/linker: libjniswresample.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:08.917 21161-21161/com.example.samuel.videostabilization W/linker: libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x668c
09-09 17:30:08.917 21161-21161/com.example.samuel.videostabilization W/linker: libavcodec.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:08.917 21161-21161/com.example.samuel.videostabilization W/linker: libavcodec.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
09-09 17:30:08.937 21161-21161/com.example.samuel.videostabilization W/linker: libjniavcodec.so: unused DT entry: type 0x1d arg 0x1ab7d
09-09 17:30:08.937 21161-21161/com.example.samuel.videostabilization W/linker: libjniavcodec.so: unused DT entry: type 0x6ffffffe arg 0x23fd8
09-09 17:30:08.937 21161-21161/com.example.samuel.videostabilization W/linker: libjniavcodec.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.027 21161-21161/com.example.samuel.videostabilization W/linker: libavformat.so: unused DT entry: type 0x6ffffffe arg 0x64b8
09-09 17:30:09.027 21161-21161/com.example.samuel.videostabilization W/linker: libavformat.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.047 21161-21161/com.example.samuel.videostabilization W/linker: libjniavformat.so: unused DT entry: type 0x1d arg 0x16629
09-09 17:30:09.047 21161-21161/com.example.samuel.videostabilization W/linker: libjniavformat.so: unused DT entry: type 0x6ffffffe arg 0x1e610
09-09 17:30:09.047 21161-21161/com.example.samuel.videostabilization W/linker: libjniavformat.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.117 21161-21161/com.example.samuel.videostabilization W/linker: libswscale.so: unused DT entry: type 0x6ffffffe arg 0xdd0
09-09 17:30:09.117 21161-21161/com.example.samuel.videostabilization W/linker: libswscale.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:09.127 21161-21161/com.example.samuel.videostabilization W/linker: libjniswscale.so: unused DT entry: type 0x1d arg 0x3993
09-09 17:30:09.127 21161-21161/com.example.samuel.videostabilization W/linker: libjniswscale.so: unused DT entry: type 0x6ffffffe arg 0x5bc0
09-09 17:30:09.127 21161-21161/com.example.samuel.videostabilization W/linker: libjniswscale.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.197 21161-21161/com.example.samuel.videostabilization W/linker: libpostproc.so: unused DT entry: type 0x6ffffffe arg 0x7a0
09-09 17:30:09.197 21161-21161/com.example.samuel.videostabilization W/linker: libpostproc.so: unused DT entry: type 0x6fffffff arg 0x1
09-09 17:30:09.207 21161-21161/com.example.samuel.videostabilization W/linker: libjnipostproc.so: unused DT entry: type 0x1d arg 0x2411
09-09 17:30:09.207 21161-21161/com.example.samuel.videostabilization W/linker: libjnipostproc.so: unused DT entry: type 0x6ffffffe arg 0x3e98
09-09 17:30:09.207 21161-21161/com.example.samuel.videostabilization W/linker: libjnipostproc.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.247 21161-21161/com.example.samuel.videostabilization W/linker: libavfilter.so: unused DT entry: type 0x6ffffffe arg 0x4408
09-09 17:30:09.247 21161-21161/com.example.samuel.videostabilization W/linker: libavfilter.so: unused DT entry: type 0x6fffffff arg 0x6
09-09 17:30:09.257 21161-21161/com.example.samuel.videostabilization W/linker: libjniavfilter.so: unused DT entry: type 0x1d arg 0xd2e3
09-09 17:30:09.257 21161-21161/com.example.samuel.videostabilization W/linker: libjniavfilter.so: unused DT entry: type 0x6ffffffe arg 0x11f6c
09-09 17:30:09.257 21161-21161/com.example.samuel.videostabilization W/linker: libjniavfilter.so: unused DT entry: type 0x6fffffff arg 0x2
09-09 17:30:09.307 21161-21161/com.example.samuel.videostabilization W/linker: libavdevice.so: unused DT entry: type 0x6ffffffe arg 0x1a38
09-09 17:30:09.307 21161-21161/com.example.samuel.videostabilization W/linker: libavdevice.so: unused DT entry: type 0x6fffffff arg 0x4
09-09 17:30:09.317 21161-21161/com.example.samuel.videostabilization W/linker: libjniavdevice.so: unused DT entry: type 0x1d arg 0x41e3
09-09 17:30:09.317 21161-21161/com.example.samuel.videostabilization W/linker: libjniavdevice.so: unused DT entry: type 0x6ffffffe arg 0x6570
09-09 17:30:09.317 21161-21161/com.example.samuel.videostabilization W/linker: libjniavdevice.so: unused DT entry: type 0x6fffffff arg 0x2

**Comment by saudet** [comment] 2017-09-10 00:11
Does this happen only on Android, or does it happen with Java SE as well?

**Comment by Nischitha-S** [comment] 2017-09-11 02:49
It is happening in andriod studio only sir

Thanks
S.Nischitha

**Comment by saudet** [comment] 2017-09-11 02:59
@Nischitha-S This issue was fixed, so please open another issue with a small code snippet and some data we can use to reproduce this. Thanks!
