### ISSUE TITLE
need help, javacv 1.5.9 memory leak 

### ISSUE THREAD

**Issue by shaoneng111** [bytedeco/javacv#2119] opened 2023-11-02 14:44 UTC
environment : centos 6.8
jdk: java8
problem: memory is growing slowly

mycode:
```
public static VideoComputeInfo computeVideoQuality(String videoContentId, InputStream videoInputStream) {
if (videoInputStream == null) {
return null;
}
long startTime = System.currentTimeMillis();
// 直接指定maximumSize
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(videoInputStream, 1000000);
grabber.setCloseInputStream(true);
try {
// 截取jpeg文件
grabber.start();
// 视频帧率
Integer frameRate = (int) grabber.getVideoFrameRate();
// 视频时长
int timeLen = (int) Math.ceil((double) grabber.getLengthInTime() / 1000000);
int frameWidth = grabber.getImageWidth();
int frameHeight = grabber.getImageHeight();
// 视频文件大小
int videoSize = videoInputStream.available();
long endTime = System.currentTimeMillis();
VideoComputeInfo videoComputeInfo = VideoComputeInfo.builder()
.frameRate(frameRate)
.height(frameHeight)
.width(frameWidth)
.timeLen(timeLen)
.videoSize(videoSize)
.build();
log.info("FfmpegUtil computeVideoQuality耗时：{}, videoContentId: {}, videoComputeInfo: {}"
, endTime - startTime, videoContentId, videoComputeInfo);
return videoComputeInfo;
} catch (Exception e) {
log.error("FfmpegUtil computeVideoQuality异常，异常信息：", e);
} finally {
try {
grabber.close();
} catch (Exception e) {
log.error("FfmpegUtil grabber.close()异常，异常信息：", e);
}
}
return null;
} 
```

i don't know what's wrong with it

**Comment by saudet** [comment] 2023-11-02 14:49
If the problem doesn't occur without VideoComputeInfo, it's a problem with your VideoComputeInfo, not JavaCV.

**Comment by shaoneng111** [comment] 2023-11-02 15:03
thank you for your reply! but VideoComputeInfo is a simple java object , use java heap. i analysis the java heap memory, its looks like normal, so the leak occurs not in java heap?

**Comment by saudet** [comment] 2023-11-02 15:05
If you can reproduce the issue without VideoComputeInfo, please provide such sample code.

**Comment by shaoneng111** [comment] 2023-11-02 15:07
> thank you for your reply! but VideoComputeInfo is a simple java object , use java heap. i analysis the java heap memory, its looks like normal, so the leak occurs not in java heap?

and VideoComputeInfo  should occupy very little memory, but actually it will eat 1G memory one day

**Comment by shaoneng111** [comment] 2023-11-02 15:10
i also want to know , Is the way I'm using javacv correct?

**Comment by saudet** [comment] 2023-11-02 15:13
Looks alright, but the problem might also be caused by your InputStream. If you're not closing your InputStream, it can leak memory. If you want me to help, you'll need to come up with something that doesn't depend on your system.

**Comment by shaoneng111** [comment] 2023-11-04 12:26
![heap_68-69](https://github.com/bytedeco/javacv/assets/7445371/eaa27c5d-9234-42cb-9860-020a5ca76778)


i use gperftools analyze the memory. it look like ffmpeg apply the av_malloc memory , is this means it leaks?

**Comment by shaoneng111** [comment] 2023-11-07 12:12
hi, i find where is bug is. when FFmpegFrameGrabber input param is inputstream，it don't realease avformat and occurs memory leak. when i change FFmpegFrameGrabber input param from  inputstream to file, memory leak disapears. 
<img width="672" alt="image" src="https://github.com/bytedeco/javacv/assets/7445371/bb666447-9e6d-469d-82c8-a9e070c653bd">
it look like avformat_free_context is invalid, should use avformat_close_input? 

otherwise, in this issue : https://github.com/bytedeco/javacv/issues/911, someone has mensioned it, looks like the same problem with me.
<img width="563" alt="image" src="https://github.com/bytedeco/javacv/assets/7445371/08e56c85-dcf7-4991-8e1f-f393e09ff1bd">

**Comment by saudet** [comment] 2023-11-07 12:22
Sounds like a fix. Please open a pull request!

**Comment by bing241639** [comment] 2024-01-24 12:47
Has this problem been fixed? I seem to have encountered the same problem

**Comment by jetamie** [comment] 2024-02-26 07:33
![image](https://github.com/bytedeco/javacv/assets/46777058/69e1ef8a-2137-4af6-a129-7bfdb7c8bcbb)
`avio_context_free(avio)` should be called here instead of  `av_free(avio)` @saudet

**Comment by jetamie** [comment] 2024-02-26 07:44
![image](https://github.com/bytedeco/javacv/assets/46777058/93911e51-4648-4e11-93d6-75f11eeba6f0)
Maybe you need to call both

**Comment by Lwine** [comment] 2024-03-30 09:05
> hi, i find where is bug is. when FFmpegFrameGrabber input param is inputstream，it don't realease avformat and occurs memory leak. when i change FFmpegFrameGrabber input param from inputstream to file, memory leak disapears. <img alt="image" width="672" src="https://private-user-images.githubusercontent.com/7445371/281032790-bb666447-9e6d-469d-82c8-a9e070c653bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODk2OTAsIm5iZiI6MTcxMTc4OTM5MCwicGF0aCI6Ii83NDQ1MzcxLzI4MTAzMjc5MC1iYjY2NjQ0Ny05ZTZkLTQ2OWQtODJjOC1hOWUwNzBjNjUzYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDkwMzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDRiODczYzc4MGZhNTE5ODcwNjkwMTdkMzI0ZTExMWUzNDExZTFmOTdkNWRhOGRmODc5YmZhN2FiZGUxYjNlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6TLPXxSGF36VhsINtp4daMk0WdpLL-Vjt66h1HGxQnM"> it look like avformat_free_context is invalid, should use avformat_close_input?
> 
> otherwise, in this issue : #911, someone has mensioned it, looks like the same problem with me. <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/7445371/281033236-08e56c85-dcf7-4991-8e1f-f393e09ff1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODk2OTAsIm5iZiI6MTcxMTc4OTM5MCwicGF0aCI6Ii83NDQ1MzcxLzI4MTAzMzIzNi0wOGU1NmM4NS1kY2Y3LTQ5OTEtOGUxZi1mMzkzZTA5ZmYxYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDkwMzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJlZjQ5ZWM5YWZjYjM3YjBmZWVlNjQ2MTk0ZGQ1ZmYyMzFkZDlkZGQxOTNhMTE1YWY0NWYyNGM1YmM5NDAzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z-PQStloBhx8to_T-GlRBJFJDKOVPxleOHZnkXovklc">

hello，i had the same problem.How did you reslove it?

**Comment by saudet** [comment] 2024-04-21 12:29
@Lwine Thanks for the fix! 

@shaoneng111 Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by Love122** [comment] 2024-05-10 02:23
How to fix this javacv 1.5.9 memory leak ? Base in javacv keep version 1.5.9,not change

**Comment by xiaobei2019** [comment] 2024-06-18 12:15
@saudet 
When will the 1.5.11 version be released to solve the memory leakage problem?
https://github.com/bytedeco/javacv/pull/2214

**Comment by saudet** [comment] 2024-11-17 04:54
JavaCV 1.5.11 has been released and should fix this issue, but please let me know if you still have problems! Thanks

**Closed by saudet** 2024-11-17 04:54 UTC
Labels: bug

**Comment by saudet** [comment] 2024-11-17 04:56
And thanks for @Lwine for the fix!
