### ISSUE TITLE
Does javacv support h.265?

### ISSUE THREAD

**Issue by duanmugou** [bytedeco/javacv#1625] opened 2021-04-11 11:00 UTC

**Comment by saudet** [comment] 2021-04-11 11:02
Yes it does.

**Comment by duanmugou** [comment] 2021-04-11 11:10
Thnaks for your reply! And if I want to push stream h.265, what encapsulation format should I use?rtmp-flv doesn't work.

**Comment by saudet** [comment] 2021-04-11 11:57
Other formats such as mp4 or mkv support it.

**Comment by saudet** [comment] 2021-04-11 11:58
Duplicate of #1497

**Closed by saudet** 2021-04-11 11:58 UTC
Labels: duplicate, question
