### ISSUE TITLE
Error on FrameFilter

### ISSUE THREAD

**Issue by jpinazo** [bytedeco/javacv#421] opened 2016-05-31 09:40 UTC
After synchronising the git codeand convert the project to Maven, verything seems right but the class FrameFilter has an error saying it cannot find FFmpegFrameFilter (cannot be resolved to a type)
Any idea on how to solve?

**Comment by saudet** [comment] 2016-06-01 09:09
Probably a duplicate of issue https://github.com/bytedeco/javacpp-presets/issues/225

**Closed** 2016-06-01 10:08 UTC
Labels: bug, duplicate
