### ISSUE TITLE
h264_nvenc @ 0x7f33246a1940] Cannot load libcuda.so.1

### ISSUE THREAD

**Issue by wanggq654321** [bytedeco/javacv#1614] opened 2021-03-28 16:53 UTC
h264_nvenc @ 0x7f33246a1940] Cannot load libcuda.so.1
org.bytedeco.javacv.FFmpegFrameRecorder$Exception: avcodec_open2() error -1: Could not open video codec. (For more details, make sure FFmpegLogCallback.set() has been called.)

**Comment by wanggq654321** [comment] 2021-03-28 16:54
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>4.3.2-${javacpp.version}</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>4.3.2-${javacpp.version}</version>
            <classifier>${javacpp.platform.linux-x86_64}</classifier>
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>4.3.2-${javacpp.version}</version>
            <classifier>${javacpp.platform.macosx-x86_64}</classifier>
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>${javacpp.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bytedeco.javacpp-presets</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>4.3.2-1.5.5</version>
        </dependency>

**Comment by wanggq654321** [comment] 2021-03-28 16:57
encodeName = "h264_nvenc";

  FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outFile, frameGrabber.getImageWidth(), frameGrabber.getImageHeight(), frameGrabber.getAudioChannels());
        // gpu 硬件编解码，mac 测试好使
        if (isSupportEncode) recorder.setVideoCodecName(encodeName);

**Comment by saudet** [comment] 2021-03-28 22:42
You'll need a GPU from NVIDIA for this to work.

**Comment by wanggq654321** [comment] 2021-03-29 03:18
Thank you for your answer. My CPU is Intel i7 integrated graphics card hd610. Can NVIDIA support GPU acceleration?

**Comment by saudet** [comment] 2021-03-29 03:31
For Intel GPUs, we can use VAAPI: https://trac.ffmpeg.org/wiki/HWAccelIntro

However, the default builds do not come with VAAPI enabled yet because it's not available on CentOS 6.

**Comment by saudet** [comment] 2021-03-29 03:31
Duplicate of #1188

**Closed by saudet** 2021-03-29 03:31 UTC
Labels: duplicate, enhancement, question

**Comment by saudet** [comment] 2021-08-10 02:49
FFmpeg is now getting built with CentOS 7, so this gets enabled by default.
Please give it a try with the snapshots: http://bytedeco.org/builds/
