### ISSUE TITLE
How do we leverage the ffmpeg concat filter?

### ISSUE THREAD

**Issue by skeshavan** [bytedeco/javacv#1048] opened 2018-08-23 07:11 UTC
The input is a stream of files in H264 format. Using them, I need to concat them into a single byte stream that can be used by FFMpegFrameGrabber to create a stream of frames. I am required to use the FFMpegFrameGrabber constructor that accepts an input stream as input (because ffmpeg runs on a different machine than where files are available).

Is there some way to do this effectively?

**Comment by saudet** [comment] 2018-08-24 07:47
I think the concat filter is going to require support for multiple inputs:
https://ffmpeg.org/ffmpeg-filters.html#concat
So I'll mark this as duplicate of issue #955. Contributions welcome!

**Closed by saudet** 2018-08-24 07:47 UTC
Labels: duplicate, enhancement

**Comment by saudet** [comment] 2018-10-28 02:46
BTW, to use `concat` or any other such filters, FFmpegFrameFilter now supports multiple inputs, see https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L163 for some sample code. For now we need to use the snapshots to access this feature: http://bytedeco.org/builds/
