### ISSUE TITLE
The sound and picture cannot be synchronized

### ISSUE THREAD

**Issue by redoriental** [bytedeco/javacv#1973] opened 2023-01-18 06:55 UTC
long interval = 1_000 / 30;

                long startTime = System.currentTimeMillis();

                Frame frame;
                while ((frame = grabber.grab()) != null) {
                    
                    recorder.record(frame);
                    long currentTime = 1_000 * (System.currentTimeMillis() - startTime);
                    long frameTime = frame.timestamp;
                    long sleepTime = (frameTime - currentTime) / 1_000;
                    try {
                        if (sleepTime > 500 + interval) {
                            Thread.sleep(interval);
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

When I use this code, I will have the problem that the sound and picture are not synchronized

**Comment by redoriental** [comment] 2023-01-18 07:00
If I use ffmpeg.exe directly, this problem will not occur

**Comment by saudet** [comment] 2023-01-18 07:02
Try to call setTimestamp(frame.timestamp) before record(). Please do not open duplicate issues.

**Comment by saudet** [comment] 2023-01-18 07:02
Duplicate of #1972.

**Closed by saudet** 2023-01-18 07:02 UTC
Labels: duplicate, question
