### ISSUE TITLE
h264_mediacodec

### ISSUE THREAD

**Issue by zhengbin1015** [bytedeco/javacv#743] opened 2017-07-13 00:40 UTC
Ffmpeg hard decoding, please
AVCodec codec = avcodec.avcodec_find_decoder_by_name ("h264_mediacodec");
Can you provide support?

**Comment by saudet** [comment] 2017-07-13 00:48
Support for what? What is the issue?

**Comment by zhengbin1015** [comment] 2017-07-13 00:58
Ffmpeg has added Android mediacodec solution support since version 3.1
To compile libraries with h264_mediacodec versions, you need to open the following options
--enable-jni
--enable-mediacodec
--enable-decoder=h264_mediacodec
--enable-hwaccel=h264_mediacodec
First, call before the JNI_OnLoad function or use the decoder
Av_jni_set_java_vm (VM, NULL); (located in libavcodec/jni.h)
To set the Java virtual machine (antiregulation mediacodec will be used)
Second, since the h264_mediacodec decoder is the same as the H264 decoder ID, the soft solution is adopted
Avcodec_find_decoder (ID) to find the decoder
When you want to use mediacodec hard solution, use
Avcodec_find_decoder_by_name ("h264_mediacodec"); looks for the specified decoder

**Comment by saudet** [comment] 2017-07-13 01:17
Ah, I see, marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/389.

BTW, if you could modify the cppbuild.sh file, and send a pull request with those settings enabled, Travis CI will automatically build new binaries for you:
https://travis-ci.org/bytedeco/javacpp-presets/pull_requests

**Closed by saudet** 2017-07-13 01:17 UTC
Labels: duplicate, enhancement

**Comment by gbenroscience** [comment] 2020-03-17 01:02
Hi! Thanks for the awesome work you are doing, @saudet and all. 

Please can I use JavaCV on PC(J2SE) to decode MediaCodec h264 data now? I already tried using FFmpegFrameGrabber to decode it but it gets stuck(hangs) on the start method of the FFmpegFrameGrabber object. I would also appreciate any cool examples on this.

Thanks a lot again
