### ISSUE TITLE
Delay in FFmpegFrameGrabber grab method

### ISSUE THREAD

**Issue by zchacker** [bytedeco/javacv#865] opened 2017-12-28 22:45 UTC
I have build rtmp flash player and publisher, in publisher part it work ok, but in player part at first time it get delay in open a stream,  the delay between 4-6 seconds in first time, and after that when i pause the streaming and replay it start fast, i set the buffer to 0 in the options but it get delay in starting playback 
here is publisher part

```
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder( url ,captureWidth , captureHeight , 2);
recorder.setInterleaved(true);
recorder.setVideoBitrate(82000);
recorder.setVideoOption("framerate", "15");
recorder.setVideoCodec(avcodec.AV_CODEC_ID_FLV1);
recorder.setFormat("flv");
recorder.setAudioOption("crf", "0");
recorder.setAudioQuality(0);
recorder.setAudioBitrate(32000);
recorder.setSampleRate(44100);
recorder.setAudioChannels(2);
recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
recorder.setOption("nobuffer", "0");
recorder.setOption("fflags", "nobuffer"); 
recorder.start();
```
and this is player part

```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(stream); // get stream video 
grabber.setVideoOption("preset", "ultrafast");
grabber.setFrameNumber(1);
grabber.setOption("fflags", "nobuffer");
grabber.setOption("loglevel", "verbose");						
grabber.start();
```

so is there a problem in FFmpeg itself or in my configurations ?

**Comment by saudet** [comment] 2017-12-29 00:01
Like I said, try to disable buffering the way explained at issue #848.

Duplicate of #862

**Closed by saudet** 2017-12-29 00:01 UTC
Labels: duplicate, question
