### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec Api level 23

### ISSUE THREAD

**Issue by Iqra786** [bytedeco/javacv#292] opened 2015-12-22 17:44 UTC
Hi ,
Whenever I set targetSdkVersion 23. following line crash the application with the following log. it works fine with compileSdkVersion 23 and target version 22.
 
String ffmpeg_link = CameraMethods.getInternalFilePath(this).getAbsolutePath();
        recorder = new FFmpegFrameRecorder(ffmpeg_link, 320, 320, 1);

Process: com.PID: 30503
                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                               at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.Class.forName(Class.java:324)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                                               at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
                                                                               at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)

**Comment by saudet** [comment] 2015-12-23 01:46
Duplicate of https://github.com/bytedeco/javacv/issues/245

**Closed by saudet** 2015-12-23 01:46 UTC
Labels: bug, duplicate
